### ISSUE TITLE
Show full QWERTY keyboard

### ISSUE THREAD

**Issue by N6REJ** [univrsal/input-overlay#1]
Please show the full keyboard, would be great for tutorials

**Comment by univrsal** [comment]
It's customizable, so you could technically make your own preset to do that. Give some time and I'll try to make a preset for the entire keyboard

**Comment by univrsal** [comment]
![screenshot](http://i.imgur.com/XzxmboU.jpg)
This is all I could put together, if you want the numpad or anything else I suggest you try making your own preset. You can get the qwerty preset in the new release

**Comment by N6REJ** [comment]
great!  thank you for the fast response.  Can it be turned off for a second when entering passwords?  I don't normally need that function but it does occur.

**Comment by N6REJ** [comment]
also, your instructions say to copy the plugins over,  you don't need presets there also?

**Comment by univrsal** [comment]
You can hide individual sources over hotkeys in the OBS settings:

![screenshot](http://i.imgur.com/CHWkLQC.png)
You can copy the presets anywhere you want. When creating a source you'll then need to select an *.ini and a *.png file from the presets.
I'd recommend taking a look at the [install guide](https://vimeo.com/229296849) if you have any more questions.

**Comment by N6REJ** [comment]
great, ty.. I'd recommend putting that install guide link in the README
