### ISSUE TITLE
Croma Key - Opacity won't work

### ISSUE THREAD

**Issue by CHEF-KOCH** [univrsal/input-overlay#10]
OBS 20.1.3 x64
Win 10: x64

Setting up Input history + Chroma key as filter with 'Opacity' won't work. I tried to play with the given options but it's still at 100%. The other input methods work which means you can make them less visible.

**Comment by univrsal** [comment]
Looks like the opacity isn't passed down to the text source. Would an opacity slider in the input history settings suffice?

**Comment by CHEF-KOCH** [comment]
I guess a slider would be good enough.

**Comment by univrsal** [comment]
Alrighty, it's not the ideal way but it works :P
[v2.1](https://github.com/univrsal/input-overlay/releases/tag/v2.1) contains the slider
