### ISSUE TITLE
Mouse Side buttons not being 'clicked` in the overlay

### ISSUE THREAD

**Issue by InternetOscar** [univrsal/input-overlay#100]
**Describe the bug**
Mouse Side buttons not being 'clicked` in the overlay

**To Reproduce**
1. Select the mouse overlay.png
2. select no movement mouse.ini

**Expected behavior**
The expected behavior is that all mouse buttons including side buttons will get detected

**Screenshots**

**Additional information:**
- Plugin version
v4.8b
- Full OBS Studio write_log
how do i get that?

**Additional context**
I have my mouse' side keys bound to the `\` and `/` keys to make it easier for some games to use the keys

**Comment by univrsal** [comment]
the mouse overlay expects the side buttons to not be rebound to anything else, which is probably why they're not working in the overlay. Can you try and unbind them and see if it works?
Right now there's no way to change what the plugin accepts as mouse buttons.

**Comment by InternetOscar** [comment]
I reset the mouse and the inputs still aren't being recognized

**Comment by univrsal** [comment]
Can you run the ``demo_hook.exe`` or ``demo_hook_async.exe`` from the util.zip over at the release page and tell me what the output is when you press the side buttons

**Comment by InternetOscar** [comment]
```refresh_locale_list [471]: GetKeyboardLayoutList(0, NULL) found 2 layouts.
refresh_locale_list [488]: Received 2 locales.
load_input_helper [861]: refresh_locale_list() found 2 locale(s).
id=1,when=0,mask=0x0
id=7,when=0,mask=0x1000,x=531,y=464,button=5,clicks=1
id=8,when=0,mask=0x0,x=531,y=464,button=5,clicks=1
id=6,when=0,mask=0x0,x=531,y=464,button=5,clicks=1
id=7,when=0,mask=0x1000,x=531,y=464,button=5,clicks=2
id=8,when=0,mask=0x0,x=531,y=464,button=5,clicks=2
id=6,when=0,mask=0x0,x=531,y=464,button=5,clicks=2
id=7,when=0,mask=0x800,x=531,y=464,button=4,clicks=1
id=8,when=0,mask=0x0,x=531,y=464,button=4,clicks=1
id=6,when=0,mask=0x0,x=531,y=464,button=4,clicks=1
id=7,when=0,mask=0x800,x=531,y=464,button=4,clicks=2
id=8,when=0,mask=0x0,x=531,y=464,button=4,clicks=2
id=6,when=0,mask=0x0,x=531,y=464,button=4,clicks=2
id=4,when=519734,mask=0x2,keycode=0x1D,rawcode=0xA2, ctrl: 2
id=4,when=519984,mask=0x2,keycode=0x1E,rawcode=0x41, ctrl: 2
id=3,when=519984,mask=0x2,keychar=a,rawcode=65
```
^^^
There's the output when I presed the side buttons a few times

**Comment by univrsal** [comment]
Well it definitely recognizes the inputs as Mouse4 and Mouse5, can you try a different preset?

**Comment by InternetOscar** [comment]
i tried a different preset (both on my mouse and in the plugin) and it wouldn't register the buttons in the overlay

**Comment by univrsal** [comment]
I can't really figure out what the problem is. Can you load a preset and then give me the obs log? Also just to make this clear you tried this with your mouse configured so that the side buttons are bound to nothing special?

**Comment by InternetOscar** [comment]
The mouse is set to its default settings, the side buttons are bound to 'back' and 'forwards'.  
Here is the log: https://gist.github.com/InternetOscar/4979ae0338c4aacc98e147c19ac4df2f

**Comment by univrsal** [comment]
I've just had someone on the forums report the same issue and it seems that it's specific for these kind of mice, so for now I'm sorry, but it seems that I can't really help you fix this

**Comment by snakecase** [comment]
Found the solution!

`mouse-no-movement.json`: both side buttons work (4, 5)
`mouse-arrow.json`: only the lower side button works (4)
`mouse-dot.json`: neither of the side buttons work

All of the configs above have **_almost_** identical sections for `smb1` and `smb2`. The difference is the `type` parameter for `smb1` and `smb2`. In `mouse-no-movement.json` it's set to 3 while in two other configs it's 1 (except for `smb2` in `mouse-arrow.json` for some reason).

So here is the solution! Edit your config in question and change these two values under `"id": "smb1"` and `"id": "smb2"`:

```
        {
            "code": 5,
            "id": "smb1",
            "mapping": [
                285,
                1,
                40,
                62
            ],
            "pos": [
                0,
                210
            ],
            "type": 1, <----------------- REPLACE THIS WITH 3
            "z_level": 1
        },
        {
            "code": 4,
            "id": "smb2",
            "mapping": [
                284,
                1,
                41,
                62
            ],
            "pos": [
                11,
                273
            ],
            "type": 1, <----------------- REPLACE THIS WITH 3
            "z_level": 1
        }
```

Have fun!
