### ISSUE TITLE
Unexplained missing input for mouse layout

### ISSUE THREAD

**Issue by sherbet-head** [univrsal/input-overlay#103]
Every input but the last loads correctly

Other mouse layouts do work as intended

cfg:
`
#
0_key_count=6
0_layout_type=1
1_mouse_layout_w_h=406,202
#
1_mouse_lmb_u_v=0,0
1_mouse_lmb_w_h=100,100
1_mouse_lmb_x_y=0,0
#
1_mouse_smb1_u_v=102,0
1_mouse_smb1_w_h=100,100
1_mouse_smb1_x_y=102,0
#
1_mouse_mwu_u_v=205,0
1_mouse_mwu_w_h=200,100
1_mouse_mwu_x_y=205,0
#
1_mouse_rmb_u_v=0,205
1_mouse_rmb_w_h=100,100
1_mouse_rmb_x_y=0,102
#
1_mouse_smb2_u_v=102,205
1_mouse_smb2_w_h=100,100
1_mouse_smb2_x_y=102,102
#
l_mouse_mwd_u_v=205,205
l_mouse_mwd_w_h=200,100
l_mouse_mwd_x_y=205,205

`

![obsLayoutOutpu](https://user-images.githubusercontent.com/32368561/73876375-cc45d900-484e-11ea-92a9-fc56c81e1aab.jpg)
![sherb3t-mouse](https://user-images.githubusercontent.com/32368561/73876404-d536aa80-484e-11ea-97f9-909170713cec.png)

**Comment by univrsal** [comment]
Can you give me the log file after trying to load the overlay?

**Comment by sherbet-head** [comment]
12:59:00.600: [ccl] Encountered errors when loading 'C:/Users/boxxybabee/Documents/OBS/Mouse/sherb3t-mouse.ini':
12:59:00.600:  [ERROR] Cannot get bool value of 'show_mouse_movement'. Doesn't exist or type mismatch
12:59:00.600:  [ERROR] Cannot get bool value of 'use_arrow'. Doesn't exist or type mismatch
12:59:00.600:  [ERROR] Cannot get int value of 'mouse_field_radius'. Doesn't exist or type mismatch
12:59:00.600:  [ERROR] Cannot get string value of 'mouse_mmb_u_v'. Doesn't exist or type mismatch
12:59:00.600:  [ERROR] Cannot get string value of 'mouse_mmb_w_h'. Doesn't exist or type mismatch
12:59:00.600:  [ERROR] Cannot get string value of 'mouse_mmb_x_y'. Doesn't exist or type mismatch
12:59:00.600:  10 more error(s) reported
12:59:00.635: Switched to scene 'main'

I don't know how to show all errors?

**Comment by univrsal** [comment]
Well looks like you're missing the section for the middle mouse button. Can you try adding it and see if ti loads? Doesn't matter what values you use (0,0 for all should work). Also make sure that there's an empty line at the end of the file

**Comment by sherbet-head** [comment]
New config:
`
0_key_count=7
0_layout_type=1
1_mouse_layout_w_h=406,202
#
1_mouse_lmb_u_v=0,0
1_mouse_lmb_w_h=100,100
1_mouse_lmb_x_y=0,0
#
1_mouse_smb1_u_v=102,0
1_mouse_smb1_w_h=100,100
1_mouse_smb1_x_y=102,0
#
1_mouse_mwu_u_v=205,0
1_mouse_mwu_w_h=200,100
1_mouse_mwu_x_y=205,0
#
1_mouse_rmb_u_v=0,205
1_mouse_rmb_w_h=100,100
1_mouse_rmb_x_y=0,102
#
1_mouse_smb2_u_v=102,205
1_mouse_smb2_w_h=100,100
1_mouse_smb2_x_y=102,102
#
l_mouse_mwd_u_v=205,205
l_mouse_mwd_w_h=200,100
l_mouse_mwd_x_y=205,205
#
l_mouse_mmb_u_v=0,0
l_mouse_mmb_w_h=0,0
l_mouse_mmb_x_y=0,0

`

New log:
20:25:02.991: [ccl] Encountered errors when loading 'C:/Users/boxxybabee/Documents/OBS/Mouse/sherb3t-mouse.ini':
20:25:02.991:  [ERROR] Cannot get bool value of 'show_mouse_movement'. Doesn't exist or type mismatch
20:25:02.991:  [ERROR] Cannot get bool value of 'use_arrow'. Doesn't exist or type mismatch
20:25:02.991:  [ERROR] Cannot get int value of 'mouse_field_radius'. Doesn't exist or type mismatch
20:25:02.991:  [ERROR] Cannot get string value of 'mouse_mmb_u_v'. Doesn't exist or type mismatch
20:25:02.991:  [ERROR] Cannot get string value of 'mouse_mmb_w_h'. Doesn't exist or type mismatch
20:25:02.991:  [ERROR] Cannot get string value of 'mouse_mmb_x_y'. Doesn't exist or type mismatch
20:25:02.991:  13 more error(s) reported
20:25:03.022: Switched to scene 'main'

**Comment by sherbet-head** [comment]
I think the issue is i've had some of the variables set to l_xxx instead of 1_xxx

After changing this all of the buttons are showing
