### ISSUE TITLE
How can I change key for azerty and R6S settings

### ISSUE THREAD

**Issue by IamXori** [univrsal/input-overlay#104]
Hello, I wish change key for azerty keyboard, and my Rainbow Six Siege config, It's possible ?

**Comment by univrsal** [comment]
yea you have to change the ini file as well as the texture, I made a tutorial for [it here](https://vimeo.com/238275966).

**Comment by Estecka** [comment]
Hi,
[The link provided in the ini files](https://github.com/univrsal/input-overlay/blob/master/libuiohook/include/uiohook.h#L137), to find a key's hex values, is dead. It should be replaced with [this link](https://github.com/kwhat/libuiohook/blob/91c26673661ded767ee3a1788c817ee6b1d88225/include/uiohook.h).
