### ISSUE TITLE
Mouse Overlay cannot accurately determine Monitor Center in multi-display environments

### ISSUE THREAD

**Issue by Shigbeard** [univrsal/input-overlay#105]
**Describe the bug**
The "Mouse Overlay" component of the Input Overlay Source cannot accurately determine the center of the monitor in scenarios where more than one monitor is in use, especially if the monitors are laid out in a non-traditional layout (such as one monitor being on a diagonal to the primary monitor.

**To Reproduce**
1. Create an Input Overlay in OBS, using the default Mouse preset shipped with the latest build.
2. Ensure you are using "mouse-arrow-movement" as your layout config file to best demonstrate the bug.
3. Enable Mouse overlay, and tick the "Use monitor center" button.

**Expected behavior**
As the "Use monitor center" button suggests it's for game's that lock the mouse, it should only find the center of the monitor the focused foreground window is in, or failing that, the primary monitor. Thus, the arrow should always be pointing directly to my mouse, given the properties dialogue typically displays in the center of the primary monitor. However, in my scenario, the arrow instead points in a different location because it thinks the monitor center is somewhere else.

**Screenshots**
Posted is a screenshot of my entire desktop. Black spaces represent areas my monitors do not cover. Included in the screenshot is Display Fusion ( an unrelated application ) showing my monitor's layout.
![2020-03-07_22-13-35](https://user-images.githubusercontent.com/4262327/76142340-f34b3100-60c0-11ea-8b40-de38a446bd3b.png)
![2020-03-07_22-16-32](https://user-images.githubusercontent.com/4262327/76142387-550b9b00-60c1-11ea-92d9-eea2d5e4a7e3.png)

**Additional information:**
- Plugin version : V4.8b (Windows)
- Full OBS Studio write_log : https://obsproject.com/logs/ge5wQ3cdAG9xDjCN

**Additional context**
It may be pertinent to create additional options for monitor center behavior as opposed to trying to find a catch-all. For most games, simply finding the center of the primary monitor would suffice. But some games allow the user to select their preferred display prior to launch, and sometimes even during runtime. Others support features like Nvidia Eyefinity, which may further dilute the act of finding the center of the monitor as that allows games to use multiple monitors as if they were one. And that's even before considering windowed mode.

Perhaps a drop-down box, with options such as "Use Active Window Center", "Use Desktop Center", "Use Active Monitor Center", "Use Primary Monitor Center"? .. I don't know, I'm just throwing ideas out there on how to tackle this issue.

**Comment by univrsal** [comment]
Did you set the monitor center yourself? The plugin does not determine the center, because there is just no way to do this reliably. I posted a video on how to determine it on a per game basis in the forum post. The issue is that if the game is running in windowed mode or in your case with multiple monitors, it's hard to find where the center of the game window is, so it's up to the user to determine it.

**Comment by Shigbeard** [comment]
Wow, thats... fucking dumb but ok. I suppose thats one way to do it. Might be worth while adding a note to the tickbox that you must manually set the center, or at least auto-fill those sliders with the primary monitor's width/2 and height/2...

**Comment by univrsal** [comment]
> Wow, thats... fucking dumb but ok.
Thanks, it's my specialty
