### ISSUE TITLE
Bug Does Not Apear on OBS

### ISSUE THREAD

**Issue by AlphaNMC1999** [univrsal/input-overlay#107]
When I create an Input Overlay and i put the .INI it gets Transparenrt and does not detect anything. The image I put for it desappears.

![Captura de pantalla (51)](https://user-images.githubusercontent.com/63130083/78411641-9df73680-7610-11ea-94d5-4c4327099e91.png)
![Captura de pantalla (52)](https://user-images.githubusercontent.com/63130083/78411645-9fc0fa00-7610-11ea-8159-371e3aa5ae05.png)
![Captura de pantalla (53)](https://user-images.githubusercontent.com/63130083/78411647-9fc0fa00-7610-11ea-8566-a50ccdb764e0.png)
![Captura de pantalla (54)](https://user-images.githubusercontent.com/63130083/78411648-a0599080-7610-11ea-8376-411d5a08861f.png)
![Captura de pantalla (55)](https://user-images.githubusercontent.com/63130083/78411650-a18abd80-7610-11ea-930e-5431e395195d.png)
![Captura de pantalla (56)](https://user-images.githubusercontent.com/63130083/78411651-a18abd80-7610-11ea-95fa-9e9edb56bc6e.png)
![Captura de pantalla (57)](https://user-images.githubusercontent.com/63130083/78411652-a2235400-7610-11ea-8f16-29a3451dc225.png)

**Additional information:**
OBS 25.0.1 64bits
Input Overlay 4.8

**Comment by univrsal** [comment]
Can you edit the ini file you're trying to open and add an empty line at the end?

**Comment by AlphaNMC1999** [comment]
Yes, it has

**Comment by univrsal** [comment]
it has what? fixed the issue?

**Comment by AlphaNMC1999** [comment]
It has the Space, it doen't fixed it.

**Comment by univrsal** [comment]
Can you send me the obs studio log after you try loading it?

**Comment by AlphaNMC1999** [comment]
How can i do it?

**Comment by univrsal** [comment]
![image](https://user-images.githubusercontent.com/8353672/78508368-dbc19f80-7775-11ea-86a3-f00cd31b4820.png)

**Comment by AlphaNMC1999** [comment]
https://obsproject.com/logs/fs7I6_gRdQz-4qUg

**Comment by univrsal** [comment]
Just tested it and it works fine for me. Did you use the presets that come with the latest release? If not please try those.

**Comment by AlphaNMC1999** [comment]
Now it works but it does not work with controller

**Comment by univrsal** [comment]
You gotta be more clear, what doesn't work?

**Comment by AlphaNMC1999** [comment]
Same as the Mouse or keyboard, but this time, it does not apperar on OBS when i summit the .ini

**Comment by univrsal** [comment]
I just tested it, it works fine for me. Are you using the latest preset config and image?

**Comment by AlphaNMC1999** [comment]
Yes.

**Comment by AlphaNMC1999** [comment]
Now its working, thaxs so much.
