### ISSUE TITLE
Does not work with 25.0.4 on Linux

### ISSUE THREAD

**Issue by crabcrabcam** [univrsal/input-overlay#108]
**Describe the bug**
Currently the Input Overlay options do not show on 25.0.4
It does however work on 23.0.x

The 23 version is currently the version in the Ubuntu packages, but at the end of this month the new Ubuntu version goes live and we'll have 25.0.4 (which I am currently running through flatpak)

The plugin folder is the exact same for both versions (I have 2 separate config installs for them)

Hopefully I'll get to use this soon, because it looks cool as all hell :D

**Comment by univrsal** [comment]
Flatpak doesn't seem to support plugins as far as I know

**Comment by univrsal** [comment]
I'll just close this for now. You should either use the AppImage or install it natively on your system, also make sure to install libuiohook, which is a dependency of input overlay..
