### ISSUE TITLE
Custom overlay like controller but for keyboard

### ISSUE THREAD

**Issue by ipodtouchdude** [univrsal/input-overlay#110]
I want to make a Gameboy Advance screen overlay but use a keyboard as the input. I want to have the ability to use the way 0_layout_type=3 and map the keys like the Gameboy Advance.

**Comment by univrsal** [comment]
If you want to use keyboard input you'll have to set the overlay type to 0

**Comment by ipodtouchdude** [comment]
Not sure how to do the overlay type 0 as it show up blank. All I want to do is use that texture (still working on it) and map the buttons to the keyboard. So for example A of the gameboy would be keyboard X and B of the gameboy would be keyboard Z and so on.

![test](https://user-images.githubusercontent.com/4242224/79124120-8bf56080-7d93-11ea-80b9-1073216f8a72.png)

**Comment by univrsal** [comment]
https://vimeo.com/238275966

**Comment by ipodtouchdude** [comment]
I've watched the video but you are showing columns and rows. I want to added the like you do with controllers. So you can set them on a background and at custom positions.

**Comment by univrsal** [comment]
That's not currently possible

**Comment by ipodtouchdude** [comment]
Would it be possible to add it in a future release please. If it is possible.

**Comment by univrsal** [comment]
It's already possible in version five, but I've been promising a release for that for way too long so I can't say when it's done

**Comment by univrsal** [comment]
This feature is now usable with the latest [pre-release](https://github.com/univrsal/input-overlay/releases)
