### ISSUE TITLE
Bigger keys shifting

### ISSUE THREAD

**Issue by Lock-The-Door** [univrsal/input-overlay#111]
When I try to make a key that's bigger than other keys, the key always shifts one pixel to the left for some reason. I did check and all the spacing was right and everything in the ini file seems fine but I can't get it to move back into the intended spot. However, all the other 1x1 keys seem perfectly fine.

![image](https://user-images.githubusercontent.com/49077851/79345604-52416880-7eff-11ea-81b1-9e8ed12c49a5.png)
![image](https://user-images.githubusercontent.com/49077851/79346062-e7dcf800-7eff-11ea-8187-af17cf9463ce.png)

I guess shift just really wanted to shift and space just wanted some space.

**Comment by univrsal** [comment]
I added an offset to center the spacebar at some point, I guess that is causing it. I'll try and look into it. Can you give me your texture and config?

**Comment by Lock-The-Door** [comment]
Here:
[Keyboard.zip](https://github.com/univrsal/input-overlay/files/4490161/Keyboard.zip)

**Comment by carb-ohydrate** [comment]
happens for me too, seems to shift by 1px per width value past one

compare 1x width spacebar with 4x width spacebar
![image](https://user-images.githubusercontent.com/77798953/105384494-24442f80-5bc7-11eb-9c08-923c687a2010.png)
![image](https://user-images.githubusercontent.com/77798953/105384542-34f4a580-5bc7-11eb-98c9-c59a1bb70c31.png)

**Comment by Fiona1729** [comment]
Also was able to reproduce this one

**Comment by univrsal** [comment]
The new version now uses a different config system, which fixes this issue.
