### ISSUE TITLE
Input Overlay option not showing when adding a source

### ISSUE THREAD

**Issue by julian-molina** [univrsal/input-overlay#112]
**Describe the bug**
After installation following the guide, the Input Overlay option does not show up in the list of Sources.

To confirm I followed the guide... this is my check list.

1. Copy the contents of the ```plugin``` folder (```data``` and ```obs-plugins```) into ```obs-studio\```.

1. Verified the input overlay locale files where copied to the destination.

1. Verified the input overlay dlls where copied fine.

1. Open OBS, the input overlay option doesn't show.

1. Open OBS as admin, still doesn't show.

1. Installed Visual C++ 2015 Redistributable and open as admin, still doesn't show.

**To Reproduce**
Steps to reproduce the behavior: The installation sequence described above.

**Expected behavior**
I expect the Input Overlay option to show up when I go to add a new source, like in the video:

![image](https://user-images.githubusercontent.com/13994516/80484051-618cd100-8957-11ea-82b5-c2a39b14a9d3.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/13994516/80484275-bb8d9680-8957-11ea-8657-1cffd4378312.png)

**Additional information:**
- Plugin version: [This release](https://github.com/univrsal/input-overlay/releases/tag/v4.8)

- Full OBS Studio write_log: [2020-04-28 13-33-08.txt](https://github.com/univrsal/input-overlay/files/4545529/2020-04-28.13-33-08.txt)

**Additional context**

**Comment by univrsal** [comment]
The log says that it was loaded, so it should show up, but your obs studio version is outdated, so please update to the latest version (25.0.8) and see if that helps.

**Comment by julian-molina** [comment]
Thanks for the prompt response. Indeed, updating to the latest version of OBS solved the problem and I'm now up and running. Thank you very much for sharing this plug in. It's awesome and I'm going to make sure I give credit in my videos.
