### ISSUE TITLE
Input not registering on Input History/Pad

### ISSUE THREAD

**Issue by sunofapitch** [univrsal/input-overlay#116]
Hello !!
 
I managed setting up the plugin , i added InputOverlay on my scenes
and i used the gamepad preset with its ini file.
I get the controller shown on the screen just fine but no matter what i press it doesnt register anything.
Tried it with both Xbox gamepad and the Dualshock4 (which i m using) same non respontiveness on both , any idea?

**Comment by univrsal** [comment]
I need the full obs-studio log. Are you using input history or input overlay? I think that input history doesn't support game pad input.

**Comment by sunofapitch** [comment]
Hello and thanks for the reply !!
I m using Input Overlay as mentioned on post , i misstyped it on the thread title.
Here's the log history , hope i pasted the right one

[2020-05-15 03-55-49.txt](https://github.com/univrsal/input-overlay/files/4631736/2020-05-15.03-55-49.txt)
[2020-05-15 02-11-39.txt](https://github.com/univrsal/input-overlay/files/4631738/2020-05-15.02-11-39.txt)
[2020-05-15 03-53-59.txt](https://github.com/univrsal/input-overlay/files/4631739/2020-05-15.03-53-59.txt)

**Comment by univrsal** [comment]
Can you take a screenshot of your input overlay source? Dualshock won't work without a thirdparty tool like [DS4Windows](http://ds4windows.com) or [DS4 Tool](https://ds4tool.com), but the xbox controller should work

**Comment by sunofapitch** [comment]
https://imgur.com/a/7zRn4Ay 

I think that's the case though, i only have Ps4 Dualshock pad and i don't use ds4windows/ds4 tools anymore, 
since steam has added built in controller support; and last time i had drivers from the mentioned programs ,pad malfuctioned (on steam games at least) in many ways or wasn't recognized until i removed those , might redownload them just to check and let ya know

**Comment by univrsal** [comment]
Have you considered checking the box that says "Gamepad overlay"?

**Comment by sunofapitch** [comment]
Yeah i tested that as well on both dualshock/xbox fonts & inis , in all possible player positions (0-3) to no avail. I ve also tried unistalling/reinstalling OBS and adding only the input overlay plugins, which didn't change anything either.
For what it matters , i've been using a different one which is a web plugin for some time
https://gamepadviewer.com/ and my inputs are shown on that one, so i guess it's lack of ds4 tools
we discussed above. I'm still considering installing thirdparty but i m afraid of it messing up again some functionality on steam games. If it can help you though, let me know and i shall .

**Comment by univrsal** [comment]
DirectInput should now be supported in the latest pre-release. I could only test it with an xbox gamepad though.
