### ISSUE TITLE
Cannot get arrow keys to register

### ISSUE THREAD

**Issue by deoxykev** [univrsal/input-overlay#118]
I'm using the following keycodes from the [libuiohook library:](https://github.com/kwhat/libuiohook/blob/1.1/include/uiohook.h) in my `.ini` file for my overlay 

```
// Begin Cursor Key Zone
#define VC_UP                                    0xE048
#define VC_LEFT                                  0xE04B
#define VC_RIGHT                                 0xE04D
#define VC_DOWN                                  0xE050
// End Cursor Key Zone
```

But they seem to map to the arrow keys on the numpad, not the traditional arrow keys that are usually next to the CTRL key on the right. 

How do I map the traditional arrow keys?

---
### Os Version
```
WindowsBuildLabEx                                       : 19041.1.amd64fre.vb_release.191206-1406
WindowsCurrentVersion                                   : 6.3
WindowsEditionId                                        : Professional
WindowsProductName                                      : Windows 10 Pro
```

### Input Overlay Version
```
v4.8b.win32.64
```

**Comment by univrsal** [comment]
Try these:
```
#define VC_KP_DOWN                               0xEE00 | VC_KP_2
#define VC_KP_LEFT                               0xEE00 | VC_KP_4
#define VC_KP_RIGHT                              0xEE00 | VC_KP_6
#define VC_KP_UP                                 0xEE00 | VC_KP_8
```
for VC_KP_DOWN it would be ``0xEE00`` + VC_KP_2 which is ``0x0050`` so ``0xEE50``

**Comment by deoxykev** [comment]
Thank you so much! I was going crazy trying to figure it out.

**Comment by univrsal** [comment]
Yeah this is a pretty stupid error. I might have to talk to the developer of libuiohook and see why this is the case
