### ISSUE TITLE
Input History Request

### ISSUE THREAD

**Issue by Nezumi72** [univrsal/input-overlay#12]
Input History fails to capture duplicate key presses. (see attached)
Also if possible an auto clear of history based on update interval or similar would be appreciated.

![input history screen grab](https://user-images.githubusercontent.com/34515152/33947420-f6c3c9a0-dfe9-11e7-972c-6a46d6b91d55.png)

**Comment by univrsal** [comment]
I intentionally left out repeated keys, because I thought it wasn't useful but I guess I'll add an option. I'll also add an option to auto clear when no keys were pressed for a certain time

**Comment by univrsal** [comment]
Alright, have a look at [v2.1.2](https://github.com/univrsal/input-overlay/releases/tag/v2.1.2):

![image](https://user-images.githubusercontent.com/8353672/34071070-b8efce1a-e270-11e7-8897-bd4da0435f53.png)
