### ISSUE TITLE
Any preset doesn't work.

### ISSUE THREAD

**Issue by lightmanLP** [univrsal/input-overlay#123]
**Describe the bug**
Any preset doesn't work.

**Additional information:**
- Plugin version
Last
- Full OBS Studio write_log
[2020-06-08 22-47-37.txt](https://github.com/univrsal/input-overlay/files/4747049/2020-06-08.22-47-37.txt)

**Additional context**
win8.1 x64
last OBS Studio version

**Comment by univrsal** [comment]
where did you get the presets from?

**Comment by lightmanLP** [comment]
they were attached in the archive

**Comment by univrsal** [comment]
can you upload the exact preset you were using?

**Comment by lightmanLP** [comment]
I downloaded the latest build now and it works. Before that, I reinstalled it 3 times and it did not work. I really don't know why.
