### ISSUE TITLE
io-cct is nowhere to be found

### ISSUE THREAD

**Issue by demonsako** [univrsal/input-overlay#124]
I hate to be that guy but I can't seem to find this software. 

> This program lets you create config files for overlays. You can download the most recent version of it along the latest release.

There is no download along the latest release.

**Comment by univrsal** [comment]
it's not done yet

**Comment by demonsako** [comment]
> 
> 
> it's not done yet

Ah my apologies.

**Comment by demonsako** [comment]
> 
> 
> > it's not done yet
> 
> Ah my apologies.

Since the thread is open would you mind helping me with something? 

I'm making a new Xbox One controller layout. How would I go about making that work? 

![image](https://user-images.githubusercontent.com/45436850/84071329-5aa7a400-a982-11ea-824d-2ec3e848863e.png)

**Comment by univrsal** [comment]
your best bet is probably to look at the existing gamepad preset and work from there

**Comment by demonsako** [comment]
> 
> 
> your best bet is probably to look at the existing gamepad preset and work from there

Ah. Will do.
