### ISSUE TITLE
Failed to build "io-cct"

### ISSUE THREAD

**Issue by Xiliusha** [univrsal/input-overlay#126]
**Is your feature request related to a problem? Please describe.**
related to #119
I try to build io-cct project and found tons of errors. Finally I compiled the exe file after fixing all the compilation errors, but the localization module still has bug.

**Describe the solution you'd like**
Code review and fix build configuration.

**Describe alternatives you've considered**

**Additional context**
![图片](https://user-images.githubusercontent.com/40131112/84378243-68755780-ac16-11ea-8af3-b7957f956e9d.png)

**Comment by univrsal** [comment]
Yeah the master branch had some issues, the dev branch should work. I haven't looked at the localization issue, but I'll see what I can do.

**Comment by univrsal** [comment]
Fixed with 508ffafacd21483a8bd99cf409384a95bcd9f071
I noticed that file paths which contain non ASCII characters will not work, so you might run into issues with that for now
