### ISSUE TITLE
Preset Configuration

### ISSUE THREAD

**Issue by demonsako** [univrsal/input-overlay#127]
This isn't necessarily a bug but I just wanted to ask how you would recommend going about making a preset. I've done all the work at making the controller overlay, all that's needed is the config file work. 

![Xbox One Overlay](https://user-images.githubusercontent.com/45436850/84583940-d99e4180-adb3-11ea-8ec3-412ce2e59176.png)

I understand that it requires X and Y coordinates on the texture image but I don't know how I would find them. 

...any help?

**Comment by univrsal** [comment]
Have you looked at the gamepad preset that is shipped with the plugin?

**Comment by demonsako** [comment]
> 
> 
> Have you looked at the gamepad preset that is shipped with the plugin?

Yes I have. I changed some of the original image so I somewhat understand how it works. 

Example of that: https://streamable.com/nucqhv

I just don't understand how I'll find the X and Y for positions. 

I also don't understand how it reads. Is it from the center or the very edges?

![image](https://user-images.githubusercontent.com/45436850/84601973-f29d0600-ae38-11ea-863c-1ccdf3efb4ff.png)

![image](https://user-images.githubusercontent.com/45436850/84601978-fdf03180-ae38-11ea-9c52-16757daf1c72.png)

So what I need to know is:

How do I find ``1_item_w=0000`` & ``1_item_h=0000``

Other than that the rest seems simple. 

I also see that some say ``_u=0000`` and ``_v=0000``. Mind elaborating on what these things mean?

**Comment by univrsal** [comment]
The image is basically a coordinate system with the top left being 0,0. ``u`` and ``v`` are x and y, but since x and y are already used in other contexts, u and v are used for textures. ``w`` and ``h`` are the width and height of the item.

**Comment by demonsako** [comment]
> 
> 
> The image is basically a coordinate system with the top left being 0,0. `u` and `v` are x and y, but since x and y are already used in other contexts, u and v are used for textures. `w` and `h` are the width and height of the item.

Thank you! Exactly what I needed to know.

**Comment by demonsako** [comment]
One last thing... A lot of the buttons are circles. Make the X and Y at the very edge like the image shown? 

![image](https://user-images.githubusercontent.com/45436850/84603081-7dcdca00-ae40-11ea-9a0b-c1520f4a1e61.png)
