### ISSUE TITLE
No input overlay option in tools menu

### ISSUE THREAD

**Issue by ask-compu** [univrsal/input-overlay#129]
The plugin loads and shows the overlay and controller input but i don't get the tools menu option to remap the buttons
![Screenshot](https://i.imgur.com/FFrHh0r.png)

[OBS Log.txt](https://github.com/univrsal/input-overlay/files/5078977/2020-08-15.11-28-54.txt)

With the default mapping for my SN30 Pro+ the left stick click doesn't register, the right stick click registers as the left stick click, the xbox/ps home button doesn't register, and the d-pad doesn't register. The analog sticks and the rest of the buttons all register fine though.

**Comment by univrsal** [comment]
that menu doesn't exist in the current release

**Comment by ask-compu** [comment]
ah, then how do i fix the mapping? and when will the new release be out? and why is the wiki showing instructions for something that isn't out yet?

**Comment by univrsal** [comment]
1. You can't, unless you recompile
2. When it's done
3. The wiki states at the top that it's WIP
