### ISSUE TITLE
"Typing mode" for input history

### ISSUE THREAD

**Issue by ecnerwala** [univrsal/input-overlay#131]
**Is your feature request related to a problem? Please describe.**
I'm trying to record streams that involve a lot of typing, and the current input history doesn't work very well. Currently, input-overlay is geared towards displaying which characters are pressed at any given point in time, so when typing quickly the characters sometimes are duplicated on multiple lines of the input history. Also, the maximum of 5 lines of history is pretty crippling when typing fast. I'd like an input history which looks more like a line of typed text (scrolls horizontally).

**Describe the solution you'd like**
I really like the look and feel of Screenkey (https://www.thregr.org/~wavexx/software/screenkey/, Linux only). Main features:
* Characters typed are displayed horizontally, and modified-keys are just included in the stream (like ` C-a ` or ` CTRL-A ` depending on settings).
* Repeats are compressed as `A`, `AA`, `AAA`, `AAA...x4`, `AAA...x5` (with a subscripted `xn`, configurable cutoff)
* When it overflows, text is ellipsized on the left

Screenkey also does a lot of work to faithfully replicate input-methods and backspace behavior, but I think that would be difficult to replicate/make cross-platform (they spawn a phantom window/input box and replay the keystrokes to try to infer what was typed).

**Describe alternatives you've considered**
I'm currently using Screenkey with a window capture, but I'd love something native in OBS.

**Additional context**
I'm interested in spending some time implementing this myself, but I'd love to get some input on whether this feature is welcome and how to get started.

**Comment by univrsal** [comment]
I've already worked on something like this before, even implemented it partially as shown in #32 then kinda just dropped it. I don't even know where the code for it went, but It should be somewhere in the git history. If you want to work on it go ahead, although you'd either have to implement it into the legacy branch, which is what the last release is based on, or into the master/dev branch which is what I'm intending to use for 5.0, which god knows when it'll be finished.

**Comment by univrsal** [comment]
See #122
