### ISSUE TITLE
Preset not working

### ISSUE THREAD

**Issue by ojrchen09cheno** [univrsal/input-overlay#133]
**Describe the bug**
The keyboard extended numeric square preset is not working. I am using the latest version and using the preset that came inside the zip folder. 

**Screenshots**
![image](https://user-images.githubusercontent.com/47124741/92982161-ee4dac80-f46a-11ea-9e43-ca24c03f5f73.png)

**Additional information:**
- Plugin version 
4.8b

- Full OBS Studio write_log
19:54:12.480: CoInitializeEx succeeded: 0x00000001
19:54:12.480: CPU Name: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
19:54:12.480: CPU Speed: 2592MHz
19:54:12.480: Physical Cores: 6, Logical Cores: 12
19:54:12.481: Physical Memory: 16231MB Total, 7305MB Free
19:54:12.481: Windows Version: 10.0 Build 19041 (release: 2004; revision: 450; 64-bit)
19:54:12.481: Running as administrator: false
19:54:12.481: Aero is Enabled (Aero is always on for windows 8 and above)
19:54:12.481: Windows 10 Gaming Features:
19:54:12.481: 	Game Bar: Off
19:54:12.481: 	Game DVR: Off
19:54:12.481: 	Game DVR Background Recording: Off
19:54:12.481: 	Game Mode: Off
19:54:12.483: Sec. Software Status:
19:54:12.484: 	Kaspersky Security Cloud: enabled (AV)
19:54:12.484: 	Microsoft Defender Antivirus: disabled (AV)
19:54:12.485: 	Kaspersky Security Cloud: disabled (FW)
19:54:12.485: 	Windows Firewall: enabled (FW)
19:54:12.485: Current Date/Time: 2020-09-11, 19:54:12
19:54:12.485: Browser Hardware Acceleration: true
19:54:12.485: Portable mode: false
19:54:12.870: OBS 25.0.8 (64-bit, windows)
19:54:12.870: ---------------------------------
19:54:12.891: ---------------------------------
19:54:12.891: audio settings reset:
19:54:12.891: 	samples per sec: 48000
19:54:12.891: 	speakers:        2
19:54:12.892: ---------------------------------
19:54:12.892: Initializing D3D11...
19:54:12.892: Available Video Adapters: 
19:54:12.901: 	Adapter 0: NVIDIA GeForce GTX 1660 Ti
19:54:12.901: 	  Dedicated VRAM: 1987051520
19:54:12.901: 	  Shared VRAM:    4214876160
19:54:12.901: 	  PCI ID:         10de:2191
19:54:12.901: 	  Driver Version: 27.21.14.5206
19:54:12.901: 	  output 0: pos={0, 0}, size={1920, 1080}, attached=true, refresh=144, name=
19:54:12.901: 	  output 1: pos={1920, 0}, size={1920, 1080}, attached=true, refresh=75, name=SB220Q
19:54:12.901: 	Adapter 1: Intel(R) UHD Graphics 630
19:54:12.901: 	  Dedicated VRAM: 134217728
19:54:12.901: 	  Shared VRAM:    4214876160
19:54:12.901: 	  PCI ID:         8086:3e9b
19:54:12.902: 	  Driver Version: 25.20.100.6617
19:54:12.910: Loading up D3D11 on adapter NVIDIA GeForce GTX 1660 Ti (0)
19:54:12.981: D3D11 loaded successfully, feature level used: b000
19:54:12.981: DXGI increase maximum frame latency success
19:54:12.981: D3D11 GPU priority setup failed (not admin?)
19:54:13.411: ---------------------------------
19:54:13.411: video settings reset:
19:54:13.411: 	base resolution:   1920x1080
19:54:13.411: 	output resolution: 1920x1080
19:54:13.411: 	downscale filter:  Lanczos
19:54:13.411: 	fps:               30/1
19:54:13.411: 	format:            NV12
19:54:13.411: 	YUV mode:          601/Partial
19:54:13.411: NV12 texture support enabled
19:54:13.412: Audio monitoring device:
19:54:13.412: 	name: Default
19:54:13.412: 	id: default
19:54:13.412: ---------------------------------
19:54:13.421: [CoreAudio encoder]: Adding CoreAudio AAC encoder
19:54:13.422: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
19:54:13.475: [AMF] Unable to load 'amfrt64.dll', error code 126.
19:54:13.477: [AMF] AMF Test failed due to one or more errors.
19:54:13.477: Failed to initialize module 'enc-amf.dll'
19:54:13.520: [obs-browser]: Version 2.8.6
19:54:13.524: NVENC supported
19:54:13.543: Couldn't find VLC installation, VLC video source disabled
19:54:13.549: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
19:54:13.549: No blackmagic support
19:54:13.554: ---------------------------------
19:54:13.554:   Loaded Modules:
19:54:13.554:     win-wasapi.dll
19:54:13.554:     win-mf.dll
19:54:13.554:     win-dshow.dll
19:54:13.554:     win-decklink.dll
19:54:13.554:     win-capture.dll
19:54:13.554:     vlc-video.dll
19:54:13.554:     text-freetype2.dll
19:54:13.554:     rtmp-services.dll
19:54:13.554:     obs-x264.dll
19:54:13.554:     obs-vst.dll
19:54:13.554:     obs-transitions.dll
19:54:13.554:     obs-text.dll
19:54:13.554:     obs-qsv11.dll
19:54:13.554:     obs-outputs.dll
19:54:13.554:     obs-filters.dll
19:54:13.554:     obs-ffmpeg.dll
19:54:13.554:     obs-browser.dll
19:54:13.554:     input-overlay.dll
19:54:13.554:     image-source.dll
19:54:13.554:     frontend-tools.dll
19:54:13.554:     enc-amf.dll
19:54:13.554:     decklink-ouput-ui.dll
19:54:13.554:     coreaudio-encoder.dll
19:54:13.554:     advanced-scene-switcher.dll
19:54:13.554: ---------------------------------
19:54:13.554: ==== Startup complete ===============================================
19:54:13.567: All scene data cleared
19:54:13.567: ------------------------------------------------
19:54:13.663: WASAPI: Device 'Speakers (Realtek(R) Audio)' [48000 Hz] initialized
19:54:13.664: [Loaded global audio device]: 'Desktop Audio'
19:54:13.664:     - filter: 'Compressor' (compressor_filter)
19:54:13.707: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Desktop Audio)
19:54:13.707: 
19:54:13.712: WASAPI: Device 'Microphone Array (Realtek(R) Audio)' [48000 Hz] initialized
19:54:13.713: [Loaded global audio device]: 'Mic/Aux'
19:54:13.713:     - filter: 'Noise Suppression' (noise_suppress_filter)
19:54:13.713:     - filter: 'Compressor' (compressor_filter)
19:54:13.713:     - filter: 'Limiter' (limiter_filter)
19:54:13.714: [Media Source 'camara borde']: settings:
19:54:13.714: 	input:                   D:/Shit que paso al otro pc/Stream/Overlay - Camara - Transicion/2_Colour_Webcam_Frame.webm
19:54:13.714: 	input_format:            (null)
19:54:13.714: 	speed:                   100
19:54:13.714: 	is_looping:              yes
19:54:13.714: 	is_hw_decoding:          yes
19:54:13.714: 	is_clear_on_media_end:   yes
19:54:13.714: 	restart_on_activate:     yes
19:54:13.714: 	close_when_inactive:     no
19:54:14.202: [window-capture: 'LOL Launcher'] update settings:
19:54:14.202: 	executable: LeagueClientUx.exe
19:54:14.203: [Media Source 'Fondo']: settings:
19:54:14.203: 	input:                   D:/Shit que paso al otro pc/Stream/Stream-Youtube Perfil/diana fondo2.mp4
19:54:14.203: 	input_format:            (null)
19:54:14.203: 	speed:                   100
19:54:14.203: 	is_looping:              yes
19:54:14.203: 	is_hw_decoding:          yes
19:54:14.203: 	is_clear_on_media_end:   yes
19:54:14.203: 	restart_on_activate:     yes
19:54:14.203: 	close_when_inactive:     no
19:54:14.203: [window-capture: 'Edge'] update settings:
19:54:14.203: 	executable: msedge.exe
19:54:14.301: [window-capture: 'Chrome'] update settings:
19:54:14.301: 	executable: chrome.exe
19:54:14.340: [Media Source 'Stinger (Stinger)']: settings:
19:54:14.340: 	input:                   D:/Shit que paso al otro pc/Stream/Overlay - Camara - Transicion/FINAL STINGER.webm
19:54:14.340: 	input_format:            (null)
19:54:14.340: 	speed:                   100
19:54:14.340: 	is_looping:              no
19:54:14.340: 	is_hw_decoding:          no
19:54:14.340: 	is_clear_on_media_end:   yes
19:54:14.340: 	restart_on_activate:     yes
19:54:14.340: 	close_when_inactive:     no
19:54:14.340: Switched to scene 'lol'
19:54:14.341: ------------------------------------------------
19:54:14.341: Loaded scenes:
19:54:14.341: - scene 'lollauncher':
19:54:14.341:     - source: 'Fondo' (ffmpeg_source)
19:54:14.341:     - source: 'LOL Launcher' (window_capture)
19:54:14.341:     - source: 'lista eventos' (browser_source)
19:54:14.341:     - source: 'chat' (browser_source)
19:54:14.341:     - source: 'overlay' (image_source)
19:54:14.341:     - source: 'Camara2' (dshow_input)
19:54:14.341:     - source: 'camara borde' (ffmpeg_source)
19:54:14.341:     - source: 'Rango' (browser_source)
19:54:14.341:     - source: 'Emote' (browser_source)
19:54:14.341:     - source: 'alertas' (browser_source)
19:54:14.341:     - source: 'Sub' (text_gdiplus_v2)
19:54:14.341:         - filter: 'Scroll' (scroll_filter)
19:54:14.341:     - source: 'Donacion' (text_gdiplus_v2)
19:54:14.341:         - filter: 'Scroll' (scroll_filter)
19:54:14.341:     - source: 'Bits' (text_gdiplus_v2)
19:54:14.341:         - filter: 'Scroll' (scroll_filter)
19:54:14.341:     - source: 'Top' (text_gdiplus_v2)
19:54:14.341:         - filter: 'Scroll' (scroll_filter)
19:54:14.341:     - source: 'SubGoal' (text_gdiplus_v2)
19:54:14.341: - scene 'lol':
19:54:14.341:     - source: 'LOL' (game_capture)
19:54:14.341:     - source: 'Camara2' (dshow_input)
19:54:14.341:     - source: 'camara borde' (ffmpeg_source)
19:54:14.341:     - source: 'overlay anytghost' (image_source)
19:54:14.341:     - source: 'Rango' (browser_source)
19:54:14.341:     - source: 'Emote' (browser_source)
19:54:14.341:     - source: 'alertas' (browser_source)
19:54:14.341:     - source: 'Sub' (text_gdiplus_v2)
19:54:14.341:         - filter: 'Scroll' (scroll_filter)
19:54:14.341:     - source: 'Donacion' (text_gdiplus_v2)
19:54:14.341:         - filter: 'Scroll' (scroll_filter)
19:54:14.341:     - source: 'Bits' (text_gdiplus_v2)
19:54:14.341:         - filter: 'Scroll' (scroll_filter)
19:54:14.341:     - source: 'Top' (text_gdiplus_v2)
19:54:14.341:         - filter: 'Scroll' (scroll_filter)
19:54:14.341: - scene 'queue':
19:54:14.341:     - source: 'Fondo' (ffmpeg_source)
19:54:14.341:     - source: 'osu' (game_capture)
19:54:14.341:     - source: 'LOL Launcher' (window_capture)
19:54:14.341:     - source: 'lista eventos' (browser_source)
19:54:14.341:     - source: 'chat' (browser_source)
19:54:14.341:     - source: 'Camara2' (dshow_input)
19:54:14.341:     - source: 'camara borde' (ffmpeg_source)
19:54:14.341:     - source: 'overlay' (image_source)
19:54:14.341:     - source: 'Rango' (browser_source)
19:54:14.341:     - source: 'Emote' (browser_source)
19:54:14.341:     - source: 'alertas' (browser_source)
19:54:14.341:     - source: 'Sub' (text_gdiplus_v2)
19:54:14.341:         - filter: 'Scroll' (scroll_filter)
19:54:14.341:     - source: 'Donacion' (text_gdiplus_v2)
19:54:14.341:         - filter: 'Scroll' (scroll_filter)
19:54:14.341:     - source: 'Bits' (text_gdiplus_v2)
19:54:14.341:         - filter: 'Scroll' (scroll_filter)
19:54:14.341:     - source: 'Top' (text_gdiplus_v2)
19:54:14.341:         - filter: 'Scroll' (scroll_filter)
19:54:14.341:     - source: 'SubGoal' (text_gdiplus_v2)
19:54:14.341: - scene 'browser':
19:54:14.341:     - source: 'Edge' (window_capture)
19:54:14.341:     - source: 'chat' (browser_source)
19:54:14.341:     - source: 'Camara2' (dshow_input)
19:54:14.341:     - source: 'camara borde' (ffmpeg_source)
19:54:14.341:     - source: 'overlay' (image_source)
19:54:14.341:     - source: 'Emote' (browser_source)
19:54:14.341:     - source: 'Sub' (text_gdiplus_v2)
19:54:14.341:         - filter: 'Scroll' (scroll_filter)
19:54:14.341:     - source: 'Donacion' (text_gdiplus_v2)
19:54:14.341:         - filter: 'Scroll' (scroll_filter)
19:54:14.341:     - source: 'Bits' (text_gdiplus_v2)
19:54:14.341:         - filter: 'Scroll' (scroll_filter)
19:54:14.341:     - source: 'Top' (text_gdiplus_v2)
19:54:14.341:         - filter: 'Scroll' (scroll_filter)
19:54:14.341:     - source: 'alertas' (browser_source)
19:54:14.342:     - source: 'SubGoal' (text_gdiplus_v2)
19:54:14.342: - scene 'Record':
19:54:14.342:     - source: 'Chrome' (window_capture)
19:54:14.342: ------------------------------------------------
19:54:14.358: warning: Could not update timestamps for skipped samples.
19:54:14.564: ---------------------------------
19:54:14.564: [DShow Device: 'Camara2'] settings updated: 
19:54:14.564: 	video device: HD User Facing
19:54:14.564: 	video path: \\?\usb#vid_04f2&pid_b64f&mi_00#6&147b4c&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global
19:54:14.564: 	resolution: 1280x720
19:54:14.564: 	flip: 0
19:54:14.564: 	fps: 30.00 (interval: 333333)
19:54:14.564: 	format: MJPEG
19:54:16.031: obs-browser: Uncaught (in promise) Something went wrong. (source: https://streamlabs.com/widgets/emote-wall?token=53A028E1ABF19636FF72:0)
19:54:22.676: User added source 'Teclado' (input-overlay) to scene 'lol'
19:54:30.520: [ccl] Encountered errors when loading 'D:/obs-studio/Input-Overlay/wasd-extended-numeric-square.ini':
19:54:30.520:  [ERROR] Cannot get string value of 'key_col'. Doesn't exist or type mismatch
19:54:30.520:  [ERROR] Value with id 'key_col' does not exist
19:55:05.206: User Removed source 'Teclado' (input-overlay) from scene 'lol'
20:11:01.847: [game-capture: 'LOL'] attempting to hook process: League of Legends.exe
20:11:01.852: [game-capture: 'LOL'] using helper (compatibility hook)
20:11:01.869: [game-capture: 'LOL'] hook not loaded yet, retrying..
20:11:04.880: [game-capture: 'LOL'] attempting to hook process: League of Legends.exe
20:11:05.136: [game-capture: 'LOL'] d3d9 shared texture capture successful
20:11:05.146: [game-capture: 'LOL'] shared texture capture successful
20:12:03.318: User added source 'Teclado' (input-overlay) to scene 'lol'
20:12:08.054: [ccl] Encountered errors when loading 'D:/obs-studio/Input-Overlay/wasd-extended-numeric-square.ini':
20:12:08.054:  [ERROR] Cannot get string value of 'key_col'. Doesn't exist or type mismatch
20:12:08.054:  [ERROR] Value with id 'key_col' does not exist

**Comment by univrsal** [comment]
try opening the ini file and add an empty line at the end of it

**Comment by ImAciidz** [comment]
> try opening the ini file and add an empty line at the end of it

I had the same issue and can confirm that adding an empty line fixed it.

**Comment by Dextructor28** [comment]
I already tried that, and it doesn't seem to be working.

**Comment by ImAciidz** [comment]
> I already tried that, and it doesn't seem to be working.

![image](https://user-images.githubusercontent.com/62849155/94112286-337ec080-fe13-11ea-8eff-189674184beb.png)

If it helps, this is exactly what I did to mine, which fixed the issue for me as I previously mentioned.
