### ISSUE TITLE
Scroll Wheel inputs not recognized while mouse is moving

### ISSUE THREAD

**Issue by ghost** [univrsal/input-overlay#134]
**Describe the bug**
The Scroll Wheel Up and Scroll Wheel Down inputs are not shown when the mouse is moving

**To Reproduce**
Use the Scroll Wheel inputs while moving the mouse.

**Expected behavior**
The mouse wheel inputs should be shown while the mouse is being moved.

**Visual evidence**
I have a short video that I uploaded to my channel, the link is the following:
https://www.youtube.com/watch?v=KPdLwsOtWgc

**Additional information:**
- Plugin version: 4.8
- Full OBS Studio write_log:
12:14:49.425: CoInitializeEx succeeded: 0x00000001
12:14:49.425: CPU Name: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
12:14:49.425: CPU Speed: 2304MHz
12:14:49.425: Physical Cores: 4, Logical Cores: 8
12:14:49.425: Physical Memory: 8041MB Total, 1820MB Free
12:14:49.425: Windows Version: 10.0 Build 18362 (release: 1903; revision: 1082; 64-bit)
12:14:49.426: Running as administrator: true
12:14:49.426: Aero is Enabled (Aero is always on for windows 8 and above)
12:14:49.426: Windows 10 Gaming Features:
12:14:49.426: 	Game Bar: Off
12:14:49.426: 	Game DVR: Off
12:14:49.426: 	Game DVR Background Recording: Off
12:14:49.426: 	Game Mode: Off
12:14:49.427: Sec. Software Status:
12:14:49.428: 	Antivirus de Windows Defender: enabled (AV)
12:14:49.429: 	Firewall de Windows: enabled (FW)
12:14:49.430: Current Date/Time: 2020-09-15, 12:14:49
12:14:49.430: Browser Hardware Acceleration: true
12:14:49.430: Portable mode: false
12:14:49.835: OBS 25.0.8 (64-bit, windows)
12:14:49.835: ---------------------------------
12:14:49.836: ---------------------------------
12:14:49.836: audio settings reset:
12:14:49.836: 	samples per sec: 44100
12:14:49.836: 	speakers:        2
12:14:49.838: ---------------------------------
12:14:49.838: Initializing D3D11...
12:14:49.838: Available Video Adapters: 
12:14:49.850: 	Adapter 0: NVIDIA GeForce GTX 1050
12:14:49.850: 	  Dedicated VRAM: 4214226944
12:14:49.850: 	  Shared VRAM:    4216012800
12:14:49.850: 	  PCI ID:         10de:1c8d
12:14:49.850: 	  Driver Version: 27.21.14.5167
12:14:49.850: 	  output 0: pos={0, 0}, size={1920, 1080}, attached=true, refresh=60, name=
12:14:49.850: 	Adapter 1: Intel(R) UHD Graphics 630
12:14:49.850: 	  Dedicated VRAM: 134217728
12:14:49.850: 	  Shared VRAM:    4216012800
12:14:49.850: 	  PCI ID:         8086:3e9b
12:14:49.851: 	  Driver Version: 27.20.100.7990
12:14:49.855: Loading up D3D11 on adapter NVIDIA GeForce GTX 1050 (0)
12:14:49.905: D3D11 loaded successfully, feature level used: b000
12:14:49.905: DXGI increase maximum frame latency success
12:14:49.905: D3D11 GPU priority setup success
12:14:50.554: ---------------------------------
12:14:50.554: video settings reset:
12:14:50.554: 	base resolution:   1920x1080
12:14:50.554: 	output resolution: 1280x720
12:14:50.554: 	downscale filter:  Bicubic
12:14:50.554: 	fps:               30/1
12:14:50.554: 	format:            NV12
12:14:50.554: 	YUV mode:          601/Partial
12:14:50.554: NV12 texture support enabled
12:14:50.555: Audio monitoring device:
12:14:50.555: 	name: Default
12:14:50.555: 	id: default
12:14:50.556: ---------------------------------
12:14:50.558: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
12:14:50.559: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
12:14:50.631: [AMF] Unable to load 'amfrt64.dll', error code 126.
12:14:50.634: [AMF] AMF Test failed due to one or more errors.
12:14:50.634: Failed to initialize module 'enc-amf.dll'
12:14:50.664: [obs-browser]: Version 2.8.6
12:14:50.667: NVENC supported
12:14:50.697: VLC found, VLC video source enabled
12:14:50.704: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
12:14:50.704: No blackmagic support
12:14:50.708: ---------------------------------
12:14:50.708:   Loaded Modules:
12:14:50.708:     win-wasapi.dll
12:14:50.708:     win-mf.dll
12:14:50.708:     win-dshow.dll
12:14:50.708:     win-decklink.dll
12:14:50.708:     win-capture.dll
12:14:50.708:     vlc-video.dll
12:14:50.708:     text-freetype2.dll
12:14:50.708:     rtmp-services.dll
12:14:50.708:     obs-x264.dll
12:14:50.708:     obs-vst.dll
12:14:50.708:     obs-transitions.dll
12:14:50.708:     obs-text.dll
12:14:50.708:     obs-qsv11.dll
12:14:50.708:     obs-outputs.dll
12:14:50.708:     obs-filters.dll
12:14:50.708:     obs-ffmpeg.dll
12:14:50.708:     obs-browser.dll
12:14:50.708:     logi_obs_plugin_x64.dll
12:14:50.708:     input-overlay.dll
12:14:50.708:     image-source.dll
12:14:50.708:     frontend-tools.dll
12:14:50.708:     enc-amf.dll
12:14:50.708:     decklink-ouput-ui.dll
12:14:50.708:     coreaudio-encoder.dll
12:14:50.708: ---------------------------------
12:14:50.722: ==== Startup complete ===============================================
12:14:50.753: All scene data cleared
12:14:50.753: ------------------------------------------------
12:14:50.788: WASAPI: Device 'Headset Speaker (2- Realtek(R) Audio)' [48000 Hz] initialized
12:14:50.788: [Loaded global audio device]: 'Audio del escritorio'
12:14:50.818: WASAPI: Device 'Headset Mic (2- Realtek(R) Audio)' [44100 Hz] initialized
12:14:50.819: [Loaded global audio device]: 'Mic/Aux'
12:14:50.819:     - filter: 'Noise Suppression' (noise_suppress_filter)
12:14:50.847: adding 46 milliseconds of audio buffering, total audio buffering is now 46 milliseconds (source: Mic/Aux)
12:14:50.847: 
12:14:51.947: Switched to scene 'Shooters (Record)'
12:14:51.961: [game-capture: 'Apex'] attempting to hook process: r5apex.exe
12:14:52.007: [game-capture: 'Apex'] d3d11 shared texture capture successful
12:14:52.020: ------------------------------------------------
12:14:52.020: Loaded scenes:
12:14:52.020: - scene 'Shooters (Record)':
12:14:52.020:     - source: 'Overwatch' (game_capture)
12:14:52.020:     - source: 'Team Fortress 2' (game_capture)
12:14:52.020:     - source: 'HyperScape' (game_capture)
12:14:52.020:     - source: 'Fortnite' (game_capture)
12:14:52.020:     - source: 'Apex' (game_capture)
12:14:52.020:     - source: 'M&KB Layout' (group)
12:14:52.020:         - source: 'Keyboard Overlay' (input-overlay)
12:14:52.020:         - source: 'Mouse Overlay' (input-overlay)
12:14:52.020: ------------------------------------------------
12:14:52.023: [game-capture: 'Apex'] shared texture capture successful
12:15:03.345: [game-capture: 'Apex'] ----------------- d3d11 capture freed ----------------
12:15:03.353: [game-capture: 'Apex'] d3d11 shared texture capture successful
12:15:03.356: [game-capture: 'Apex'] shared texture capture successful
12:15:04.935: Starting recording due to hotkey
12:15:05.027: [jim-nvenc: 'recording_h264'] settings:
12:15:05.027: 	rate_control: CBR
12:15:05.027: 	bitrate:      20000
12:15:05.027: 	cqp:          20
12:15:05.027: 	keyint:       60
12:15:05.027: 	preset:       default
12:15:05.027: 	profile:      high
12:15:05.027: 	width:        1280
12:15:05.027: 	height:       720
12:15:05.027: 	2-pass:       false
12:15:05.027: 	b-frames:     2
12:15:05.027: 	lookahead:    false
12:15:05.027: 	psycho_aq:    true
12:15:05.027: 
12:15:05.041: ---------------------------------
12:15:05.042: [FFmpeg aac encoder: 'Track1'] bitrate: 160, channels: 2, channel_layout: 3
12:15:05.042: 
12:15:05.099: ==== Recording Start ===============================================
12:15:05.099: [ffmpeg muxer: 'adv_file_output'] Writing file 'E:/AAplicaciones/OBS/Videos OBS/2020-09-15 12-15-04.mkv'...
12:15:09.333: Stopping recording due to hotkey
12:15:09.674: [ffmpeg muxer: 'adv_file_output'] Output of file 'E:/AAplicaciones/OBS/Videos OBS/2020-09-15 12-15-04.mkv' stopped
12:15:09.674: Output 'adv_file_output': stopping
12:15:09.674: Output 'adv_file_output': Total frames output: 128
12:15:09.674: Output 'adv_file_output': Total drawn frames: 137
12:15:09.675: ==== Recording Stop ================================================
12:15:09.675: Video stopped, number of skipped frames due to encoding lag: 10/135 (7.4%)
12:17:29.159: [game-capture: 'Apex'] ----------------- d3d11 capture freed ----------------
12:17:29.168: [game-capture: 'Apex'] d3d11 shared texture capture successful
12:17:29.190: [game-capture: 'Apex'] shared texture capture successful
12:18:08.254: [game-capture: 'Apex'] ----------------- d3d11 capture freed ----------------
12:18:08.272: [game-capture: 'Apex'] d3d11 shared texture capture successful
12:18:08.290: [game-capture: 'Apex'] shared texture capture successful
12:21:15.156: [game-capture: 'Apex'] capture window no longer exists, terminating capture
12:21:15.156: [game-capture: 'Apex'] capture stopped
12:25:18.158: [game-capture: 'Apex'] attempting to hook process: r5apex.exe
12:25:18.170: [game-capture: 'Apex'] using helper (compatibility hook)
12:25:18.246: [game-capture: 'Apex'] hook not loaded yet, retrying..
12:25:21.190: [game-capture: 'Apex'] attempting to hook process: r5apex.exe
12:25:21.346: [game-capture: 'Apex'] Hooked DXGI
12:25:21.347: [game-capture: 'Apex'] d3d11 shared texture capture successful
12:25:21.356: [game-capture: 'Apex'] shared texture capture successful
12:28:23.781: [game-capture: 'Apex'] ----------------- d3d11 capture freed ----------------
12:28:23.789: [game-capture: 'Apex'] d3d11 shared texture capture successful
12:28:23.789: [game-capture: 'Apex'] shared texture capture successful
12:28:25.498: [game-capture: 'Apex'] ----------------- d3d11 capture freed ----------------
12:28:25.505: [game-capture: 'Apex'] d3d11 shared texture capture successful
12:28:25.522: [game-capture: 'Apex'] shared texture capture successful
12:28:27.918: [game-capture: 'Apex'] ----------------- d3d11 capture freed ----------------
12:28:27.933: [game-capture: 'Apex'] d3d11 shared texture capture successful
12:28:27.960: [game-capture: 'Apex'] shared texture capture successful
12:29:00.306: [jim-nvenc: 'recording_h264'] settings:
12:29:00.306: 	rate_control: CBR
12:29:00.306: 	bitrate:      20000
12:29:00.306: 	cqp:          20
12:29:00.306: 	keyint:       60
12:29:00.306: 	preset:       default
12:29:00.306: 	profile:      high
12:29:00.306: 	width:        1280
12:29:00.306: 	height:       720
12:29:00.306: 	2-pass:       false
12:29:00.306: 	b-frames:     2
12:29:00.306: 	lookahead:    false
12:29:00.306: 	psycho_aq:    true
12:29:00.306: 
12:29:00.316: ---------------------------------
12:29:00.317: [FFmpeg aac encoder: 'Track1'] bitrate: 160, channels: 2, channel_layout: 3
12:29:00.317: 
12:29:00.361: ==== Recording Start ===============================================
12:29:00.361: [ffmpeg muxer: 'adv_file_output'] Writing file 'E:/AAplicaciones/OBS/Videos OBS/2020-09-15 12-29-00.mkv'...
12:29:02.505: [game-capture: 'Apex'] ----------------- d3d11 capture freed ----------------
12:29:02.513: [game-capture: 'Apex'] d3d11 shared texture capture successful
12:29:02.523: [game-capture: 'Apex'] shared texture capture successful
12:29:31.943: Stopping recording due to hotkey
12:29:32.314: [ffmpeg muxer: 'adv_file_output'] Output of file 'E:/AAplicaciones/OBS/Videos OBS/2020-09-15 12-29-00.mkv' stopped
12:29:32.314: Output 'adv_file_output': stopping
12:29:32.314: Output 'adv_file_output': Total frames output: 949
12:29:32.314: Output 'adv_file_output': Total drawn frames: 958
12:29:32.315: ==== Recording Stop ================================================

**Additional context**
Nothing else to report

**Comment by univrsal** [comment]
Should be fixed with the latest pre-release
