### ISSUE TITLE
Installer[FEATURE REQUEST]

### ISSUE THREAD

**Issue by DankBoi293** [univrsal/input-overlay#135]
I am thinking of a installer that directly imports the add-on into the OBS program files folder.
kind of like the one you have for [Tuna](https://github.com/univrsal/tuna/releases/tag/v1.4.2)

**Comment by Arridian** [comment]
This would be so great. I can't install it. Can you help me?

**Comment by univrsal** [comment]
I have added installers to the nightly builds, which will be available for the next release. You can see past nightly builds [here](https://github.com/univrsal/input-overlay/actions).
