### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by Arridian** [univrsal/input-overlay#137]
I can't install the plugin, I read and watched the tutorial, but the files I got look nothing like the ones in the tutorial.
What the tutorial Shows:
![image](https://user-images.githubusercontent.com/73617059/99865882-ab424080-2b61-11eb-9765-1ad5f68b646d.png)
What my obs folder looks like:
![image](https://user-images.githubusercontent.com/73617059/99865906-daf14880-2b61-11eb-88cd-2c75359da17e.png)
What the file I download from github looks like:
![image](https://user-images.githubusercontent.com/73617059/99865910-e80e3780-2b61-11eb-9c0b-9652d3d3dc28.png)
Where should I put these files? Which ones do I use?
Thank you so much.

**Comment by univrsal** [comment]
You downloaded the source code, not the actual plugin

**Comment by Arridian** [comment]
Where is the plugin? How do I download that?
