### ISSUE TITLE
Support non-grid layouts

### ISSUE THREAD

**Issue by AaronVickers** [univrsal/input-overlay#138]
Currently, it is impossible to create a layout that is anything other than a grid without creating multiple input overlay layers. I would like to have more freedom with my layouts without having to use multiple layers.

I have already attempted to use different scaling but that caused massively oversized buttons.

I also tried using decimal values for key height, width, row and column but that didn't work either. If you made those support decimal values and stopped treating them strictly as rows and columns then I assume that would work.

**Comment by univrsal** [comment]
This is implemented for version 5, you can play around with test builds [here](https://github.com/univrsal/input-overlay/actions), any entry with a check mark has test builds attached under "artifacts".
