### ISSUE TITLE
Gamepad buttons

### ISSUE THREAD

**Issue by Fubaxiusz** [univrsal/input-overlay#14]
Is it possible to make xinput gamepad buttons to work?

**Comment by univrsal** [comment]
if you can give me a clue on how to query game-pad input through windows it should be doable.
I might look into it myself but it'll take some time

**Comment by Fubaxiusz** [comment]
I found something like this https://docs.microsoft.com/en-us/windows/uwp/gaming/raw-game-controller
But i have no idea if it will help.

**Comment by univrsal** [comment]
thanks I'll take a look at it

**Comment by univrsal** [comment]
Welp, it's done. It took way more effort than I thought it'd would but now it's implemented.
I'll make some finishing touches and make a release

**Comment by Fubaxiusz** [comment]
Great! Thanks man
