### ISSUE TITLE
(5.0 test | io-cct) Duplicate selected element.

### ISSUE THREAD

**Issue by fatihG** [univrsal/input-overlay#141]
It can be a pain to set up multiple similar elements for each of them from scratch.
If you have 2 analogue sticks for example, you have to create them both separately.

It would be nice if it was possible to simply duplicate an element. 
All you would need to do then is just go in there and map it to the Left Stick, if you had already set it up for the Right Stick. 
Same goes for the facebuttons. If you have Triangle set up for example, just duplicate it 3 times and edit it for Square, Circle, etc.

**Comment by univrsal** [comment]
Yeah copy and paste should probably be supported. I also wanted to allow selecting elements

**Comment by univrsal** [comment]
This is now supported on the web version of the tool.
