### ISSUE TITLE
(5.0 test | io-cct) Default Element names - Text Selection, Copying and Pasting.

### ISSUE THREAD

**Issue by fatihG** [univrsal/input-overlay#142]
Since the tool right now doesn't support selecting text or the copying and pasting of it, it is a pain to rename all the elements manually. 
All the elements get 'Unnamed' as its name, it doesn't check if something is already called 'Unnamed', on creation, to add a  number after it. Like Unnamed_01 for example. 
It only gives you a warning when you want to confirm the creation of an element. As you can imagine sitting there and watch the bar go back slowly when hitting backspace is not the most workflow or user friendly. 

It would be nice if certain elements had a default name based on those elements.
If the default for a button element was 'Button_00', its easier to hit backspace twice and type something else instead.
Same for Analogue Sticks, make the default AStick_00 for example.
Button_00 > Button_A
Button_01 > Button_Space
AStick_00 > AStick_Right
Etc.

If the tool automatically increments button names and each element type has a preset default name, just going in there and quickly prototyping will be allot easier to do. 
If someone wouldn't be bothered to rename everything properly, just having all buttons as Button_00, Button_01, Button_02, etc. automatically, would already make this a nicer experience. 

Or if anything... implementation of selecting, copying and pasting text would help as well. 
At the same time, why not both?

**Comment by univrsal** [comment]
This is also possible in the new tool now.
