### ISSUE TITLE
(5.0 test | OBS) Input Overlay in OBS does not match io-cct.exe

### ISSUE THREAD

**Issue by fatihG** [univrsal/input-overlay#143]
The Input Overlay plugin does not work the same as in the io-cct.exe tool. 
None of the buttons register any button inputs, except for the Dpad, which register the wrong button inputs.

Happens without fail when I import my custom .json and .png that was generated in io-cct.exe

**Expected behavior**
Obviously expect the buttons to all work and actually light up what I am pressing.

**Screenshots**
[https://youtu.be/0mcUzKG2CL4](https://youtu.be/0mcUzKG2CL4)

**Additional information:**
[2021-01-09 00-17-46.txt](https://github.com/univrsal/input-overlay/files/5791276/2021-01-09.00-17-46.txt)
- Full OBS Studio write_log
(not sure if this is the correct file)

**Additional context**

**Comment by univrsal** [comment]
the gamepad stuff isn't finished yet. keyboard should work though

**Comment by fatihG** [comment]
Yes, makes sense. 

I figured I'd make a video anyway just in case, since you mentioned it was WIP and the more I can do to break/help the better. 

Also I noticed some dinput and xinput stuff in the code.
Does that mean we would get support for non xbox controllers? (Did you finally buy a DualShock? 🤣)

**Comment by univrsal** [comment]
> Also I noticed some dinput and xinput stuff in the code.
Does that mean we would get support for non xbox controllers? 

Yes and no. I didn't buy a dualshock, but I wrote my own gamepad library which supports direct input and xinput. It also allows rebinding buttons and axis. It works well on it's own but I haven't tested the integration into the plugin

**Comment by fatihG** [comment]
Nice!

If you ever need someone to test a dualshock or a dualsense out for you, just let me know.

**Comment by fatihG** [comment]
Hey, you replied on the forums, but I figure I'd continue replying here.

You mentioned that you hadn't finished the windows side of things as of yet and that the bindings were specific to an xbox gamepad.

When I test my 360 gamepad I get the exact same issue btw. 
Which didn't surprise me as I have been using 360 gamepad emulation anyway.

**Comment by univrsal** [comment]
Well then I guess it might be my gamepad that's wrong. It's not an actual 360 gamepad, just a knock off. Did you set input overlay to Xinput or DInput?

**Comment by fatihG** [comment]
The only option I get is 'Generic Xinput gamepad 0' when I have a 360 pad connected.

I got a knockoff Switch Pro Controller, which windows recognizes as a 360 controller as well. 
I get the same results in OBS with that. 

For my DS4 and DS5, they get recognized as 'Wireless controller'.
When those are plugged in the Gamepad ID is just blank, and it doesn't let me pick anything.

**Comment by univrsal** [comment]
I'll try and do some testing on windows this week.

**Comment by mlugg** [comment]
> the gamepad stuff isn't finished yet. keyboard should work though

Sorry to hijack the issue, but: should mouse input work? The project tracker suggests to me it should be done, but no mouse input at all is registered for me. (Void Linux; OBS Studio 26.1.2; input-overlay master). If this is actually a bug I'll open an issue for it, I just thought it might simply not be working yet :)

**Comment by univrsal** [comment]
The list is more about the element types, not the input. I didn't test mouse and as it seems something's broken.

**Comment by univrsal** [comment]
Fixed with the latest [pre-release](https://github.com/univrsal/input-overlay/releases)
