### ISSUE TITLE
French people

### ISSUE THREAD

**Issue by MrTomaDonPapa** [univrsal/input-overlay#144]
Hello ! Thanks for the plugin! Is it possible to create the AZERTY format for us French? I found a plugin that put the keyboard in French but this one bugged the controller plugin. 

Plugin link found : http://www.mediafire.com/file/z6mffgw7p6b1ym5/Overlay_OBS_Clavier_souris_.rar/file 

Thanks !!!

**Comment by univrsal** [comment]
I won't do it, but I think someone else might have already done it. You can look through the [forum post](https://obsproject.com/forum/threads/input-overlay.72759/) and see if there's one.
