### ISSUE TITLE
Overlay not working with Unity

### ISSUE THREAD

**Issue by spiraloid** [univrsal/input-overlay#145]
**Describe the bug**
I'm trying to use the overlay of keyboard and mouse with the Unity editor.  it works when other windows have focus, but as soon as Unity has the focus, the overlay become non-responsive.  Anyone know of a workaround?

**To Reproduce**
try to use the overlay with unity3d.

**Expected behavior**
expect the overlay to work with unity.

**Screenshots**
![image](https://user-images.githubusercontent.com/36362743/104626859-32380480-564b-11eb-80eb-6282532e22bf.png)

**Comment by univrsal** [comment]
Try running obs studio as administrator
