### ISSUE TITLE
No build/compile instructions

### ISSUE THREAD

**Issue by cerpintext** [univrsal/input-overlay#147]
Not strictly a bug, but there're no instructions or prerequisites specified for building the project and contributing, making it harder to pick up on your own and making posts like these necessary to handle.
Did project structure change drastically enough for build procedure to be affected or something?

None of the links in this section work (for me at least)
https://github.com/univrsal/input-overlay/wiki/Contributing
![image](https://user-images.githubusercontent.com/27957371/105498305-52596a80-5cc0-11eb-9bd8-e0cdaf5cb1fc.png)

**Comment by univrsal** [comment]
The links just point to the folders in the repository. The compiling link works though. I updated it to include both the legacy branch and the master branch.
