### ISSUE TITLE
deps/mongoose not pulling

### ISSUE THREAD

**Issue by cerpintext** [univrsal/input-overlay#148]
**Describe the bug**
Following the Build the plugin (master branch, v5.0 and up) for Windows 10 and set up OBS-Studio build env, on the next step running `$ git clone --recursive https://github.com/univrsal/input-overlay.git` results in this error:
```
Cloning into '<path>/input-overlay/deps/mongoose'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'https://github.com/cesanta/mongoose/' into submodule path '<path>/overlays/input-overlay/deps/mongoose' failed
Failed to clone 'deps/mongoose'. Retry scheduled
...
Failed to clone 'deps/mongoose' a second time, aborting
``` 

I am not sure what I am missing specifically, and looking around in the mongoose repo etc hasn't been fruitful so far.

**Comment by univrsal** [comment]
Just did a fresh clone and couldn't reproduce this. Seems to be an issue on your side. The library isn't used yet anyways

**Comment by cerpintext** [comment]
what the heck. I wish I knew what specifically to reproduce it, but I honestly don't

**Comment by cerpintext** [comment]
Was there any initial first time setup you might've done months back?

**Comment by univrsal** [comment]
No, even if I did I would've seen it when I did a fresh clone

**Comment by cerpintext** [comment]
Update: using ssh in .submodules instead of https let me clone the sub-module properly, so that might be an option to make note of in-case someone else needs it in the future.

**Comment by univrsal** [comment]
It probably was the trailing '/' in the url
