### ISSUE TITLE
Keys overlay each other instead of appearing next to each other

### ISSUE THREAD

**Issue by finndrude** [univrsal/input-overlay#149]
I've followed the instruction video on how to customise the layout, but every time I load it in OBS, it stacks my columns on top of each other rather than displaying them as columns... 

Here's the content of my .ini file:
![key overlay ini](https://user-images.githubusercontent.com/77978446/105723867-2e479480-5f1f-11eb-9e8a-528ae55e66b3.png)

I've attached my texture file
![hp-keys](https://user-images.githubusercontent.com/77978446/105723532-ce50ee00-5f1e-11eb-9564-d0405112418e.png)

Also the link for the key names doesn't seem to be working for me?

Thanks for any help in advance!

**Comment by cerpintext** [comment]
Right off the bat, here is a working version of the keycode link:
https://github.com/kwhat/libuiohook/blob/f4bb19be8aee7d7ee5ead89b5a89dbf440e2a71a/include/uiohook.h#L133

**Comment by univrsal** [comment]
Try adding an empty line at the end. The config parser seems to break when it's missing.

**Comment by finndrude** [comment]
You guys are lifesavers!!! Thanks so much for the link and the empty line did the trick!
