### ISSUE TITLE
OBS Studio Version: 20.1.3 After replacing the file, start OBS did not find in the add "Input Overlay"

### ISSUE THREAD

**Issue by Arnaud-Github** [univrsal/input-overlay#15]
OBS Studio Version: 20.1.3 After replacing the file, start OBS did not find in the add "Input Overlay"

**Comment by univrsal** [comment]
Hmm must be something on your end then because it works just fine here:
![obs](https://w.wew.wtf/srjwqi.PNG)

**Comment by Arnaud-Github** [comment]
Now it's fine, but the Zowie EC-2 mouse clicks the side button below and the OBS shows it is the side button clicked on.

![](https://ws1.sinaimg.cn/large/e2f35984gy1fn22psjsfzj202p03fq2q.jpg)
![](https://ws1.sinaimg.cn/large/e2f35984gy1fn22pwkiayj202u03iq2q.jpg)

**Comment by Arnaud-Github** [comment]
In addition, is there a template of PUBG? Thank you!

**Comment by univrsal** [comment]
As for the issue with the mouse try [this](https://w.wew.wtf/cvaqmx.ini) ini file
There's no preset for PUBG since I do not have the time to make presets for every game.
But if you feel like you have the time you can look at [this video](https://vimeo.com/238275966) and try to make your own.

**Comment by fragmental** [comment]
The folder in the v3 zip is called "plugin" instead of "obs-plugins"

**Comment by univrsal** [comment]
The folder "obs-plugins" is inside it though alongside "data" like it always has been

**Comment by fragmental** [comment]
Correct.  I must have been confused.

**Comment by univrsal** [comment]
I'll close this one, since the presets have been fixed
