### ISSUE TITLE
master branch: Causes OBS UI to hang on Linux

### ISSUE THREAD

**Issue by HugLifeTiZ** [univrsal/input-overlay#150]
Hi there. I've compiled this plugin for use with the Flatpak version of OBS on Linux and it *seems* to load fine, but the UI immediately hangs with it loaded. The tray icon does not appear, and none of the UI elements can be interacted with, but the preview continues to update in real-time. In fact, the preview is the *only* thing that updates. If I switch focus to another window and switch back, none of the Qt widgets appear; only the preview. The window manager intervenes and offers to kill the program when it notices it's not responding to close requests, but OBS continues running in the background.

I did get the legacy branch to install and run by building it as an extension Flatpak, and building and installing libuiohook as part of the process, but it does not correctly detect my dpad, and there seems to be no way to configure any mappings.

There aren't any input overlay solutions for Linux that actually seem to work aside from this one--and I'm thankful you bothered at all--so I'm very happy to help you in any way that I can. :)

**Comment by univrsal** [comment]
Yeah there's a deadlock with the gamepad binding UI. I already fixed it, but I changed some other stuff, so the master branch most likely won't work for now. Have you tried https://gamepadviewer.com? Last time I checked it worked fine with the browser source on linux.

**Comment by HugLifeTiZ** [comment]
Browser-based gamepad viewers aren't working in either the external browser plugin or the internal one for the OBS Flatpak, and that's probably related to the fact that gamepad viewers aren't working in Chromium either. They don't normally work in Firefox, but if I override to expose `/run/udev` to the sandbox, they suddenly do work. But that doesn't work for Chromium. I wonder what else Chromium--and hence, CEF--needs to see gamepads. I would use minipadder if I could, because that interface is super nice, but it's probably less resource usage if I can replicate the look in this plugin.

**Comment by univrsal** [comment]
If you want to use input overlay you're gonna need patience because I have no estimate on when it'll be done.

**Comment by HugLifeTiZ** [comment]
Entirely understandable. In the meantime, I've been trying to see what I can do to get gamepad input working in browser sources. Best wishes, I'm cheering for you. :)

**Comment by univrsal** [comment]
Fixed with the latest [pre-release](https://github.com/univrsal/input-overlay/releases)
