### ISSUE TITLE
DualShock not working (PC, USB)

### ISSUE THREAD

**Issue by ilegacy** [univrsal/input-overlay#151]
**Describe the bug**
I've setup the plugin and it works perfectly fine for keyboard / mouse / xbox gamepad. But my PS4/USB-Controller which I've connected via USB-Cable to my PC does not get noticed. I can use it to play my game, but the OBS-Plugin does not register any button presses nor stick-movement. I also tried to use a different controller ID (1 instead of 0) but this did not help.

**To Reproduce**
- Connect PS4 controller via usb cable to pc
- use the dualshock4-preset
- see, that nothing is registered

**Expected behavior**
- the buttons and sticks of my controller should be registered and shown in the graphic of the plugin

**Screenshots**

**Additional information:**
- Plugin version: v4.7.4b

12:15:50.288: CPU Name: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
12:15:50.288: CPU Speed: 3600MHz
12:15:50.288: Physical Cores: 8, Logical Cores: 16
12:15:50.288: Physical Memory: 32699MB Total, 25366MB Free
12:15:50.288: Windows Version: 10.0 Build 18363 (release: 1909; revision: 1316; 64-bit)
12:15:50.288: Running as administrator: false
12:15:50.288: Aero is Enabled (Aero is always on for windows 8 and above)
12:15:50.288: Windows 10 Gaming Features:
12:15:50.288: 	Game DVR: On
12:15:50.290: Sec. Software Status:
12:15:50.291: 	Windows Defender Antivirus: enabled (AV)
12:15:50.292: 	Windows-Firewall: enabled (FW)
12:15:50.292: Current Date/Time: 2021-01-28, 12:15:50
12:15:50.292: Browser Hardware Acceleration: true
12:15:50.292: Portable mode: false
12:15:50.567: OBS 26.1.1 (64-bit, windows)
12:15:50.567: ---------------------------------
12:15:50.568: ---------------------------------
12:15:50.568: audio settings reset:
12:15:50.568: 	samples per sec: 48000
12:15:50.568: 	speakers:        2
12:15:50.570: ---------------------------------
12:15:50.570: Initializing D3D11...
12:15:50.570: Available Video Adapters: 
12:15:50.572: 	Adapter 0: NVIDIA GeForce RTX 2080 Ti
12:15:50.572: 	  Dedicated VRAM: 2994733056
12:15:50.572: 	  Shared VRAM:    4258938880
12:15:50.572: 	  PCI ID:         10de:1e07
12:15:50.572: 	  Driver Version: 27.21.14.5671
12:15:50.572: 	  output 0: pos={0, 0}, size={5120, 1440}, attached=true, refresh=60, name=C49RG9x
12:15:50.577: Loading up D3D11 on adapter NVIDIA GeForce RTX 2080 Ti (0)
12:15:50.618: D3D11 loaded successfully, feature level used: b000
12:15:50.618: DXGI increase maximum frame latency success
12:15:50.618: D3D11 GPU priority setup failed (not admin?)
12:15:50.948: ---------------------------------
12:15:50.948: video settings reset:
12:15:50.948: 	base resolution:   1920x1080
12:15:50.948: 	output resolution: 1920x1080
12:15:50.948: 	downscale filter:  Bicubic
12:15:50.948: 	fps:               30/1
12:15:50.948: 	format:            NV12
12:15:50.948: 	YUV mode:          709/Partial
12:15:50.948: NV12 texture support enabled
12:15:50.949: Audio monitoring device:
12:15:50.949: 	name: Default
12:15:50.949: 	id: default
12:15:50.952: ---------------------------------
12:15:50.960: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
12:15:50.961: Failed to load 'en-US' text for module: 'decklink-captions.dll'
12:15:50.962: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
12:15:50.988: [AMF] Unable to load 'amfrt64.dll', error code 126.
12:15:50.990: [AMF] AMF Test failed due to one or more errors.
12:15:50.990: Failed to initialize module 'enc-amf.dll'
12:15:51.010: [obs-browser]: Version 2.9.1
12:15:51.010: [obs-browser]: CEF Version 75.1.16+g16a67c4+chromium-75.0.3770.100
12:15:51.015: NVENC supported
12:15:51.092: VLC found, VLC video source enabled
12:15:51.099: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
12:15:51.100: No blackmagic support
12:15:51.104: ---------------------------------
12:15:51.104:   Loaded Modules:
12:15:51.104:     win-wasapi.dll
12:15:51.104:     win-mf.dll
12:15:51.104:     win-dshow.dll
12:15:51.104:     win-decklink.dll
12:15:51.104:     win-capture.dll
12:15:51.104:     vlc-video.dll
12:15:51.104:     text-freetype2.dll
12:15:51.104:     rtmp-services.dll
12:15:51.104:     obs-x264.dll
12:15:51.104:     obs-vst.dll
12:15:51.104:     obs-transitions.dll
12:15:51.104:     obs-text.dll
12:15:51.104:     obs-qsv11.dll
12:15:51.104:     obs-outputs.dll
12:15:51.104:     obs-filters.dll
12:15:51.104:     obs-ffmpeg.dll
12:15:51.104:     obs-browser.dll
12:15:51.104:     input-overlay.dll
12:15:51.104:     image-source.dll
12:15:51.104:     frontend-tools.dll
12:15:51.104:     enc-amf.dll
12:15:51.104:     decklink-ouput-ui.dll
12:15:51.104:     decklink-captions.dll
12:15:51.104:     coreaudio-encoder.dll
12:15:51.104: ---------------------------------
12:15:51.104: ==== Startup complete ===============================================
12:15:51.108: All scene data cleared
12:15:51.108: ------------------------------------------------
12:15:51.144: WASAPI: Device 'Speakers (USB Audio CODEC )' [48000 Hz] initialized
12:15:51.144: [Loaded global audio device]: 'Desktop‐Audio'
12:15:51.145: [WASAPISource::TryInitialize]:[Microphone (5- USB Audio CODEC )] Failed to activate client context: 88890004
12:15:51.145: [WASAPISource::WASAPISource] Device '{0.0.1.00000000}.{b00b744a-26b6-4172-bf5f-01d54bb52bed}' not found.  Waiting for device
12:15:51.145: [Loaded global audio device]: 'Mikrofon/AUX‐Audio'
12:15:51.145: [window-capture: 'Fensteraufnahme'] update settings:
12:15:51.145: 	executable: Engine-Vulkan.exe
12:15:51.145: 	method selected: Automatic
12:15:51.145: 	method chosen: BitBlt
12:15:51.145: 
12:15:51.146: [duplicator-monitor-capture: 'Bildschirmaufnahme 2'] update settings:
12:15:51.146: 	display: 1 (5120x1440)
12:15:51.146: 	cursor: true
12:15:51.146: [duplicator-monitor-capture: 'Bildschirmaufnahme'] update settings:
12:15:51.146: 	display: 1 (5120x1440)
12:15:51.146: 	cursor: true
12:15:51.147: [duplicator-monitor-capture: 'Middle'] update settings:
12:15:51.147: 	display: 1 (5120x1440)
12:15:51.147: 	cursor: true
12:15:51.147: Switched to scene 'Scene'
12:15:51.147: ------------------------------------------------
12:15:51.147: Loaded scenes:
12:15:51.147: - scene 'Scene':
12:15:51.147:     - source: 'Bildschirmaufnahme' (monitor_capture)
12:15:51.147:     - source: 'Bildschirmaufnahme 2' (monitor_capture)
12:15:51.147:     - source: 'Middle' (monitor_capture)
12:15:51.147:     - source: 'Fensteraufnahme' (window_capture)
12:15:51.147:     - source: 'Input Overlay' (input-overlay)
12:15:51.147: ------------------------------------------------
12:16:02.220: User added source 'Input History' (input-history) to scene 'Scene'
12:16:36.773: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Desktop‐Audio)
12:16:36.773:

**Comment by univrsal** [comment]
You need an xinput compatible device. That means that you'll need to use something like DS4Windows or similar.
