### ISSUE TITLE
How do I get the keyboard texture  to work? Someone pls send file for keyboard texture 

### ISSUE THREAD

**Issue by DarkLeGend56** [univrsal/input-overlay#152]
I cant use the Image for the keyboard Texture

**Comment by univrsal** [comment]
Don't use the preview image, use the actual texture.

**Comment by DarkLeGend56** [comment]
What texture? Where do I find it?

**Comment by DarkLeGend56** [comment]
> Don't use the preview image, use the actual texture.

Where do I find the texture? Where in the file?

**Comment by univrsal** [comment]
Have you watched the tutorial?
