### ISSUE TITLE
Ghost Mouse Input to game

### ISSUE THREAD

**Issue by ultimate-tester** [univrsal/input-overlay#157]
**Describe the bug**
Whenever I play MW3 with either a keyboard overlay or mouse overlay enabled, I'm getting ghost mouse input in game. What I mean with this is that there's "extra" mouse movement added to my normal mouse movement or simply completely random input added to the game. This results in abrupt mouse movements over which I have no control. This behavior started with this plugin and disappeared when unloading this plugin.

**To Reproduce**
Steps to reproduce the behavior: Load plugin, put a mouse overlay and play MW3.

**Expected behavior**
There should be no ghost input at all

**Screenshots**
N/A

**Additional information:**
- **Plugin version** input-overlay.v4.8b.win32.64, **UPDATE:** also tested on the latest version found in _Artifact_ of latest _Action_
- **Full OBS Studio write_log:** Please standby while I'm trying to find this file...

**Additional context**
Pretty standard setup. I have Razer equipment with Razer Central installed, could there be interference?

**Comment by univrsal** [comment]
You'll probably need to use the monitor center to properly calculate the mouse movement
