### ISSUE TITLE
Flathub package for input-overlay plugin

### ISSUE THREAD

**Issue by HugLifeTiZ** [univrsal/input-overlay#158]
Hi there. So I did some work on the OBS Studio Flathub package to enable extension packages for plugins. I've submitted obs-websockets and I'll be submitting the legacy branch of this plugin as well (since 5.0 is still in development). Do you want to have maintainership rights on the resulting repo?

Here's some information on app submission to Flathub: https://github.com/flathub/flathub/wiki/App-Submission

I don't mind taking on the burden for this if you'd like me to; after all, both this and websockets are pretty much permanent parts of my OBS workflow, and I'll stay invested in keeping them working and updated.

**Comment by univrsal** [comment]
nah, I don't use flatpak so I wouldn't be of much help, thanks for asking though

**Comment by HugLifeTiZ** [comment]
You got it, thanks chief.
