### ISSUE TITLE
More Flexibility

### ISSUE THREAD

**Issue by Polyphysim** [univrsal/input-overlay#159]
I was making a custom preset for the Input Display, but the program limits me to a grid like pattern for my keys. The keys either have to be double in length or height, there's no way to have different size keys

I would love it if you could set a custom parameter for an individual key, instead of the 1,1,1,3 you could have 150x150, 150x150, 150, 150x450. It would allow for more customization

Here's the keyboard design I came up with.

PS. The art is not mine
![Keyboard](https://user-images.githubusercontent.com/71330075/111893717-d3cc3100-89c1-11eb-95a1-d5a3359bfb72.png)
![Keyboard Active](https://user-images.githubusercontent.com/71330075/111893718-d464c780-89c1-11eb-9289-2468aa97233b.png)
![WASD](https://user-images.githubusercontent.com/71330075/111893721-d62e8b00-89c1-11eb-8ade-a69782c67b87.png)
![WASD Active](https://user-images.githubusercontent.com/71330075/111893723-d75fb800-89c1-11eb-9e32-1b27814d1beb.png)

**Comment by univrsal** [comment]
I'm already working on that, you can see a preview of how overlays overlays will be created [here](https://univrsal.github.io/input-overlay/cct).

**Comment by univrsal** [comment]
This feature is now usable with the latest [pre-release](https://github.com/univrsal/input-overlay/releases)
