### ISSUE TITLE
Issues with mouse ini in release v3

### ISSUE THREAD

**Issue by fragmental** [univrsal/input-overlay#16]
So,  the mouse overlay was disappearing when I added the ini.  I looked at it and changed "1_layout_type=0" to "1_layout_type=1" and that fixed it.  However, the side buttons were reversed, so I swapped them and that fixed that.  However mouse wheel up and down weren't working, and I wasn't able to get that to work.

**Comment by univrsal** [comment]
Windows does not offer an easy way to query the mouse wheel, that's why I left that out.
I'll fix the config file though
