### ISSUE TITLE
GamePad Not Showing Inputs

### ISSUE THREAD

**Issue by royaltongue** [univrsal/input-overlay#162]
**Describe the bug**
I am able to add a gamepad as a source, but no inputs are shown.

**To Reproduce**
Download and install input-overlay as described by putting files in OBS root (or by using installer in 5.0 beta)
Add input-overlay source using gamepad texture and settings

**Expected behavior**
Inputs should be shown

**Screenshots**
![image](https://user-images.githubusercontent.com/61848270/114478751-02a68300-9bcd-11eb-80de-675de835dba0.png)
.

**Additional information:**
- I've tried with the latest stable release as well as the 5.0 beta.
- OBS.Live 21.3.8.729
- https://obsproject.com/logs/rbUhh6-54l_-upVR

**Additional context**
Inputs are shown when using input-overlay to display keyboard
I've tried running OBS as admin as well as running it regularly

**Comment by univrsal** [comment]
what gamepad are you using?

**Comment by royaltongue** [comment]
My main controller is a Switch Pro Controller with [ProconXInput](https://github.com/MTCKC/ProconXInput), but I've also tried an Xbox Elite v2 controller.

Both didn't show any inputs

**Comment by univrsal** [comment]
I only have an xbox 360 controller for testing which works fine so I don't really know about newer gamepads

**Comment by univrsal** [comment]
I just realized you're using OBS.live. I can't support that as it heavily modifies obs studio. Also the latest pre-release adds support for DirectInput, which should fix this.
