### ISSUE TITLE
impossible to have it working on ubuntu 20.08

### ISSUE THREAD

**Issue by paillave** [univrsal/input-overlay#163]
The plugin is not listed in the possible sources.
I followed everything that is mentioned on https://obsproject.com/forum/resources/input-overlay.552/
I complied libuiohook, ran the setup and even installed it on the suitable folders.
I copied the plugin input-overlay. in every possible folder.
Can you help me on this?

**Comment by abrac** [comment]
I also have the same issue (on Ubuntu 20.08 as well).

When I run `obs` from terminal, I found the following lines in the output, which indicate that obs-studio could not find the libuiohook library:

```
error: os_dlopen(/home/<username>/.config/obs-studio/plugins/input-overlay/bin/64bit/input-overlay.so->/home/<username>/.config/obs-studio/plugins/input-overlay/bin/64bit/input-overlay.so): libuiohook.so.0: cannot open shared object file: No such file or directory

warning: Module '/home/<username>/.config/obs-studio/plugins/input-overlay/bin/64bit/input-overlay.so' not loaded
```

Do you also have the same error/warning?

Possibly we didn't install libuiohook correctly. I followed the build instructions and then used `sudo checkinstall` to install the library. But when I look in `/usr/lib` I'm not able to find libuihook.so...

**Comment by basile-henry** [comment]
I had the same issue. Solved it with: `sudo ln -s /usr/lib/x86_64-linux-gnu/libuiohook.so /usr/lib/x86_64-linux-gnu/libuiohook.so.0`

**Comment by univrsal** [comment]
You can check if input overlay is missing dependencies via ``$ ldd /path/to/input-overlay.so`` It'll show you which libraries it can't find and where it's expecting them.

**Comment by univrsal** [comment]
Can you try the latest pre release? The linux zip file has a .deb installer which should install it correctly.

**Comment by paillave** [comment]
> Can you try the latest pre release? The linux zip file has a .deb installer which should install it correctly.

It works perfectly! Thanks!
