### ISSUE TITLE
How can I embeded this project into my QT5 project?

### ISSUE THREAD

**Issue by ZHENGYUN01** [univrsal/input-overlay#164]
I want to use input-overlay and record my screen in a QT5 project, could you help me to fix it up?

**Comment by univrsal** [comment]
This project is a plugin for obs studio, it has little to nothing to do with qt. You'd have to basically create your own input visualizer.

**Comment by ZHENGYUN01** [comment]
well, i mean to directlly use your code and create a demo QT project?

**Comment by univrsal** [comment]
Everything up to the point where the overlay is drawn could be reused.
