### ISSUE TITLE
Input Overlay v5 sources not in source list

### ISSUE THREAD

**Issue by Scutterman** [univrsal/input-overlay#168]
**Describe the bug**
After installing Input Overlay version 5, I ran OBS and attempted to add an overlay to the scene.
There's no sources relating to Input Overlay showing up.
The log file says:
`obs_register_source: Tried to register obs_source_info with size 392 which is more than libobs currently supports (384)`

**To Reproduce**
- Install Input Overlay v5 using either the zip file or the executable
- Open OBS
- Add a scene
- Click the "+" to add a source to the scene
- No Input Overlay sources present

**Expected behavior**
Two sources for Input Overlay and History to appear in the Sources list

**Screenshots**
![image](https://user-images.githubusercontent.com/2962703/117576108-778daf80-b0dc-11eb-8b12-4cb5f354d57c.png)

**Additional information:**
- v5.0.0
[2021-05-09 15-30-57.txt](https://github.com/univrsal/input-overlay/files/6447702/2021-05-09.15-30-57.txt)

**Additional context**
Windows 10 x64, OBS Studio x64, UK locale / keyboard / etc.

**Comment by univrsal** [comment]
Please read the big bold text at the top of the release page

**Comment by Scutterman** [comment]
Sorry, I honestly have no idea how I missed that. Thanks for all of the work you've put into this other plugins :-)

**Comment by univrsal** [comment]
No problem, I added that yesterday at some point so maybe it just wasn't there when you dowloaded.

**Comment by lul999** [comment]
I tried that and it still didint work
