### ISSUE TITLE
laptop doesnt exactly work with this

### ISSUE THREAD

**Issue by raytopin** [univrsal/input-overlay#169]
PLEASE FILL THIS OUT CORRECTLY OR THE ISSUE WILL BE CLOSED

(You can remove this text after you've filled out the form)

**Describe the bug**
im on a windows laptop with 2 graphics cards, i think because i use laptop arrow keys input overlay doesnt work (mouse overlay works) so yeah idk what to do
**To Reproduce**
get a laptop and try idk
**Expected behavior**
to work properly/ actually show up on my screen
**Screenshots**

**Additional information:**
- Plugin version
- Full OBS Studio write_log

**Additional context**
watch this video for more unerstanding https://youtu.be/jctZCRSrQM0

**Comment by univrsal** [comment]
No the gpu has nothing to do with this, the arrow preset isn't made for input overlay it's made for input-history.
