### ISSUE TITLE
Can you create new install guide ? 

### ISSUE THREAD

**Issue by krirk0137** [univrsal/input-overlay#17]
i'm download input-overlay-master.zip
but when i open zip file > input-overlay-master folder> preset,data,ccl,.h,.c,.md,.hpp,.cpp    
i dont know what it mean

your old install guild  not have   (   preset,data,ccl,.h,.c,.md,.hpp,.cpp    )   
i really like your input-overlay plugin ^^ but i cant use T^T   
Thank for help

**Comment by univrsal** [comment]
The installation process hasn't changed but here you go:
[Video](https://w.wew.wtf/isgmbt.mp4)
Or as an image:
![howto](https://w.wew.wtf/pcbioa.png)

**Comment by krirk0137** [comment]
OMG THANK YOU!
i really like u video ^_^
