### ISSUE TITLE
Unable to detect up, down, left, and right

### ISSUE THREAD

**Issue by 502milk** [univrsal/input-overlay#171]
Unable to detect up, down, left, and right

5.0 Pre release
OSB 27.0.0-rc4

**Comment by wct666** [comment]
up 0XEE48
down 0XEE50
left 0XEE4B
right 0XEE4D

Please convert hexadecimal

**Comment by 502milk** [comment]
> 向上0XEE48
> 向下0XEE50
> 左0XEE4B
> 右0XEE4D
> 
> 请转换为十进制

After I used the Config creation tool, it incorrectly recognized the key as
up 0XE048
down 0XE050
left 0XE04B
right 0XE04D
