### ISSUE TITLE
Plugin installed but its not showing up as a source

### ISSUE THREAD

**Issue by MasterGamer64** [univrsal/input-overlay#172]
PLEASE FILL THIS OUT CORRECTLY OR THE ISSUE WILL BE CLOSED

(You can remove this text after you've filled out the form)

**Describe the bug**
 I have installed the plugin checked that all the files are in place and there is no source input overlay the settings work fine.
**To Reproduce**
Steps to reproduce the behavior: I am not sure what coused it

**Expected behavior**
When i click add source as a option to be a input overlay.
**Screenshots**
![image](https://user-images.githubusercontent.com/83783476/118361186-d9459200-b592-11eb-9647-4786c38124a0.png)

![image](https://user-images.githubusercontent.com/83783476/118361198-e5315400-b592-11eb-892b-eba155cb604a.png)

![image](https://user-images.githubusercontent.com/83783476/118361208-eebabc00-b592-11eb-9e51-70f05e2acbf1.png)
![image](https://user-images.githubusercontent.com/83783476/118361214-fa0de780-b592-11eb-9193-7a6943696348.png)
![image](https://user-images.githubusercontent.com/83783476/118361217-02662280-b593-11eb-8a3f-dacb58100490.png)

**Additional information:**
- Plugin version: input-overlay.v5.0.0rc1-8d04a98.win
- Full OBS Studio log (https://obsproject.com/logs/a60yduYJV42yvHmZ)

**Additional context**
Other plugins: transition matrix, shaderfilter, move transition, spectralizer, streamFX

**Comment by univrsal** [comment]
Please read the big bold text on the pre release page.
