### ISSUE TITLE
Input-overlay does not show up in sources

### ISSUE THREAD

**Issue by L-i-n-u-x-C-a-t** [univrsal/input-overlay#176]
**Describe the bug**
Input-overlay does not show up in sources.

**To Reproduce**
- Open OBS
- Add a new source

**Expected behavior**
Input-overlay would be available to add as a new source

**Screenshots**
![image](https://user-images.githubusercontent.com/46047705/120113685-e4e0ad80-c17b-11eb-9984-67ea0b2eedea.png)

**Additional information:**
- Plugin version : [v5.0.0-rc1](https://github.com/univrsal/input-overlay/tree/v5.0.0-rc1)
- Full OBS Studio log : https://obsproject.com/logs/NF_0WPzmKqvtbJBq
- OS : Pop!_OS 20.10

**Additional context**
Now i know this might look like any other issues, but as far as i saw, the others had the normal release of OBS, while i have 27.0 release candidate 7 (downloaded [here](https://github.com/obsproject/obs-studio/actions/runs/890270884#artifacts)).
If i'm just stupid, please tell me. (i have built libuiohook from source, tell me if there's also something wrong with that)

**Comment by univrsal** [comment]
You don't need to compile libuiohook anymore, it's statically linked into input overlay, that said are you using the flatpak or snap version of obs studio? If so I can't help you because the sandboxes cause issues with plugins that I don't want to deal with.

**Comment by L-i-n-u-x-C-a-t** [comment]
Thanks for your answer.
I'm using the deb version of OBS, not snap nor flatpak.

**Comment by JulianTexo** [comment]
I have the same issue for OBS 26.1.1 on Windows any ide what I could be doing wrong?

**Comment by univrsal** [comment]
how did you install it?

**Comment by Asditus** [comment]
I also have the same issue. I tried the installer as well as manually installing the script. The input overlay settings show up tho, in the tools menu. I'm using OBS 26.1.1 x64 on windows. Thx for any help!

**Comment by L-i-n-u-x-C-a-t** [comment]
> how did you install the plugin?

I installed it with the .deb installer. Should i try manually?



> I also have the same issue. I tried the installer as well as manually installing the script. The input overlay settings show up tho, in the tools menu. I'm using OBS 26.1.1 x64 on windows. Thx for any help!

you need at least OBS 27.0 release candidate 3...

**Comment by L-i-n-u-x-C-a-t** [comment]
The issue could also come from OBS itself, since it's a release candidate.

**Comment by univrsal** [comment]
Install it manually, the deb installer might not work for pop os

**Comment by L-i-n-u-x-C-a-t** [comment]
> Install it manually, the deb installer might not work for pop os

I still don't have anything. The folder structure looks like this:

```
/home/linuxcat
│
├.config
 ├obs-studio
  ├plugins
   ├input-overlay
    ├plugin
     ├bin
     │├64bit
     │ ├input-overlay.so
     │
     ├data
     │ ├locale
     │  ├de-DE.ini
     │  ├en-US.ini
     │  ├ru-RU.ini
     │
     ├obs-plugins
      ├32bit
       ├input-overlay.dll
       ├input-overlay.pdb
      ├64bit
       ├input-overlay.dll
       ├input-overlay.pdb
```
Please tell me if something is wrong.

**Comment by univrsal** [comment]
You didn't install it correctly and you installed the windows version ontop of the linux version. Please read [this guide](https://github.com/univrsal/input-overlay/wiki/Installation#linux)

**Comment by L-i-n-u-x-C-a-t** [comment]
> You didn't install it correctly and you installed the windows version ontop of the linux version. Please read [this guide](https://github.com/univrsal/input-overlay/wiki/Installation#linux)

oops, my bad! i installed manually and it worked. sorry for the inconvenience!
