### ISSUE TITLE
Can't Add Input Overlay Source

### ISSUE THREAD

**Issue by MattBaileyDesign** [univrsal/input-overlay#177]
**Describe the bug**
Input overlay does not show up in sources. The plugin shows up in the Tools menu, however.

**To Reproduce**
Run OBS (as administrator or normally)
Try to add new source

**Expected behavior**
I can add Input Overlay as a source

**Screenshots**
![image](https://user-images.githubusercontent.com/36735446/120220778-456afb80-c20b-11eb-8908-5d4c85dfc696.png)

**Additional information:**
- Plugin version: v5.0.0
- Full OBS Studio log (https://obsproject.com/logs/d3_lbjVrTT8bt0Yo)

**Additional context**
I tried installing with both the installer and manually, uninstalling both OBS and any Input Overlay files and restarting the system each time.

**Comment by univrsal** [comment]
Please read the big bold text at the top of the pre-release page
