### ISSUE TITLE
No support for full keyboard?

### ISSUE THREAD

**Issue by 5adb0i** [univrsal/input-overlay#178]
**Describe the bug**
After installation, when going to add a source for the keyboard, I select the texture for the full keyboard, but there's no configuration file that displays the full keyboard. I am an audio engineer and producer and want to showcase the shortcuts I use when live streaming.

**To Reproduce**
Install via .exe file, Add Input Overlay Source

**Expected behavior**
Be able to select a configuration file for the full keyboard. It should be there, but there's no file for it.

**Additional information:**
- Plugin version = 5.0 pre release
- Full OBS Studio log = ??? Don't know how to get this

**Comment by univrsal** [comment]
There is no preset for the full keyboard for 5.0, you'll have to create one.
