### ISSUE TITLE
after paste the files,can not see the menu item

### ISSUE THREAD

**Issue by sharljimhtsin** [univrsal/input-overlay#18]
not work on OBS-Studio-20.1.3-Small Chinese-Simpl Language. Windows 7 64 bit.

**Comment by univrsal** [comment]
Are all files in the correct place? Like in this picture:
![img](https://w.wew.wtf/rpwrvo.PNG)

If you installed it correctly can you please give me a log file:
![log](http://www.hnng.moe/f/XNI.png)

**Comment by sharljimhtsin** [comment]
here is the log file.
https://gist.github.com/anonymous/e7dd25075ca66f99a85396515e576948

**Comment by univrsal** [comment]
Okay, so after asking for some help from a obs developer the only clue I got is that you're missing some VC runtimes.
Can you please try and install this version and see if it works for you?
[input-overlay v3.2.zip](https://github.com/univrsal/input-overlay/files/1623857/input-overlay.v3.2.zip)

**Comment by sharljimhtsin** [comment]
@univrsal download & install the new plugin,seems not work.

here is the log:
https://gist.github.com/f7b81c6d95e27408f08187eb005a972e

**Comment by univrsal** [comment]
Alright, so I have two last fixes that hopefully will do the trick:

1. Can you try out this new version: [v3.3](https://w.wew.wtf/bucawz.zip)

2. If this still does not work, you'll probably have to install a newer version of [directx from here](https://www.microsoft.com/zh-cn/download/details.aspx?id=35).

I'm sorry that this is giving you so much issues but I'm not that experienced with these kind of issues :/

**Comment by oapjr** [comment]
I'm using obs 20.1.3 and the only version working for me is v1, v1.1 and v3.3. I didn't try v3.2.

**Comment by univrsal** [comment]
@oapjr Can you give me your log?

**Comment by sharljimhtsin** [comment]
@univrsal okay,use the v3.3 plugins,it works now. thank you!

here is the log: https://gist.github.com/3e096e7744bf491123bd166dab17130c

p.s. sorry for my later reply,the test PC machine is in my office. i can not access it while holiday.

**Comment by univrsal** [comment]
@sharljimhtsin no problem, thanks for the feedback!
