### ISSUE TITLE
Tried to Install .zip and the .exe but no sources or config files exist

### ISSUE THREAD

**Issue by bWildcard** [univrsal/input-overlay#182]
I've tried to install both the Zip and the exe extractor.

opened OBS and added the InPut Overlay source but there are no OverLay Image files anywhere in the OBS DIR or Overlay Config Files....

How does this even work?  Is this Pre-Release missing files?

**Comment by univrsal** [comment]
https://github.com/univrsal/input-overlay/wiki/Usage#input-overlay
