### ISSUE TITLE
Frame perfect accuracy?

### ISSUE THREAD

**Issue by Koblasco** [univrsal/input-overlay#185]
I downloaded this program to check my inputs when speedrunning when I noticed that sometimes (about 50% of the time) the input displayed on IP is 1 frame faster than the game footage.
It throws me off a bit because due to how inconsistently it happens I can't trust the imputs shown in the recordings to be frame perfect.
How do I fix this?
I record at 120 fps, should I assume that IP is even higher than that?
Or maybe it's an OBS quirk that's not correctly synchronizing IP and my game?

**Comment by univrsal** [comment]
What do you mean by "IP"?

**Comment by Koblasco** [comment]
Sorry, that was a typo. I meant IO, as in Input Overlay.
Unfortunately, messing with render delays doesn't solve the problem as it either doesn't change anything or delays IO too much, making the game capture faster than IO.
As I mentioned before, the major issue is the inconsistency.
If IO was consistently 1 frame faster than the game capture it wouldn't be a big deal.
My speculation is that the update interval doesn't sync with my recordings' 60 fps (not 120 btw, that's another mistake on my part).

**Comment by Koblasco** [comment]
I tried another application which displays keystrokes.
This one runs at a consistent 60 fps and as a result it synchronizes with the game footage so I think the issue is indeed the fps.
