### ISSUE TITLE
Pre-release has no Input History

### ISSUE THREAD

**Issue by r3sus** [univrsal/input-overlay#186]
Hi! Thanks a lot for great project!

OBS 27.01 / Win 7 / Pre-Req-s met (VS19, CRT)
Using win installer or extracting zip manually, there's Input_Overlay (fully functional), but no _History. 
Release has both, and working fine.

Thanks.

**Comment by univrsal** [comment]
https://github.com/univrsal/input-overlay/wiki/Usage#WebSocket-Server
