### ISSUE TITLE
Tilde Key, Left super key, and back mouse button are not detected

### ISSUE THREAD

**Issue by Djaenk** [univrsal/input-overlay#187]
**Describe the bug**
The input overlay fails to show the tilde key, left windows key, and lower thumb mouse button being pressed.

**To Reproduce**
Load the attached texture png and overlay json into the plugin. Press the tilde key, left super key, and thumb buttons on the mouse.

**Expected behavior**
When the mentioned keys are pressed, the overlay should highlight the appropriate keys as blue.

**Screenshots**

**Additional information:**
- Plugin version 5.0 Pre release
- Full OBS Studio log https://obsproject.com/logs/sC35vV5DTvBLJueD

**Additional context**
Link to overlay.json contents: https://pastebin.com/a8WiZzvW
Below is my overlay texture.

![Input textures](https://user-images.githubusercontent.com/10876318/125719341-e56815fd-3a31-4298-838c-b807af98932f.png)

**Comment by univrsal** [comment]
Tile seems to work if you manually enter 0x29, meta doesn't seem to work. I can't test the back/forth mouse buttons right now.

**Comment by Prometheus3375** [comment]
> left windows key

It does not work, because you put 0x5B, not 0x**E**5B.

**Comment by univrsal** [comment]
> > left windows key
> 
> It does not work, because you put 0x5B, not 0x**E**5B.

that doesn't work either at least on linux

**Comment by Prometheus3375** [comment]
Seems like Windows and Linux have different keycodes, because 0x5EB works in Win 10.

**Comment by univrsal** [comment]
See #298 for further tracking
