### ISSUE TITLE
Suggestion - Show the pressed keys, but HIDE them when not pressed.

### ISSUE THREAD

**Issue by TheBitcoinBaron** [univrsal/input-overlay#188]
I want to do a tutorial series, but want every key pressed and clicked to be shown, in case I forget to explain them. From looking at this, it looks good, but I dont want the full keyboard/mouse on screen all the time. Just want to have them show after being pressed, even as text would be good, for like 5 seconds... or maybe the show time after pressing could be made optional? At present, this plugin is no good as a full keyboard and mouse on the screen is too much and too distracting.

**Comment by univrsal** [comment]
That's what input history was used for which is now replaced by the browser source and a websocket server, meaning the browser source can visualize input events, you'll need to write some html, css and javascript though.

**Comment by TheBitcoinBaron** [comment]
Amazing so this plugin is only usable by elite web coders, it's not ready
to go, has missing files and no tutorial SHOWING how to set it up from
scratch.... brillliant plugin!!

**Comment by univrsal** [comment]
I'm sorry that you're unhappy with the plugin, I will refund your money immediately
<br/><br/>
<br/><br/>
<br/><br/>
oh, right.
