### ISSUE TITLE
Does not record the inputs during game (does record inputs outside of the game windows)

### ISSUE THREAD

**Issue by infinitysoullol** [univrsal/input-overlay#189]
Hello,
thank you very much for the plugin it looks dope.
I unfortunatly run in this issue :
input recorder does not show any input when my game window is the main focus.
It does show when other screen are the main focus (right now it is working just fine)

**To Reproduce**
Windows 7
OBS 27.0.1 64bits
OBS has a screen capture window on
Downloaded input overlay through the installer.
Downloaded the presets and put them in the C:\Program Files\obs-studio\obs-plugins
Input overlay created in obs : 
values =
C:/Program Files/obs-studio/obs-plugins/input-overlay.v5.0.0rc1-8d04a98.presets/wasd/wasd.png
C:/Program Files/obs-studio/obs-plugins/input-overlay.v5.0.0rc1-8d04a98.presets/wasd/wasd-full.json

I have a AZERTY keyboard, but I switch my language to Qwerty on my LoL window.

Are there any things that I am missing ? Thank you in advance for your help.

**Comment by univrsal** [comment]
Try running obs studio as administrator

**Comment by infinitysoullol** [comment]
It works ! Thank you very much !
