### ISSUE TITLE
DPAD axis support (DS4)

### ISSUE THREAD

**Issue by Shinmera** [univrsal/input-overlay#191]
**Describe the bug**
Certain controllers like the Dual Shock 4 do not report the DPAD as 4 buttons, but rather 2 axes.

**To Reproduce**
Steps to reproduce the behavior: plug in a DS4 controller, open the input-overlay settings, go to the gamepad bindings tab, and attempt to set the dpad input IDs. They instead map to other buttons.

**Expected behavior**
Being able to properly map the dpad buttons as axis directions.

**Additional information:**
- Plugin version: afb4c0831c3270c684e8d95124ae71b7fb47acf2

**Comment by JustAKat** [comment]
This issue may be related to the potential ghost inputs issue: https://github.com/univrsal/input-overlay/issues/175#issuecomment-909092021

**Comment by univrsal** [comment]
See #297 for further tracking
