### ISSUE TITLE
qwerty preset for 5.0

### ISSUE THREAD

**Issue by Prometheus3375** [univrsal/input-overlay#192]
I noticed that the pre-release of v5.0 does not have qwerty preset, so I have just created one. It works properly on Windows 10.
[qwerty.zip](https://github.com/univrsal/input-overlay/files/6872903/qwerty.zip)
Preview and texture were taken from 4.8 presets.

I generated JSON using [this](https://github.com/univrsal/input-overlay/files/6872904/OBS.qwerty.config.generator.txt) Python 3.9 script, feel free to edit it if you need create other config for qwerty texture.

**Comment by yuya495** [comment]
I would be happy if there were more ↑ ↓ ← → keys.

**Comment by Prometheus3375** [comment]
> I would be happy if there were more ↑ ↓ ← → keys.

qwerty texture does not have these keys.

**Comment by yuya495** [comment]
I want additional up / down / left / right arrow keys

**Comment by univrsal** [comment]
Every time that gets asked I delay it by a week.

**Comment by LewkyB** [comment]
I've added the arrows. Could probably use some better alignment, but it works on Ubuntu.

[qwerty-arrows.zip](https://github.com/univrsal/input-overlay/files/6903318/qwerty-arrows.zip)

**Comment by deltadex7** [comment]
I can confirm this works on Arch Linux (x64), however some keys were not registered properly.
* Left Win (Super) not registered, perhaps Linux implementation issue.
* Right Alt registered by left arrow instead of the expected key.
* Right Win (Super) registered by down arrow key, actual key does not exist on my device.
* Right Ctrl not registered despite having the actual key.

I am using standard QWERTY layout. I will follow up for any updates.

**Comment by Prometheus3375** [comment]
@deltadex7, I checked qwerty .ini file of overlay version 4.8 for Linux, and found out that it is identical with .ini file for Windows. So, old overlay also does not work properly in Linux.

I googled a bit, seems like you can get keycodes via `xev`. Then you can edit .json to fix keycodes for Linux. Right Lat have keycode 108 on Linux, 3640 on Windows.

**Comment by univrsal** [comment]
> @deltadex7, I checked qwerty .ini file of overlay version 4.8 for Linux, and found out that it is identical with .ini file for Windows. So, old overlay also does not work properly in Linux.
> 
> I googled a bit, seems like you can get keycodes via `xev`. Then you can edit .json to fix keycodes for Linux. Right Alt have keycode 108 on Linux, 3640 on Windows.

That might work, but keep in mind that the keycodes used by input overlay are provided by libuiohook which uses its own keycode system (it might overlap with keycodes on windows or linux but I'm not sure about that)

**Comment by jamall07** [comment]
how do you use python script for converting it to json?

**Comment by univrsal** [comment]
I'll just close this one for now. I might revise the python script to be able to convert all ini presets at some point.

**Comment by Prometheus3375** [comment]
@jamall07 I do not understand the question. I've just defined associations key name -> (keycode, row, column, width, height). Then I defined lines. And finally, I went through all lines to generates JSON for each key, added editor and overlay information, and saved the result into output.json.
