### ISSUE TITLE
XBOX 360/XBOX One Gamepad / Buttons swapped / No D-Pad / Analog Sticks misaligned

### ISSUE THREAD

**Issue by 7HEPOW** [univrsal/input-overlay#195]
**Describe the bug**
- Back/Start buttons are swapped
- D-Pad doesn't work
- Analog sticks get misaligned after first use

**To Reproduce**
Create a profile in io-cct and import it to OBS

**Expected behavior**
Proper buttons being mapped, D-Pad working, Sticks recenter accordingly

**Screenshots**
Left side shows Chromium / Right side is the preview window in OBS.
Pushing Back shows up as Start in OBS and vice versa.
Pushing any direction on the D-Pad shows nothing in OBS.
Analog sticks show up properly aligned in OBS until moved and end up misaligned to the lowest and rightmost position. Edit: I moved the left stick on both axes which puts it at the bottom right and the right stick was moved to the right only resetting it at the rightmost position on releasing it.
![20210808 091550 3840x1080](https://user-images.githubusercontent.com/35022098/128625166-734b87c5-7710-4e16-973c-c82ca6be6b72.png)

**Additional information:**
This is present in the 5.0.0-rc1 and also https://github.com/univrsal/input-overlay/commit/e9ba14f268182bf1362ad756b5cdb159dbaed3b6
Log file: https://obsproject.com/logs/XP46z6Yt8zpAYDAp

**Additional context**
Back/Start swapping can easily be fixed in the config file, but not rest unfortunately.

Thanks for your efforts! This is an amazing piece of software! :smile:

**Comment by univrsal** [comment]
For the dpad and the back/start buttons, did you try rebinding them in the input overlay settings? They're in the tools menu of obs.

**Comment by 7HEPOW** [comment]
How did I miss that? :)

It turned Back to DPad right and Start to DPad down. DPad does nothing and the sticks will still misalign after being moved.

**Comment by 7HEPOW** [comment]
Interestingly there's similar behavior with a SNES Clone I have:
![20210809 021839 3840x1080](https://user-images.githubusercontent.com/35022098/128650145-22208665-6cc0-41bd-b3dd-90f902d6c222.png)
Up+Left / Select / B is correct in Chromium, but B is Down (also A is Right) and the DPad doesn't work.

**Comment by mihawk90** [comment]
The analogue-stick issue seems the same I mentioned here:

https://github.com/univrsal/input-overlay/issues/183#issuecomment-868732601

I was about to open a proper issue for this when I saw this open issue :sweat_smile:

**Comment by 7HEPOW** [comment]
Change the title to match both Gamepads and also make it easier to find :)

**Comment by univrsal** [comment]
See #297 for further tracking
