### ISSUE TITLE
Input Overlay causing short freeze-frames every few seconds

### ISSUE THREAD

**Issue by DylanNeyaz** [univrsal/input-overlay#196]
**Describe the bug**
When I use Input Overlay (specifically for my Venom PS4 Arcade Stick), the entire screen on OBS freezes for a short while. This happens every few seconds, and is seen even in any videos recorded. The overlay itself also freezes when this happens.

**To Reproduce**
Use a Venom PS4 Arcade Stick and use the Arcade-Stick preset given in the release for Input Overlay v5.0.0-rc1 (This issue also occurs when using a custom profile made in io-cct, however).

**Expected behavior**
Smooth recordings with no issues and no freezing.

**Screenshots**
In case it may be helpful, this image shows the device I am using. As for why two are listed, I do not know. The first one works with my inputs, and the second one does nothing.
![image](https://user-images.githubusercontent.com/30506481/128641571-86b37115-2e16-4057-8899-46c60e3f0489.png)

**Videos**
With overlay: 

https://user-images.githubusercontent.com/30506481/128641757-61588808-a61f-428b-8752-0b07490f916c.mp4

Without overlay: 

https://user-images.githubusercontent.com/30506481/128641759-872f8cff-f821-4eb1-9fbe-51c915c5a4ee.mp4

**Additional information:**
- Plugin version: v5.0.0-rc1
- OBS version: 27.0.1
- Full OBS Studio log: [2021-08-08 19-06-36.txt](https://github.com/univrsal/input-overlay/files/6951266/2021-08-08.19-06-36.txt)

**Additional context**
Opening OBS as an administrator shows no difference. Removing all scenes and sources and only leaving the Input Overlay on its own does not change anything either.

**Comment by univrsal** [comment]
Seems like input overlay keeps losing the connection to the device. Do you have any other gamepad around to test and see if it's just that device?

**Comment by DylanNeyaz** [comment]
![image](https://user-images.githubusercontent.com/30506481/128647748-35738ba3-b74f-4e50-a984-082c04a29c1a.png)
In this case, it shows only one device (my DS4), and I am using DirectInput, as XInput did not pick it up. I am using the gamepad preset provided with v5.0.0-rc1.

https://user-images.githubusercontent.com/30506481/128647885-6f3fb96c-0c70-41a0-b320-fd7d320e4066.mp4

The freezing still occurs, in and out of recording.
Full log: [2021-08-08 23-37-02.txt](https://github.com/univrsal/input-overlay/files/6951561/2021-08-08.23-37-02.txt)

**Comment by univrsal** [comment]
The buttons can be remapped, but it seems like the disconnecting is not the root of the issue

**Comment by fatihG** [comment]
I narrowed it down to being an issue with controller configs in v5.0. Keyboard configs seem to work fine.

After not being able to access my PC for over a month (and gennerally not having streamed in a while) I had decided to give streaming a go today, untill I stumbled upon this issue as well. 

After a couple of hours, trial and erroring, deleting sources one by one I narrowed it down to Input Overlay being the culprit. 
As I dont remember having issues last time I streamed with a KB v5.0 overlay, I was surpised Input Overlay was the issue. 

I did however mess around with some controller overlays and messed around with the input-overlay settings. (generally v5.0 and controllers just dont want to work for me nicely at all, but that's not related to this issue.)

After deleting all the Input Overlay sources I had in my scene collection, the framedrops stopped happening. 
I re-added a KB config. No frame drops, all work fine. 
I changed the source to use a controller config. The framedrops started happening again. 

-------------

As I typed this I decided to double check in OBS, and I changed the Controller input overlay srouce back to KB and the framedrops continued to happen. 

I tried to reproduce it and changed the Kb back to a controller config and change it back again to KB and this time the frames did not continue to drop.

**Comment by univrsal** [comment]
> I narrowed it down to being an issue with controller configs in v5.0. Keyboard configs seem to work fine.
> 
> After not being able to access my PC for over a month (and gennerally not having streamed in a while) I had decided to give streaming a go today, untill I stumbled upon this issue as well.
> 
> After a couple of hours, trial and erroring, deleting sources one by one I narrowed it down to Input Overlay being the culprit.
> As I dont remember having issues last time I streamed with a KB v5.0 overlay, I was surpised Input Overlay was the issue.
> 
> I did however mess around with some controller overlays and messed around with the input-overlay settings. (generally v5.0 and controllers just dont want to work for me nicely at all, but that's not related to this issue.)
> 
> After deleting all the Input Overlay sources I had in my scene collection, the framedrops stopped happening.
> I re-added a KB config. No frame drops, all work fine.
> I changed the source to use a controller config. The framedrops started happening again.
> 
> As I typed this I decided to double check in OBS, and I changed the Controller input overlay srouce back to KB and the framedrops continued to happen.
> 
> I tried to reproduce it and changed the Kb back to a controller config and change it back again to KB and this time the frames did not continue to drop.

What gamepad (if any) did you use and did you set input overlay to Xinput or DirectInput? Does it happen all the time or just when you use the gamepad?

**Comment by fatihG** [comment]
The selected controller type was Xinput. BUT, it might very well be that a switched the input type without restarting OBS. I'll do some tests later.  

I have a few gamepads plugged in. A generic third party '360' controller (gets recognized as a 360 pad) 
And a Dual Sense. 

I dont think the controllers I am using is the culprit. 
I just did a quick test, unplugged all my controllers, disabled any xinput emulators. With no controllers plugged in nor detected by windows/OBS/InputOverlay I still get frame drops. 

I switched to Dinput and restarted OBS. Framedrops Continue.
I switched back to Xinput and restarted OBS. No framedrops. 

So it seems its an issue with DInput.

**Comment by JustAKat** [comment]
I can unfortunately also confirm this issue with DirectInput causing framedrops, got me confused when some of my recorded videos had framedrops at constant intervals, even though they were in another scene, and the issue only went away after removing all of the DirectInput sources.

**Comment by Morze99** [comment]
I was having trouble wit both XInput and DInput (framedrops and freeze every few seconds) and i solved not using the pre-release 5.0.0-rc1 of input-overlay but using the latest release 4.8 instead. Im on OBS 27.0.1.

**Comment by univrsal** [comment]
I assume that this is also an issue with my gamepad library, I plan on switching to SDL2 which is tracked in issue #297. There's a test application for displaying gamepad input which you can use for testing, but I don't expect it to cause this issue as sdl2 is a tried and true library used in many games.
