### ISSUE TITLE
Update the Input Overlay Creation Tool to support the latest version of the plugin.

### ISSUE THREAD

**Issue by ToshiyukiDoma** [univrsal/input-overlay#197]
It's kind of confusing converting the json overlay that I made from the website. I was using the old version but I accidentally upgraded.

Nothing really important but it would be a nice touch if the editor will be upgraded too.

![image](https://user-images.githubusercontent.com/23119677/130332934-09453447-ba75-4871-ad2b-205d3fdec2be.png)

**Comment by ToshiyukiDoma** [comment]
Ah yeah. I made this layout for a specific game called DJMAX Respect V.
He's how my input overlay worked.

https://www.youtube.com/watch?v=CVrVoOy2RUw

**Comment by univrsal** [comment]
the editor was specifically made for the latest pre release, I'm not sure what you mean

**Comment by ToshiyukiDoma** [comment]
> the editor was specifically made for the latest pre release, I'm not sure what you mean

I mean the editor exports the code in json format but the plugin supports ini format

**Comment by univrsal** [comment]
you need the pre release

**Comment by ToshiyukiDoma** [comment]
Oh. My bad. I downloaded the wrong version. Thank you! I apologize for the inconvenience!
