### ISSUE TITLE
Reload controllers in the 'input-overlay settings' menu.

### ISSUE THREAD

**Issue by fatihG** [univrsal/input-overlay#199]
**Is your feature request related to a problem? Please describe.**
Just a hassle to switch windows while trying to make your controller work/remapping buttons.

**Describe the solution you'd like**
A similar/same button as what you get in the Input Overlay source when you have a controller config loaded in. 

**Describe alternatives you've considered**
.

**Additional context**
.

**Comment by univrsal** [comment]
Won't be needed any more with the new gamepad backend
