### ISSUE TITLE
The "spacebar" doesn't show

### ISSUE THREAD

**Issue by ImperfectLion** [univrsal/input-overlay#20]
What happened: When pressing spacebar, the "spacebar" icon doesn't change colour

What was supposed to happend: When pressing spacebar, the spacebar icon should change colour

Log file: I don't know where to find this

**Comment by univrsal** [comment]
[v4.2](https://github.com/univrsal/input-overlay/releases/tag/v4.2) contains new versions of the qwerty preset which fixes this.
