### ISSUE TITLE
Make History differentiate between presses and releases

### ISSUE THREAD

**Issue by tsbreuer** [univrsal/input-overlay#200]
**Is your feature request related to a problem? Please describe.**
I'd love to be able to have history with repeat so i can see when i'm doing a combo: For example, if i'm pressing D twice, and i enable repeat keys, i dont want to see D be displayed 3+ times,

**Describe the solution you'd like**
Add a toggle that only identifies press down of a key (activation) rather than constant

**Describe alternatives you've considered**

**Additional context**

**Comment by univrsal** [comment]
There's already a repeat keys option I think. But input history has been removed anyways. It's replaced with the ability to visualize inputs in the browser source, but I haven't gotten around to finishing the input history preset for that.

**Comment by ViktarLos** [comment]
Input history is a very useful. Is it worth waiting for the return of this overlay?

**Comment by univrsal** [comment]
It's already (mostly) a thing again
https://github.com/univrsal/input-overlay/tree/master/projects/presets/input-history-windows
