### ISSUE TITLE
make keyboard keysize multiplier allow decimal values as multipliers

### ISSUE THREAD

**Issue by Suppresed** [univrsal/input-overlay#202]
**Is your feature request related to a problem? Please describe.**
i cant make the alt key on my layout fit cause its not a integer multiplier

**Describe the solution you'd like**
allow to set **1_key_width** to a decimal value

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by univrsal** [comment]
The old config format is no longer being developed
