### ISSUE TITLE
Can you create a sample texture image that contains all the characters on the keyboard?

### ISSUE THREAD

**Issue by SilverKnightKMA** [univrsal/input-overlay#204]
it can be the same as your 4.8b version, however it is no longer usable because there is not enough 3 pixel spacing
![qwerty-arrows-preview](https://user-images.githubusercontent.com/55577865/136669735-b29364cc-7caa-461a-8ed3-b015f23ce000.png)
Currently your sample presets do not have a full layout preset
Thanks for reading!

**Comment by univrsal** [comment]
I don't have the time to create presets for others, sorry. I think someone else has created a full keyboard preset. You'll have to look through the [forum thread](https://obsproject.com/forum/threads/input-overlay.72759/).
