### ISSUE TITLE
Mousewheel overlay render issues

### ISSUE THREAD

**Issue by ThomasParkSim** [univrsal/input-overlay#206]
The overlay for the mousewheel not being pressed interferes with the rendering of the overlay for the mousewheel being pressed.

![image](https://user-images.githubusercontent.com/92251084/136690878-1ff22191-d645-4e70-912e-58892cf0b854.png)
In this image, both m2 and mousewheel is being pressed but the mousewheel shows up as slightly darker despite having the same colour in the overlay image file.

![image](https://user-images.githubusercontent.com/92251084/136690947-6aecf744-6e81-4d43-a12a-a269de613450.png)
In this image with an example overlay image file, the mousewheel is not being pressed

![image](https://user-images.githubusercontent.com/92251084/136690963-6b2757af-5e0a-4cdb-8d04-72dd770bd091.png)
In this image with an example overlay image file, the mousewheel is being pressed and both the unpressed and pressed overlay for the mousewheel are being rendered.

**Comment by univrsal** [comment]
Do the textures have alpha? The images are layered on top which could cause this.

**Comment by univrsal** [comment]
The thing is that you can scroll and click the wheel at the same time which makes use of the layering

**Comment by ThomasParkSim** [comment]
Yeah that's fair, I didn't think of that. I wish it would actually layer the pressed mousewheel on top though, right now it seems the unpressed mousewheel is the top layer and the pressed buttons and scroll up/down is rendered beneath.

**Comment by univrsal** [comment]
https://github.com/univrsal/input-overlay/blob/master/projects/plugin/src/util/element/element_mouse_wheel.cpp#L41
It's actually exactly like that. First unpressed, then pressed and finally up/down.

**Comment by univrsal** [comment]
I changed it so either the pressed or unpressed textures are rendered.
