### ISSUE TITLE
Dinput crashes obs with spacemouse connected

### ISSUE THREAD

**Issue by Arbel-arad** [univrsal/input-overlay#208]
**if you set the mode to Dinput while a spacemouse (3dxware) is connected, obs will no longer open**

**To Reproduce**
connect any* device using the 3dxware drivers

**Expected behavior**

**Screenshots**

**Additional information:**
- Plugin version: latest, wasn't able to find the number.
- log with error:
`16:42:03.144: Command Line Arguments: --startreplaybuffer
16:42:03.144: CPU Name: AMD Ryzen 7 1700 Eight-Core Processor          
16:42:03.144: CPU Speed: 3494MHz
16:42:03.144: Physical Cores: 8, Logical Cores: 16
16:42:03.144: Physical Memory: 49098MB Total, 20121MB Free
16:42:03.144: Windows Version: 10.0 Build 19044 (release: 2009; revision: 1320; 64-bit)
16:42:03.144: Running as administrator: false
16:42:03.144: Aero is Enabled (Aero is always on for windows 8 and above)
16:42:03.144: Windows 10 Gaming Features:
16:42:03.144: 	Game Bar: On
16:42:03.144: 	Game DVR: On
16:42:03.144: 	Game DVR Background Recording: Off
16:42:03.144: 	Hardware GPU Scheduler: On
16:42:03.146: Sec. Software Status:
16:42:03.148: 	Microsoft Defender Antivirus: enabled (AV)
16:42:03.148: 	Windows Firewall: enabled (FW)
16:42:03.148: Current Date/Time: 2021-11-06, 16:42:03
16:42:03.148: Browser Hardware Acceleration: true
16:42:03.148: Portable mode: false
16:42:03.484: OBS 27.1.3 (64-bit, windows)
16:42:03.484: ---------------------------------
16:42:03.485: ---------------------------------
16:42:03.485: audio settings reset:
16:42:03.485: 	samples per sec: 48000
16:42:03.485: 	speakers:        8
16:42:03.487: ---------------------------------
16:42:03.487: Initializing D3D11...
16:42:03.487: Available Video Adapters: 
16:42:03.489: 	Adapter 0: NVIDIA GeForce GTX 1660 Ti
16:42:03.489: 	  Dedicated VRAM: 1987051520
16:42:03.489: 	  Shared VRAM:    4266840064
16:42:03.489: 	  PCI ID:         10de:2182
16:42:03.490: 	  Driver Version: 30.0.14.9649
16:42:03.490: 	  output 0: pos={0, 0}, size={2560, 1440}, attached=true, refresh=144, name=LC32G5xT
16:42:03.490: 	  output 1: pos={-2560, 0}, size={2560, 1440}, attached=true, refresh=144, name=LC32G5xT
16:42:03.494: Loading up D3D11 on adapter NVIDIA GeForce GTX 1660 Ti (0)
16:42:03.592: D3D11 loaded successfully, feature level used: b000
16:42:03.592: DXGI increase maximum frame latency success
16:42:03.592: D3D11 GPU priority setup failed (not admin?)
16:42:04.093: ---------------------------------
16:42:04.093: video settings reset:
16:42:04.093: 	base resolution:   2560x1440
16:42:04.093: 	output resolution: 2560x1440
16:42:04.093: 	downscale filter:  Lanczos
16:42:04.093: 	fps:               60/1
16:42:04.093: 	format:            NV12
16:42:04.093: 	YUV mode:          709/Partial
16:42:04.093: NV12 texture support enabled
16:42:04.094: Audio monitoring device:
16:42:04.094: 	name: Default
16:42:04.094: 	id: default
16:42:04.095: ---------------------------------
16:42:04.097: [Audio Monitor] loaded version 0.7.1
16:42:04.192: Skipping module '../../obs-plugins/64bit/chrome_elf.dll', not an OBS plugin
16:42:04.199: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
16:42:04.200: Failed to load 'en-US' text for module: 'decklink-captions.dll'
16:42:04.201: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
16:42:04.203: Skipping module '../../obs-plugins/64bit/DirectML.dll', not an OBS plugin
16:42:04.277: [AMF] Unable to load 'amfrt64.dll', error code 126.
16:42:04.279: [AMF] AMF Test failed due to one or more errors.
16:42:04.279: Failed to initialize module 'enc-amf.dll'
16:42:04.286: LoadLibrary failed for 'C:/Windows/System32/python36.dll': The specified module could not be found.
16:42:04.286:  (126)
16:42:04.286: [Python] Could not load library: C:/Windows/System32/python36.dll
16:42:04.291: [input-overlay] Loading v5.0.0 build time 2021.05.08 00:02
16:42:04.292: [input-overlay] Using 'Direct Input' gamepad backend
16:42:04.435: [input-overlay] 'Keyboard/Mouse/Joystick' connected
16:42:04.452: [input-overlay] 'SpaceMouse Enterprise' connected
16:42:04.809: [input-overlay] '3Dconnexion KMJ Emulator' connected
16:42:04.809: [input-overlay] gamepad hook started
16:42:04.810: [input-overlay::libgamepad] Hook thread started
`

**Additional context**
i have the enterprise version, but i believe the issue is due to the presence of too many axis eg. 6dof controller. 
i don't actually wish to display this device, it is used for other things.

-log without error:
`16:42:54.916: Command Line Arguments: --startreplaybuffer
16:42:54.916: CPU Name: AMD Ryzen 7 1700 Eight-Core Processor          
16:42:54.916: CPU Speed: 3494MHz
16:42:54.916: Physical Cores: 8, Logical Cores: 16
16:42:54.916: Physical Memory: 49098MB Total, 20128MB Free
16:42:54.916: Windows Version: 10.0 Build 19044 (release: 2009; revision: 1320; 64-bit)
16:42:54.916: Running as administrator: false
16:42:54.916: Aero is Enabled (Aero is always on for windows 8 and above)
16:42:54.916: Windows 10 Gaming Features:
16:42:54.916: 	Game Bar: On
16:42:54.916: 	Game DVR: On
16:42:54.916: 	Game DVR Background Recording: Off
16:42:54.916: 	Hardware GPU Scheduler: On
16:42:54.918: Sec. Software Status:
16:42:54.919: 	Microsoft Defender Antivirus: enabled (AV)
16:42:54.919: 	Windows Firewall: enabled (FW)
16:42:54.920: Current Date/Time: 2021-11-06, 16:42:54
16:42:54.920: Browser Hardware Acceleration: true
16:42:54.920: Portable mode: false
16:42:55.266: OBS 27.1.3 (64-bit, windows)
16:42:55.266: ---------------------------------
16:42:55.267: ---------------------------------
16:42:55.267: audio settings reset:
16:42:55.267: 	samples per sec: 48000
16:42:55.267: 	speakers:        8
16:42:55.269: ---------------------------------
16:42:55.269: Initializing D3D11...
16:42:55.269: Available Video Adapters: 
16:42:55.271: 	Adapter 0: NVIDIA GeForce GTX 1660 Ti
16:42:55.271: 	  Dedicated VRAM: 1987051520
16:42:55.271: 	  Shared VRAM:    4266840064
16:42:55.271: 	  PCI ID:         10de:2182
16:42:55.271: 	  Driver Version: 30.0.14.9649
16:42:55.271: 	  output 0: pos={0, 0}, size={2560, 1440}, attached=true, refresh=144, name=LC32G5xT
16:42:55.271: 	  output 1: pos={-2560, 0}, size={2560, 1440}, attached=true, refresh=144, name=LC32G5xT
16:42:55.275: Loading up D3D11 on adapter NVIDIA GeForce GTX 1660 Ti (0)
16:42:55.371: D3D11 loaded successfully, feature level used: b000
16:42:55.371: DXGI increase maximum frame latency success
16:42:55.371: D3D11 GPU priority setup failed (not admin?)
16:42:55.892: ---------------------------------
16:42:55.892: video settings reset:
16:42:55.892: 	base resolution:   2560x1440
16:42:55.892: 	output resolution: 2560x1440
16:42:55.892: 	downscale filter:  Lanczos
16:42:55.892: 	fps:               60/1
16:42:55.892: 	format:            NV12
16:42:55.892: 	YUV mode:          709/Partial
16:42:55.893: NV12 texture support enabled
16:42:55.894: Audio monitoring device:
16:42:55.894: 	name: Default
16:42:55.894: 	id: default
16:42:55.894: ---------------------------------
16:42:55.896: [Audio Monitor] loaded version 0.7.1
16:42:55.988: Skipping module '../../obs-plugins/64bit/chrome_elf.dll', not an OBS plugin
16:42:55.994: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
16:42:55.995: Failed to load 'en-US' text for module: 'decklink-captions.dll'
16:42:55.997: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
16:42:55.999: Skipping module '../../obs-plugins/64bit/DirectML.dll', not an OBS plugin
16:42:56.063: [AMF] Unable to load 'amfrt64.dll', error code 126.
16:42:56.065: [AMF] AMF Test failed due to one or more errors.
16:42:56.065: Failed to initialize module 'enc-amf.dll'
16:42:56.072: LoadLibrary failed for 'C:/Windows/System32/python36.dll': The specified module could not be found.
16:42:56.072:  (126)
16:42:56.072: [Python] Could not load library: C:/Windows/System32/python36.dll
16:42:56.077: [input-overlay] Loading v5.0.0 build time 2021.05.08 00:02
16:42:56.077: [input-overlay] Using 'XInput' gamepad backend
16:42:56.078: [input-overlay::libgamepad] Loading Xinput from C:\Windows\system32\xinput1_3.dll
16:42:56.079: [input-overlay::libgamepad] Xinput 1.3 loaded successfuly
16:42:56.079: [input-overlay::libgamepad] No Devices detected. Waiting for connection...
16:42:56.079: [input-overlay] gamepad hook started
16:42:56.079: [input-overlay::libgamepad] Hook thread started
16:42:56.110: Skipping module '../../obs-plugins/64bit/libcef.dll', not an OBS plugin
16:42:56.116: Skipping module '../../obs-plugins/64bit/libEGL.dll', not an OBS plugin
16:42:56.117: Skipping module '../../obs-plugins/64bit/libGLESv2.dll', not an OBS plugin
16:42:56.122: [Move Transition] loaded version 2.5.2
16:42:56.125: Failed to load 'en-US' text for module: 'obs-backgroundremoval.dll'
16:42:56.125: [obs-backgroundremoval] plugin loaded successfully (version 0.3.0)
16:42:56.126: [obs-browser]: Version 2.16.3
16:42:56.126: [obs-browser]: CEF Version 75.1.16+g16a67c4+chromium-75.0.3770.100
16:42:56.129: Failed to load 'en-US' text for module: 'obs-color-monitor.dll'
16:42:56.129: [obs-color-monitor] plugin loaded successfully (version 0.2.6)
16:42:56.132: NVENC supported
16:42:56.133: [noise suppress]: NVIDIA RTX denoiser disabled, redistributable not found
16:42:56.135: [obs-ndi] hello ! (version 4.9.0)
16:42:56.135: [obs-ndi] Trying 'D:\apps\NDIv4'
16:42:56.135: [obs-ndi] Found NDI library at 'D:/apps/NDIv4/Processing.NDI.Lib.x64.dll'
16:42:56.139: [obs-ndi] NDI runtime loaded successfully
16:42:56.144: [obs-ndi] NDI library initialized successfully (NDI SDK WIN64 06:20:19 Apr  1 2020 4.5.1.0)
16:42:56.371: starting virtual-output on VirtualCam'1'
16:42:56.374: [obs-websocket] you can haz websockets (version 4.9.1)
16:42:56.374: [obs-websocket] qt version (compile-time): 5.15.2 ; qt version (run-time): 5.15.2
16:42:56.376: [obs-websocket] module loaded!
16:42:56.377: Skipping module '../../obs-plugins/64bit/onnxruntime.dll', not an OBS plugin
16:42:56.382: [Source Dock] loaded version 0.1.3
16:42:56.383: [Source Record] loaded version 0.2.5
16:42:56.386: [StreamFX] Loading Version 0.11.0.0a3-g23207d04
16:42:56.393: [StreamFX] <nvidia::cuda::cuda> Driver reported CUDA version: 11.5.0
16:42:56.536: [StreamFX] <nvidia::cuda::context> Initialized CUDA on device 'NVIDIA GeForce GTX 1660 Ti' (787d3de2-7cb9-86d1-b3fc-5f8d9e29a11b, 00013895, 1).
16:42:56.543: [StreamFX] <NVIDIA Face Tracking Filter> Failed to load NVIDIA AR SDK runtime.
16:42:56.544: [StreamFX] <nvidia::cv::cv> No supported NVIDIA SDK is installed to provide 'NVCVImage.dll'.
16:42:56.544: [StreamFX] <filter::video_superresolution> Failed to make NVIDIA Super-Resolution available due to error: Failed to load 'NVCVImage.dll'.
16:42:56.544: [StreamFX] <filter::video_superresolution> All supported Super-Resolution providers failed to initialize, disabling effect.
16:42:56.544: [StreamFX] Loaded Version 0.11.0.0a3-g23207d04
16:42:56.584: Couldn't find VLC installation, VLC video source disabled
16:42:56.586: Failed to load 'en-US' text for module: 'win-capture-audio.dll'
16:42:56.594: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
16:42:56.595: No blackmagic support
16:42:56.602: ---------------------------------
16:42:56.602:   Loaded Modules:
16:42:56.602:     win-wasapi.dll
16:42:56.602:     win-mf.dll
16:42:56.602:     win-dshow.dll
16:42:56.602:     win-decklink.dll
16:42:56.602:     win-capture.dll
16:42:56.602:     win-capture-audio.dll
16:42:56.602:     vlc-video.dll
16:42:56.602:     text-freetype2.dll
16:42:56.602:     StreamFX.dll
16:42:56.602:     source-record.dll
16:42:56.602:     source-dock.dll
16:42:56.602:     rtmp-services.dll
16:42:56.602:     obs-x264.dll
16:42:56.602:     obs-websocket.dll
16:42:56.602:     obs-vst.dll
16:42:56.602:     obs-virtualoutput.dll
16:42:56.602:     obs-transitions.dll
16:42:56.602:     obs-text.dll
16:42:56.602:     obs-qsv11.dll
16:42:56.602:     obs-outputs.dll
16:42:56.602:     obs-ndi.dll
16:42:56.602:     obs-filters.dll
16:42:56.602:     obs-ffmpeg.dll
16:42:56.602:     obs-color-monitor.dll
16:42:56.602:     obs-browser.dll
16:42:56.602:     obs-backgroundremoval.dll
16:42:56.602:     move-transition.dll
16:42:56.602:     input-overlay.dll
16:42:56.602:     image-source.dll
16:42:56.603:     frontend-tools.dll
16:42:56.603:     enc-amf.dll
16:42:56.603:     dir-watch-media.dll
16:42:56.603:     decklink-ouput-ui.dll
16:42:56.603:     decklink-captions.dll
16:42:56.603:     coreaudio-encoder.dll
16:42:56.603:     audio-monitor.dll
16:42:56.603: ---------------------------------
16:42:56.603: ==== Startup complete ===============================================
16:42:56.610: All scene data cleared
16:42:56.610: ------------------------------------------------
16:42:56.703: WASAPI: Device 'VoiceMeeter Input (VB-Audio VoiceMeeter VAIO)' [48000 Hz] initialized
16:42:56.703: [Loaded global audio device]: 'Desktop Audio'
16:42:56.741: WASAPI: Device 'VoiceMeeter Aux Input (VB-Audio VoiceMeeter AUX VAIO)' [48000 Hz] initialized
16:42:56.741: [Loaded global audio device]: 'Desktop Audio 2'
16:42:56.779: WASAPI: Device 'VoiceMeeter VAIO3 Output (VB-Audio VoiceMeeter VAIO3)' [48000 Hz] initialized
16:42:56.779: [Loaded global audio device]: 'Mic/Aux'
16:42:56.792: [window-capture: 'Window Capture'] update settings:
16:42:56.792: 	executable: javaw.exe
16:42:56.792: 	method selected: Automatic
16:42:56.792: 	method chosen: BitBlt
16:42:56.792: 
16:42:56.822: adding 21 milliseconds of audio buffering, total audio buffering is now 21 milliseconds (source: Mic/Aux)
16:42:56.822: 
16:42:56.985: [obs-backgroundremoval] Destroy scalers.
16:42:57.321: [obs-backgroundremoval] Model input: name input_1:0 shape 256 x 256 x 3, output: name activation_10 shape 256 x 256 x 1
16:42:57.346: [duplicator-monitor-capture: 'right display'] update settings:
16:42:57.346: 	display: 2 (2560x1440)
16:42:57.346: 	cursor: true
16:42:57.346: 	method: WGC
16:42:57.406: [duplicator-monitor-capture: 'left display'] update settings:
16:42:57.406: 	display: 1 (2560x1440)
16:42:57.406: 	cursor: true
16:42:57.406: 	method: WGC
16:42:57.454: [obs-ndi] started A/V threads for source 'ARBEL-QD80 (laptop)'
16:42:57.455: [obs-ndi] A/V thread for 'NDI™ Source' started
16:42:57.455: [Media Source 'Media Source']: settings:
16:42:57.455: 	input:                   C:/Users/arbel/Videos/recordings/Replay 2021-10-31 16-20-41.mkv
16:42:57.455: 	input_format:            (null)
16:42:57.455: 	speed:                   100
16:42:57.455: 	is_looping:              no
16:42:57.455: 	is_linear_alpha:         no
16:42:57.455: 	is_hw_decoding:          yes
16:42:57.455: 	is_clear_on_media_end:   yes
16:42:57.455: 	restart_on_activate:     yes
16:42:57.455: 	close_when_inactive:     yes
16:42:57.505: Switched to scene 'single display'
16:42:57.506: [obs-color-monitor] save_load_scope_docks saving=0
16:42:57.506: ------------------------------------------------
16:42:57.506: Loaded scenes:
16:42:57.506: - scene 'displays with camera [full]':
16:42:57.506:     - source: 'left display' (monitor_capture)
16:42:57.506:         - filter: 'HDR > SDR' (streamfx-filter-color-grade)
16:42:57.506:     - source: 'right display' (monitor_capture)
16:42:57.506:         - filter: 'HDR > SDR' (streamfx-filter-color-grade)
16:42:57.506:     - source: 'input overlay' (scene)
16:42:57.506:         - filter: 'Crop/Pad' (crop_filter)
16:42:57.506:     - source: 'camera' (scene)
16:42:57.506:     - source: 'separator 1' (color_source_v3)
16:42:57.506: - scene 'displays with camera [split]':
16:42:57.506:     - source: 'left display' (monitor_capture)
16:42:57.506:         - filter: 'HDR > SDR' (streamfx-filter-color-grade)
16:42:57.506:     - source: 'right display' (monitor_capture)
16:42:57.506:         - filter: 'HDR > SDR' (streamfx-filter-color-grade)
16:42:57.506:     - source: 'input overlay' (scene)
16:42:57.506:         - filter: 'Crop/Pad' (crop_filter)
16:42:57.506:     - source: 'camera' (scene)
16:42:57.506:     - source: 'separator 1' (color_source_v3)
16:42:57.506: - scene 'single display':
16:42:57.506:     - source: 'right display' (monitor_capture)
16:42:57.506:         - filter: 'HDR > SDR' (streamfx-filter-color-grade)
16:42:57.506:     - source: 'camera' (scene)
16:42:57.506:     - source: 'input overlay background' (color_source_v3)
16:42:57.506:         - filter: 'Color Correction' (color_filter_v2)
16:42:57.506:     - source: 'input overlay' (scene)
16:42:57.506:         - filter: 'Crop/Pad' (crop_filter)
16:42:57.506: - scene 'temp':
16:42:57.506:     - source: 'right display' (monitor_capture)
16:42:57.506:         - filter: 'HDR > SDR' (streamfx-filter-color-grade)
16:42:57.506:     - source: 'Window Capture' (window_capture)
16:42:57.506:         - filter: 'Luma Key' (luma_key_filter_v2)
16:42:57.506:         - filter: 'Crop/Pad' (crop_filter)
16:42:57.506:         - filter: 'Color Correction' (color_filter_v2)
16:42:57.506:     - source: 'camera' (scene)
16:42:57.506: - scene 'inspection camera':
16:42:57.506:     - source: 'Video Capture Device 2' (dshow_input)
16:42:57.506: - scene 'laptop - ndi':
16:42:57.506:     - source: 'NDI™ Source' (ndi_source)
16:42:57.506:         - filter: 'obs-ndi - Fix alpha blending' (premultiplied_alpha_filter)
16:42:57.506: - scene 'camera':
16:42:57.506:     - source: 'main camera' (dshow_input)
16:42:57.506:         - filter: 'Apply LUT' (clut_filter)
16:42:57.506:         - filter: 'Render Delay' (gpu_delay)
16:42:57.506:         - filter: 'Background Removal' (background_removal)
16:42:57.506:         - filter: 'Chroma Key' (chroma_key_filter_v2)
16:42:57.506:     - source: 'obs.ninja - camera' (browser_source)
16:42:57.506:         - filter: 'Apply LUT' (clut_filter)
16:42:57.506: - scene 'input overlay':
16:42:57.506:     - source: 'mouse' (input-overlay)
16:42:57.506:     - source: 'keyboard' (input-overlay)
16:42:57.506:     - source: 'keyboard analog' (input-overlay)
16:42:57.506:     - source: 'minipadder' (browser_source)
16:42:57.506:         - filter: 'Crop/Pad' (crop_filter)
16:42:57.506:         - filter: 'Color Correction' (color_filter_v2)
16:42:57.506:     - filter: 'Crop/Pad' (crop_filter)
16:42:57.506: - scene 'replay':
16:42:57.506:     - source: 'Media Source' (ffmpeg_source)
16:42:57.506:         - filter: 'Directory watch media' (dir_watch_media)
16:42:57.506: ------------------------------------------------
16:42:57.727: ---------------------------------
16:42:57.727: [DShow Device: 'main camera'] settings updated: 
16:42:57.727: 	video device: UVC Camera
16:42:57.727: 	video path: \\?\usb#vid_1d6b&pid_0104&mi_00#8&3520b3c4&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global
16:42:57.727: 	resolution: 1920x1080
16:42:57.727: 	flip: 0
16:42:57.727: 	fps: 30.00 (interval: 333333)
16:42:57.727: 	format: MJPEG
16:42:57.780: [Media Source 'Media Source']: settings:
16:42:57.780: 	input:                   C:/Users/arbel/Videos/recordings/Replay 2021-10-31 16-20-41.mkv
16:42:57.780: 	input_format:            (null)
16:42:57.780: 	speed:                   100
16:42:57.780: 	is_looping:              no
16:42:57.780: 	is_linear_alpha:         no
16:42:57.780: 	is_hw_decoding:          yes
16:42:57.780: 	is_clear_on_media_end:   yes
16:42:57.780: 	restart_on_activate:     yes
16:42:57.780: 	close_when_inactive:     yes
16:42:57.971: [obs-websocket] WSServer::start: Not locked to IPv4 bindings
16:42:57.972: [obs-websocket] server started successfully on port 4444
16:42:57.972: [obs-websocket] IO thread started.
16:42:58.102: [jim-nvenc: 'recording_h264'] settings:
16:42:58.102: 	rate_control: CBR
16:42:58.102: 	bitrate:      10000
16:42:58.102: 	cqp:          18
16:42:58.102: 	keyint:       250
16:42:58.102: 	preset:       hq
16:42:58.102: 	profile:      high
16:42:58.102: 	width:        2560
16:42:58.102: 	height:       1440
16:42:58.102: 	2-pass:       false
16:42:58.102: 	b-frames:     2
16:42:58.102: 	lookahead:    false
16:42:58.102: 	psycho_aq:    false
16:42:58.102: 
16:42:58.127: ---------------------------------
16:42:58.127: [FFmpeg aac encoder: 'all'] bitrate: 320, channels: 8, channel_layout: 63f
16:42:58.127: 
16:42:58.128: ---------------------------------
16:42:58.129: [FFmpeg aac encoder: 'mic'] bitrate: 320, channels: 8, channel_layout: 63f
16:42:58.129: 
16:42:58.130: ---------------------------------
16:42:58.130: [FFmpeg aac encoder: 'desktop'] bitrate: 320, channels: 8, channel_layout: 63f
16:42:58.130: 
16:42:58.132: ---------------------------------
16:42:58.132: [FFmpeg aac encoder: 'discord'] bitrate: 320, channels: 8, channel_layout: 63f
16:42:58.132: 
16:42:58.134: ---------------------------------
16:42:58.134: [FFmpeg aac encoder: 'Track5'] bitrate: 320, channels: 8, channel_layout: 63f
16:42:58.134: 
16:42:58.136: ---------------------------------
16:42:58.136: [FFmpeg aac encoder: 'Track6'] bitrate: 320, channels: 8, channel_layout: 63f
16:42:58.136: 
16:42:58.142: ==== Replay Buffer Start ===========================================
16:42:58.185: [StreamFX] <updater> Automatic checks at launch are now enabled.
16:42:58.271: [obs-color-monitor] save_load_scope_docks saving=1
16:42:58.331: [obs-websocket] new client connection from [::ffff:127.0.0.1]:58751
16:42:58.339: [obs-websocket] new client connection from [::ffff:127.0.0.1]:58768
16:44:26.426: adding 640 milliseconds of audio buffering, total audio buffering is now 661 milliseconds (source: NDI™ Source)
16:44:26.426: 
16:44:26.657: adding 213 milliseconds of audio buffering, total audio buffering is now 874 milliseconds (source: NDI™ Source)
16:44:26.657: 
16:44:27.345: Max audio buffering reached!
16:44:27.345: adding 85 milliseconds of audio buffering, total audio buffering is now 960 milliseconds (source: NDI™ Source)
16:44:27.345: 
16:44:27.345: Source NDI™ Source audio is lagging (over by 69.36 ms) at max audio buffering. Restarting source audio.
`

**Comment by univrsal** [comment]
See #297 for further tracking
