### ISSUE TITLE
Overlay failed to load, lacking obs_module_load in uiohook.dll

### ISSUE THREAD

**Issue by dvr333** [univrsal/input-overlay#21]
What happened: Input Overlay failed to load, log file mentions "Required module function 'obs_module_load' in module '../../obs-plugins/64bit/uiohook.dll' not found, loading of module failed".

What was supposed to happen: Input Overlay loads

Log file: https://pastebin.com/r2tU62s0

**Comment by univrsal** [comment]
That's not actually the issue. Windows 7 doesn't come with a  certain *.dll that Windows 8 and up have, which is why the plugin won't load for you.
Can you try [v4.2](https://github.com/univrsal/input-overlay/releases/tag/v4.2) and tell me if it's fixed?

**Comment by dvr333** [comment]
It's fixed. Thanks
