### ISSUE TITLE
Backtick/tilde key does not register on US QWERTY layout

### ISSUE THREAD

**Issue by FAT9L** [univrsal/input-overlay#216]
**Describe the bug**
Backtick/tilde (Windows virtual key 0xC0, keycode 0x0029, VC_BACKQUOTE in libuiohook) does not register when using the overlay. It does show and function properly in io-cct, although the keycode will appear as "0x0". Once the .json config is exported, the correct keycode is listed in the .json file, however input-overlay does not recognize the input (will not illuminate/react, key remains blank in OBS when pressed).

**To Reproduce**

1. Open config/texture file in io-cct
2. Add keyboard element, assign texture and keycode
3. Save/export JSON file
4. Launch OBS and confirm plugin is active
5. Press "`" key
6. Confirm it does not activate

**Expected behavior**
Backtick\tilde key illuminates on OBS when key is pressed

**Screenshots**

Current JSON file showing correct keycode:
![ioscreenshot1](https://user-images.githubusercontent.com/96025485/145731006-4341c660-2100-47e0-a5b0-5c5e2ac48c95.png)

OBS input with all top-left keys pressed:
![ioscreenshot2](https://user-images.githubusercontent.com/96025485/145731007-08ac53e9-c801-42bc-9270-08773ce0daf6.png)

**Additional information:**
- Plugin version: 5.0.0.-rc1
- Full OBS Studio log: https://obsproject.com/logs/T3zdvxV_ChNmCK3j

**Additional context**
As mentioned, the correct keycode is being written to the JSON file that is exported from io-cct. I'm not sure if this is an issue with how libuiohook is integrated to recognize those codes, or something else. io-cct DOES recognize the key, which to me seems that whatever fix was pushed to io-cct did not make it to the actual end program. Every other key on my board (tenkeyless) provides the correct inputs.

**Comment by univrsal** [comment]
Can you download the nightly build from [here](https://github.com/univrsal/libuiohook/releases/tag/1.2.0), unpack ``demo_hook.exe`` from ``x86_64-win32-msvc/bin`` as well as ``uiohook.dll`` from ``x86_64-win32-msvc/lib`` somewhere and confirm the keycode you get when pressing that button?

**Comment by FAT9L** [comment]
> Can you download the nightly build from here, unpack demo_hook.exe from x86_64-win32-msvc/bin as well as uiohook.dll from x86_64-win32-msvc/lib somewhere and confirm the keycode you get when pressing that button?

Attached is a screenshot of the cmd output. It gives a keycode of "0x29", as well as a rawcode of "192".
![io_output_backtick_nightlybuild](https://user-images.githubusercontent.com/96025485/145756016-a7ae148c-f992-4b5b-8103-368adcab0e51.png)

Hope this helps.

**Comment by Gn9sis** [comment]
Exact same issue here. For me, I have found that the key lights up when I press ' instead of `. It has been very frustrating, as this key happens to be extremely important in the footage I'm trying to record.

On the other hand, the display for ' does not light up at all.

To summarize, the key set to code 41 lights up when I press ', instead it should light up when I press `.

And the key set to code 40 simply does not work, instead it should light up when I press '.

**Comment by FAT9L** [comment]
> For me, I have found that the key display set to code 41 lights up when I press ' (40) instead of ` (41).

Interesting, I never got any behavior like that even when testing everything I could. 


> Edit: Fixed by running demo_hook.exe and checking the hexadecimal keycode for `, which for me turned out to be 125 for some reason. Swapped all the keycodes in the .json config file and it all works now.

That's so bizarre, I tried the same thing and got no results out of it. Are you on US QWERTY layout?

**Comment by Gn9sis** [comment]
Yes, I'm on the US keyboard layout. I originally thought we had the same issue, but we probably had separate issues.

I asked around and it's not very common of an issue/symptom. In my case, it was easy enough to fix but I have no clue what your issue might be.

I would try a different keyboard and see if that changes anything.

**Comment by univrsal** [comment]
See #298 for further tracking
