### ISSUE TITLE
NumPad arrows not registering

### ISSUE THREAD

**Issue by McDeJay** [univrsal/input-overlay#22]
Hey!

I'm trying to set up an overlay where I have only 3 buttons, left arrow, right arrow and the Numpad up arrow that I use for jumping.

However I do not know what to write in order to have the Numpad up arrow to register. In the list of buttons this is what is says: 0xEE00 | VC_KP_8.

But even if I write it like that, or if I replace "VC_KP_8" with its code, it doesn't work. Could you please help me how I have to enter it into the ini file?
![kep](https://user-images.githubusercontent.com/36477565/36205777-3194b0bc-1190-11e8-8cba-50cbbd2069b1.png)

Thank you!

**Comment by univrsal** [comment]
You can't use bitwise operators like '|' in the config. You'll have to write them out as hex codes. In this case 0xEE00|0x0048 would turn into 0xEE48. '|' merges the two codes together.
Using those codes it should work

**Comment by McDeJay** [comment]
It is not working with 0xEE48, that seems to be the regular up arrow. 

I found the solution, however. I needed to use 0xE084, which should be the regular up arrow, based on the list, but it seems that it is the Numpad one. So thank you for the answer and help!

**Comment by univrsal** [comment]
Yeah I some keys are mixed up in the header file. Keys like Home, End, Page up etc. are mixed up with the same keys on the numpad (when numlock is off)
