### ISSUE TITLE
[WIKI] AUR package is obs-plugin-input-overlay-bin not obs-input-overlay-bin

### ISSUE THREAD

**Issue by xproot** [univrsal/input-overlay#220]
In the [installation page](https://github.com/univrsal/input-overlay/wiki/Installation) the option for arch linux users mentions aur package 'obs-input-overlay-bin' 
![image](https://user-images.githubusercontent.com/49620652/150051944-d8e54937-4884-4889-8e15-84b5d0878f3a.png)
while the package is actually named obs-plugin-input-overlay-bin
https://aur.archlinux.org/packages/obs-plugin-input-overlay-bin/

**Comment by univrsal** [comment]
fixed
