### ISSUE TITLE
support for GPD Win Max with overlay

### ISSUE THREAD

**Issue by SubmarineM1** [univrsal/input-overlay#221]
I'm always frustrated when i tried to find  a software that reads and looks of a GPD Win Max, but couldent find any T_T

I would love to have this app have support of a GPD Win Max, with all the features of the original software (and hopefully also for Streamlabs as well)

this is the link to the hardware, for context-
https://gpd.hk/gpdwinmax2021

i appreciated it :)

**Comment by SubmarineM1** [comment]
almost forgot- was also hoping it would work on multiple computers, so that i can read my GPD Win Max input, via usb data cable or other means, on my tower pc

**Comment by univrsal** [comment]
This is just a windows pc, there's nothing special about it, it should work out of the box. Inputs can be sent to obs via the client tool, but it's a bit spotty right now.
