### ISSUE TITLE
not install it on debian 11!!!!!!!

### ISSUE THREAD

**Issue by CodingBDX** [univrsal/input-overlay#224]
hey!!
the install destroy grub on debian 11 in last release...
so please, look it!!!!!!!!

**Comment by univrsal** [comment]
There's basically no way that the installer could affect grub in any way. The more likely scenario is that grub broke in another way.
Also the installer is targeted towards ubuntu.

**Comment by CodingBDX** [comment]
well i install manually the deb because it touch at libq....it's break my interface...
so now it's work, but the gamepad overlay not, it don't detect the gamepad id.. i use flatpak...

**Comment by univrsal** [comment]
so the installer wasn't the problem
