### ISSUE TITLE
Is Input Overlay on OBS's flatpak page outdated?

### ISSUE THREAD

**Issue by Freeplayg** [univrsal/input-overlay#225]
I was wanting to use the Flatpak version of OBS, and wanted to have the input overlay as well. But it seems to work slightly differently than the one on Github? It doesn't work with any of the presets or ones created with io-cct

Could it be an outdated version of the plugin?
![Screenshot from 2022-02-19 10-16-41](https://user-images.githubusercontent.com/40742947/154807060-d8ec9019-d129-43de-8237-99f7454acb9c.png)

**Comment by univrsal** [comment]
It probably uses the last stable release and not the pre-release. I don't have anything to do with it so you'll have to talk to whoever is in charge of the flatpak version.
