### ISSUE TITLE
Function invoke name mismatch

### ISSUE THREAD

**Issue by christiankyle-ching** [univrsal/input-overlay#227]
https://github.com/univrsal/input-overlay/blob/af0cbfc4c2974766dab7948d9090f7b08f951243/projects/plugin/data/example.html#L31-L43

https://github.com/univrsal/input-overlay/blob/af0cbfc4c2974766dab7948d9090f7b08f951243/projects/plugin/data/example.html#L41

Shouldn't this be `start_websocket` instead of `startWebsocket`?

**Comment by univrsal** [comment]
Yeah that's correct, oops
