### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ngoccuong358** [univrsal/input-overlay#23]
What happened:

What was supposed to happend:

Log file:
![image](https://user-images.githubusercontent.com/36512370/36268252-9c860c0e-12a8-11e8-9f5c-7b4b02c960f0.png)

**Comment by univrsal** [comment]
I need more info than that. What obs version are you using and the entire log of obs studio.
You can upload them under the "help" menu

**Comment by univrsal** [comment]
I'll just close this until I get more info
