### ISSUE TITLE
WebSocket Server Crashes

### ISSUE THREAD

**Issue by univrsal** [univrsal/input-overlay#230]
https://github.com/univrsal/input-overlay/issues/194#issuecomment-1058394774
https://github.com/univrsal/input-overlay/issues/194#issuecomment-1057536752
https://github.com/univrsal/input-overlay/issues/194#issuecomment-1057106186

**Comment by GitHubGoody** [comment]
Here are my latest crash reports:
[Crash 2022-03-07 13-00-06.txt](https://github.com/univrsal/input-overlay/files/8200160/Crash.2022-03-07.13-00-06.txt)
[Crash 2022-03-07 13-14-23.txt](https://github.com/univrsal/input-overlay/files/8200161/Crash.2022-03-07.13-14-23.txt)
[Crash 2022-03-07 13-22-20.txt](https://github.com/univrsal/input-overlay/files/8200162/Crash.2022-03-07.13-22-20.txt)
[Crash 2022-03-07 13-40-44.txt](https://github.com/univrsal/input-overlay/files/8200163/Crash.2022-03-07.13-40-44.txt)
[Crash 2022-03-07 13-45-27.txt](https://github.com/univrsal/input-overlay/files/8200159/Crash.2022-03-07.13-45-27.txt)

**Comment by christiankyle-ching** [comment]
I don't know if this will help, but I noticed this quite often in the stacktrace.

https://github.com/univrsal/input-overlay/blob/94067421e1237f7408acc82e397e1d5f5aa0c463/projects/plugin/src/network/mg.cpp#L42

Again, I don't know C++ so I can't help much 😅
