### ISSUE TITLE
Input Overlay (flatpak) not seemingly showing key presses for OBS Studio (flatpak) on Fedora 35 Kinoite

### ISSUE THREAD

**Issue by FilBot3** [univrsal/input-overlay#231]
# The Problem

I have OBS Studio installed via a Flatpak on Fedora 35 Kinoite (rpm-ostree).
I wanted to use this to help record videos I'm doing to teach people more about
certain command-line tools, and I feel showing the key presses could be helpful
to some. After installing OBS Studio and the Input Overlay extensions, I do see
the Input Overlay option to add

![image](https://user-images.githubusercontent.com/3039509/156836904-dd0ec761-099c-4c59-aed5-fc7374cee4e6.png)

I also used the [Wiki](https://github.com/univrsal/input-overlay/wiki/Usage#input-overlay)
to get the overlay presets for QWERTY. I think I loaded them up correctly.

![Peek 2022-03-04 14-23](https://user-images.githubusercontent.com/3039509/156836738-316ea17c-ed7e-42ad-bcce-7b82424778db.gif)

However, no keyboard presses are showing up. Is there something else I need to
do to get Input Overlay to work with OBS StudiO Flatpak?

## Supporting Details

Fedora Version and Flatpak Version information.

<details>

```bash
~❯ flatpak --version
Flatpak 1.12.6

~❯ rpm -q flatpak
flatpak-1.12.6-1.fc35.x86_64

~❯ cat /etc/os-release 
NAME="Fedora Linux"
VERSION="35.20220228.0 (Kinoite)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora Linux 35.20220228.0 (Kinoite)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-kinoite/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=35
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=35
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Kinoite"
VARIANT_ID=kinoite
OSTREE_VERSION='35.20220228.0'

~❯ flatpak list # Output trimmed to show only OBS Studio flatpaks
Name                                              Application ID                                               Version                        Branch                 Origin                   Installation
OBS Studio                                        com.obsproject.Studio                                        27.2.3                         stable                 flathub                  user
GStreamer Plugin                                  com.obsproject.Studio.Plugin.Gstreamer                       0.3.3                          stable                 flathub                  user
Input Overlay Plugin                              com.obsproject.Studio.Plugin.InputOverlay                                                   stable                 flathub                  user

```

</details

**Comment by univrsal** [comment]
You have to use the old presets from [here](https://github.com/univrsal/input-overlay/tree/legacy/presets), as the flatpak version uses the last stable release.

**Comment by FilBot3** [comment]
That did the trick! Thank you @univrsal ! I'm guessing that means that the Flatpak should be updated, or have a different channel to use your latest?

**Comment by univrsal** [comment]
I don't have anything to do with the flatpak and I'm generally not a fan of how it handles plugins. Currently 5.0 is still a pre-release so the version that the flatpak uses is up to date, it's apparently just missing the presets.
