### ISSUE TITLE
How do you convert ini to json?

### ISSUE THREAD

**Issue by invasionofsmallcubes** [univrsal/input-overlay#233]
Hi,
it took me all morning to understand that JSON ONLY works on pre-release whereas INI works in release.
So first of all a little bit of clarity on the part on the wiki would be better.
Question is: the current editing tool, only supports json but the current release only support ini.

Given I have a working ini, is there a way to convert it to JSON?

Thanks

**Comment by univrsal** [comment]
Nope, at least not right now. I might write a quick script for it at some point. I'll add a note to the wiki for now, sorry that it wasn't clearer.
