### ISSUE TITLE
D-pad not detected under Linux

### ISSUE THREAD

**Issue by GameKyuubi** [univrsal/input-overlay#241]
**Describe the bug**
In v5 prerelease all functions work except d-pad.  On v4.8 the d-pad is detected normally.

**To Reproduce**
Steps to reproduce the behavior: set up as usual, see that d-pad does not work

**Expected behavior**
D-pad works

**Additional information:**
- Plugin version: 5.0.0rc1
- Full OBS Studio log: https://pastebin.com/raw/pryXkQjA

**Additional context**
Problem seems to have been introduced post-4.8

**Comment by GameKyuubi** [comment]
I should note I am using the presets from the 5.0.0rc1 release

**Comment by GameKyuubi** [comment]
https://github.com/univrsal/libgamepad/blob/793cf5cc39d0af84c973310309d1762788ac9717/src/binding-default.cpp#L131

Maybe the issue is here?  For me, the d-pad for my Series X controller shows up as axes 6 and 7, but there's no entry addressing axes 6 and 7.  Is there a `is_hat` or `is_dpad` option?

**Comment by GameKyuubi** [comment]
output of `jstest`:
```
Joystick (Microsoft Xbox One X pad) has 8 axes (X, Y, Z, Rx, Ry, Rz, Hat0X, Hat0Y)
and 11 buttons (BtnA, BtnB, BtnX, BtnY, BtnTL, BtnTR, BtnSelect, BtnStart, BtnMode, BtnThumbL, BtnThumbR).
```

**Comment by univrsal** [comment]
Those fixes are for the 4.8 version, which doesn't use the new gamepad library. Did you try and rebind your dpad in the settings dialog (Tools > input-overlay settings in the OBS main window)?
![image](https://user-images.githubusercontent.com/8353672/160239820-b55591e8-2754-46fd-a789-9989cd54dce5.png)

**Comment by GameKyuubi** [comment]
Problem is it's looking for four buttons, not two axes.  D-pad for Series X uses 2 axes labeled 6 and 7, so Dpad left registers as "6", but so does Dpad right, because it's the same axis.  Same with up and down, both get assigned "7".  In fact I could probably register the Dpad as an analog stick and it would work, but then I'd lose usage of that stick.

**Comment by HereInPlainSight** [comment]
I'm pretty sure that yes, it's trying to use the two axes as buttons.  Included is a video (I'm using a DS4 controller), and you can see that while the `io-cct` config page sees everything (and they all default absolutely correctly, I had to make changes for the plugin via the gamepad bindings, also visible, configured by pressing every button to be as safe as possible), but the overlay itself gets confused when it comes to the back triggers and the directional pad's right and down, and doesn't see the *actual* dpad presses at all.

https://user-images.githubusercontent.com/766446/170803149-0168b2dd-e088-4092-bdba-b7c05771280f.mp4

I'm also attaching the log that was visible -- which _only_ includes the items seemingly affected by this issue.  The issuing command was `./libgamepad_tests | grep -E 'Controller|Hook|button event: Native id: 6|button event: Native id: 7|axis event: Native id: 2|axis event: Native id: 5|axis event: Native id: 6|axis event: Native id: 7'`, based on output I got from running ./libgamepad_tests previously without pressing any of the other buttons.

The key here seems to be that releasing the left trigger starts with a `button event: Native id: 6, Virtual id: 0xEC07 (60423) val: 1.000000`, `val: 0.000000` on release.  (There are multiple axis events for the amount of pressure on the trigger, but the Native id is 2 and doesn't match up.)  Pressing the right DPad button returns an `axis event: Native id: 6, Virtual id: 0x0 (0) val: 0.999992` on push, , `val: 0.500000` on release.  The right trigger's `button event: Native id: 7, Virtual id: 0xEC06 (60422)`, down (1) and up (0) are `axis event: Native id: 7, Virtual id: 0x0 (0)`, with everything else being the same.
[DPadIssue.txt](https://github.com/univrsal/input-overlay/files/8790193/DPadIssue.txt)

I can make a new log of whatever might be helpful to diagnose / resolve the issue.

**Comment by univrsal** [comment]
So I never anticipated that gamepads would use an axis for buttons, which at the time seemed like a fairly sane assumption. So if I get this correctly not pressing left or right will result in a virtual value of 0, pressing left will result in 0.5 and pressing right returns 1 and the same for up/down just with a different axis id?

**Comment by HereInPlainSight** [comment]
Sorry, not quite.  For absolute clarity: pressing left will result in a value of zero*, pressing right will result in a value of 1*.  Releasing them results in a value of 0.5, making that the neutral / resting value.  Left/right was identified as native id 6 for the axis, up/down was identified as native id 7.  Up was 0*, down was 1*, middle was again .5.

(*) The actual 'zero' value for me appears to always be 0.000008, the 'one' value is always 0.999992, for both directions.  I don't *think* that's incredibly relevant, but I'm trying to provide you all information.  Apologies if I'm just confusing the matter.

For a more visual representation of the above:
```
        0
        |  Axis 6
        |
 0 ---- .5 ---- 1   Axis 7
        |
        |
        1
```

**Comment by makotoworkshop** [comment]
Hello !
I'have same problem here, both on Linux or windows. ( input-overlay.v5.0.0rc1-8d04a98 )

So i tried to remap as seen in vidéo @HereInPlainSight 's video, like this :
![image](https://user-images.githubusercontent.com/8409473/179832061-705e78d6-ad1b-4068-988b-8f6d017a8864.png)
cliking in the Dpad Left box, move the gamepad cross left
cliking in the Dpad Right box, move the gamepad cross right, and so on.
Then i clicking _Save_ and _OK_.

But Dpad not working at all, so i return to the binding config, and see that the remap values (left and up) are not stored…
![image](https://user-images.githubusercontent.com/8409473/179831987-6d282a5a-a787-4052-83c1-e82a8f00974a.png)

**Comment by univrsal** [comment]
What does the log file look like after you tried rebinding? The bindings should also be saved to ~/.config/input-overlay so you might want to check what the json file looks like

**Comment by makotoworkshop** [comment]
Thanks for theses suggestions.
Here the OBS log file https://pastebin.com/f4YrAQmm

Unfortunately there is no binding file in the ~/.config/input-overlay  directory, neither childs directory.
Maybe in another location ?

**Comment by univrsal** [comment]
Well it should be created once you click save and apply, if it can't it'll log an error

**Comment by makotoworkshop** [comment]
Ok.
Sorry, but when i click save, nothing happened and no apply button appeared.

**Comment by univrsal** [comment]
Yeah I meant Ok, not Apply. If you just open the dialog and click save without doing any binding and then close obs it should save the config file. If that doesn't work I don't know what the issue is.

**Comment by makotoworkshop** [comment]
Sorry, my bad, i'm tired it's late for me at 1h03 AM. I have looking in _.config/obs-studio/plugins/input-overlay _instead of_ .config/input-overlay_
Se the file _gamepad_bindings.json_ exist
`{"bindings": [{"binds": [{"from": 0, "is_axis": true, "to": 60431}, {"from": 1, "is_axis": true, "to": 60432}, {"from": 2, "is_axis": true, "to": 60433}, {"from": 3, "is_axis": true, "to": 60434}, {"from": 4, "is_axis": true, "to": 60435}, {"from": 5, "is_axis": true, "to": 60436}, {"from": 0, "is_axis": false, "to": 60428}, {"from": 1, "is_axis": false, "to": 60430}, {"from": 2, "is_axis": false, "to": 60418}, {"from": 3, "is_axis": false, "to": 60419}, {"from": 4, "is_axis": false, "to": 60420}, {"from": 5, "is_axis": false, "to": 60421}, {"from": 6, "is_axis": false, "to": 60423}, {"from": 7, "is_axis": false, "to": 60422}, {"from": 8, "is_axis": false, "to": 60424}, {"from": 9, "is_axis": false, "to": 60425}, {"from": 10, "is_axis": false, "to": 60426}, {"from": 11, "is_axis": false, "to": 60427}, {"from": 12, "is_axis": false, "to": 60428}, {"from": 13, "is_axis": false, "to": 60429}, {"from": 14, "is_axis": false, "to": 60430}], "name": "test"}], "bindings_map": [{"binding_id": "test", "device_id": "(js0) Paul Qureshi Arcade Joystick v1.1"}]}`

I try to replace 11 by 0
And 13 by 1
But not better result, the field are empty when reload OBS
![image](https://user-images.githubusercontent.com/8409473/179863755-925c0533-e9eb-4ba6-8eea-813510e33216.png)

And at next OBS starting, 11 and 13 are back

**Comment by univrsal** [comment]
Well I just checked myself and using xboxdrv my dpad now is also an axis. This is just great...

**Comment by univrsal** [comment]
See #297 for further tracking
