### ISSUE TITLE
Can't find the provided presets.

### ISSUE THREAD

**Issue by Layarion** [univrsal/input-overlay#242]
**Describe the bug**
I cannot find any link to these so called "presets" that I'm told not to forget in the readme.

**To Reproduce**
Go look for them.

**Expected behavior**
When a readme says "don't forget the presets!" there should be a link there!

**Additional information:**
- Plugin version 5.0.0c1
- Full OBS Studio log (https://obsproject.com/logs/PWd1YrZnm5DnjulU)

**Additional context**
I used the windows installer, I tried looking for a preset folder, there doesn't seem to be one provided, and for some reason, not a single link is provided to these so called "presets" on the readme, the wiki readme, I don't see anything in the projects tab, and no link to them in the OBS forums. JFC I'm so frustrated right now.

**Update:**
I downloaded the source file and then went into projects and presets. I feel like it was not explained at all, that you could only get them by downloading the entire project's source file. I also feel like having no link to such file whenever you're told to get them, is also a place for improvement.

**Comment by univrsal** [comment]
https://github.com/univrsal/input-overlay/wiki/Installation

![image](https://user-images.githubusercontent.com/8353672/159910683-d0715b2d-fd46-4708-aba2-a8373e27ba6c.png)

https://github.com/univrsal/input-overlay/wiki/Usage

![image](https://user-images.githubusercontent.com/8353672/159910788-0edf7a4b-4e81-437f-87ea-37b5f017ea7b.png)

https://obsproject.com/forum/resources/input-overlay.552/

![image](https://user-images.githubusercontent.com/8353672/159910344-a28eeba0-1011-48a9-82fe-08317ce17fec.png)

What readme are you talking about?

**Comment by Layarion** [comment]
The moment I seen those numbers I thought they were just different installers. How about you scroll down, and explain in the readme why you don't have a hyperlink going to those presets?

**Comment by univrsal** [comment]
I have replaced the note in the windows section with a link to the usage section which should be clear enough about where to get the presets.
