### ISSUE TITLE
[Suggestion] Implement a hook that supports Wayland (Linux)

### ISSUE THREAD

**Issue by m2jest1c** [univrsal/input-overlay#243]
**Is your feature request related to a problem? Please describe.**
according to https://github.com/kwhat/libuiohook/issues/100 libuiohook does not support Wayland, and as a result this plugin is absolutely useless as far as I can tell on Wayland.

**Describe the solution you'd like**
A way for this plugin to be functional on Wayland would be great. However, I understand that achieving this may not be possible.

**Describe alternatives you've considered**
Using Xorg is always an option, but it's significantly slower than Wayland for me, and if Reddit's worth listening to, many others.

**Additional context**
I'm using KDE Plasma 5.24.3 with Wayland on Fedora 35. The plugin does not function. On Plasma with Xorg, it functions as expected.

**Comment by univrsal** [comment]
It's not really up to me. When libuiohook supports Wayland input overlay will, but considering that OBS doesn't even support global keybinds on Wayland it seems to me like there is no decent way of implementing this kind of system on Wayland right now.

**Comment by m2jest1c** [comment]
Figured. Damn.
