### ISSUE TITLE
Crash when trying to use key names file: std::out_of_range

### ISSUE THREAD

**Issue by ewen-lbh** [univrsal/input-overlay#245]
**Describe the bug**
OBS crashes after selecting a properly-formatted key names config file (see #68).

The last lines dumped to stdout when running `obs --verbose` could be helpful (they do not appear in the OBS Studio Full log)

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::at: __n (which is 0) >= this->size() (which is 0)
```

**To Reproduce**
1. Add an Input History source
2. Try to load a file with the following contents:
    ```ini
    # The first line has to be a comment, since it's ignored by the config loader

    2_0x001E=TEST
    ```

**Expected behavior**
The config file loads and is applied

**Additional information:**
- Plugin version v4.8 ([Small fixes](https://github.com/univrsal/input-overlay/releases/tag/v4.8))
- Full OBS Studio log https://pastebin.com/raw/33sdnADd

Additionnally, the config syntax for key name remapping should be documented somewhere, I had to dig through issues to find it. (I'm willing to make a PR to document it, if the syntax described in #68 is still valid, that is)

**Comment by univrsal** [comment]
Have you tried removing the empty line?

**Comment by ewen-lbh** [comment]
That solved the issue. But really, the syntax of this file should be documented somewhere. And I wonder why empty lines make the parser hang. It might be easier to simply use JSON, and let the JSON parsing library handle all the parsing:

```json
{
  "001E": "TEST"
}
```

**Comment by ewen-lbh** [comment]
I did a bit of research, and it seems like you use scan codes directly.
I found how to get a key's scancode on linux, here are the steps (so that it can be documented):

1. Switch to a virtual console (`Ctrl` + `Alt` + `F2`)
2. Execute `showkey --scancodes`
3. Press a key, it'll show the scancode in hexadecimal
4. Wait 10s, the program will exit by itself (since you can't use anything to exit it, as all keys are captured to show their scancodes)
5. Switch back to X11 (`Ctrl` + `Alt` + `F7`)

**Comment by univrsal** [comment]
input overlay uses libuiohook codes from here https://github.com/kwhat/libuiohook/blob/1.2/include/uiohook.h
The plugin uses json for overlays in 5.0.0 but input history has been replaced by the websocket server which sends inputs to browser sources.
