### ISSUE TITLE
Side mouse buttons don't register

### ISSUE THREAD

**Issue by Vehzx** [univrsal/input-overlay#247]
**Describe the bug**
Side mouse buttons are not registered in overlay when clicked.

**To Reproduce**
Saw previous post from a couple years or so ago, pretty sure it's just certain mice, wondering if there is a fix yet. (Logitech X Superlight Wireless).

**Expected behavior**
Side mouse buttons should register

**Screenshots**
Don't think it's needed

**Additional information:**
Will leave this here as i'm almost certain I have the exact issue this guy had: https://github.com/univrsal/input-overlay/issues/100

**Additional context**

**Comment by MC-dusk** [comment]
same problem, logi M650

**Comment by snakecase** [comment]
Found a fix! https://github.com/univrsal/input-overlay/issues/100#issuecomment-1320928469

**Comment by univrsal** [comment]
See #298 for further tracking
