### ISSUE TITLE
New Chinese translation file

### ISSUE THREAD

**Issue by GodGun968** [univrsal/input-overlay#249]
The original Chinese Chinese translation is too old
There is a lot of text that is still in English
So I made a new Chinese version
[zh-CN.zip](https://github.com/univrsal/input-overlay/files/8746865/zh-CN.zip)
Please add it to your project(Remember to unzip)
Thank you
(In addition, there are many places that do not provide English text
![image](https://user-images.githubusercontent.com/67826085/169632829-ff62a608-2cd5-4a09-b027-174aad03469a.png)
So my Chinese translation may not be that accurate
Hope you can provide them soon
I will fix my Chinese translation at that time)

**Comment by GodGun968** [comment]
Although these places do not provide detailed English text, but I also translated into Chinese, so it may lead to inaccurate translation

**Comment by univrsal** [comment]
Please create a pull request for updating the translation
