### ISSUE TITLE
Wrong Layout // offset wrong

### ISSUE THREAD

**Issue by Hedrauta** [univrsal/input-overlay#25]
What happened:
![obs64_2018-02-21_19-25-18](https://user-images.githubusercontent.com/20142298/36497901-0048e1a6-173d-11e8-93cf-0fc55bf180ce.png)

What was supposed to happen:
... you shall know it.

Log file:
[2018-02-21 19-23-08.txt](https://github.com/univrsal/input-overlay/files/1745245/2018-02-21.19-23-08.txt)

BTw... i would prefer a QWERTZ-Layout.... don't do american QWERTY only ;)

**Comment by Hedrauta** [comment]
opened obs in DX11-mode.... it changed "a bit"
![obs64_2018-02-21_20-37-03](https://user-images.githubusercontent.com/20142298/36501285-0127cace-1747-11e8-94b7-327fa7f0c78f.png)

**Comment by univrsal** [comment]
Ich muss zugeben, dass ich so nen Fehler bis jetzt noch nicht gesehen hab. Ich geh mal davon aus, dass du immer die passenden *.ini Dateien verwendet hast (also game-pad.ini für game-pad.png etc.)
Kannst du mal das plugin in einer neuen Scene collection, in der sich nichts außer dem inpu-overlay befindet, ausprobieren?

Im log steht nichts interessantes außer, dass du nen Virenscanner benutzt, aber der sollte damit nichts zu tun haben.

Ich hab außerdem leider nicht die Zeit und Lust alle Tastaturlayouts zu erstellen. Es ist aber möglich eigene zu erstellen: [Tutorial](https://vimeo.com/242474782)

**Comment by Hedrauta** [comment]
:D jo moment

![obs64_2018-02-21_22-33-01](https://user-images.githubusercontent.com/20142298/36506560-4baa3126-1757-11e8-9389-fb11e9f8fef0.png)
![obs64_2018-02-21_22-33-29](https://user-images.githubusercontent.com/20142298/36506561-4bc814d4-1757-11e8-9ff6-9c5a9db41441.png)

**Comment by Hedrauta** [comment]
scheint einfach nur, als wäre ein Grund-Layout erstellt worden... nur an der falschen position 😐

**Comment by Hedrauta** [comment]
und wäre es möglich, die Trigger(LT/RT) auch analog darzustelllen? wie bei gamepad-viewer... bzgl tastatur: ich denke, das bekomme ich noch iwie hin :D mit viel lust und laune

**Comment by univrsal** [comment]
Ich bin leider komplett überfragt. Ich benutze nur Funktionen, die in OBS enthalten sind um die Textur zuzuschneiden.
Grafikkartentreiber sind wahrscheinlich die neuesten?
Evtl. mal eine ältere version von input-overlay versucht?

Wenn du willst kannst du noch folgendes machen:
- Windows Taste + R
- "dxdiag" eingeben
- "Alle Informationen speichern..."
- Und dann die Textdatei hochladen
Da stehen nen paar Informationen drin, die mir vllt. helfen könnten.

Ansonsten bin ich aber etwas ratlos (Ich kann die Tage evtl. mal die OBS Entwickler fragen).
Um die LT & RT Tasten kann ich mich kümmern, aber das wird dir momentan wahrscheinlich eh nicht viel bringen :P

**Comment by Hedrauta** [comment]
iiich versuch gleich mal ne ältere version.... und dxdiag ist hier: [DxDiag.txt](https://github.com/univrsal/input-overlay/files/1745925/DxDiag.txt)

**Comment by Hedrauta** [comment]
Mein Controller ist außerdem ein XBOX One Elite 😀 das hat sogar noch Paddel 👍

**Comment by Hedrauta** [comment]
aha! 
v4.3.1.... 
![obs64_2018-02-21_23-22-34](https://user-images.githubusercontent.com/20142298/36508848-2932cb1a-175e-11e8-9734-8f4b95aee795.png)

**Comment by Hedrauta** [comment]
dann muss was bei 4.4 nicht stimmen

**Comment by univrsal** [comment]
Ok, das ist schon mal ein Anfang. Ich hab zwischen 4.4 und 4.3 nur die Struktur nen bisschen aufgeräumt also kannst du ja für's erste die ältere Version verwenden. Ich schau mal nach welche Änderung für den Fehler verantwortlich sein könnte

**Comment by Hedrauta** [comment]
https://clips.twitch.tv/TallSourKleePermaSmug
Funktioniert superb auf der 4.3.1.... wenn ich jetzt noch die Controller-knöpfe in der History-config  einbauen kann, wird es episch.
PS: LT/RT analog wäre dann bei Fahr-Simulationen oder Rennspielen sehr effektiv...
PPS: Was mir nur auffiel, war, dass die History die Knöpfe "doppelt" erkannte..... ich denke, eine reine 1 sollte als Trigger reichen 😉

**Comment by univrsal** [comment]
Was meinst du mit "doppelt"?
Gamepad input in input-history ist eigentlich nicht geplant, weil ich das nicht für nützlich halte.

**Comment by Hedrauta** [comment]
![obs64_2018-02-23_20-53-59](https://user-images.githubusercontent.com/20142298/36614054-b8d4fe4a-18db-11e8-9922-8755824c7771.png)
"Schaltung-" (ergo Taste B bei mir) wurde nur 1x gedrückt.... kann da windows mitfummeln wegen tastenwiederholung?
Gamepad für Tastendefinition, damit man auch nachverfolgen könnte, ob man ( wie bei mir im Video zu erkennen ) auch eine Taste drückt ( die dann zuvor definiert wurde mit bspw.: _3_BUTTON_4=Tempomat Ein/Aus_ )

**Comment by Hedrauta** [comment]
Liegt an der Abfrage pro Frame:
wenn ich Taste A bei Frame 1 drücke, wird dort die Taste angezeigt, aber dann immer wieder ausgelöst, wenn Frame 2 und so weiter geladen wird. (ergo 30x pro Sek einen Eintrag in die History)
Wenn ich die Abfrage auf bspw. alle 10 Frames limitiere, werden bei gehaltener Taste 3 Anschläge pro Sekunde angezeigt (bei 30FPS-Stream) 🙃 

Eigentlich sollte bei es doch bei Frame 1 beim halten der Taste auslösen, und  solange zählen, bis ich bei Frame X die Taste wieder löse , oder nicht? 😕 

😄 versteh mich da nicht falsch, das Plugin ist richtig super, jedoch besteht an manchen Ecken großer Nachfrage-bedarf 😉

**Comment by univrsal** [comment]
input-history ist eigentlich nur für Tastenkombinationen gedacht. Das bedeutet, dass das Plugin bei z.B. einer Aktualisierungsrate von 10, 9 Bilder lang wartet und alle gedrückten Tasten sammelt. Beim 10. Bild werden alle gedrückten Tasten zusammengefügt und als Eintrag hinzugefügt.
Es wird also nicht unterschieden zwischen Taste gedrückt und gedrückt halten.

Ich denke, dass sich das wahrscheinlich realisieren lassen würde, allerdings müsste ich dafür die Quelle komplett überarbeiten und für's erste sollte ich erst Mal raus finden warum die neuste version bei manchen nicht mehr funktioniert.

**Comment by Hedrauta** [comment]
Erstmal Bugs, dann Features 😄 mir reicht derzeit schon das Plugin voll und ganz.. aber warum nicht mehr rauskitzeln können, wenn der Entwickler aktiv dran sitzt 😸

**Comment by univrsal** [comment]
Kleines update: Ich habs jetzt irgendwie geschafft den Fehler zu reproduzieren, sollte also möglich sein, dass ich das bald gefixt krieg

**Comment by univrsal** [comment]
Ich schließ das fürs erste bis ich ne Rückmeldung bekomm

**Comment by Hedrauta** [comment]
4.5 will wieder das problem aus meinem 1ste Post replizieren... ich lade gerade die zip von dir runter...
