### ISSUE TITLE
In need of help with custom gamepad JSON

### ISSUE THREAD

**Issue by KesslerBrowsing** [univrsal/input-overlay#254]
Hello univrasl! I am writing to you because of an issue I am having with a _JSON_ I have created for my HORI Taiko Drum.
I followed your tutorial with keyboard buttons and applied the button element method to both middle sides of the Taiko drum on a texture, and they worked as expected by lighting up when clicked in **io-cct**. However, when loaded into **OBS**, the same previewed operations in io-cc _do not seem to work at all as only the idle, unlit texture is shown._ Attached via zip are the texture and .json files in question.

[TaikoOverlay.zip](https://github.com/univrsal/input-overlay/files/8800120/TaikoOverlay.zip)

Please do help ASAP, I don't know where I could've gone wrong- Please and thank you.
-Future Taiko No Tatsujin Twitch Streamer

**Comment by univrsal** [comment]
Does the gamepad show up in the source settings?

**Comment by KesslerBrowsing** [comment]
Yes it does, sorry about the late response btw xd
![image](https://user-images.githubusercontent.com/96976863/171047712-e0dbb2e9-5817-4060-ae2b-d7c6c3d580de.png)

**Comment by univrsal** [comment]
Can you try rebinding the gamepad? Go to Tools > input-overlay settings > Gamepad bindings
Then enter a name, click the plus and select the text box for the buttons that the overlay uses (It looked to me like it's using the left stick and right stick being pressed, which would be "Left stick pressed" and "Right stick pressed") and press the corresponding button on your gamepad.

**Comment by KesslerBrowsing** [comment]
Just tried the binding switch (with"Left Stick Pressed" assigned to the Left Don and "Right Stick Pressed" assigned to the Right Don), and for some reason only the Left Don lights up with that method??? I think the Right Don is either linked to something else or my JSON is messed up (i dont think it's the latter as I presume u checked the attached JSON and saw no problems with it--)

**Comment by KesslerBrowsing** [comment]
(Also Gamepad testing does show that all parts of the drum controller are functional, it's just that apparently the plugin doesn't seem to like the Right Don/Button 11[or 0xEC10 according to io-cct] atm, probs cuz of me having no clue what binding could trigger it)

**Comment by KesslerBrowsing** [comment]
((Clearer example of one side working and the other not here:with epic maibachi ASMR XD)) @univrsal 

https://user-images.githubusercontent.com/96976863/171052814-6e4983a5-2b88-41f2-9a5f-ae1ca481d0cb.mp4

)

**Comment by univrsal** [comment]
What does the binding for the triggers look like in the binding dialog?

**Comment by KesslerBrowsing** [comment]
Sorry for the delay, timezones and all-!  Stuff just exists like this here xd
![image](https://user-images.githubusercontent.com/96976863/171185090-6119fa6c-644b-40aa-81e6-2039453187f5.png)

**Comment by KesslerBrowsing** [comment]
So ye- Do u know why the right don is detected by the io-cct thing as normal but not in the actual OBS bindings? when the left don is detected in both?? qwq""" @univrsal

**Comment by univrsal** [comment]
The config tool uses the browser for handling the gamepad, input overlay uses a separate gamepad library so they work completely different. If you're feeling adventurous you can download all files in this folder:
https://github.com/univrsal/input-overlay/tree/master/projects/plugin/data/overlay_render
(Including everything in the js folder, best to just get the entire repository and then extract the overlay_render folder)
Then put the json of your overlay here:
https://github.com/univrsal/input-overlay/blob/master/projects/plugin/data/overlay_render/renderer.html#L17
Then replace texture.png with your texture and load renderer.html in a browser source in obs studio.

If the image doesn't load you might need to upload it somehwere and replace "./texture.png" with the link:
https://github.com/univrsal/input-overlay/blob/master/projects/plugin/data/overlay_render/js/main.js#L29

Other than that I can't really help you right now.

**Comment by univrsal** [comment]
yeah the actual json, there's already an overlay in there and you have to replace it

**Comment by KesslerBrowsing** [comment]
Oh my god it works!! Thank you so much! The only thing is that the overlay appears cut off at the bottom, but either putting it in a different spot in my stream setup or fiddling with the html or js texture res should fix it! :D 
Cya, have a good day! ^u^
