### ISSUE TITLE
I cant find the deb

### ISSUE THREAD

**Issue by cloudcant** [univrsal/input-overlay#258]
i looked for the deb installer but i cant find
@univrsal 
srry for ping i just want someone to repspond

**Comment by univrsal** [comment]
https://github.com/univrsal/input-overlay/wiki/Installation

**Comment by cloudcant** [comment]
> 

still cant find deb, i looked in every dl >_>

**Comment by univrsal** [comment]
![image](https://user-images.githubusercontent.com/8353672/175287918-5cf60465-4888-4c26-a93f-24242e915ff3.png)

That being said I haven't even tested the installer so if it doesn't work manually installing is always an option.
