### ISSUE TITLE
Input History Crash

### ISSUE THREAD

**Issue by Hedrauta** [univrsal/input-overlay#26]
What happened:
Nachdem ich die Qwerty-Config geladen habe:
[Crash 2018-02-22 16-31-06.txt](https://github.com/univrsal/input-overlay/files/1748481/Crash.2018-02-22.16-31-06.txt)

What was supposed to happend:

Es sollte ein klassischer Input-History eingebunden werden

Log file:
[2018-02-22 11-25-04.txt](https://github.com/univrsal/input-overlay/files/1748485/2018-02-22.11-25-04.txt)

**Comment by univrsal** [comment]
Was für eine Qwerty config? War die für ein input-overlay oder für input-history?

**Comment by Hedrauta** [comment]
uh.... warte
:D da gibt es unterschiede?

**Comment by Hedrauta** [comment]
Ooooohhh... ich habs nu -.- etwas sehr verwirrend .... ist da irgendwo ein Beispiel für die Tastennamen-config

**Comment by univrsal** [comment]
Bis jetzt nicht, aber eine Datei könnte so aussehen:
```
# Erste Zeile muss immer ein Kommentar sein
# Danach können die Neudefinitionen folgen
# "2_" + Tasten Code + "=" + Tastenname
# Die Tastencodes kannst du mit dem angehängten Programm bekommen
# Einfach demo_hook.exe ausführen und dann die Tasten drücken
# (Das Programm zeigt zwar 0x39, aber es sollten immer vier Ziffern sein,
# deswegen den Rest einfach auffüllen)
# Für die Leertaste wäre das dann z.B. 
2_0039=Nicht Leertaste
```
[demo_hook.zip](https://github.com/univrsal/input-overlay/files/1748941/demo_hook.zip)

**Comment by Hedrauta** [comment]
dann kann ich das issue closen... 😄 ein Beispiel für die History sollte aber vielleicht hinterlegt werden.... dann würde da auch weniger missverständnisse geben ;)

**Comment by univrsal** [comment]
Vergess ich meistens, weil ich solche Features meistens auf anfrage für bestimme Leute hinzugefügt habe und diese von mir immer direkt eine Erklärung bekommen haben

**Comment by kaimi** [comment]
Ich weiß, Nekromantie und so … aber kann man in der config auch irgendwie Maustasten umbenennen? Meine Versuche waren bisher fruchtlos oder haben gleich OBS crashen lassen :)

**Comment by univrsal** [comment]
Version & Log bidde. Umbenennen geht mit einer extra Datei, mit folgendem Format
```
# Key name config
# "2_" + keycode + "=" + your desired name
# 0x0039 is the code for space bar
2_0x0039=Not spacebar
```

**Comment by kaimi** [comment]
Weiß ich, ich hab den Thread hier ja gelesen. Die Frage ist, welche Codes die Maustasten haben bzw. was ich stattdessen für Maustasten angeben muss.

Die Frage konnte ich mir mit Codelektüre leider nicht selbst beantworten.

**Comment by univrsal** [comment]
[Die](https://github.com/univrsal/input-overlay/blob/master/util/util.hpp#L158) sollten passen.
