### ISSUE TITLE
How to install it on Mac? Thanks!!

### ISSUE THREAD

**Issue by yrdimple** [univrsal/input-overlay#263]
PLEASE FILL THIS OUT CORRECTLY OR THE ISSUE WILL BE CLOSED

(You can remove this text after you've filled out the form)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional information:**
- Plugin version
- Full OBS Studio log (https://cdn.discordapp.com/attachments/376042662580715521/768461567347261470/unknown.png)

**Additional context**

**Comment by univrsal** [comment]
https://github.com/univrsal/input-overlay/wiki#does-this-work-on-macos

**Comment by Nitrodist** [comment]
I would love it if this worked in Mac 🥹

**Comment by univrsal** [comment]
I value my time and sanity more than supporting macos.
