### ISSUE TITLE
SoulCalibur 6 Overlay - Keyboard Only (for now)

### ISSUE THREAD

**Issue by Aeryn1023** [univrsal/input-overlay#265]
Hi, I'm not sure if this is the right place to post this at all, but I made an overlay for SoulCalibur 6, specifically for keyboard users.

This overlay requires you to use the default controls, or modify the image in some way to your preferred controls. All sources (fonts, border, etc.) are included in the README. Please also note that there is an issue with this where sc6.png is too large, and I'm not sure if downscaling it means I'll have to fix the .json or not.

[sc6_kb.zip](https://github.com/univrsal/input-overlay/files/9285992/sc6_kb.zip)
 
I apologize if this is not the correct place to put this, I'm new to submitting overlays.

![sc6](https://user-images.githubusercontent.com/95365759/183543577-d378b89c-2c79-4b92-a0ee-0c02a0b38556.png)

**Comment by univrsal** [comment]
Thanks for the preset!
The maximum texture size for obs is 4096x4096 if I recall correctly. So you have to downscale it. There isn't really any reason to have a texture this large as you'll downscale the source in obs anyways which just means wasted vram. If you want this to be included with the plugin you can make a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) and add the files in a separate folder [here](https://github.com/univrsal/input-overlay/tree/master/projects/presets)

**Comment by Aeryn1023** [comment]
> The maximum texture size for obs is 4096x4096 if I recall correctly. So you have to downscale it. 

Ah, ok. I'll be sure to downscale it today and make a pr 👍
