### ISSUE TITLE
Mouse Bug

### ISSUE THREAD

**Issue by hamzamoboi** [univrsal/input-overlay#266]
**What happened**
I was preparing for a recording for minecraft but when I tried to use the thumb button noticed that they were swapped.

**Expected behavior**
When I installed the plugin I thought that the thumb buttons will work perfectly.

**Additional information:**
- v4.8b

**Additional context**
- To fix the problem use this zip file:
 [thumb button bug fix.zip](https://github.com/univrsal/input-overlay/files/9289675/thumb.button.bug.fix.zip)

**Comment by univrsal** [comment]
See #298 for further tracking
