### ISSUE TITLE
Source not showing up in menu

### ISSUE THREAD

**Issue by grande1900** [univrsal/input-overlay#268]
**Describe the bug**
The Input-Overlay source isn't appearing in the menu

**To Reproduce**
???

**Expected behavior**
Input-Overlay source appears in the Sources>Add menu

**Screenshots**
![image](https://user-images.githubusercontent.com/54255077/185336986-7fd936ec-a98b-46bb-88c4-7c616fca4c71.png)

**Additional information:**
- Plugin version 5.0
- Full OBS Studio log https://obsproject.com/logs/UNc7ZGE3gNbEZ7xe

**Additional context**
I used the win-zip, it didn't work, then I tried the installer, that didn't work either.
I also tried installing the VC++ Redists but that didn't work.

**Comment by grande1900** [comment]
I just upgraded to 27.2.4 from 22.0.2, and that fixed it.

**Comment by Kyogre** [comment]
I already have 27.2.4 64bit, deleted all older input-overlay files/folders, done all that you done, rebooted PC, but still no source shows up.

**Comment by Kyogre** [comment]
upd. As creator says in https://github.com/univrsal/input-overlay/issues/272#issuecomment-1225534283 version 5.0 is only for OBS version 28 or newer.
