### ISSUE TITLE
Plugin doesn't load in OBS 21.0.1

### ISSUE THREAD

**Issue by JayCZ** [univrsal/input-overlay#27]
Downloaded the plugin and copied files to designated folders, OBS didn't load it.

Log file says:
LoadLibrary failed for '../../obs-plugins/64bit/input-overlay.dll': (null) (126)
Module '../../obs-plugins/64bit/input-overlay.dll' not loaded

32bit version behaves the same. 

Please advise, and thank you for your time.

**Comment by univrsal** [comment]
Well I'd need the entire log file to begin with

**Comment by JayCZ** [comment]
Thank you,
Version 4.3 behaves the same.
Full log:

> 11:30:03.005: CPU Name: Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz
11:30:03.006: CPU Speed: 2400MHz
11:30:03.006: Physical Cores: 2, Logical Cores: 4
11:30:03.006: Physical Memory: 8085MB Total, 3867MB Free
11:30:03.006: Windows Version: 10.0 Build 16299 (revision: 248; 64-bit)
11:30:03.006: Running as administrator: false
11:30:03.006: Aero is Enabled (Aero is always on for windows 8 and above)
11:30:03.006: Windows 10 Gaming Features:
11:30:03.006: 	Game DVR: On
11:30:03.008: Sec. Software Status:
11:30:03.009: 	Antivirová ochrana v programu Windows Defender: enabled (AV)
11:30:03.010: 	Brána Windows Firewall: enabled (FW)
11:30:03.010: 	Antivirová ochrana v programu Windows Defender: enabled (ASW)
11:30:03.010: Portable mode: false
11:30:03.036: OBS 21.0.1 (64bit, windows)
11:30:03.036: ---------------------------------
11:30:03.048: ---------------------------------
11:30:03.048: audio settings reset:
11:30:03.048: 	samples per sec: 44100
11:30:03.048: 	speakers:        2
11:30:03.049: ---------------------------------
11:30:03.049: Initializing D3D11...
11:30:03.049: Available Video Adapters: 
11:30:03.050: 	Adapter 1: Intel(R) HD Graphics 620
11:30:03.050: 	  Dedicated VRAM: 134217728
11:30:03.050: 	  Shared VRAM:    4238940160
11:30:03.051: 	  output 1: pos={0, 0}, size={1920, 1080}, attached=true
11:30:03.051: 	  output 2: pos={-1920, 0}, size={1920, 1080}, attached=true
11:30:03.052: Loading up D3D11 on adapter Intel(R) HD Graphics 620 (0)
11:30:03.060: D3D11 loaded successfully, feature level used: 45056
11:30:04.043: ---------------------------------
11:30:04.044: video settings reset:
11:30:04.044: 	base resolution:   1920x1080
11:30:04.044: 	output resolution: 1920x1080
11:30:04.044: 	downscale filter:  Bicubic
11:30:04.044: 	fps:               30/1
11:30:04.044: 	format:            NV12
11:30:04.046: Audio monitoring device:
11:30:04.046: 	name: VĂ˝chozĂ­
11:30:04.046: 	id: default
11:30:04.049: ---------------------------------
11:30:04.059: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/chrome_elf.dll' not found, loading of module failed
11:30:04.069: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
11:30:04.135: [AMF] <obs_module_load> AMF not supported (no AMD graphics)
11:30:04.135: Failed to initialize module 'enc-amf.dll'
11:30:04.220: LoadLibrary failed for '../../obs-plugins/64bit/input-overlay.dll': (null) (126)
11:30:04.220: Module '../../obs-plugins/64bit/input-overlay.dll' not loaded
11:30:04.267: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libcef.dll' not found, loading of module failed
11:30:04.268: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libEGL.dll' not found, loading of module failed
11:30:04.274: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libGLESv2.dll' not found, loading of module failed
11:30:04.278: Failed to load 'en-US' text for module: 'obs-browser.dll'
11:30:04.278: [browser_source: 'Version: 1.29.0']
11:30:04.317: LoadLibrary failed for 'nvEncodeAPI64.dll': (null) (126)
11:30:04.468: LoadLibrary failed for '../../obs-plugins/64bit/uiohook.dll': (null) (126)
11:30:04.468: Module '../../obs-plugins/64bit/uiohook.dll' not loaded
11:30:04.479: Couldn't find VLC installation, VLC video source disabled
11:30:04.506: No blackmagic support
11:30:04.764: ---------------------------------
11:30:04.764:   Loaded Modules:
11:30:04.764:     win-wasapi.dll
11:30:04.764:     win-mf.dll
11:30:04.764:     win-dshow.dll
11:30:04.764:     win-decklink.dll
11:30:04.764:     win-capture.dll
11:30:04.764:     vlc-video.dll
11:30:04.764:     text-freetype2.dll
11:30:04.764:     rtmp-services.dll
11:30:04.764:     obs-x264.dll
11:30:04.764:     obs-vst.dll
11:30:04.764:     obs-transitions.dll
11:30:04.764:     obs-text.dll
11:30:04.764:     obs-qsv11.dll
11:30:04.764:     obs-outputs.dll
11:30:04.764:     obs-filters.dll
11:30:04.764:     obs-ffmpeg.dll
11:30:04.764:     obs-browser.dll
11:30:04.764:     image-source.dll
11:30:04.764:     frontend-tools.dll
11:30:04.764:     enc-amf.dll
11:30:04.764:     coreaudio-encoder.dll
11:30:04.764: ---------------------------------
11:30:04.765: ==== Startup complete ===============================================
11:30:04.800: All scene data cleared
11:30:04.800: ------------------------------------------------
11:30:04.918: WASAPI: Device 'PL2288H (Intel(R) Display Audio)' initialized
11:30:04.943: WASAPI: Device 'PL2288H (Intel(R) Display Audio)' initialized
11:30:04.960: WASAPI: Device 'Mikrofon (C922 Pro Stream Webcam)' initialized
11:30:05.009: Switched to scene 'ScĂ©na'
11:30:05.012: adding 23 milliseconds of audio buffering, total audio buffering is now 23 milliseconds
11:30:05.028: ------------------------------------------------
11:30:05.028: Loaded scenes:
11:30:05.028: - scene 'ScĂ©na':
11:30:05.028:     - source: 'HlavnĂ­ obrazovka' (monitor_capture)
11:30:05.028:     - source: 'Webkamera' (dshow_input)
11:30:05.028: - scene 'ScĂ©na+KreslenĂ­':
11:30:05.028:     - source: 'HlavnĂ­ obrazovka' (monitor_capture)
11:30:05.029:     - source: 'Webkamera' (dshow_input)
11:30:05.029: - scene 'ScĂ©na bez kamery':
11:30:05.029:     - source: 'HlavnĂ­ obrazovka' (monitor_capture)
11:30:05.029: ------------------------------------------------
11:30:05.936: adding 23 milliseconds of audio buffering, total audio buffering is now 46 milliseconds
11:30:08.452: ---------------------------------
11:30:08.452: [DShow Device: 'Webkamera'] settings updated: 
11:30:08.452: 	video device: C922 Pro Stream Webcam
11:30:08.452: 	video path: \\?\usb#vid_046d&pid_085c&mi_00#6&3a969417&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global
11:30:08.452: 	resolution: 640x480
11:30:08.452: 	fps: 30.00 (interval: 333333)
11:30:08.452: 	format: YUY2

**Comment by Hedrauta** [comment]
try to pull the text-file into the typing field :D it will upload it automatically ;) 

but whatever... you sure installed the full plugin... not just even that 1 file? because:

> 14:40:05.432:   Loaded Modules:
> 14:40:05.433:     input-overlay.dll

is in my [log](https://github.com/univrsal/input-overlay/files/1762354/2018-02-24.14-40-03.txt), but i dont see any line in yours <.<

**Comment by Hedrauta** [comment]
![screen 1](https://user-images.githubusercontent.com/20142298/36727014-05472a5e-1bbc-11e8-893d-c99f970bbe3b.gif)
that's how **i** install it <.<
@univrsal Fühl dich frei, dieses Gif als "animierte installations-anleitung" zu verwenden 👍  hab da keine Hemmungen mit ;)

**Comment by JayCZ** [comment]
Sorry about the log file :)
It's there, 
>11:30:04.220: LoadLibrary failed for '../../obs-plugins/64bit/input-overlay.dll': (null) (126)
11:30:04.220: Module '../../obs-plugins/64bit/input-overlay.dll' not loaded.

Nice Gif, I actually did just that to install :]

**Comment by univrsal** [comment]
Yeah the plugin files are there so it might be that you don't have the Visual C++ 2015 Redistributable installed.
Can you try installing [this](https://www.microsoft.com/en-us/download/details.aspx?id=52685) (x86 & x64) and possibly [this](https://www.microsoft.com/en-us/download/details.aspx?id=5555) and see if it changes anything?

OBS isn't very helpful when it comes to logs sadly, which is why this is just a guess from me.

**Comment by JayCZ** [comment]
Thank you, that fixed it! It shows properly now. I'd recommend adding the 2015 c++ redist. to required libraries. Most people will have them, but since I'm using OBS to record tutorials at work, nothing else would have installed them.

I have a different problem now, but I'll open new issue for it if I don't find the solution.

**Comment by univrsal** [comment]
I'll add them as a note. I don't even know why they're required since OBS itself doesn't need them.
Btw, did you install both or only the 2015 redist?

**Comment by Pyrii** [comment]
I'm getting this issue on 21.0.1, I have all the redists already installed, files are int he correct locations. Win7
```03:28:54.906: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/chrome_elf.dll' not found, loading of module failed
03:28:54.907: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
03:28:54.957: [AMF] <obs_module_load> AMF not supported (no AMD graphics)
03:28:54.957: Failed to initialize module 'enc-amf.dll'
03:28:54.965: LoadLibrary failed for '../../obs-plugins/64bit/input-overlay.dll': The specified module could not be found.
03:28:54.965:  (126)
03:28:54.965: Module '../../obs-plugins/64bit/input-overlay.dll' not loaded
03:28:54.982: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libcef.dll' not found, loading of module failed
03:28:54.983: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libEGL.dll' not found, loading of module failed
03:28:54.983: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libGLESv2.dll' not found, loading of module failed
03:28:54.983: Failed to load 'en-US' text for module: 'obs-browser.dll'
03:28:54.983: [browser_source: 'Version: 1.29.0']
03:28:54.986: NVENC supported
03:28:55.107: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/uiohook.dll' not found, loading of module failed
03:28:55.108: Couldn't find VLC installation, VLC video source disabled
03:28:55.112: No blackmagic support
03:28:55.116: [Media Foundation encoder]: plugin is disabled for performance reasons on Windows versions prior to 8```

CFF Explorer seems to think that obs.dll and XINPUT1_4.dll are missing, I assume obs.dll is already loaded by the program.

**Comment by Pyrii** [comment]
Sorry for taking awhile to get back to you, been busy and sick. I just tested the version you linked and it works great.

**Comment by univrsal** [comment]
The gamepad doesn't work with the input-history, yet.
