### ISSUE TITLE
input overlay not working on latest version of plugin/obs

### ISSUE THREAD

**Issue by Tschis** [univrsal/input-overlay#270]
**Describe the bug**
- The Input-Overlay source isn't appearing in the menu for latest version
- When finding a version that shows up, configuration doesn't work

**To Reproduce**
Trying to add a new source, the options do not show `input overlay`

**Expected behavior**
Expected the `input overlay` source option

**Screenshots**
![image](https://user-images.githubusercontent.com/20662669/185796192-ae923400-42af-4943-83f5-1ff71bf74793.png)

**Additional information:**
- 5.0.0
- [Full OBS Studio log](https://obsproject.com/logs/Iuu6arQjqgctcHaZ)

**Additional context**
- OBS latest version (27.2.4) with plugin latest version (5.0.0) do not work
  - Using older version of plugin (4.x.x) makes the source appear, but still can't configure it
- OBS latest version (27.2.4) expects `.ini` file for configuration, plugin uses `.json`
  - If using version 4.x.x of the plugin, choosing the json file anyway seems to have no effect on behavior. Overlay becomes just a static image

**Comment by univrsal** [comment]
The plugin isn't being loaded. Did you use the installer of 5.0.0-rc? If you have obs-studio in a different location than the default folder, you'll have to manually install it.

**Comment by Tschis** [comment]
> Obs can't find the plugin so it's not in the correct folder. Did you use the installer of 5.0.0-rc? If you have obs-studio in a different location than the default folder, you'll have to manually install it or point the installer to the correct folder.

I have used both the installer and also the zip, moving the files manually.
By the way, the documentation is also out of date, as there is no `plugins` folder inside the zip.

As I said, using an older version of the plugin works, so I don't know what I would be doing wrong from a zip file to another :/

**Comment by univrsal** [comment]
5.0.0 Only works with obs studio 28.0.0, you need the installer for 5.0.0-rc if you use OBS Version 27

**Comment by Tschis** [comment]
> 5.0.0 Only works with obs studio 28.0.0, you need the installer for 5.0.0-rc if you use OBS Version 27

Thank you
