### ISSUE TITLE
Input-overlay does not show up in my sources

### ISSUE THREAD

**Issue by DS1337** [univrsal/input-overlay#272]
**Describe the bug**
I installed this plugin but it is not showing up on the sources.

**Screenshots**

![Nop](https://user-images.githubusercontent.com/39350646/186312121-1ddc923c-f9aa-464b-aba8-2f5668dc4e6b.png)

**Additional information:**
- Plugin version: v5.0.0
- Full OBS Studio log: -
- OS: Win 10 Pro 64Bit

What did i do wrong?
i followed the instructions like [here](https://github.com/univrsal/input-overlay/wiki/Installation)

**Comment by univrsal** [comment]
The latest release is only for OBS 28.0.0. You need this release https://github.com/univrsal/input-overlay/releases/tag/v5.0.0-rc1

**Comment by DS1337** [comment]
Working perfect, ty very much bro!
