### ISSUE TITLE
Can`t move my own overlay in OBS

### ISSUE THREAD

**Issue by DS1337** [univrsal/input-overlay#273]
**Describe the bug**
I cant move my overlay in OBS

**To Reproduce**

**Expected behavior**

**Screenshots**
![Overlay](https://user-images.githubusercontent.com/39350646/186444257-d2a195ad-0434-4ef0-8b1b-e6bc3cf6c5f0.png)

**Additional information:**
- Plugin version: [v5.0.0-rc1](https://github.com/univrsal/input-overlay/releases/tag/v5.0.0-rc1)
- OBS version: StreamElements OBS 27.2.4

**Additional context**

I did my own on https://univrsal.github.io/input-overlay/cct/, but with my own json file i cant move my overlay on OBS.
when I insert the "wasd-full.json" (Original), I can move it, but not my own one.

What I have to do, to move my own overlay in OBS?

json files:
[Original wasd-full.json](https://pastebin.com/8Bi5U1JL)
[My own created](https://pastebin.com/hMRWUQSV)

**Comment by univrsal** [comment]
For some reason the layout has a width and height of 0, try this layout
https://pastebin.com/H7LCWrsL

**Comment by DS1337** [comment]
ah I see, working fine now :) 

![Overlay2](https://user-images.githubusercontent.com/39350646/186449394-7aeded91-149a-4c79-8779-0dbbf93bf4cd.png)

ty again <3
