### ISSUE TITLE
ps3 pad

### ISSUE THREAD

**Issue by SpeedSpy** [univrsal/input-overlay#275]
bro please make one for ps3 pad you can use Xelu_Free_Controller&Key_Prompts like you do for dualsense 
have a good day and thanks <3

**Comment by univrsal** [comment]
I don't have time to make presets for others, you'll have to make it yourself or commission someone to do it.

**Comment by SpeedSpy** [comment]
i dont know how ;c

**Comment by univrsal** [comment]
https://github.com/univrsal/input-overlay/wiki/Usage#io-cct
https://github.com/univrsal/input-overlay/wiki/Creating-presets
And looking at other presets should give you a basic idea, otherwise look for someone who's willing to take a commission.
