### ISSUE TITLE
After installing (installer and manually) i cannot see the oprion to add a "input overlay" source in my obs

### ISSUE THREAD

**Issue by Stevendsm** [univrsal/input-overlay#279]
**Describe the bug**
Just what the title say

**Expected behavior**
After installing and rebooting the system i should get the input overlay source

**Additional information:**
- Plugin version latest
- Full OBS Studio log https://obsproject.com/logs/KHCYcOvU4MV_4F0A

**Additional context**
![Immagine 2022-08-29 172408](https://user-images.githubusercontent.com/104093397/187236573-80b7c218-a704-4263-a291-8fd3c0d1f38b.png)

**Comment by univrsal** [comment]
> Plugin version latest

You mean this version?
![image](https://user-images.githubusercontent.com/8353672/187237250-5d84899a-077d-4346-ae56-7dea25a78a91.png)

**Comment by Stevendsm** [comment]
Yes

**Comment by univrsal** [comment]
So you mean the release where it says
## This Version Only works with OBS Studio 28.0.0 and up. Use [this](https://github.com/univrsal/input-overlay/releases/tag/v5.0.0-rc1) release for older OBS versions
Do you mean that one?

**Comment by Stevendsm** [comment]
Oh god so i’m just running a wrong version of obs? I will retry with the other version you provided me. Sorry for wasting your time🙏😅

**Comment by univrsal** [comment]
It's mostly my fault, I should have waited with the new release until obs 28.0.0 is released

**Comment by Stevendsm** [comment]
Don’t worry at all, thank you for your reply
