### ISSUE TITLE
Imput History

### ISSUE THREAD

**Issue by LeoKornowski** [univrsal/input-overlay#28]
Hi
What happened: I try to use key icons instead plain text, using the samples arrow-key-icon, when i load .ini file, my OBS just crash, i will try to understand how .ini file works to apply to another layout that i made.

Theres someting wrong with this samples files, because i really cant use.

This is I have into .ini file:

.# Input Overlay config v.4
.# The amount of key icons in the texture
.1_icon_count=4
.# Dimensions of the keys
.1_icon_w=128
.1_icon_h=128
.# The order of the icon order using their key codes
.# Get them here (Search for "VC_" and then the key name):
.# https://github.com/univrsal/input-overlay/blob/master/libuiohook/include/uiohook.h#L137
.#2_icon_order=0xEE4D,0xEE50,0xEE4B,0xEE48
.2_icon_order=0xE048,0xE050,0xE04B,0xE04D"

In the 2 last lines, i change some keys from the github, bus still getting error, ignore the first dot.

And i attached a .png file and my log file.
![arrow-keys](https://user-images.githubusercontent.com/36929856/36803576-b0d8594e-1c96-11e8-9665-cf15fb5e0754.png)
[log.txt](https://github.com/univrsal/input-overlay/files/1768224/log.txt)

**Comment by univrsal** [comment]
huuh, yeah input-history seems to be broken.
Give me a little time and I'll look into it

**Comment by univrsal** [comment]
Okay, I fixed it. I messed up and deleted a variable too early and accessed it afterwards...
