### ISSUE TITLE
I have a visual bug and can't use script.

### ISSUE THREAD

**Issue by ShrienaT** [univrsal/input-overlay#281]
I have a visual bug and can't use script. I don't know why but there is a visual bug in my OBS. Can someone help me ?
![image](https://user-images.githubusercontent.com/112517507/187538993-23365fd6-b4d2-43b5-957b-e7a2aa04a737.png)

**Comment by univrsal** [comment]
You're using the preview image instead of the actual texture. You have to use `mouse-no-movement.png` and not `mouse-no-movement-preview.png`
