### ISSUE TITLE
.deb not working on linux mint? 

### ISSUE THREAD

**Issue by Srjoao** [univrsal/input-overlay#283]
I'm trying to install the plugin on obs 28 on Linux Mint 20.3 Cinnamon with .deb, but after installation obs doesn't change anything no option for creating a new input-overlay appears.

![image](https://user-images.githubusercontent.com/36121215/188031689-79d9bdc8-60ab-454f-b7d8-0864c5bccc0f.png)

- Plugin version: v5.0.0 https://github.com/univrsal/input-overlay/releases/tag/v5.0.0
- Full OBS Studio log https://obsproject.com/logs/LaX0CVODiFLpHwQ3

**Comment by univrsal** [comment]
Your version of obs is using Qt5, but 28.0.0 is supposed to upgrade to Qt6. You'll have to either compile the plugin from source or wait until Mint uses Qt6.

**Comment by Srjoao** [comment]
> Your version of obs is using Qt5, but 28.0.0 is supposed to upgrade to Qt6. You'll have to either compile the plugin from source or wait until Mint uses Qt6.

thankyou

**Comment by Srjoao** [comment]
> Your version of obs is using Qt5, but 28.0.0 is supposed to upgrade to Qt6. You'll have to either compile the plugin from source or wait until Mint uses Qt6.

Is there any tutorial teaching how to compile the source?

**Comment by univrsal** [comment]
1. Build OBS with these instructions https://github.com/obsproject/obs-studio/wiki/Build-Instructions-For-Linux
2. Clone this repository `git clone https://github.com/univrsal/input-overlay --recursive`
3. configure it with `cmake -S <path_to_input_overlay_folder> -DCMAKE_PREFIX_PATH="/usr;<path_to_obs_build>/build/UI/obs-frontend-api/;<path_to_obs_build>/build/libobs/" -DLOCAL_INSTALLATION=ON`
4. Build it with make, which will automatically install it to ~/.config/obs-studio/plugins
