### ISSUE TITLE
Gamepad overlay analog stick position drifting

### ISSUE THREAD

**Issue by ellischeng123** [univrsal/input-overlay#285]
**Describe the bug**
After updating to obs 28 and input overlay v5.0.0, gamepad overlay analog sticks drifted away from center without input or controller disconnected.

**To Reproduce**
Add a input overlay with gampad presets v5.0.0.

**Expected behavior**
Analog should stay in center when no input.

**Screenshots**
![drifted analog sticks gamepad overlay](https://i.imgur.com/pY3ZscN.png)

**Additional information:**
- v5.0.0
- [Full OBS Studio log](https://obsproject.com/logs/I-kvO2nwjxbgmLBK) No error though.

**Additional context**
None

**Comment by Andre601** [comment]
I can confirm that this is an issue.
The analog stick is displayed with a top-left shifting in the overlay (Image 1), while when loaded into the io-cct site (Overlay editor), everything looks normal (Image 2)

I used the same settings JSON file in both cases.

Image 1:
![image](https://user-images.githubusercontent.com/11576465/190493401-35574d43-1764-4094-9729-b4cadd6dbbe6.png)

Image 2:
![image](https://user-images.githubusercontent.com/11576465/190493497-48c77617-679e-4f9b-b7ca-a657125b981e.png)

**Comment by pumacatrun2** [comment]
Thirding, this is what mine shows up as when resting totally still. Any advice much appreciated. Disconnecting the controller/restarting the computer hasn't worked.
![image](https://user-images.githubusercontent.com/30131073/191903750-227a7bf3-26af-42ee-ba3f-67c0dab4311a.png)

**Comment by pumacatrun2** [comment]
Thank you, that does the job for now! Appreciate it.

**Comment by sergicosicas** [comment]
Hi! I fixed it by editing game-pad.json. I hope it's useful for you, you can download it [here](https://drive.google.com/file/d/1Sb3R3T957b06up8-MDFQ3q9-QIUvwJfj/view?usp=sharing).

**Comment by catb0t** [comment]
> Hi! I fixed it by editing game-pad.json. I hope it's useful for you, you can download it [here](https://drive.google.com/file/d/1Sb3R3T957b06up8-MDFQ3q9-QIUvwJfj/view?usp=sharing).

Thank you for that!

**Comment by AsrielDewitt** [comment]
> Hi! I fixed it by editing game-pad.json. I hope it's useful for you, you can download it [here](https://drive.google.com/file/d/1Sb3R3T957b06up8-MDFQ3q9-QIUvwJfj/view?usp=sharing).


I tried it, it doesn't work, It just...stuck there, weirdly enough

**Comment by univrsal** [comment]
See #297, should be fixed with the new gamepad backend
