### ISSUE TITLE
Inconsistent behavious between OBS and io-cct

### ISSUE THREAD

**Issue by BamberBoozler** [univrsal/input-overlay#286]
Overlay behaves differently between io-cct with the same texture and config.

**To Reproduce**
Have a DS4 plugged in via USB, try to use with dualsense presets, with either stock or custom json file

**Expected behavior**
Both versions to act the same and be an accurate representation of controller inputs

https://user-images.githubusercontent.com/50951969/190042800-47a8402b-3d6f-4c7c-a857-e4c66c440585.mp4

**Additional information:**
- v5.0.0
- https://obsproject.com/logs/aJCFqQciONyYTyZ2

**Comment by danelynnn** [comment]
seconding this, just realized this happened and was looking for some clarification lol

**Comment by dekuscrublife** [comment]
im having this issue as well, would love some help

**Comment by SteamboatTaco** [comment]
I have this same issue, and I feel like I was able to resolve this about 75 percent of the way through. I am still having trouble properly mapping the triggers on a Dualsense controller to work here and the sticks are very much off set when sitting still.

To get most of the way there you have to go to Tools> input-overlay settings > Local Features. In there select Use DInput, click OK and restart OBS. Return to Local Features and go to the Gamepad Bindings, Select your device, add a name in Binding Config and click the little plus button. From there you can rebind your keys to match better. I have attached what my currrent bindings look like.
https://pastebin.com/Dh4xRM1i

P.S. The binding config will pick up on stick micromovements, so I suggest while connected to set it down on as flat a surface as possible and using an online controller tester to see if the sticks are moving and changing your bindings.

**Comment by FiveArms** [comment]
I'm experiencing this issue as well. While @SteamboatTaco has great advice for potentially getting closer to a fix, note well that you may not be able to recover the default gamepad bindings. I've tried to uninstall and reinstall the input-overlay plugin to recover the defaults with no success.

Ultimately, with no documentation on what the "gamepad bindings" (in 'input-overlay-settings') values mean, and no way to get default values back, it's very hard to debug this as a user. Further, the inconsistency from the io-cct tool and obs output is very confusing. Why does io-cct show everything working perfectly when OBS input overlay does not?

Thanks in advance to anyone that helps with this issue.

**Comment by univrsal** [comment]
The gamepad input in the config tool is handled by your browser, the gamepad input in the plugin is handled by a gamepad library that I wrote. It shouldn't come as a surprise that the former is a bit more ironed out. I have considered just copy-pasting gamepad code from SDL2, but I currently am busy with other stuff.

**Comment by univrsal** [comment]
See #297 for further tracking
