### ISSUE TITLE
Source not showing up when trying to add it

### ISSUE THREAD

**Issue by Kiffolisk** [univrsal/input-overlay#287]
**Describe the bug**
When trying to add the Input Overlay source, I cannot find it in the list

**To Reproduce**
Install the .deb file and start OBS then try adding the source

**Expected behavior**
The Input Overlay source appearing in the list

**Screenshots**
![image](https://user-images.githubusercontent.com/45130240/190623158-ebd096b2-a29f-4870-967a-24ece071216b.png)

**Additional information:**
- Plugin version: 5.0.0
- [Full OBS Studio log](https://obsproject.com/logs/QbiOEkHTZLGVguVP)

**Additional context**
As said before, I am using Linux. Specifically Linux Mint 20.2 x86_64.

**Comment by univrsal** [comment]
See #283

**Comment by Kiffolisk** [comment]
Thanks
