### ISSUE TITLE
io_client.exe not present in release. 

### ISSUE THREAD

**Issue by crstalli** [univrsal/input-overlay#288]
**Describe the bug**
io_client.exe not present in the installation zip of release 5.0.0.

**To Reproduce**
Download windows installation zip files for 5.0.0. Notice no util folder. 

**Expected behavior**
There should be a util folder with an io_client.exe present as described on the wiki. 

**Screenshots**
N/A.

**Additional information:**
- Plugin version: 5.0.0
- OBS Version: not needed.

**Additional context**
If we have to clone and compile locally for io_client.exe functionality; it would be helpful to update the documentation.

**Comment by david-kishi** [comment]
@univrsal Please update release with a built io_client.exe. Attempting to utilize remote connection for a dual PC streaming/recording setup and this is the last thing I need. 🙏

**Comment by PsiborgJhin** [comment]
ditto

**Comment by PsiborgJhin** [comment]
okay, I learned CMake enough to make and run the project. it seems the issue is with the input buffer. so to save a long story, it's a bit broken at the moment, but i dont mind reporting back if i find the cause

**Comment by univrsal** [comment]
The client hasn't changed since the pre-release, I just never updated the CI to build it. You can get the old client here https://github.com/univrsal/input-overlay/releases/tag/v5.0.0-rc1 from the input-overlay.v5.0.0rc1-8d04a98.win.zip file, but the remote connection is currently pretty unreliable

**Comment by PsiborgJhin** [comment]
Do you know if there is a reason for the hook_run() method to freeze on windows 11? that is the current issue i'm seeing at the moment that is preventing the program from collecting messages.

**Comment by PsiborgJhin** [comment]
deleted my previous message, I think I may not have built it correctly with the current branch

**Comment by univrsal** [comment]
As of af8e50c the client is now packaged into the windows zip files
