### ISSUE TITLE
New to OBS - Need Help Installing Please (Unsuccessful so far)

### ISSUE THREAD

**Issue by LightWav** [univrsal/input-overlay#29]
What happened: Sorry, but I'm fairly new to OBS and I can't seem to install this plugin correctly. I'm running the 32 bit on Windows 10. I've tried following the instructions, but can't get it to show up in OBS. Your help would be appreciated!

**Comment by univrsal** [comment]
First I'll need a obs log file.
![image](https://user-images.githubusercontent.com/8353672/36915920-aa9e8856-1e52-11e8-8a5e-14483afa5a50.png)

**Comment by LightWav** [comment]
I don't know how to do that. I opened OBS and could not select "Upload Current Log File". So I did a Preview and then Uploaded the current log file. I don't know where it uploaded.
Also, I just realized I think I'm using OBS Classic, not OBS Studio. I'm going to install Studio. Do you think that will help?

**Comment by univrsal** [comment]
Yeah.. That would help. OBS Classic is severely outdated and is not compatible with any OBS Studio plugins.

**Comment by LightWav** [comment]
So I've installed OBS Studio. I still can't quite figure things out. I unzipped your package in the obs-studio directory. That didn't work so I pasted the "data" and "obs-plugins" folders in the the obs-studio directory. That allowed me to add Input Overlay source in OBS Studio, but I don't see an overlay, and I don't know if I need to do anything to it's properties. Any pointers? I'm attaching a couple screenshots for you to see. Thanks for any help you can offer! I'm excited to use this plugin.
![screenshot 2018-03-03 11 31 19](https://user-images.githubusercontent.com/36994006/36937868-e3748c50-1ed6-11e8-9ea1-64d2f9628bf1.png)
![screenshot 2018-03-03 11 31 50](https://user-images.githubusercontent.com/36994006/36937869-e3a49ef4-1ed6-11e8-8ab3-95be18d3e99c.png)

**Comment by LightWav** [comment]
And here's my current log file, even though I don't know how log files work.
https://gist.github.com/6c81e0a07bd94fc629969afdb4e3c1c7

**Comment by univrsal** [comment]
You installed it correctly, now you should take a look at my [guide](https://vimeo.com/229296849)

**Comment by LightWav** [comment]
Nice! I'll do that. Thank you.

**Comment by univrsal** [comment]
I'll just close this for now. Just comment if you run into any other issues
