### ISSUE TITLE
displaying the keyboard keys as other regular keystroke apps

### ISSUE THREAD

**Issue by alezzacreative** [univrsal/input-overlay#290]
i want to know if we can have an option to use the keyboard overlays as other regular keystrokes software like this https://www.youtube.com/watch?v=T1eRRuD87v8
or
https://www.youtube.com/watch?v=4p5en7TX05k
where only the pressed keys get shown instead of them being displayed all the time
i record design tutorials and displaying a lot of keys all the time is very intrusive
thank you

**Comment by univrsal** [comment]
See https://github.com/univrsal/input-overlay/tree/master/presets/input-history-windows

**Comment by alezzacreative** [comment]
cool thank you for you quick response
that's what i have in mind but i wanted to use a custom SVG skin i created as a key background 
if you could point me to the right method cuz i have zero knowledge on that matter
thank you

**Comment by univrsal** [comment]
Everything you need is in that html file. Unless you know js, html and css it'll be tricky to do though
