### ISSUE TITLE
nohboard.exe not present

### ISSUE THREAD

**Issue by Hiroiscoding** [univrsal/input-overlay#292]
Describe the bug
In the extracted file from the .zip, the nohboard.exe application isn't there to run.

To Reproduce
All I did was download the file and extract the .zip

Expected behavior
I expected the .exe file to be there, so I can run it.

Screenshots
N/A

**Comment by univrsal** [comment]
Did you even wrote my last comment? This is the repository for input overlay it has nothing to do with noboard.
You can download nohboard here:
https://github.com/ThoNohT/NohBoard/releases/tag/v1.3.0
