### ISSUE TITLE
On Ubuntu 22.04 Input-overlay v.5.0.0 causes crash of OBS Studio 28.1.2 on start-up 

### ISSUE THREAD

**Issue by Seamas73** [univrsal/input-overlay#293]
On Ubuntu 22.04 and OBS Studio 28.1.2 if I install plugin input-overlay v5.0.0 OBS studio don't start. When I try to start it from console I see the message:

> info: [input-overlay] [input-overlay] Loading v5.0.0 build time 2022.08.21 10:40
> info: [input-overlay] Using '/dev/input/js*' for gamepad discovery
> info: [input-overlay::libgamepad] No Devices detected. Waiting for connection...
> info: [input-overlay] gamepad hook started
> info: [input-overlay::libgamepad] Hook thread started
> QWidget: Must construct a QApplication before a QWidget
> Emergency stop (memory stack flushed to disk)

Then OBS-Studio stops.
When I uninstall plugin, OBS Studio starts without any problem.

**Comment by univrsal** [comment]
Please post the entire log file, also try running `gdb obs -ex run` and then `bt` once it crashes to get a back trace

**Comment by Seamas73** [comment]
`19:03:44.676: Using EGL/X11
19:03:44.688: CPU Name: Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
19:03:44.688: CPU Speed: 3700.000MHz
19:03:44.688: Physical Cores: 2, Logical Cores: 4
19:03:44.688: Physical Memory: 15869MB Total, 1550MB Free
19:03:44.688: Kernel Version: Linux 5.15.0-53-lowlatency
19:03:44.689: Distribution: "Ubuntu" "22.04"
19:03:44.689: Session Type: x11
19:03:44.689: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1
19:03:44.689: Qt Version: 5.15.3 (runtime), 5.15.3 (compiled)
19:03:44.689: Portable mode: false
19:03:44.816: OBS 28.1.2-dfsg1-0ubuntu1~22.04.sav0 (linux)
19:03:44.816: ---------------------------------
19:03:44.874: ---------------------------------
19:03:44.874: audio settings reset:
19:03:44.874: 	samples per sec: 44100
19:03:44.874: 	speakers:        2
19:03:44.874: 	max buffering:   1044 milliseconds
19:03:44.874: 	buffering type:  dynamically increasing
19:03:44.882: ---------------------------------
19:03:44.882: Initializing OpenGL...
19:03:44.927: Loading up OpenGL on adapter NVIDIA Corporation NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
19:03:44.927: OpenGL loaded successfully, version 3.3.0 NVIDIA 515.65.01, shading language 3.30 NVIDIA via Cg compiler
19:03:44.956: ---------------------------------
19:03:44.956: video settings reset:
19:03:44.956: 	base resolution:   1920x1080
19:03:44.956: 	output resolution: 1920x1080
19:03:44.956: 	downscale filter:  Bicubic
19:03:44.956: 	fps:               60/1
19:03:44.956: 	format:            NV12
19:03:44.956: 	YUV mode:          Rec. 709/Partial
19:03:44.956: NV12 texture support not available
19:03:44.956: P010 texture support not available
19:03:44.956: Audio monitoring device:
19:03:44.956: 	name: По умолчанию
19:03:44.956: 	id: default
19:03:44.956: ---------------------------------
19:03:44.960: No AJA devices found, skipping loading AJA UI plugin
19:03:44.960: Failed to initialize module 'aja-output-ui.so'
19:03:44.963: No AJA devices found, skipping loading AJA plugin
19:03:44.963: Failed to initialize module 'aja.so'
19:03:44.964: Failed to load 'en-US' text for module: 'decklink-captions.so'
19:03:44.966: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
19:03:44.968: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
19:03:44.968: Failed to initialize module 'decklink.so'
19:03:45.050: [input-overlay] [input-overlay] Loading v5.0.0 build time 2022.08.21 10:40
19:03:45.062: [input-overlay] Using '/dev/input/js*' for gamepad discovery
19:03:45.062: [input-overlay::libgamepad] No Devices detected. Waiting for connection...
19:03:45.063: [input-overlay] gamepad hook started
19:03:45.063: [input-overlay::libgamepad] Hook thread started
`

**Comment by Seamas73** [comment]
seamas@Ubuntu-desktop:~$ gdb obs -ex run
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from obs...
(No debugging symbols found in obs)
Starting program: /usr/bin/obs 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffea038640 (LWP 81731)]
[New Thread 0x7fffe943e640 (LWP 81732)]
[New Thread 0x7fffe8c11640 (LWP 81733)]
debug: Found portal inhibitor
[New Thread 0x7fffdbbba640 (LWP 81734)]
[New Thread 0x7fffdb3b9640 (LWP 81735)]
[New Thread 0x7fffdabb8640 (LWP 81736)]
[New Thread 0x7fffda3b7640 (LWP 81737)]
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/locale/ru-RU.ini
Attempted path: /usr/share/obs/obs-studio/locale/ru-RU.ini
info: Using preferred locale 'ru-RU'
Attempted path: share/obs/obs-studio/themes/Yami.qss
Attempted path: /usr/share/obs/obs-studio/themes/Yami.qss
info: Using EGL/X11
info: CPU Name: Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
info: CPU Speed: 3699.996MHz
info: Physical Cores: 2, Logical Cores: 4
info: Physical Memory: 15869MB Total, 1824MB Free
info: Kernel Version: Linux 5.15.0-53-lowlatency
info: Distribution: "Ubuntu" "22.04"
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1
[New Thread 0x7fffd9901640 (LWP 81741)]
[New Thread 0x7fffd9100640 (LWP 81742)]
info: Qt Version: 5.15.3 (runtime), 5.15.3 (compiled)
info: Portable mode: false
[New Thread 0x7fffd88ff640 (LWP 81743)]
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
QMetaObject::connectSlotsByName: No matching signal for on_actionShowTransitionProperties_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_actionHideTransitionProperties_triggered()
info: OBS 28.1.2-dfsg1-0ubuntu1~22.04.sav0 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 44100
	speakers:        2
	max buffering:   1044 milliseconds
	buffering type:  dynamically increasing
[New Thread 0x7fffb8dff640 (LWP 81749)]
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter NVIDIA Corporation NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
info: OpenGL loaded successfully, version 3.3.0 NVIDIA 515.65.01, shading language 3.30 NVIDIA via Cg compiler
info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: 1920x1080
	downscale filter:  Bicubic
	fps:               60/1
	format:            NV12
	YUV mode:          Rec. 709/Partial
[New Thread 0x7fffb17ff640 (LWP 81750)]
info: NV12 texture support not available
info: P010 texture support not available
[New Thread 0x7fffabfff640 (LWP 81751)]
info: Audio monitoring device:
	name: По умолчанию
	id: default
info: ---------------------------------
warning: No AJA devices found, skipping loading AJA UI plugin
warning: Failed to initialize module 'aja-output-ui.so'
warning: No AJA devices found, skipping loading AJA plugin
warning: Failed to initialize module 'aja.so'
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
warning: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
libDeckLinkAPI.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
warning: Failed to initialize module 'decklink.so'
[New Thread 0x7fffaaecf640 (LWP 81753)]
info: [input-overlay] [input-overlay] Loading v5.0.0 build time 2022.08.21 10:40
[New Thread 0x7fffa8c35640 (LWP 81754)]
info: [input-overlay] Using '/dev/input/js*' for gamepad discovery
info: [input-overlay::libgamepad] No Devices detected. Waiting for connection...
[New Thread 0x7fff9bfff640 (LWP 81758)]
info: [input-overlay] gamepad hook started
QWidget: Must construct a QApplication before a QWidget
info: [input-overlay::libgamepad] Hook thread started

Thread 1 "obs" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737128268928) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: Нет такого файла или каталога.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737128268928) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737128268928) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737128268928, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff4430476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff44167f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007fffa8db1265 in qErrnoWarning(char const*, ...) () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#6  0x00007fffa9b3ef6c in  () at /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#7  0x00007fffa9daaeec in QDialog::QDialog(QWidget*, QFlags<Qt::WindowType>) () at /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#8  0x00007fffaa1d65bb in io_settings_dialog::io_settings_dialog(QWidget*) (this=this@entry=0x555558409d30, parent=parent@entry=0x555555befb10)
    at /usr/include/x86_64-linux-gnu/qt6/QtCore/qflags.h:109
#9  0x00007fffaa1cc99c in obs_module_load() () at /home/runner/work/input-overlay/input-overlay/plugin/src/input_overlay.cpp:78
#10 0x00007ffff55d675b in obs_init_module () at /lib/x86_64-linux-gnu/libobs.so.0
#11 0x00007ffff55d6bd1 in  () at /lib/x86_64-linux-gnu/libobs.so.0
#12 0x00007ffff55d84ec in obs_find_modules2 () at /lib/x86_64-linux-gnu/libobs.so.0
#13 0x00007ffff55d6c6b in obs_load_all_modules2 () at /lib/x86_64-linux-gnu/libobs.so.0
#14 0x00005555556950c9 in  ()
#15 0x000055555562bb3c in  ()
#16 0x00005555555f50bd in main ()
(gdb)

**Comment by univrsal** [comment]
You're using Qt5, but OBS 28 is supposed to switch to qt6 which is what input overlay requires. You will either have to compile the plugin yourself or upgrade to a version of obs that uses qt6.

**Comment by Seamas73** [comment]
> You're using Qt5, but OBS 28 is supposed to switch to qt6 which is what input overlay requires. You will either have to compile the plugin yourself or upgrade to a version of obs that uses qt6.

Yes, You are right: my OBS Studio updated not from ppa:obsproject/obs-studio, but from ppa:savoury1/multimedia where OBS Studio 28.1.2 compiled with Qt5 dependencies. I pinned the ppa:obsproject/obs-studio repository so I can Install OBS Studio with Qt6 dependencies, and your plugin began to work.
Thanks for help.
