### ISSUE TITLE
Cannot add to OBS

### ISSUE THREAD

**Issue by LibTheBirdLover** [univrsal/input-overlay#296]
I've downloaded all the required items, yet 'Input Overlay' does not show up in obs. Please help

**Comment by LukeSaward1** [comment]
Did you put it in the right directory? And did you download the right Input Overlay for your OBS version?

**Comment by markpaul099** [comment]
> Did you put the plugin in the right directory? And did you download the right Input Overlay for your OBS version?

Used the installer and manually installed with the files, both didn't work, I'm on the latest version of OBS, Windows 11, "Input Overlay" is not showing up in sources option.

**Comment by starchyunderscore** [comment]
i am having the same issue on nobara. at one point i did manage to have it show up but it said it was outdated. obs 28.1.2 latest relese of input-overlay

**Comment by EmMper** [comment]
My obs version is the newest 28.1.2, and I downloaded input-overlay 5.0.0, install it to "path_to_obs/obs-plugin/64bit", or "path_to_obs/data/obs-plugin/64bit", both paths are not working. Someone knows reason?

**Comment by In2013** [comment]
29.0 same problem

**Comment by univrsal** [comment]
If this issue still persists, please open a new issue and fill out the template correctly.
