### ISSUE TITLE
key stroke won't register in some games

### ISSUE THREAD

**Issue by syzhk3** [univrsal/input-overlay#3]
this is a great tool,but i've noticed that when i'm playing this MMORPG Guild Wars 2,the key strokes won't register. when I test it on OBS screen , it works just fine. but when i got back to the game(GW2 in this case), key strokes just won't be registered anymore. and what is even more strange is that when im in GW2, the alphabets won't register,but the tab, caps locks ,shift,ctrl ,enter ,space and back space will be correctly registered.
do you know what is the problem?
ps: some other games works just fine on my pc witcher 3 etc.

**Comment by syzhk3** [comment]
problem solved. run obs as administrator and everything will work.
thanks for creating this plug

**Comment by univrsal** [comment]
Thanks for the feedback!
Does the game run as administrator? That might be why OBS needs to also have admin rights.

**Comment by syzhk3** [comment]
no i don't run the game as administrator,just double click to run it.
