### ISSUE TITLE
overlay wrong keys displayed

### ISSUE THREAD

**Issue by MrVeniveci** [univrsal/input-overlay#30]
What happened:
when i put in the wasd-full.ini with the wasd.png it doesnt display the tab,r or f key correctly 
![obs64_2018-03-04_12-24-02](https://user-images.githubusercontent.com/37030860/36941069-f8284f58-1fa6-11e8-89f0-f05ac8dd3c00.png)

What was supposed to happend:
http://www.hnng.moe/f/YH0
Log file:

**Comment by MrVeniveci** [comment]
I thought i found the fix in closed issues it did not work

**Comment by univrsal** [comment]
I already found the reason for this issue but I'm waiting for someone else to report me about a different issue. I'll make a quick release for now though that fixes this.

**Comment by univrsal** [comment]
I'll close this for now. Just comment again if anything's off

**Comment by MrVeniveci** [comment]
wait so how do i fix it?

**Comment by MrVeniveci** [comment]
NVM FIGURED IT OUT

**Comment by MrVeniveci** [comment]
ty ty
