### ISSUE TITLE
Feature: Add delay and fade effect

### ISSUE THREAD

**Issue by rajinder-yadav** [univrsal/input-overlay#301]
This is a request for 2 features to be added. I find the overlay key flash really quickly.

It would be nice to have a configurable delay (in milliseconds) and then have the overlay return to it's unpressed state.
Also having a fade effect, which could be a boolean option would be nice.

As a resut of adding a delay. When a key is pressed rapidly, you would not see the presses, only its on state. One way around this would be to fade the overlay by a certain percentage quickly, then begin the delay counter. This way, you would notice rapid keypress by the intensity of the overlay.

Would love to see at least a delay option added.

**Comment by univrsal** [comment]
You could achieve this with css animations I guess, but I won't add it to the native overlay source.
