### ISSUE TITLE
Controller Input Not Detected

### ISSUE THREAD

**Issue by DrakePHOSE** [univrsal/input-overlay#302]
Hit my A button (for example) on my Xbox controller and it will show up in the configuration web tool but not in OBS.

I tried reinstalling OBS and Input Overlay and the issue stayed. I tried making a separate source with only the A button and that didn't work. I even asked someone else to take my source and try it and it worked for them.

OBS 29.0.0
Input Overlay 5.0.0
Windows 10 19044
Earlier patches of Windows 10 as well. (Only a few months ago did I take the time to make sure every other variable was accounted for. Then I forgot to report it for a while. Still doesn't work.)
Log: https://obsproject.com/logs/JjqD1TjJx2FQhOO7

**Comment by univrsal** [comment]
see #297
