### ISSUE TITLE
Cannot Install since installer only wants to install onto steam version

### ISSUE THREAD

**Issue by derric-young** [univrsal/input-overlay#303]
**Describe the bug**
Detects Steam version only when Both is installed. much prefer non-steam version

**To Reproduce**
Steps to reproduce the behavior: just run the installer with the steam version installed as well as the non-steam version

**Expected behavior**
Should Defualt to Non-steam version

**Additional information:**
- Latest at the time of creating
- log cannot be provided since this is not a obs thing. its a installer thing
- would seem to only work if i have the steam version Not be Installed. 

**Additional context**
tried to add a input viewer for my twitch layout. usually use the non-steam version becuase it is what i usually use.

**Comment by univrsal** [comment]
Just change the location to the other obs installation or install it manually.
