### ISSUE TITLE
Failure to Recognize Inputs (DualSense)

### ISSUE THREAD

**Issue by ItsRogueRen** [univrsal/input-overlay#304]
**Describe the bug**
Plugin is either detecting no inputs at all, or detecting the wrong inputs (i.e. pressing L2 activates select). Going to remap the buttons results on the input field cycling through random values with no input, and any given input is immediately changed. 

**To Reproduce**
Install OBS 29 via the Ubuntu PPA (Offcial OBS release)
Install plugin via provided .deb file
Download presets
Add an overlay to the scene, choosing the DualSense controller
Go to tool>input-overlay settings>gamepad bindings
click on an input field

**Expected behavior**
Select field should not change until an input is given, and ONLY when an input is given

**Screenshots**
[Video example](https://youtu.be/bBwdi4Wck0I)

**Additional information:**
- Plugin version 5.0.0
- Full OBS Studio log (https://obsproject.com/logs/eCZfv6QeKpcir43i)

**Additional context**
OS: Pop!_OS 22.04 LTS

**Comment by univrsal** [comment]
See #297

**Comment by ItsRogueRen** [comment]
> See #297

I did and it had everyone saying the DualSense was fine, but mine isn't. Is there something I missed for that?

**Comment by univrsal** [comment]
Fine as in they work with SDL2, which is not yet used by input overlay

**Comment by ItsRogueRen** [comment]
> 

Well that explains it, I thought everything was closed because it had been added and I was somehow still having issues

**Comment by univrsal** [comment]
I just closed all issues related to gamepads to sum them all up into one issue

**Comment by ItsRogueRen** [comment]
> I just closed all issues related to gamepads to sum them all up into one issue

Awesome, then I just need to wait for your next release! Thanks!!

**Comment by univrsal** [comment]
Well, if the last release is any indication it'll take roughly three years.

**Comment by ItsRogueRen** [comment]
> Well, if the last release is any indication it'll take roughly three years.

...wait what? Can I build a version with it from source then?

**Comment by univrsal** [comment]
[input-overlay/tree/sdl2-gamepad](https://github.com/univrsal/input-overlay/tree/sdl2-gamepad) contains the current changes, idk if it'll build though.
