### ISSUE TITLE
can't zoom out on overlay texture in io-cct

### ISSUE THREAD

**Issue by oinkymoo** [univrsal/input-overlay#305]
the zoom level is capped at much too low a value, so I can't access most of the keys in larger files

**Comment by oinkymoo** [comment]
as a workaround, i can zoom out the tab, but I shouldn't have to do that to use the page

**Comment by univrsal** [comment]
Just right click and move the texture

**Comment by oinkymoo** [comment]
ah, i missed that, sorry
