### ISSUE TITLE
Input Overlay not displaying properly

### ISSUE THREAD

**Issue by ETwess** [univrsal/input-overlay#306]
Setup all the files and followed all the guides and reinstalled everything to make sure

This is what is displayed in obs, the inputs work but the display is bugged

![Untitled](https://user-images.githubusercontent.com/125094130/218207325-a0ac937c-d1c3-4751-b4bd-29000e8eb02a.png)

![Untitled2](https://user-images.githubusercontent.com/125094130/218207588-68c00c28-b63b-4dbf-97f2-6ed5349c97c9.png)

**Comment by univrsal** [comment]
You're using the preview images as you can see by the `preview` in the filename.

**Comment by ETwess** [comment]
which files should I be using? could you please link me to the right files? i would greatly appreciate it, thank you

**Comment by univrsal** [comment]
they are literally in the same folder

**Comment by ETwess** [comment]
i'm a donut, thank you so much
