### ISSUE TITLE
Can't find gamepad button keycodes

### ISSUE THREAD

**Issue by HyperBeast43** [univrsal/input-overlay#307]
I can't find the gamepad button keycodes anywhere, and the "record keycode" option on the website doesn't seem to work.

**Comment by univrsal** [comment]
https://github.com/univrsal/input-overlay/blob/master/docs/cct/js/vc.js#L178-L192

**Comment by HyperBeast43** [comment]
ok but why is that nowhere in the readme

**Comment by univrsal** [comment]
it is now
