### ISSUE TITLE
Mouse/Keyboard Presets Not Recording Inputs

### ISSUE THREAD

**Issue by sclead03** [univrsal/input-overlay#308]
**Describe the bug**
Using the packaged preset QWERTY and Mouse-no-movement overlays, no input is displayed or recorded. Win10 19045.2486, OBS 29.0.2

**To Reproduce**

Install input-overlay in obs-studio\obs-plugins\64bit.
Copy zipped presets folder to c:\Program Files\obs-studio\presets
Add keyboard and mouse overlays as sources in OBS

**Expected behavior**
See on-screen feedback displayed of inputs on mouse and/or keyboard.

**Screenshots**
https://i.imgur.com/7OTpWQ0.png
https://i.imgur.com/luqiKLp.png
https://i.imgur.com/9awwFyK.png

**Additional information:**
- Plugin version 5.0.0
- Full OBS Studio log: https://obsproject.com/logs/6sZIL8WLPUifV9BS

**Additional context**

**Comment by univrsal** [comment]
try running obs as administrator

**Comment by sclead03** [comment]
I did try that, should've mentioned as much. Tried again just now to be sure. Still no luck, including after a couple restarts.
