### ISSUE TITLE
mouse over sensitive in game 

### ISSUE THREAD

**Issue by hazethegreat** [univrsal/input-overlay#31]
What happened: (v4.2 because 4.4 won't install) Mouse direction flickers all over the place in-game (Quakeworld) even during smooth single directional moevement. Works properly out of game. Sensitivity doesnt fix the issue. It is like the movement indicator is trying to 'recenter' after every tic. "Use Monitor center" option freezes the mouse input.

What was supposed to happend:

Log file:

**Comment by univrsal** [comment]
First off, I'd need some input on why 4.4 doesn't install (e.g. a log). Did you install the VC runtimes?

Also have you watched the video on the OBS forums on how to use "Use Monitor center"?
It's in the spoiler called What is "Monitor horizontal/vertical center"?
If you don't put any values for Monitor horizontal/vertical center the option use monitor center won't work.

**Comment by hazethegreat** [comment]
Thanks for the response. Yes it's my bad on the centering thing, I didnt search guides. Mouse works great now :) I have the VC runtimes, and 4.2 works properly. but the same installation method doesn't work for 4.4 or 4.5. the OBS menu simply doesn't show an option to add input overlay.

**Comment by univrsal** [comment]
then I'll need a log

**Comment by univrsal** [comment]
I'll close this for now. If you do come back to this please try the version that is linked under v4.5 with the label "Running Windows 7?". I'm just guessing that you use Windows 7 since I didn't get a log from you.
