### ISSUE TITLE
Report version number in "about" section

### ISSUE THREAD

**Issue by GameKyuubi** [univrsal/input-overlay#311]
**Describe the problem**
I can't check what version of the plugin OBS is actually using with 100% certainty.

**To Reproduce**
Open OBS, go to tools -> input-overlay configuration -> about.  Notice that the version number is absent.

**Expected behavior**
"about" tab should display the version number of the plugin in use

**Screenshots**
![image](https://user-images.githubusercontent.com/6174313/219904708-955ae607-42a7-4b75-a4d1-ed59fd259255.png)

**Additional information:**
- Plugin version 5.0.0.r9.g05b175f-1 .. I think?  This is what I'm trying to check lol

**Comment by univrsal** [comment]
You can check the log, it contains the version as well as the build date.

**Comment by GameKyuubi** [comment]
I found
```
info: [input-overlay] [input-overlay] Loading v5.0.0 build time 2023.02.01 21:38
```
in the log.  It'd be cool if it's in the about section as well but that's sufficient.  Is it supposed to not contain the revision?

**Comment by univrsal** [comment]
I've added this now, it'll be in the next release, whenever that'll happen
