### ISSUE TITLE
xbox controller buttons not working

### ISSUE THREAD

**Issue by andreottigiulio** [univrsal/input-overlay#312]
PLEASE FILL THIS OUT CORRECTLY OR THE ISSUE WILL BE CLOSED

(You can remove this text after you've filled out the form)

**Describe the bug**
BUTTONS NOT WORKING in XBOX 360 controller but everything else (dpad, triggers analog) is working fine

**To Reproduce**
just use XBOX 360 controllers and buttons did not work

**Expected behavior**
i expect the buttons working out of box like other controllers

**Screenshots**

**Additional information:**
- Plugin version 5.0.0

00:21:04.163: CPU Name: Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
00:21:04.163: CPU Speed: 3398MHz
00:21:04.163: Physical Cores: 4, Logical Cores: 4
00:21:04.163: Physical Memory: 16319MB Total, 12120MB Free
00:21:04.163: Windows Version: 10.0 Build 19045 (release: 22H2; revision: 2604; 64-bit)
00:21:04.163: Running as administrator: false
00:21:04.163: Windows 10/11 Gaming Features:
00:21:04.163: 	Game Bar: On
00:21:04.163: 	Game DVR: On
00:21:04.163: 	Game DVR Background Recording: Off
00:21:04.163: 	Game Mode: Probably On (no reg key set)
00:21:04.164: Sec. Software Status:
00:21:04.165: 	Microsoft Defender Antivirus: enabled (AV)
00:21:04.166: 	Windows Firewall: enabled (FW)
00:21:04.166: Current Date/Time: 2023-02-20, 00:21:04
00:21:04.166: Browser Hardware Acceleration: true
00:21:04.166: Hide OBS windows from screen capture: false
00:21:04.166: Qt Version: 6.3.1 (runtime), 6.3.1 (compiled)
00:21:04.166: Portable mode: false
00:21:04.525: OBS 29.0.2 (64-bit, windows)
00:21:04.525: ---------------------------------
00:21:04.577: ---------------------------------
00:21:04.577: audio settings reset:
00:21:04.577: 	samples per sec: 48000
00:21:04.577: 	speakers:        2
00:21:04.577: 	max buffering:   960 milliseconds
00:21:04.577: 	buffering type:  dynamically increasing
00:21:04.577: ---------------------------------
00:21:04.577: Initializing D3D11...
00:21:04.577: Available Video Adapters: 
00:21:04.580: 	Adapter 0: NVIDIA GeForce GTX 1660 SUPER
00:21:04.580: 	  Dedicated VRAM: 1975517184
00:21:04.580: 	  Shared VRAM:    4261236736
00:21:04.580: 	  PCI ID:         10de:21c4
00:21:04.580: 	  Driver Version: 31.0.15.2849
00:21:04.580: 	  output 0:
00:21:04.580: 	    name=X233H
00:21:04.580: 	    pos={0, 0}
00:21:04.580: 	    size={1920, 1080}
00:21:04.580: 	    attached=true
00:21:04.580: 	    refresh=60
00:21:04.580: 	    bits_per_color=8
00:21:04.580: 	    space=RGB_FULL_G22_NONE_P709
00:21:04.580: 	    sdr_white_nits=80
00:21:04.580: 	    nit_range=[min=0.500000, max=270.000000, max_full_frame=270.000000]
00:21:04.580: 	Adapter 1: NVIDIA GeForce GTX 1660 SUPER
00:21:04.580: 	  Dedicated VRAM: 1975517184
00:21:04.580: 	  Shared VRAM:    4261236736
00:21:04.580: 	  PCI ID:         10de:21c4
00:21:04.580: 	  Driver Version: 31.0.15.2849
00:21:04.582: Loading up D3D11 on adapter NVIDIA GeForce GTX 1660 SUPER (0)
00:21:04.674: D3D11 loaded successfully, feature level used: b000
00:21:04.674: DXGI increase maximum frame latency success
00:21:04.674: D3D11 GPU priority setup failed (not admin?)
00:21:06.103: ---------------------------------
00:21:06.103: video settings reset:
00:21:06.103: 	base resolution:   1280x720
00:21:06.103: 	output resolution: 1280x720
00:21:06.103: 	downscale filter:  Bicubic
00:21:06.103: 	fps:               60/1
00:21:06.103: 	format:            NV12
00:21:06.103: 	YUV mode:          Rec. 709/Partial
00:21:06.103: NV12 texture support enabled
00:21:06.103: P010 texture support not available
00:21:06.106: Audio monitoring device:
00:21:06.106: 	name: Predefinito
00:21:06.106: 	id: default
00:21:06.106: ---------------------------------
00:21:06.109: No AJA devices found, skipping loading AJA UI plugin
00:21:06.109: Failed to initialize module 'aja-output-ui.dll'
00:21:06.111: No AJA devices found, skipping loading AJA plugin
00:21:06.111: Failed to initialize module 'aja.dll'
00:21:06.111: Skipping module '../../obs-plugins/64bit/chrome_elf.dll', not an OBS plugin
00:21:06.114: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
00:21:06.114: Failed to load 'en-US' text for module: 'decklink-captions.dll'
00:21:06.115: Failed to load 'en-US' text for module: 'decklink-output-ui.dll'
00:21:06.118: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
00:21:06.118: Failed to initialize module 'decklink.dll'
00:21:06.146: [AMF] Unable to load 'amfrt64.dll', error code 126.
00:21:06.148: [AMF] AMF Test failed due to one or more errors.
00:21:06.148: Failed to initialize module 'enc-amf.dll'
00:21:06.160: Failed to load 'it-IT' text for module: 'input-overlay.dll'
00:21:06.160: [input-overlay] [input-overlay] Loading v5.0.0 build time 2022.08.21 10:41
00:21:06.160: [input-overlay] Using 'XInput' gamepad backend
00:21:06.161: [input-overlay::libgamepad] No device with id '{97136E70-01BA-11EB-8001-444553540000} Controller (XBOX 360 For Windows)'
00:21:06.161: [input-overlay::libgamepad] Couldn't set binding.
00:21:06.161: [input-overlay::libgamepad] Loading Xinput from C:\Windows\system32\xinput1_3.dll
00:21:06.161: [input-overlay::libgamepad] Xinput 1.3 loaded successfuly
00:21:06.162: [input-overlay] 'Generic Xinput gamepad 0' connected
00:21:06.162: [input-overlay] gamepad hook started
00:21:06.162: [input-overlay::libgamepad] Hook thread started
00:21:06.209: Skipping module '../../obs-plugins/64bit/libcef.dll', not an OBS plugin
00:21:06.210: Skipping module '../../obs-plugins/64bit/libEGL.dll', not an OBS plugin
00:21:06.210: Skipping module '../../obs-plugins/64bit/libGLESv2.dll', not an OBS plugin
00:21:06.220: [obs-browser]: Version 2.19.0
00:21:06.221: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.0.0-5060-shared-textures.2591+g4204d54+chromium-103.0.5060.134 (compiled)
00:21:06.225: NVENC supported
00:21:06.470: [NVENC] AV1 is not supported
00:21:06.473: [noise suppress]: NVIDIA denoiser disabled, redistributable not found or could not be loaded.
00:21:06.473: Failed to get NVVideoEffects.dll version info size
00:21:06.474: [NVIDIA VIDEO FX]: FX disabled, redistributable not found or could not be loaded.
00:21:06.515: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.1.0 | RPC Version: 1)
00:21:06.515: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.3.1 | Qt version (run-time): 6.3.1
00:21:06.515: [obs-websocket] [obs_module_load] Linked ASIO Version: 101201
00:21:06.523: [obs-websocket] [obs_module_load] Module loaded.
00:21:06.530: [vlc-video]: Couldn't find VLC installation, VLC video source disabled
00:21:06.538: ---------------------------------
00:21:06.538:   Loaded Modules:
00:21:06.538:     win-wasapi.dll
00:21:06.538:     win-mf.dll
00:21:06.538:     win-dshow.dll
00:21:06.538:     win-capture.dll
00:21:06.538:     vlc-video.dll
00:21:06.538:     text-freetype2.dll
00:21:06.538:     rtmp-services.dll
00:21:06.538:     obs-x264.dll
00:21:06.538:     obs-websocket.dll
00:21:06.538:     obs-vst.dll
00:21:06.538:     obs-transitions.dll
00:21:06.538:     obs-text.dll
00:21:06.538:     obs-qsv11.dll
00:21:06.538:     obs-outputs.dll
00:21:06.538:     obs-filters.dll
00:21:06.538:     obs-ffmpeg.dll
00:21:06.538:     obs-browser.dll
00:21:06.538:     input-overlay.dll
00:21:06.538:     image-source.dll
00:21:06.538:     frontend-tools.dll
00:21:06.538:     decklink-output-ui.dll
00:21:06.538:     decklink-captions.dll
00:21:06.538:     coreaudio-encoder.dll
00:21:06.539: ---------------------------------
00:21:06.539: ==== Startup complete ===============================================
00:21:06.583: All scene data cleared
00:21:06.583: ------------------------------------------------
00:21:06.598: [win-wasapi: 'Audio del desktop'] update settings:
00:21:06.598: 	device id: default
00:21:06.598: 	use device timing: 1
00:21:06.601: [Loaded global audio device]: 'Audio del desktop'
00:21:06.657: WASAPI: Device 'Altoparlanti (Realtek High Definition Audio)' [48000 Hz] initialized
00:21:07.291: Switched to scene 'Sekiro'
00:21:07.291: ------------------------------------------------
00:21:07.291: Loaded scenes:
00:21:07.291: - scene 'Sekiro':
00:21:07.291:     - source: 'Cattura gioco' (game_capture)
00:21:07.291:     - source: 'https://app.gpv.gg/?p=1' (browser_source)
00:21:07.291:     - source: 'Input Overlay' (input-overlay)
00:21:07.291: ------------------------------------------------
00:21:07.909: [obs-browser: 'https://app.gpv.gg/?p=1'] Error: Unable to parse mapping object. (https://gamepadviewer.com/main.js:510)
00:21:07.978: [obs-browser: 'https://app.gpv.gg/?p=1'] Error: Error: no_div (https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6461293058804731:44)
00:21:07.982: [obs-browser: 'https://app.gpv.gg/?p=1'] Error: Error: no_div (https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6461293058804731:44)

**Comment by univrsal** [comment]
See #297
