### ISSUE TITLE
No way to manually install in non-debian distros

### ISSUE THREAD

**Issue by billionai** [univrsal/input-overlay#317]
The installation instructions (https://github.com/univrsal/input-overlay/wiki/Installation) mention that the folder `input-overlay`  from the file `input-overlay.<version>.linux.zip` but in the releases page, there is no `.linux.zip` file. How would a Fedora user install this overlay?

**Comment by univrsal** [comment]
The CI currently only creates a deb installer, so you'll either have to build the plugin from source or [manually extract the deb file](https://vrsal.xyz/issues/linux).

**Comment by billionai** [comment]
thank you

**Comment by univrsal** [comment]
The CI now builds a zip file with the binaries.
