### ISSUE TITLE
dualshock 4 - cct and obs do not report bumpers

### ISSUE THREAD

**Issue by chboishabba** [univrsal/input-overlay#318]
**Describe the bug**
All other inputs display as intended, but does not display shoulder button activations, while using the dualsense preset. 

**To Reproduce**
Use the dualsense preset with a dualshock 4 controller. The controller is confirmed working as per online gamepad testers.

**Expected behavior**
All inputs are displayed.

**Screenshots**
Explanation should be sufficient.

**Additional information:**
- Plugin version 5.0.0
- Full OBS Studio log - issue occurs independent of OBS using current json preset

**Additional context**
I guess the fact it's a dualshock and not a dualsense.

**Comment by chboishabba** [comment]
Sorry just watching back footage and it doesn't show the ABXY buttons or a touchpad click either.

**Comment by chboishabba** [comment]
Forgot to note this this is using DS4Windows Windows 10 and set to emulate XBOX controller and the plugin is reading XInput

**Comment by univrsal** [comment]
So the buttons just do not work in the config tool at all? Like when you enable the option "record keycode" and press them nothing happens?

The buttons not working in obs is addressed in #297 people have already tested ds4 gamepads, but you can download the gamepad test zip archive and see if your gamepad works.

**Comment by chboishabba** [comment]
All the inputs display correctly using the gamepad tester but none of the
face buttons nor the bumpers work in cct and the recording doesn't seem to
work either, at least using the one included.
Using the cct from the github homepage does display face button inputs but
does not release the input and does not display subsequent inputs for the
buttons. The github cct does not appear to capture inputs using the record
function either. It also seem that it will not accept arbitrary inputs for
the keycode like if I were to collect it from the tester exe somehow...
Perhaps it may be useful to display button codes within the GUI of the
tester app and change the input filtering for the button ID field in cct? I
love using this though, I've already learned about how I use the gamepad...

**Comment by univrsal** [comment]
Closing this for now.
