### ISSUE TITLE
No way to determine when History should start a new line

### ISSUE THREAD

**Issue by Greg-J** [univrsal/input-overlay#32]
This plugin is phenomenal for tutorials, but in applications where you're using a command line - in my case, Rhino 3d where you type the name of a command rather than a shortcut key - it's not useful.

I'm wondering if an option to determine what keys/clicks determine when you go to a new line. For instance, any time Ctrl, Space, Enter, or Right Click is pressed it starts a new line.

**Comment by univrsal** [comment]
Why would you want to show someone what is already shown on screen in the terminal?

**Comment by Greg-J** [comment]
Love the quick response.

I suppose I can only speak to my particular use case. Source Window is 4k which is almost always viewed at 1080p or below which makes the source text unreadable. Your solution is so much cleaner than adding a 2nd source and cropping it.

**Comment by univrsal** [comment]
I guess upping the font size isn't an option?
It should be doable, but you'll have to give me some time

**Comment by Greg-J** [comment]
> I guess upping the font size isn't an option?

Negative.

Being able to keylog has some benefits too. Showing a multiline history for any app that you get output from input would be incredibly useful for people pausing and following along so they don't have to  pause and keep tracking through the tutorial. That would be super useful for Terminal stuff.

**Comment by univrsal** [comment]
This is as close as I can get:
![gif](https://i.imgur.com/KsRt92c.gif)

It has some quirks, which means it only works with "real" text fields (e.g. cmd.exe doesn't seem to work)

**Comment by univrsal** [comment]
I'll close this for now, until I get some more feedback

**Comment by Greg-J** [comment]
Missed the last notification. This rocks. Thanks!

**Comment by univrsal** [comment]
I still need your input on whether it works with your application
