### ISSUE TITLE
Error in input_data.hpp

### ISSUE THREAD

**Issue by patlefort** [univrsal/input-overlay#321]
**Describe the bug**
Simple mistake in this line: https://github.com/univrsal/input-overlay/blob/e89fca51dbe81b1e7ab7e313084d461c4be6e122/deps/common/input_data.hpp#L97
Mixing j and i variables.

**Additional information:**
- Plugin version: 5.0.1

**Additional context**
Compiling with warnings turned on on GCC catched this error: 
```
input-overlay/deps/common/input_data.hpp:97:26: warning: unused variable ‘j’ [-Wunused-variable]
   97 |             for (uint8_t j = 0; i < button_count; i++) {
```

**Comment by univrsal** [comment]
Yeah I know, those functions aren't used anyways, I just forgot to remove them.

**Comment by univrsal** [comment]
Fixed
