### ISSUE TITLE
Xbox gamepad input not working correctly in v5.0.1

### ISSUE THREAD

**Issue by KaiLee2588** [univrsal/input-overlay#322]
**Describe the bug**
Xbox Series X Controller input not working properly in v5.0.1.  
Only seems to register RT and LT inputs, not showing any other inputs.  

**To Reproduce**
- Install v5.0.1 via x64 installer.
- Add new input-overlay, use /v5.0.1-preset/gamepad/ preset.
- Connect controller.
- Choose proper gamepad id, which it did correctly recognized as Xbox Series X Controller.
- No input shown except Trigger buttons.

**Expected behavior**
No input shown except Trigger buttons.  
And the triggers buttons display feels "glitched", it only register properly when "both RT & LT are pressed".  

**Screenshots**

**Additional information:**
- Windows 11 w/ OBS 29.0.2
- Xbox Controller firmware up to date
- input-overlay v5.0.1
- Full OBS Studio log (https://obsproject.com/logs/RHB50ZQWGwBB6ro9)
(Reproduced in portable version of OBS)

**Additional context**
SDL2 Tester #297  is working properly without issues.  
Downgrade to v5.0.0 is working fine with v5.0.0 preset fixes from #285 .
I'm thinking maybe it's the preset issues?   
But I tired using v5.0.0 presets on v5.0.1 plugins, didn't resolve the issue.

**Comment by univrsal** [comment]
Try this build it should fix the issue
https://github.com/univrsal/input-overlay/actions/runs/4354836239

**Comment by KaiLee2588** [comment]
> Try this build it should fix the issue https://github.com/univrsal/input-overlay/actions/runs/4354836239

Got it, it's working great now! This build does it.
Using v5.0.1 preset with no drifting or other fixes needed.
