### ISSUE TITLE
3rd party controllers not supported

### ISSUE THREAD

**Issue by GameDevon** [univrsal/input-overlay#324]
**Describe the bug**
My 3rd party controller is not detected by the input overlay plugin

**To Reproduce**
Connect Culeedtech Switch Pro Controller
Install OBS and set up the switch pro controller input overlay config
Press buttons

**Expected behavior**
The buttons are tracked by the plugin
The gamepad id shows up in the dropdown if it doesn't work immediately

**Screenshots**
![image](https://user-images.githubusercontent.com/82553545/225468938-7f515939-f964-49f3-b014-bd04b3f69a46.png)

**Additional information:**
- Plugin version 5.0.0
- Full OBS Studio log N/A
- Amazon link to controller https://www.amazon.ca/CuleedTec-Wireless-Controller-Nintendo-Switch/dp/B07P8Q868K/ref=rvi_sccl_13/138-5676459-6344326?pd_rd_w=4aAs9&content-id=amzn1.sym.8b4d8c20-8e51-4634-a76f-c00a1995a502&pf_rd_p=8b4d8c20-8e51-4634-a76f-c00a1995a502&pf_rd_r=TXRHH93KC502YXA9PGN8&pd_rd_wg=HEyRf&pd_rd_r=9d568501-49a0-4ae6-8f97-7e20d8dda874&pd_rd_i=B07P8Q868K&psc=1

**Additional context**
If the cost of the controller is an issue for the developers, I can send them one if they ask in DMs. I suspect that other 3rd party controllers have a similar issue.

**Comment by univrsal** [comment]
Closing this for now
