### ISSUE TITLE
Wasd overlay issue

### ISSUE THREAD

**Issue by FrazelBazel** [univrsal/input-overlay#326]
**Describe the bug**
Whenever I try to add the config file to use the wasd overlay the image mashes together in the middle of the upper bar of the image

**To Reproduce**
adding the config file to use the input overlay for wasd

**Expected behavior**
a normal tracking of wasd like seen in vidoes

**Screenshots**
https://user-images.githubusercontent.com/129277002/228512581-51b3aaad-95ea-4a51-a40e-6dfa24a62493.png

**Additional information:**
- Plugin version: v5.0.3

**Additional context**
Im not sure if I'm doing something wrong or if this is just a recent issue

**Comment by univrsal** [comment]
This isn't a bug, you're just selecting the wrong image. Don't select files that contain the word "preview" since they're, you know, previews.
![image](https://user-images.githubusercontent.com/8353672/228614268-c96f6198-62de-4d19-b6d3-bfa0f88a6e52.png)

**Comment by FrazelBazel** [comment]
I am so sorry thank you for the help
