### ISSUE TITLE
Inputs don't show, templates appear glitched

### ISSUE THREAD

**Issue by seanwisegamgee** [univrsal/input-overlay#328]
**Describe the bug**
I can add the input overlay sources but when I try to add the preset png and json files for wasd/mouse, the display glitches out. Inputs don't appear when I press keys.

**To Reproduce**
Install input overlay, create new source, add wasd-minimal.png and wasd-minimal.json

**Expected behavior**
I'd expect to see the inputs

**Screenshots**
![image](https://user-images.githubusercontent.com/129617080/229305663-3f91a4d8-49a4-407c-b582-c9ba0076a5d2.png)

**Additional information:**
- I'm using 5.0.3 now, I tried a few weeks ago with 5.0.0 and got the same thing. I am running OBS in administrator mode
- Full OBS Studio log (https://obsproject.com/logs/ctIHE0KOxisPFzjO)

**Comment by univrsal** [comment]
https://github.com/univrsal/input-overlay/issues/326#issuecomment-1488976806
i'll remove the previews at some point since people keep using them for some reason

**Comment by seanwisegamgee** [comment]
Wait sorry what? Am I using the wrong files? I'm just trying to get this to work, any tips you got would be appreciated.

**Comment by seanwisegamgee** [comment]
Oh oops, I see. However I still don't see the actual inputs showing up, just the outline of them. Any tips?

**Comment by univrsal** [comment]
You gotta tell me a little more than that

**Comment by seanwisegamgee** [comment]
Haha fair enough. I can see the overlay: 
![image](https://user-images.githubusercontent.com/129617080/229306075-41d4a7fc-42e9-409b-9761-fc4427c608c2.png)
But pressing those keys on my keyboard does not make the keys on the screen go yellow when I press them. It's just a static overlay.

**Comment by univrsal** [comment]
Can you take a screenshot of the "local features" tab in the input overlay settings dialog?

![](https://i.imgur.com/WBUxQu4.png)

**Comment by seanwisegamgee** [comment]
![image](https://user-images.githubusercontent.com/129617080/229306339-513c0d98-8590-444b-bc81-05ad71245e1b.png)

**Comment by univrsal** [comment]
Well you configured it so it would only accept inputs when you're using the window with the title "dunkstream - Twitch - Mozilla Firefox"

**Comment by seanwisegamgee** [comment]
![image](https://user-images.githubusercontent.com/129617080/229306540-b467f960-4f4f-40c4-8d3a-22fd7f5729ef.png)
Tried changing to valorant and clicked into game and pressed keys, same issue if i also remove all filters

**Comment by univrsal** [comment]
just disable input control entirely and see if it works at all

**Comment by seanwisegamgee** [comment]
AH removed and readded a couple times, now it appears to be working. Thanks so much for your help, I appreciate it
