### ISSUE TITLE
Plugin won't load in OBSS 21.0.1 (similar to closed topic below)

### ISSUE THREAD

**Issue by 2useless** [univrsal/input-overlay#33]
Similar to the problem below, OBS Studio won't load the plugin and seems to produce the same error (with slightly different formatting). I have tried installing the suggested VC++ runtimes (which apparently fixed it for the previous issue) but it did not work for me. Please see below the log file generated after installing the VC++ runtimes, which looks the same as it did before.

Also, please feel free to giggle at the age of my system. Still going strong 10+ years later.

01:44:05.082: CPU Name: Intel(R) Core(TM)2 Quad  CPU   Q9450  @ 2.66GHz
01:44:05.082: CPU Speed: 3600MHz
01:44:05.082: Physical Cores: 4, Logical Cores: 4
01:44:05.082: Physical Memory: 8190MB Total, 5554MB Free
01:44:05.082: Windows Version: 6.1 Build 7601 (revision: 24024; 64-bit)
01:44:05.082: Running as administrator: false
01:44:05.082: Aero is Disabled
01:44:05.083: Portable mode: false
01:44:05.101: OBS 21.0.1 (64bit, windows)
01:44:05.101: ---------------------------------
01:44:05.102: ---------------------------------
01:44:05.102: audio settings reset:
01:44:05.102: 	samples per sec: 44100
01:44:05.102: 	speakers:        2
01:44:05.104: ---------------------------------
01:44:05.104: Initializing D3D11...
01:44:05.104: Available Video Adapters: 
01:44:05.106: 	Adapter 1: NVIDIA GeForce GTX 1050 Ti
01:44:05.106: 	  Dedicated VRAM: 4192665600
01:44:05.106: 	  Shared VRAM:    4025626624
01:44:05.106: 	  output 1: pos={0, 0}, size={1920, 1080}, attached=true
01:44:05.110: Loading up D3D11 on adapter NVIDIA GeForce GTX 1050 Ti (0)
01:44:05.142: D3D11 loaded successfully, feature level used: 45056
01:44:05.936: ---------------------------------
01:44:05.936: video settings reset:
01:44:05.936: 	base resolution:   1920x1080
01:44:05.936: 	output resolution: 1280x720
01:44:05.936: 	downscale filter:  Bicubic
01:44:05.936: 	fps:               30/1
01:44:05.936: 	format:            NV12
01:44:05.939: Audio monitoring device:
01:44:05.939: 	name: Default
01:44:05.939: 	id: default
01:44:05.939: ---------------------------------
01:44:05.941: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/chrome_elf.dll' not found, loading of module failed
01:44:05.942: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
01:44:05.965: [AMF] <obs_module_load> AMF not supported (no AMD graphics)
01:44:05.965: Failed to initialize module 'enc-amf.dll'
**01:44:05.972: LoadLibrary failed for '../../obs-plugins/64bit/input-overlay.dll': The specified module could not be found.
01:44:05.972:  (126)
01:44:05.972: Module '../../obs-plugins/64bit/input-overlay.dll' not loaded**
01:44:05.986: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libcef.dll' not found, loading of module failed
01:44:05.987: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libEGL.dll' not found, loading of module failed
01:44:05.987: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libGLESv2.dll' not found, loading of module failed
01:44:05.988: Failed to load 'en-US' text for module: 'obs-browser.dll'
01:44:05.988: [browser_source: 'Version: 1.29.0']
01:44:05.990: NVENC supported
01:44:06.070: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/uiohook.dll' not found, loading of module failed
01:44:06.070: Couldn't find VLC installation, VLC video source disabled
01:44:06.077: No blackmagic support
01:44:06.082: [Media Foundation encoder]: plugin is disabled for performance reasons on Windows versions prior to 8
01:44:06.084: ---------------------------------
01:44:06.084:   Loaded Modules:
01:44:06.084:     win-wasapi.dll
01:44:06.084:     win-mf.dll
01:44:06.084:     win-dshow.dll
01:44:06.084:     win-decklink.dll
01:44:06.084:     win-capture.dll
01:44:06.084:     vlc-video.dll
01:44:06.084:     text-freetype2.dll
01:44:06.084:     rtmp-services.dll
01:44:06.084:     obs-x264.dll
01:44:06.084:     obs-vst.dll
01:44:06.084:     obs-transitions.dll
01:44:06.084:     obs-text.dll
01:44:06.084:     obs-qsv11.dll
01:44:06.084:     obs-outputs.dll
01:44:06.084:     obs-filters.dll
01:44:06.084:     obs-ffmpeg.dll
01:44:06.084:     obs-browser.dll
01:44:06.084:     image-source.dll
01:44:06.084:     frontend-tools.dll
01:44:06.084:     enc-amf.dll
01:44:06.084:     coreaudio-encoder.dll
01:44:06.084: ---------------------------------
01:44:06.084: ==== Startup complete ===============================================
01:44:06.087: All scene data cleared
01:44:06.088: ------------------------------------------------
01:44:06.126: WASAPI: Device 'Speakers (Realtek High Definition Audio)' initialized
01:44:06.159: adding 23 milliseconds of audio buffering, total audio buffering is now 23 milliseconds
01:44:06.512: Switched to scene 'Scene'
01:44:06.512: [game-capture: 'Game Capture'] attempting to hook fullscreen process: explorer.exe
01:44:06.512: [game-capture: 'Game Capture'] cannot capture explorer.exe due to being blacklisted
01:44:06.513: ------------------------------------------------
01:44:06.513: Loaded scenes:
01:44:06.513: - scene 'Scene':
01:44:06.513:     - source: 'Game Capture' (game_capture)
01:44:06.513: ------------------------------------------------

**Comment by univrsal** [comment]
This is probably because you're using Windows 7. I accidentally compiled the plugin against a newer version XInput which only ships with Windows 8 and up.
Can you try [this](https://github.com/univrsal/input-overlay/files/1792533/v4.6-pre.zip) version and tell me the results? I'll put it up as a proper release since it seems that a lot of people run into the same issue.

btw: I'm running old hardware myself so I'd have to right to laugh at anyone's setup^^

**Comment by 2useless** [comment]
The change appears to have been successful, on startup I see two new input sources "Input Overlay" and "Input History". Now I'm trying to figure out how to set it up. :)

**Comment by 2useless** [comment]
Aaaand I think I'm golden! Slick plugin btw, looks really nice. Streaming some Path of Exile and thought it would be fun for viewers to be able to see the commands I'm feeding the game.

www.twitch.tv/lordbean if you want to look (shameless plug - I'm a novice streamer, I don't really have a viewership lol)
