### ISSUE TITLE
Overlay not loading the correct color space if OBS is set to REC2010 Color space

### ISSUE THREAD

**Issue by anchaides** [univrsal/input-overlay#333]
**Describe the bug**
Overlay gets loaded with the standard REC709 color space even though the scene is set to P010 Pixel Format and color spaces and REC2100 Color spaces. I have a local build that fixes the issue and I would like to contribute to the project by merging it. 

**To Reproduce**
On Settings -> Advanced -> Video 
Select P010 on Color Format 
Select Rec.2100 (PQ) Color Space 
Select Full   in Color Range 

Add "input_overlay" source to scene. 
In source properties, select any Overlay image/layout pair 

**Expected behavior**
Displayed image should match color and format as if loading "image" source with the same overlay image. 

**Screenshots**
![image](https://user-images.githubusercontent.com/127638307/230804948-26a13869-810f-453f-b0b6-2678160a89f3.png)

**Additional information:**
- Plugin version 5.0.3
- Full OBS Studio log 29.0.2 64 bit (
![image](https://user-images.githubusercontent.com/127638307/230804994-d674b5b4-d90f-4ba7-aac4-72631e50709d.png)
)

**Additional context**
Hi univrsal, 

As discussed in the forum already have a working set of commits which fix this issue. Kindly provide the necessary permissions so I can push my local branch, create a pull request and discuss the changes further. 

Kind Regards,
Antonio

**Comment by univrsal** [comment]
To create a pull request you just have to fork the repo and then push to the fork, after that you can create a pull request from your fork to the master branch.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by anchaides** [comment]
Oh thanks, I was not aware I needed to fork. 

I couldn't fix the plugin loading issue, I just loaded it directly into my main OBS install. Will create the fork right away.
