### ISSUE TITLE
No checksum on v5.0.3

### ISSUE THREAD

**Issue by scarf005** [univrsal/input-overlay#337]
**Describe the bug**
v5.0.3 release does not have checksum.

**To Reproduce**
1. go to https://github.com/univrsal/input-overlay/releases/tag/v5.0.3

**Expected behavior**
there is checksum like [other version](https://github.com/univrsal/input-overlay/releases/tag/v5.0.2)

**Screenshots**
![image](https://user-images.githubusercontent.com/54838975/232359819-91792780-3f1a-4c5b-b7df-307b13f836b2.png)

**Comment by univrsal** [comment]
I don't remember why this broke but I'll just not bother with checksums any more I guess.
