### ISSUE TITLE
Skipping module '../../obs-plugins/64bit/input-overlay.dll' due to possible import conflicts after compile

### ISSUE THREAD

**Issue by danielocdh** [univrsal/input-overlay#339]
**Describe the bug**
The compiled plugin doesn't work

**To Reproduce**
- Tried to compile according to https://github.com/univrsal/input-overlay/wiki/Compiling#building-the-plugin-master-branch-v50-and-up
- Got "Plugin Load Error" popup with this on the log: `Skipping module '../../obs-plugins/64bit/input-overlay.dll' due to possible import conflicts`

**Expected behavior**
Compiled plugin to work the same as the released one

**Screenshots**

**Additional information:**
- Tested with the latest version of obs
- Tested with the latest version of the plugin code and with commit 39a1d1a (v5.0.3)
- The release plugin works fine with my compiled obs, the compiled plugin doesn't
- Built the plugin and the io-client
- To install the compiled plugin I copied the folder/file structure from input-overlay-5.0.3-windows-x64.zip but with the compiled files

**Additional context**
The release input-overlay.dll depends on qt v6, and the compiled input-overlay.dll depends on qt v5, I had both installed and tried to choose v6 on cmake gui but v5 was used anyway

**Comment by univrsal** [comment]
The qt version is selected exactly like in the [obs plugin template](https://github.com/obsproject/obs-plugintemplate/blob/master/CMakeLists.txt), so if the same errors happens there, you'd have to report it in that repository. Also the build instructions are outdated so that might be part of the issue.

**Comment by danielocdh** [comment]
> The qt version is selected exactly like in the [obs plugin template](https://github.com/obsproject/obs-plugintemplate/blob/master/CMakeLists.txt), so if the same errors happens there, you'd have to report it in that repository. Also the build instructions are outdated so that might be part of the issue, I don't have my windows installation right now, so I can't check the exact steps, but the scripts in [.github/scripts](.github/scripts) should work.

that worked perfectly, thanks
