### ISSUE TITLE
Input Overlay isnt a listed source.

### ISSUE THREAD

**Issue by TheBitcoinBaron** [univrsal/input-overlay#341]
**Describe the bug**
OBS 29.0.2 - Installed most recent plugin version, is not showing up under the new source list.

**To Reproduce**
Install OBS 29.0.2 and then install latest version.

**Expected behavior**
Appears in source list like in previous versions

**Additional information:**
- Plugin version: Most recent.
- Full OBS Studio log https://obsproject.com/logs/rQcH3s3uKvwDVyUJ

**Comment by neldonado** [comment]
I'm having the same issue

**Comment by Bohdan2505** [comment]
Hello. I have same issue on debian 12 bookworm. Same version, same issue

**Comment by ackl** [comment]
Same issue even now. Debian 12; OBS Studio - 29.0.2.1-1+b1 (linux)

**Comment by univrsal** [comment]
Debian uses an old version of OBS. Input overlay is compiled against the latest version on Ubuntu 22.04. You'll most likely have to compile the plugin yourself.
