### ISSUE TITLE
How do I uninstall this plugin?

### ISSUE THREAD

**Issue by beyond9thousand** [univrsal/input-overlay#342]
PLEASE FILL THIS OUT CORRECTLY OR THE ISSUE WILL BE CLOSED

(You can remove this text after you've filled out the form)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional information:**
- Plugin version
- Full OBS Studio log (https://cdn.discordapp.com/attachments/376042662580715521/768461567347261470/unknown.png)

**Additional context**

**Comment by univrsal** [comment]
If you used the installer you uninstall it like any other software. If you manually installed it you also have to manually remove the files you installed.
