### ISSUE TITLE
Arrow Keys not detected on OBS

### ISSUE THREAD

**Issue by Equ1no0x** [univrsal/input-overlay#343]
**Describe the bug**
Modified existing preset with CCT to add arrow keys. Arrow keys are detected on CCT, but not on OBS.

**To Reproduce**

1. Add a new element to JSON using CCT.
2. Export new JSON.
3. Test in OBS.

**Expected behavior**
Overlay keys should be highlighted if detected when arrow keys are pressed. This is not the case.

**Screenshots**
CCT Editor
![image](https://user-images.githubusercontent.com/77862920/236141737-724d047f-57b8-40fa-9687-e10fe9da31df.png)
OBS
![image](https://user-images.githubusercontent.com/77862920/236141766-a6336660-ab7d-4194-a35d-e213feaf4272.png)

**Additional information:**
- Plugin version: 5.0.3

**Comment by univrsal** [comment]
Try this build: https://github.com/univrsal/input-overlay/actions/runs/4882225902
Downloads are at the bottom.

**Comment by Equ1no0x** [comment]
> 

Works like a charm. Much appreciated!
