### ISSUE TITLE
Cannot use 2 controllers for overlay for the life of me!

### ISSUE THREAD

**Issue by GlitchNo** [univrsal/input-overlay#345]
Describe the bug: So I want to have 2 controllers at the same time using the overlay but ONLY player 1's controller can be used. Even Using Different controllers, player 2 does not work. Even swapping controllers (Player 2 to Player 1) now it works since it's player 1. So this isn't a controller issue. OBS even crashes when I unplug and plug the controllers. (Sometimes) 

To Reproduce: Add a new "Input Delay", Add "Overlay Image File" to a controller one. (I used Duelsense) Add "Overlay Config File" I added the "duelsense.json" Since that's the one with it. Now it gives me the option: "Gamepad id". Clicking it will show 2 options "0 PS5 Controller - PS5 Controller" and "1 PS5 Controller - PS5 Controller". 0 is player 1, the one connected first. 1 is player 2, the one connected second. Clicking 0 works just fine! Then once adding a new overlay to put it for 1, it does not work at all... I tried many different things and I just give up thinking this was something that would be obviously working.

Expected: To use 2 controllers simply... 

![IMG_6121](https://user-images.githubusercontent.com/132953061/236947659-e6105249-f389-47c7-9077-4bdd6d25e120.jpg)

![IMG_6122](https://user-images.githubusercontent.com/132953061/236947675-3570e036-5cc4-4fff-af1d-03a38d027689.jpg)

![IMG_6124](https://user-images.githubusercontent.com/132953061/236947694-2bcb0707-917b-48eb-80ee-d5a106d9c418.jpg)

Plugin Version: input-overlay v5.0.3

**Comment by univrsal** [comment]
Fixed in b47d444

**Comment by GlitchNo** [comment]
> Fixed in [b47d444](https://github.com/univrsal/input-overlay/commit/b47d4448075e68b0a85f7f33e64424e1b454ce39)

I'm sorry but I cannot figure out how to put all of this into the files to update it to get it working. You just gave me code which I do not know where to replace in. I tried but kept getting lost. Did not want to bother you but I would like you to explain where I should update the files so it can work.

**Comment by univrsal** [comment]
just wait for the next release.
