### ISSUE TITLE
Can’t get the `DELETE` key to work / be registered

### ISSUE THREAD

**Issue by kaimi** [univrsal/input-overlay#35]
**What happened:**

I am currently trying to add the `DELETE` key to my overlay. According to https://github.com/univrsal/input-overlay/blob/master/libuiohook/include/uiohook.h#L236 it should be `0x0E53`. When I use that in my `.ini`, the key is not registered in the input overlay.  i even tried using a 1x1 overlay with it being the only key.

**What was supposed to happend:**

When I hit `DELETE`, input overlay should detect it and light the `DELETE` key in my overlay.

**Log file:**

[2018-03-20 10-08-39.txt](https://github.com/univrsal/input-overlay/files/1828612/2018-03-20.10-08-39.txt)

Might be that I’m just missing something here, of course. I’m pretty new to this tool and the whole input hooking thing in general :)

**Comment by univrsal** [comment]
Uiohook isn't exactly well documented on this, but the keycode you're using is the delete key on your Numpad.
You want 0x0E52

**Comment by kaimi** [comment]
Doesn’t work. `0x0E52` also doesn’t trigger on hitting`INSERT`, which it would be supposed to according to the `uiohook.h` list. Weird.

Side note: I really appreciate your incredibly fast response time and willingness to help. A rare thing :)

**Comment by kaimi** [comment]
> but the keycode you're using is the delete key on your Numpad

That made me test “numpad” keycodes. `0xEE53` works for my `DELETE` key, `0xEE52` for `INSERT`. So either my keyboard firmware or `uiohook` goofed there.

**Comment by univrsal** [comment]
I'm as clueless as you when it comes to this. I never worked with libuiohook before and only switched to it because it's crossplatform.
Also thanks, I'm trying my best^^
