### ISSUE TITLE
Volume Down + Up Constantly showing until pressed

### ISSUE THREAD

**Issue by xamionex** [univrsal/input-overlay#355]
**Describe the bug**
When OBS Launches at startup, the input history overlay will process keys normally _but_ it will add Volume Up + Volume Down as if they're being held during every key until I press them in which they will then disappear

**To Reproduce**
1. OBS on Startup
2. Press any key, it will display as `Volume Down + Volume Up + Key`

For me it happens only on startup of obs, but I've found a way to reproduce it using [AutoHotkey](https://www.autohotkey.com/)
Simply making an .ahk with this does it
```
Send, {Volume_Up}
Send, {Volume_Down}
Exit
```
I've also seen it happen when I press Volume up + down in quick succession sometimes, but I'm not sure if that's the case because I change the volume rarely

**Expected behavior**
1. OBS on Startup
2. Press any key, it will display as just `Key`

**Screenshots**
![image](https://github.com/univrsal/input-overlay/assets/57235791/1fefc471-a1e8-47f1-8e43-65ce4c2d6d50)

**Additional information:**
- Plugin Version: 5.0.4

Logs from today if they help you:
- [2023-07-02 05-29-06.txt](https://github.com/univrsal/input-overlay/files/11928977/2023-07-02.05-29-06.txt)
- [2023-07-02 09-21-30.txt](https://github.com/univrsal/input-overlay/files/11928975/2023-07-02.09-21-30.txt)
- [2023-07-02 09-33-42.txt](https://github.com/univrsal/input-overlay/files/11928974/2023-07-02.09-33-42.txt)
- [2023-07-02 10-03-48.txt](https://github.com/univrsal/input-overlay/files/11928970/2023-07-02.10-03-48.txt)

**Additional context**
I haven't modified any code except switching sides of Left and Right scroll, everything else is styling.

**Comment by univrsal** [comment]
I can't reproduce this so it's most likely an issue on your end. You can just disable volume up and down in the input history preset, by removing these lines:

**Comment by xamionex** [comment]
Alright, I've done that, but when testing with AHK some keys also did that, most likely an issue with how AHK works or my keyboard layout maybe and not the plugin? Not quite sure but thank you
