### ISSUE TITLE
io-cct Tool seems to be buggy

### ISSUE THREAD

**Issue by CatWithaGun0719** [univrsal/input-overlay#358]
In the io-cct used to customize the input overlay, the cropping of the keys is slightly inaccurate. When pressing down on the key, the image it changes to is poorly cropped.

Steps to reproduce the behavior: This happened specifically when I was trying to add the "C" key to my input overlay. The initial process went as intended, but I noticed that when I pressed on the key the highlight would be poorly cropped, the key would move up and part of a lower key would appear.

Originally, this shouldn't happen, the image should stay in the same place and should only appear as if the original key being lit up.

Screenshots: 
![2023-07-22 (4)](https://github.com/univrsal/input-overlay/assets/140276206/16b9028b-030e-4c33-85fe-6d524e90629e)
![2023-07-22 (13)](https://github.com/univrsal/input-overlay/assets/140276206/c642466f-81a8-4168-912e-25065b286a7e)

- Plugin version: 5.0.4

**Comment by univrsal** [comment]
Seems like you didn't crop the element correctly. Can you export the preset and upload it here?

**Comment by CatWithaGun0719** [comment]
Yeah, I can do that.
 And also; the I dont have control over the element, I only have control
over the cropping of the first one before the key is being pressed.

**Comment by CatWithaGun0719** [comment]
The damn thing didn't show up when I sent it via email

**Comment by univrsal** [comment]
I think you have to upload it here on github

**Comment by CatWithaGun0719** [comment]
I tried, it says it doesn't support the file format...

**Comment by univrsal** [comment]
.txt should work

**Comment by CatWithaGun0719** [comment]
Here u go

[wasd-full.txt.txt](https://github.com/univrsal/input-overlay/files/12140429/wasd-full.txt.txt)

**Comment by univrsal** [comment]
The only key that's not working correctly in that preset is alt, which isn't selected correctly:
![image](https://github.com/univrsal/input-overlay/assets/8353672/eb556485-c3eb-4bda-bcf3-62dfbc19f80c)
correct:
![image](https://github.com/univrsal/input-overlay/assets/8353672/00b2b012-fac2-4921-9838-75ab696e54aa)

**Comment by CatWithaGun0719** [comment]
Wait, so was it my error or a code?
If you're saying that it was my problem I didn't select it correctly, then that's the problem I had! It resets itself after I crop it.

1. The cropping (which you showed); When I fixed it myself it seemed fine. But, when I press down and give it an input, the poorly cropped image appears, as I showed in a screenshot when I first made this issue.
2. The cropping you said that was wrong seems to be what was happening to me. At first, I thought it was because I selected it wrong, but then I noticed that it would actually just reset what I had originally selected for the cropping, and it wasn't me being dumb.

**Comment by CatWithaGun0719** [comment]
And by "reset", I literally mean it would adjust the area I selected to an area that looks similar to what you had in your first picture.

**Comment by univrsal** [comment]
What browser are you using?

**Comment by CatWithaGun0719** [comment]
I'm using Google.

**Comment by univrsal** [comment]
I can't reproduce any of the issues with chrome, so I can't really help you with this.

**Comment by CatWithaGun0719** [comment]
The issue didn't occur after I exported it, it happened even while I was in io-cct. Does the browser type really have that much of an effect? If you want, I can make a video so you can see what's happening...

**Comment by univrsal** [comment]
you can try

**Comment by CatWithaGun0719** [comment]
overlaybug.mov
<https://drive.google.com/file/d/1Wjx64KJ7lEOdX9Pcn1YCtmzRdhXWTBo8/view?usp=drive_web>

**Comment by univrsal** [comment]
You are not selecting the button correctly. You can't just eyeball it, it has to be exactly selected or the alignment won't work.

This is wrong:
![image](https://github.com/univrsal/input-overlay/assets/8353672/e2b810a6-8c91-486d-ab11-b565ad2825f4)

This is right:

![image](https://github.com/univrsal/input-overlay/assets/8353672/58066d9b-cf94-49f9-8f31-28823c0d5409)
