### ISSUE TITLE
Doesn't work with OBS 29

### ISSUE THREAD

**Issue by Layarion** [univrsal/input-overlay#359]
**Describe the bug**
Input-overlay doesn't add itself to the "tools" section of OBS Studio version 29.

**To Reproduce**
Install OBS 29.1.3, then install the 64bit 5.0.4 plugin on a 64bit OS. Manually or with the installer, doesn't matter which.

Once done, run OBS Studio and at the top of the window, click on "tools". Observe that it's not there.

**Expected behavior**
For the tools tab to have the plugin's line added.

**Screenshots**
![image](https://github.com/univrsal/input-overlay/assets/7917992/04a55ba1-eb73-4c7c-b57f-8f5b348d9bbd)

**Additional information:**
- 5.0,4
- Full OBS Studio log [(https://cdn.discordapp.com/attachments/376042662580715521/768461567347261470/unknown.png)](https://obsproject.com/logs/BLPWy6zaxK0gOwbn)

**Additional context**
I reverted to the latest 28.1.2 version of OBS, and I was able to get this to work.

**Comment by univrsal** [comment]
You have SRBeep installed, which also ships with SDL2 which conflicts with the SDL2 that input overlay ships.

**Comment by Layarion** [comment]
> You have SRBeep installed, which also ships with SDL2 which conflicts with the SDL2 that input overlay ships.

that fixed it, thanks. sadly SRBeep wasn't working anyway. i downloaded it awhile ago, perhaps there's a new version out now.

**Comment by univrsal** [comment]
Ideally input overlay would dynamically load sdl2 to prevent conflicts, but i'm currently too lazy to work on that.
