### ISSUE TITLE
Combined Keys, shift + 1....

### ISSUE THREAD

**Issue by Jaypower27** [univrsal/input-overlay#36]
Hi, Im trying to set up multiple key with the keyboard overlay. In your .ini file, there's a line named key_order = . I try a lot of combination like 0x0036 && 0x0002, etc... Nothing working.

**Comment by univrsal** [comment]
What do you mean by combined keys? Like key combinations?

**Comment by Jaypower27** [comment]
yes, I play a MMorpg game and Im trying to enlight my abilities in the game bar when I stroke a key. But Im using some keybind abilities with shift, I want to enlight thoses keys too when I stroke the combination of shift + something at the same time.

**Comment by univrsal** [comment]
That's not possible, you can only show the shift key and when you'd press a key combination like Shift + 1, the Shift key and the "1" key would be highlighted.

**Comment by Treehee** [comment]
This would actually be extremely usefull, since windows registers the Alt-Gr button as alt + lcontrol, so being able to at least specify if the key should activate while alt is pressed would be nice :)

**Comment by univrsal** [comment]
I'll close this since it's the same as #73 It's still on my todo list though
