### ISSUE TITLE
Arrow Keys Dead

### ISSUE THREAD

**Issue by HarryLLC** [univrsal/input-overlay#361]
**Bug Description**
Arrow keys do not register input in OBS when pressed.

**To Reproduce**
1. Create arrow key texture
2. Assign texture to key in io-cct and export as JSON
3. Open in OBS
4. Press arrow key and nothing will happen

**Expected Behavior**
Input shows up as highlighted key

**Additional information:**
- Plugin version: 5.0.3

**Additional context**
In io-cct itself, they key is highlighted like normal when pressed. Everything appears to be working right. The problem is using it in OBS.
I was digging through previous issues and saw someone say that they were accidentally mapped to the number pad arrow keys...those don't do anything, either.
![KeyboardLayout](https://github.com/univrsal/input-overlay/assets/85977473/d44dc871-8fe7-49e5-afca-c0d8bcda4584)
Github doesn't natively support .json files, so here's a google drive link to my .json file: https://drive.google.com/file/d/180ZsM9qjJotjsmy70c0Wd0TLczo2EUsr/view?usp=sharing

**Comment by univrsal** [comment]
Can you upload your obs studio log? Also try it again with version 5.0.4 https://github.com/univrsal/input-overlay/releases/tag/v5.0.4
