### ISSUE TITLE
arrow keys not working

### ISSUE THREAD

**Issue by lebin28** [univrsal/input-overlay#363]
**Describe the bug**
Arrow keys not being recognized in OBS even after correcting their decimal values in the .json file per issue #174 

**To Reproduce**
1. Uninstall OBS completely
2. Reinstall OBS
3. Add the input overlay plugin with the same ,json file as before

**Expected behavior**
Arrow keys should've still worked after reinstalling OBS

**Additional information:**
- Plugin version: 5.0.4
- Full OBS Studio log: https://obsproject.com/logs/6OiipjfDBH7A1STf

**Additional context**
I used an older version of OBS before reinstalling to the latest version (29.1.3)

**Comment by univrsal** [comment]
what preset are you using?

**Comment by lebin28** [comment]
> what preset are you using?

the preset i made with io-cct

**Comment by univrsal** [comment]
Upload it, so I can test with it.

**Comment by lebin28** [comment]
https://drive.google.com/drive/folders/145h1Kj-EaxWe-6cwkfHuHGDRVY4c2kAO?usp=sharing

**Comment by univrsal** [comment]
Try this one:
https://up.vrsal.xyz/overlay2.json (click get in the top right corner)

**Comment by lebin28** [comment]
i tested that already, didn't work

**Comment by lebin28** [comment]
> Try this one: https://up.vrsal.xyz/overlay2.json (click get in the top right corner)

apparently it works now... i swear i tried this before but whatever thanks :)

**Comment by Kirbo** [comment]
> > Try this one: https://up.vrsal.xyz/overlay2.json (click get in the top right corner)
> 
> apparently it works now... i swear i tried this before but whatever thanks :)

Can anyone share the config here as well, as the JSON file is not there up for grabs anymore?

**Comment by univrsal** [comment]
I checked my server but the file isn't there anymore. But arrow keys should work with cct, so you could just download the files from the google drive link and rebind the arrow key elements
