### ISSUE TITLE
[request]have wiki explain what "apply alpha in linear space" means

### ISSUE THREAD

**Issue by Layarion** [univrsal/input-overlay#365]
i tried looking on the wiki, i don't know what this is for. i know what alpha is roughly, but no idea what this setting does, nor when i should or shouldn't use it.

**Comment by univrsal** [comment]
https://github.com/univrsal/input-overlay/wiki/Usage#apply-alpha-in-linear-space

I didn't add the feature, but that's roughly how I understood it.
