### ISSUE TITLE
Fix XInput in CMakeLists.txt

### ISSUE THREAD

**Issue by erneut** [univrsal/input-overlay#37]
Hello.

Today I've been trying to build your plugin in VS2017.

After couple hours of struggling I found probably your thread https://obsproject.com/forum/threads/solved-issues-with-plugin-loading.79508/

So it should be linked with XInput9_1_0 rather that XInput. Please fix this for the future developers. This issue is hard to diagnose, but solution is very simple.

**Comment by univrsal** [comment]
I'll do that, but have you read the README? Could've saved you some research.

![screen](https://i.imgur.com/oFhPC5x.png)
