### ISSUE TITLE
Request for font names to be added to documentation

### ISSUE THREAD

**Issue by hheimbuerger** [univrsal/input-overlay#370]
I've been trying to extend the `wasd` preset with more keys (cursor keys, in my case), but struggling to find characters that fit the style of the existing buttons. Could you share the name of the font (and possibly settings like characters size, stroke width, rotation angle/tilt, etc.) that you used to create these, and possibly the same for the other presets?

It should probably be added to the wiki, I was looking for it under [Creating presets](https://github.com/univrsal/input-overlay/wiki/Creating-presets), but couldn't find anything. My apologies if it's in the 54 pages of conversations in the OBS forum... I did not read them all and couldn't find a way to search that thread. 😣

Thanks!

---

My embarassing work-in-progress below, so you believe me that this is really needed! ;)
![image](https://github.com/univrsal/input-overlay/assets/159414/002f82b7-0835-4061-a15c-817d581598c0)
I'll probably also redo the ALT, because it and TAB surprisingly use a different font size than CTRL and SHIFT.

**Comment by univrsal** [comment]
I've added the info [here](https://github.com/univrsal/input-overlay/wiki#what-fonts-do-the-wasd-and-qwerty-presets-use). I only created the wasd and qwerty presets, for the other ones you'd have to look at the respective readme files and ask the authors.

**Comment by hheimbuerger** [comment]
> I've added the info [here](https://github.com/univrsal/input-overlay/wiki#what-fonts-do-the-wasd-and-qwerty-presets-use). I only created the wasd and qwerty presets, for the other ones you'd have to look at the respective readme files and ask the authors.

Thanks again!

@univrsal I reviewed this now, and I'm pretty sure the font used (e.g. for the `wasd` layout) is not `BigNoodleToo`, but rather `BigNoodleTooOblique`. The former produces either too little (no) slant, or too much slanting in its italic configuration.

`BigNoodleTooOblique` however is apparently a separate font that produces exactly the same amount of slant as used by the `wasd` layout.

**Comment by pbaykalov** [comment]
@univrsal Thanks for the great plugin! Can you please add "extended numeric" as well?

**Comment by univrsal** [comment]
The PSD for that? I don't have that, didn't make the preset.

**Comment by pbaykalov** [comment]
You can add my version if you want, I added some keys.
Made in Krita.

<img width="1736" height="636" alt="Image" src="https://github.com/user-attachments/assets/1f621abc-d9f6-450a-881e-7cf26dfcc016" />

[wasd-extended-numeric-CUSTOM.zip](https://github.com/user-attachments/files/25853581/wasd-extended-numeric-CUSTOM.zip)
