### ISSUE TITLE
Preset Editor not recognising side button inputs at all.

### ISSUE THREAD

**Issue by walkingtalkingexistentialcrisis** [univrsal/input-overlay#374]
**Describe the bug**

The preset editor isn't recognising my side buttons at all. A similar issue is mentioned in issue [#100](https://github.com/univrsal/input-overlay/issues/100), but I don't think the same fix is working. Even trying to Record Keycode isn't working since when I click my side buttons on my mouse, nothing changes at all.

**To Reproduce**
Steps to reproduce the behaviour:

1. Open Preset Editor
2. Select the mouse preset of your choice (The one I'm using is Alternative > DJOSH95)
3. Select Side Button elements
4. Attempt to Record Keycode, Keycode is not recognising Side Button inputs as any kind of input,

**Expected behaviour**

Side Button Element should be recognising button/key presses as inputs.

**Screenshots**

**Additional information:**
- Plugin version
- Full OBS Studio log (https://cdn.discordapp.com/attachments/376042662580715521/768461567347261470/unknown.png)

**Additional context**
In [#100](https://github.com/univrsal/input-overlay/issues/100), it mentions something about testing inputs with a `deep_hook.exe` or `deep_hook_async.exe` being able to be found in a util.zip area of the release page, but I've looked and cannot find any such EXE files in said folder, so I'm unsure what else to do other than submit a bug report. I've attempted to use the fix in [#100](https://github.com/univrsal/input-overlay/issues/100), but it isn't working from what I've tried.

**Comment by univrsal** [comment]
What browser are you using? It works fine for me in chromium based ones, but not in firefox.

**Comment by walkingtalkingexistentialcrisis** [comment]
I just installed Firefox on my gaming PC this morning, so I guess it was just inconvenient timing I guess. Will try again in Chrome tomorrow and update here on if it works then
