### ISSUE TITLE
Unexpected Behavior with Custom QWERTZ Preset

### ISSUE THREAD

**Issue by FatalBulletHit** [univrsal/input-overlay#377]
I created a [custom QWERTZ preset](https://github.com/FatalBulletHit/input-overlay/tree/master/presets/qwertz_full_size_german) with the help of io-cct and upon testing it in OBS I encountered a rather unexpected behavior - while io-cct highlights the correct keys, OBS does not:

https://youtu.be/I8QidWzqiMM
(io-cct top, OBS overlay bottom)

Key Pressed | io-cct | OBS Overlay
| - | - | - | 
\- | 0x0035 (VC_SLASH) | 0x000c (VC_MINUS)
ß | 0x000c (VC_MINUS) | 0x001a (VC_OPEN_BRACKET)
Ü | 0x001a (VC_OPEN_BRACKET) | 0x0027 (VC_SEMICOLON)
Ö| 0x0027 (VC_SEMICOLON) | 0x0029 (VC_BACKQUOTE)
^ | 0x0029 (VC_BACKQUOTE) | 0x002b (VC_BACK_SLASH)
#| 0x002b (VC_BACK_SLASH) | 0x0035 (VC_SLASH)

**To Reproduce**
Not sure, preset can be found [here](https://github.com/FatalBulletHit/input-overlay/tree/master/presets/qwertz_full_size_german).
Does the Windows keyboard layout settings have any effect on this?

**Additional information:**
- Plugin version: 5.0.4-HEAD-5f18f42 build on 2023.05.08 07:27
- [Full OBS Studio log](https://obsproject.com/logs/OaWdIlxWiIEQ8fwO)

**Comment by univrsal** [comment]
Yeah the mapping for some special keys isn't that straightforward. You'll have to manually enter the key codes for those keys for now.

**Comment by FatalBulletHit** [comment]
It's easy to work around, but why does io-cct and OBS differ when using the same exact config?
Does OBS or the io-cct webtool interpret the key presses incorrectly? 🤔

**Comment by univrsal** [comment]
The inputs from the browser have to be converted to the keycodes that libuiohook uses, which is the library that input overlay uses for keyboard and mouse input, but there are inconsistencies between browsers, operating systems and keyboard layouts

**Comment by FatalBulletHit** [comment]
Ok, thanks for the explanation. 🙂

**Comment by FatalBulletHit** [comment]
Ok, thanks for the explanation. 🙂
