### ISSUE TITLE
put an "Alt" please 

### ISSUE THREAD

**Issue by L1cardo** [univrsal/input-overlay#38]
can you put an "`Alt`" in to the  "wasd-extended"? it would be nice if i have an "`Alt`" 
![image](https://user-images.githubusercontent.com/33802186/40583983-a8d62af8-61cb-11e8-9a63-44cc30545383.png)

**Comment by univrsal** [comment]
You can modify the overlays yourself, [here](https://vimeo.com/238275966)'s the tutorial on how to do it.
I know that it's in english, but I don't have the time to modify the layout to everyone's needs.
Also I'm currently busy working on a new version, so I'd rather put my time into that, sorry.

**Comment by L1cardo** [comment]
It is OK . I will figure it out myself. Thank you anyway.
