### ISSUE TITLE
Input overlay no longer responds to input

### ISSUE THREAD

**Issue by TemApex** [univrsal/input-overlay#383]
**Describe the bug**
Input overlay used to work but suddenly stopped responding to inputs.

**To Reproduce**
Unsure. It suddenly stopped working after working fine for years.

**Expected behavior**
The input overlay should show the buttons being pressed. It doesn't do this.

**Additional information:**
- Plugin 5.0.4 (64-bit), OBS 30.0.2 (64-bit)
- [obsproject.com/logs/nfXeWHzoNKOn9oBt](https://obsproject.com/logs/nfXeWHzoNKOn9oBt)
- [Using a custom overlay](https://drive.google.com/file/d/1EjxUgHCKV0bTworbZqVZ3HWpIfuddTDw/view?usp=sharing)
- C++ redistributables are installed
- Plugin was both reinstalled manually and with the installer, neither worked

**Additional context**
The website to create custom overlays works fine and shows inputs registering properly but it doesn't work in OBS. The overlay displays in OBS (and I can even create new ones), but it does not respond to input and is stuck in an inactive state despite the key being pressed.

**Comment by univrsal** [comment]
Can you check if you have input filtering enabled? It's the "Enable input control" option in the settings dialog:
![Screenshot_20240110_121233](https://github.com/univrsal/input-overlay/assets/8353672/0aa0ce95-9894-4b22-a04d-fe3dbbe2abf3)

**Comment by TemApex** [comment]
This is going to sound really stupid. I had no idea that settings menu existed, and apparently the mouse and keyboard hook was disabled?
![image](https://github.com/univrsal/input-overlay/assets/57864042/e7203866-94f0-4376-b62e-6364e6475bcc)
I have no idea how this happened but it works again now. Really not sure what caused the hooks to be disabled though, strange
