### ISSUE TITLE
Documentation: The Usage wiki page does not describe basic usage, only special scenarios

### ISSUE THREAD

**Issue by jpaugh** [univrsal/input-overlay#386]
I want to explain the challenge new users face before adopting your wonderful product. This challenge will no doubt slow the adoption of your product among streamers, who are sometimes less tech savvy than their audience. Every question I'm asking below is a chance for a new, non-technical user to give up and walk away from your product before even trying it out. Many of them will not be familiar enough with Github to even open a new issue.

I am installing this plugin for the first time, and this is the first plugin I've tried to use with OBS,  so I'm especially qualified to write this bug report. In 10 minutes, when I have used my black-belt tech-fu to attack this challenge, I will lose the ability to ask these questions properly, so I've held off on doing any research to solve my own problem. 

I have the following questions, which should be answered by the Installation wiki or the Usage wiki. Currently, they are not, and it requires technical expertise or familiarity with your product to answer each of them.

* How do I verify that the plugin is installed correctly? Should I expect any UI changes to my OBS instance? New menus? New sources? New ...?

    A few screenshots would be nice. Once I install it correctly and find your plugin UI, I have no more need of this. However, if I've installed it incorrectly, I won't know that I've done it wrong, because I have no way to get feedback about it.

* Where and how do I install the presets?

    The usage page instructs me to unzip the preset files, but doesn't say where. Does it matter where? It also doesn't say what the next step is to install or use them. Will your plugin automatically scan my `~/random/bits/` folder? Will it prompt me to choose a location? I don't know.

   If I knew the knew the next step, I could guess where to unzip the files and whether it matters where.

* How do I find this plugin within OBS?

    I have never used an OBS plugin before, so I have no idea what the convention is. Because I'm familiar with installing plugins for other software, I have some good guesses. Not everyone will.

* How do I go through the _most basic_ workflow to get something to show up in my stream or recording?

    You've got some documentation for advanced cases on the Usage page already, which is great for when I'm ready to get advanced. What I need first, though, is the minimum necessary steps to get anything to happen at all. Is it turned on by default? Will it find my presets and pick one automatically? Where do I change the settings if the defaults aren't working for me?

**Comment by univrsal** [comment]
I've added some parts to clarify the usage in the wiki but there's also a [video tutorial](https://www.youtube.com/watch?v=7DTVIh3w6U8) which goes through the entire process in detail.

>How do I verify that the plugin is installed correctly? Should I expect any UI changes to my OBS instance? New menus? New sources? New ...?

>How do I find this plugin within OBS?

See the new [troubleshooting](https://github.com/univrsal/input-overlay/wiki/Installation#troubleshooting) section

>Where and how do I install the presets?

It now says that the location does not matter. You select the files in the properties of the source.

>How do I go through the most basic workflow to get something to show up in my stream or recording?

It's a new source type that has to be added to the scene like any other source.
