### ISSUE TITLE
Please add extended keyboard support

### ISSUE THREAD

**Issue by tinydrunkblyat** [univrsal/input-overlay#388]
**Describe the bug**
There isnt any extended keyboard support, specifically for the numpad.

**To Reproduce**
try to get the thing set up to read numpad
**Expected behavior**
no numpad support

**Screenshots**
NA

**Additional information:**
4.8b
- Full OBS Studio log - NA

**Additional context**
i want to use this for fighting games but i use numpad for directions instead of arrow keys please help

**Comment by univrsal** [comment]
There's a [numpad](https://github.com/univrsal/input-overlay/tree/master/presets/qwerty-pixel-with-keypad) preset in the latest version. It contains the entire keyboard, but you can either crop it or edit it using the config editor. See https://github.com/univrsal/input-overlay/wiki/Usage#io-cct

**Comment by tinydrunkblyat** [comment]
thank you
