### ISSUE TITLE
Overlay could not be found

### ISSUE THREAD

**Issue by ViruzTeddy** [univrsal/input-overlay#389]
please help i already installed the overlay but it could not be found

[2024-03-08 02-02-04.txt](https://github.com/univrsal/input-overlay/files/14528946/2024-03-08.02-02-04.txt)
![image](https://github.com/univrsal/input-overlay/assets/162627427/7df39efa-d4e8-4e7c-97f3-faa7da816472)

**Comment by univrsal** [comment]
Your OBS version is outdated. Update to 30.0.2
