### ISSUE TITLE
Key Mapping

### ISSUE THREAD

**Issue by ChristopheCVB** [univrsal/input-overlay#39]
Key Mapping on https://github.com/univrsal/input-overlay/blob/master/libuiohook/include/uiohook.h seems not to be the same from https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

**Comment by univrsal** [comment]
Yeah I know, initially I used the windows method GetAysncKeyState, which uses the windows Virtual-Key Codes.
In all later versions I switched to libuiohook, which provides its own key codes, which you can find in uiohook.h

**Comment by ChristopheCVB** [comment]
Maybe you should update it in the Readme and the tutorial video ^^
