### ISSUE TITLE
online json creator program cannot scroll down on tall PNG imports

### ISSUE THREAD

**Issue by Diddz7** [univrsal/input-overlay#393]
**Describe the bug**
json creation tool cuts off the bottom half of the imported png file, inability to scroll the tool to the bottom half

**To Reproduce**
import a PNG file and an existing json to edit, when adding a new key, bottom half of the base png is inaccessible

**Expected behavior**
scroll mouse wheel down to move the view to the bottom half of the png

**Screenshots**
![image](https://github.com/univrsal/input-overlay/assets/140991292/6f5c61ff-d7a4-401d-b196-ef29d87f810f)

**Additional information:**
- 5.0 (but does not seem applicable to the preset creation process through the online tool

**Additional context**
trying to edit one of the included clean keyboard overlays to include the 10-key keypad (edits to the preset's PNG were made a copy of as the base)

**Comment by univrsal** [comment]
You can move the view by holding right click and dragging the mouse.
