### ISSUE TITLE
Input Overlay 5.0.5 QWERTY Preset Crashes OBS Studio (30.1.2)

### ISSUE THREAD

**Issue by mcorrigan** [univrsal/input-overlay#396]
**Describe the bug**
I have a fresh install of OBS Studio 30.1.2 installed and used the Windows x64 bit installer to install Input Overlay 5.0.5. I also downloaded the presets for 5.0.5. I tried wasd first, which worked. Then tried QWERTY which crashed the program.

**To Reproduce**
Install OBS Studio (using scoop), install Input Overlay 5.0.5 using Windows x64 Installer. Select the /current directory in scoop application for the target installation of Input Overlay. Download the presets 5.0.5. In OBS Studio, add an Input Overlay.  Add the wasd preset. It should work fine. Now edit the existing Input Overlay source and change it to be the QWERTY preset, first my choosing the image and then the JSON file. 

The application should now crash. 

**Expected behavior**
It would seem that the wasd related resources would be cleared and replaced with QWERTY resources as defined by the preset files.

**Screenshots**
No screenshot available.

**Additional information:**
- Plugin version 5.0.5
- Full OBS Studio log here: https://pastebin.com/eGE4BYGp
- 

**Additional context**
If I create a new Input Overlay source and set it to the QWERTY preset, it works just fine.

**Comment by univrsal** [comment]
I can't reproduce on a fresh installation of obs 30.1.2 and input overlay 5.0.5. Which preset did you use exactly? wasd-minimal or wasd-full? Can you also upload your obs studio log?

**Comment by mcorrigan** [comment]
Sorry I missed that, it was wasd-minimal.

**Comment by univrsal** [comment]
I still can't reproduce it. Does it repeatedly happen for you? Does it also happen in an empty scene collection. Did you make any changes to the input overlay settings in the settings dialog?

**Comment by mcorrigan** [comment]
It does not seem to crash now when I do it. Before my scene had a Display Capture as well. But now I can't replicate the issue and cause it to crash. Thanks for looking into this, I'll let you know if I am able to replicate it again.
