### ISSUE TITLE
WASD layout broken ?

### ISSUE THREAD

**Issue by Neko250** [univrsal/input-overlay#4]
When loading WASD preset there's no `R`, `F` or `TAB` keys, it looks like this:

![obs64_2017-09-24_16-36-50](https://user-images.githubusercontent.com/2650578/30783648-b890d754-a146-11e7-9e5a-591b3d1aa208.png)

I've tried with both `.ini` files, the one from `v1.0` and `v1.1`, same error.
However the config seems to be correct, those missing keys are specified in the fields `key_order`, `key_width`, `key_height`, `key_row` and `key_col`.

**Comment by univrsal** [comment]
Hmm, I the plugin is having issues loading the textures from the second row. It'll take me some time to set up my development environment again so you can use [this](http://hnng.moe/f/Uev) layout which only uses one texture row for now.

**Comment by univrsal** [comment]
I'm going to close this for now. If you run into any other issues go ahead and tell me
