### ISSUE TITLE
.deb file not working

### ISSUE THREAD

**Issue by david-marco** [univrsal/input-overlay#403]
**Describe the bug**
I installed .deb using my package manager, but I see no input overlay in OBS

**To Reproduce**
Install .deb file

**Expected behavior**
I expected that the input overlay will appear when .deb is installed.

**Additional information:**
- Plugin version: `5.0.5`
- Full OBS Studio log *(the image link is no longer available so idk how to get it)*

**Comment by univrsal** [comment]
![img](https://up.vrsal.cc/selif/p1dppvig.png)

**Comment by david-marco** [comment]
> ![img](https://camo.githubusercontent.com/44b47af439d1f9fe34610f498febb49874cca67edfd16c108adbf44d71658614/68747470733a2f2f75702e767273616c2e63632f73656c69662f70316470707669672e706e67)

https://obsproject.com/logs/BVhZ9uGVOBXJOLoT

**Comment by univrsal** [comment]
You're running the flatpak version of obs. It can't load plugins from outside the sandbox. Try installing it from flathub https://flathub.org/apps/com.obsproject.Studio.Plugin.InputOverlay

I have nothing to do with that version, though. If it doesn't work you have to report issues here https://github.com/flathub/com.obsproject.Studio.Plugin.InputOverlay/issues

**Comment by david-marco** [comment]
Thank you bro, I think I'm gonna switch from flatpak to smth different.

**Comment by univrsal** [comment]
You can just install obs via the [ppa](https://obsproject.com/download):
![image](https://github.com/univrsal/input-overlay/assets/8353672/f78c287f-8f0b-43cb-bc04-4aa63df13d5f)
