### ISSUE TITLE
Gamepad input event does not broadcast in WebSocket 

### ISSUE THREAD

**Issue by Tma2333** [univrsal/input-overlay#404]
**Describe the bug**
Gamepad input event does not show up in the WebSocket. 

**To Reproduce**
1. Connect gamepad 
2. Start game support gamepad
3. Enable forward/receive event in setting 
4. Start a simple WebSocket echo listener script (I am using python), it just print out all events
5. Move around gamepad and no event shows up. 

**Expected behavior**
Maybe this is not supported? 
1. I expect the event to show up in the WebSocket event. 

**Screenshots**
N/A

**Additional information:**
- Plugin version: 5.05

**Comment by univrsal** [comment]
Try the builds at the bottom from this nighly run https://github.com/univrsal/input-overlay/actions/runs/9880707227

**Comment by Tma2333-Scale** [comment]
Working with this nightly build. Thanks!

**Comment by Tma2333** [comment]
It is working with this nightly build. Thanks!
