### ISSUE TITLE
[feature request] Standalone usage without OBS

### ISSUE THREAD

**Issue by Unknow0059** [univrsal/input-overlay#406]
**Describe the bug**
This is not a bug, but a feature request.

**Expected behavior**
I expected to be able to use this tool outside OBS, because I expected this to have been standalone first, then to having been ported into plugin form for use within OBS later.
This isn't the case, it was made as a plugin for OBS only.

I sought a tool to display my keypresses through a real-time updating graphic representation of my keyboard - this is it, except it's stuck as a plugin.

It would surely be easier for this to be made into a standalone program, than for someone else to make it from the ground-up entirely.

**Use case?**

Video recordings and video-streaming methods made with Anything other than OBS, e.g.: ShareX, FFMPEG, Discord, Steam, Nvidia Shadowplay, My Phone's Camera, etc.

Demonstration to & Visualization of key inputs on-screen by third-parties who are locally or remotely present, and/or ignorant about input methods & usage.

**Additional context**
I'm using Windows 10.

**Comment by univrsal** [comment]
Try [Nohboard](https://github.com/ThoNohT/NohBoard).

**Comment by Unknow0059** [comment]
Thank you kindly. 🙇‍♂️
