### ISSUE TITLE
Is there any possibility to have a standalone server?

### ISSUE THREAD

**Issue by qakcn** [univrsal/input-overlay#408]
Hello, thank you for your wonderful project.

Here I have some suggestions. I don't want to give you any pressure, you can ignore me as your wish.

I have a PC for gaming (**PC1**), and another one for streaming (**PC2**). As present version of *input-overlay*, if I want to show **PC1** inputs in **PC2** streaming, I have to:

  1. Open an _OBS_ software on PC1, start the _WebSocket server_ in _input-overlay_;
  2. Run standalone _io-client_ on PC2.
  3. Open another _OBS_ on PC2, use _input-overlay_.

In this procedure, **two** _OBS_ with **two** _input-overlay_ and **one** extra process (_io-client_) are running. _OBS_ on PC1 is unnecessary because streaming is worked on PC2.

If there is a standalone server, and the client is integrated into _input-overlay_, the procedure can be optimized as:

  1. Open a **standalone server** on PC1.
  2. Open _OBS_ on PC2, use _input-overlay_ with client integrated.

Only **one** _OBS_ with _input-overlay_ now, and **one** extra process (standalone server).

I hope it's not too much to ask. Thank you.

**Comment by univrsal** [comment]
You don't have to start two versions of OBS. I'm not sure how you got that idea. You can just use input overlay in the first instance of OBS.

**Comment by univrsal** [comment]
You don't use OBS on PC1, you use the client on that machine. That's the whole point of the client.
![New Project](https://github.com/user-attachments/assets/437ce611-e601-4766-b77a-0987074493b9)

**Comment by qakcn** [comment]
You mean the client is the sender and the server is the receiver?

My fault, I misunderstand this. Sorry.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by univrsal** [comment]
> You mean the client is the sender and the server is the receiver?

Yes, that's correct.
