### ISSUE TITLE
The mouse arrow points in one direction when stopped

### ISSUE THREAD

**Issue by hatrac** [univrsal/input-overlay#409]
**Describe the bug**
The arrow always points to the right, but it can reflect the movement of the mouse like this

**To Reproduce**
![recording](https://github.com/user-attachments/assets/3f12dccd-bdf7-49dc-b98b-d68d3e6d62d9)

**Expected behavior**
I hope the arrow can point in that direction the last time the mouse moves. 

**Additional information:**
- v5.05
- Full OBS Studio log (https://up.vrsal.cc/selif/p1dppvig.png)

**Comment by univrsal** [comment]
The arrow really only works if you define the monitor center and then play a game that locks the mouse.

**Comment by hatrac** [comment]
> The arrow really only works if you define the monitor center and then play a game that locks the mouse.

 thank u but i tried. it has only two directions
![recording](https://github.com/user-attachments/assets/c4335cce-5baf-4f06-8ffe-b11e42912ae7)

**Comment by univrsal** [comment]
I think I'll just remove the arrow preset. It's too complicated to setup properly.

**Comment by hatrac** [comment]
> I think I'll just remove the arrow preset. It's too complicated to setup properly.

Well, actually it's okay to use it now. Anyway, thank you
