### ISSUE TITLE
I can not find the obs folder

### ISSUE THREAD

**Issue by Baleh01** [univrsal/input-overlay#41]
**Describe the bug**
I do not find the obs folder I did the processes I read in the folder sheet the obs folder is not there I checked in the x86 programs and programs folder
**To Reproduce**
Steps to reproduce the behavior: folder obs

**Expected behavior**

**Screenshots**

**Additional information:**
- Plugin version 4.5
- Full OBS Studio log

**Additional context**

**Comment by univrsal** [comment]
Do you have additional hard drives? Maybe it's on there.
Other than that just right click on the OBS shortcut and select the second option. I don't know what it says in the english version, but I think it's something like "Open path":

![image](https://user-images.githubusercontent.com/8353672/42372640-0bd2d348-8113-11e8-95dc-06fd214b6cc9.png)

**Comment by univrsal** [comment]
If you don't answer me I can't really help you
