### ISSUE TITLE
Overlay not Reflecting my Inputs

### ISSUE THREAD

**Issue by ChaSam1** [univrsal/input-overlay#412]
**Describe the bug**
The overlay is not responding to any inputs despite being read by libuiohook

**To Reproduce**
install input-overlay through the installer (and afterwards try the manual installation)
use one of the premade presets provided
press any of the keys or buttons requested

**Expected behavior**
When I input a movement or mouse adjustment it's reflected

**Screenshots**
![Screenshot (79)](https://github.com/user-attachments/assets/9da94464-5d27-43b7-a05d-af1092db2227)

**Additional information:**
- Version 5.0.5
- Full OBS Studio log (https://obsproject.com/logs/dNXOidI89vB5Sd4X)

**Additional context**
It was working previously a few days ago however mid playthrough it just stopped working

**Comment by univrsal** [comment]
You enabled input control with a whitelist which blocks all inputs unless a window with a specific title is active but the list of window titles that are whitelisted is empty, so events are always blocked.

**Comment by ChaSam1** [comment]
Ohhhh I feel like an idiot, I'll change that and see if it works!

**Comment by ChaSam1** [comment]
I just changed the setting and restarted my computer just in case and unfortunately it still doesn't work

**Comment by ChaSam1** [comment]
> You enabled input control with a whitelist which blocks all inputs unless a window with a specific title is active but the list of window titles that are whitelisted is empty, so events are always blocked.

Sorry if I'm bothering but yeah I restarted my PC and OBS and unchecked input control but still nothing unfortunately https://obsproject.com/logs/q0JA6F50WuRzyJuO

**Comment by coconuty4765** [comment]
Try turning off the Gamepad Hook, I tried that and it worked for me

**Comment by ChaSam1** [comment]
> Try turning off the Gamepad Hook, I tried that and it worked for me

THANK YOU! That solved it
