### ISSUE TITLE
Some features of Input Overlay not working / greyed out

### ISSUE THREAD

**Issue by Dinu5346** [univrsal/input-overlay#413]
**Describe the bug**
When I open OBS and go to Tools -> Input-overlay settings, the configuration window says "Most of these settings will require a restart!".  And I can't use Filter mode, Window title for filter and Current filters. Other settings on that page work correctly. Input overlay for keyboard and mouse work correctly.

**To Reproduce**
Download input-overlay-5.0.5-windows-x64.zip and input-overlay-5.0.5-presets.zip and extract the contents of overlay-5.0.5-windows-x64.zip to the installation directory of OBS (C:\Program Files\obs-studio). Then open OBS and go to Tools -> Input-overlay settings.

**Expected behavior**
In the Input-overlay configuration window, all the settings enabled and no warning labels.

**Screenshots**
![image](https://github.com/user-attachments/assets/4f4596f2-0681-4732-a217-7229fe209a49)

**Additional information:**
- Plugin version: 5.0.5
- Full OBS Studio log: https://obsproject.com/logs/Wpzg6XA091hFI842

**Additional context**
None.

**Comment by univrsal** [comment]
The settings are grayed out because you don't have input control enabled.

https://github.com/user-attachments/assets/fac8760d-c27a-4c5c-a3fa-412630bc528b
