### ISSUE TITLE
Mouse side buttons reversed (v4.5)

### ISSUE THREAD

**Issue by wickles** [univrsal/input-overlay#42]
Hi, the side buttons on my mouse are reversed. I saw that in a previous version this was supposed to be fixed. Maybe it fixed it for some mice and broke it for others? Can this be reconfigured easily? 

I'm using input-overlay v4.5, OBS 21.1.2, and have a Razer DeathAdder Chroma.

**Comment by univrsal** [comment]
It seems that every mouse is doing this differently. The key order is sadly hardcoded so I can't provide you with an easy fix for that right now, except if you want to compile it yourself

**Comment by wickles** [comment]
I solved it by changing the ini file, swapping 1/2 in `2_mouse_smb(1/2)_A_B`.

**Comment by univrsal** [comment]
I guess that would work as well

**Comment by VoidsShadow** [comment]
It could be useful to keep a list of mice that behave one way or the other.
For reference, my G903's Back button is registered as "Button 4" in DirectInput. Forward is "Button 5".
This seems to be the norm for every Logitech mouse I've owned over the years. Mice sold and branded by ASUS and Monoprice seem to have the same virtual layout.
