### ISSUE TITLE
Plugin doesn't load in obs flatpak

### ISSUE THREAD

**Issue by claymorwan** [univrsal/input-overlay#423]
**Describe the bug**
The input-overlay plugin doesn't show up in my sources, I tried both installing it from flathub (like obs recommends) and manually but none work.

**To Reproduce**
1. Install obs from flatpak
2. Try installing the plugin
3. Open obs

**Expected behavior**
Expected to load

**Screenshots**

**Additional information:**
- Plugin version: v5.0.5
- Full OBS Studio log: https://obsproject.com/logs/cFom1BbBNmFKCKHa

**Comment by univrsal** [comment]
The normal version only works with a normal installation of OBS as I don't use Flatpak. The version from Flathub should work, if it doesn't you have to report it to the maintainer. It seems to be a known issue https://github.com/flathub/com.obsproject.Studio.Plugin.InputOverlay/issues/10

**Comment by 5n00p4eg** [comment]
As a temporary fix:
`flatpak override --env=LD_LIBRARY_PATH=/app/lib com.obsproject.Studio`
[Details](https://github.com/flathub/com.obsproject.Studio.Plugin.InputOverlay/issues/10#issuecomment-2431492890)

**Comment by claymorwan** [comment]
> As a temporary fix: `flatpak override --env=LD_LIBRARY_PATH=/app/lib com.obsproject.Studio` [Details](https://github.com/flathub/com.obsproject.Studio.Plugin.InputOverlay/issues/10#issuecomment-2431492890)

So that worked, but now it only detects when I'm pressing tab, shift and ctrl for some reason

**Comment by univrsal** [comment]
Seems like you're using wayland, libuihook doesn't work with wayland.

**Comment by claymorwan** [comment]
Bowomp, again sumthing that doesn't work with wayland

**Comment by univrsal** [comment]
Not much that can be done from what I can tell. Wayland does not support input hooking for security reasons and (as far as I know) offers no proper solution for legitimate use cases.

**Comment by univrsal** [comment]
If you're on Wayland it can't detect inputs because of how Wayland is designed.

**Comment by kayronnBR** [comment]
Run this command in the terminal and be happy.
`flatpak install flathub com.obsproject.Studio.Plugin.InputOverlay`
