### ISSUE TITLE
Linux Installation 

### ISSUE THREAD

**Issue by SuperSwagger** [univrsal/input-overlay#43]
The instructions in the README file are ineffective in installing the plugin. I tried those steps and others numerous times in multiple different ways, and none of them worked. Many of us would like a clarification on how to install the plugin on linux, please.

**Comment by univrsal** [comment]
[I answered you over on the obs forums](https://obsproject.com/forum/threads/input-overlay.72759/page-10#post-363323)

**Comment by Lightsockie** [comment]
Perhaps adding a note of needing libuiohook to the installation documentation would be a good idea (I know it existed in the credits section of the repo's README). Sure, Linux guys are prolly sharp enough to trace the error down and figure it out eventually, but surely a note in the docs could improve a lot of people's quality of life.

**Comment by univrsal** [comment]
It's mentioned in the forum post, as well as in the installation video, but I might add a note here
