### ISSUE TITLE
Where I should put the io_client?

### ISSUE THREAD

**Issue by Septemberlemon** [univrsal/input-overlay#431]
PLEASE FILL THIS OUT CORRECTLY OR THE ISSUE WILL BE CLOSED

(You can remove this text after you've filled out the form)

when I finish download the zip file,I get three folders and the readme.md says that I should just put two of them to where they should be,but what about the io_client directory?can I throw it away?if it's useless,why it will be there
**Describe the bug**
as above
**To Reproduce**
I expected a better readme file if possible
**Expected behavior**

**Screenshots**

**Additional information:**
- Plugin version
- Full OBS Studio log (https://up.vrsal.cc/selif/p1dppvig.png)

**Additional context**

**Comment by univrsal** [comment]
It's for showing inputs from other computers. See https://github.com/univrsal/input-overlay/wiki/Usage#remote-connection
