### ISSUE TITLE
Incorrect folder location

### ISSUE THREAD

**Issue by reaply** [univrsal/input-overlay#46]
Hello, 

I found the bug to be happening while I'm using it on Fedora 28. What ends up happening is that the readme describing to move the files to /.config/obs-studio/plugins/ but:
1. The plugins folder was not created and I attempted to install it into the plugins_conf
2. I created the plugins folder but OBS will not pick up the plugin 
3. I put the .so file in /usr/lib64/obs-plugins/ and OBS will pick it up but the output will be 
`error: os_dlopen(/usr//lib64/obs-plugins/input-overlay.so->/usr//lib64/obs-plugins/input-overlay.so): libuiohook.so.0: cannot open shared object file: No such file or directory`
As you can see, it's created additional / for the folders. I tried to look through the source code but I am not a programmer so my searching is limited where to look to change the path. 

If you can get back to this thread or release an update (or even give some advice of how to stumble through the code to change it myself) it would be very much appreciated. Thank you.

**Comment by univrsal** [comment]
Did you install libuiohook?
Also the installation instructions in the readme are wrong, I haven't changed them yet.
I have a  video up on the obs forums explaining the whole process, but you can also follow the instructions made for [solus](https://solus-project.com/articles/software/open-broadcaster-software/en/#input-overlay) (Which should work for most distros)

**Comment by reaply** [comment]
Hey, thank you for responding back to me. 

I did not have libuiohook installed but I compiled it so now I do have it. (I have it located in /usr/local/lib/).

I tried it again after compiling it and the results are the same. OBS doesn't read the plugin in the .config path. It will only read it when I put input-overlay.so in /usr/lib64/obs-plugins/. But I still get the error of:

`error: os_dlopen(/usr//lib64/obs-plugins/input-overlay.so->/usr//lib64/obs-plugins/input-overlay.so): libuiohook.so.0: cannot open shared object file: No such file or directory

warning: Module '/usr//lib64/obs-plugins/input-overlay.so' not loaded
`
The solus tutorial does not seem to work for Fedora as OBS on Fedora cannot find the plugin on the .config folder (as I previously mentioned.) And Fedora does not have a repository for libuiohook so I had to compile it.

**Comment by reaply** [comment]
So, I tried moving the libuiohook.so.0 in various different folders:
```
1. /usr/.config/obs-studio/plugins/input-overlay
2. /usr/.config/obs-studio/plugins/input-overlay/plugin-linux
3. /usr/.config/obs-studio/plugins/input-overlay/plugin-linux/bin/64bit
4. /usr/local/lib
5. /usr/local/lib64
6. /usr/lib
7. /usr/lib64
```

And I tried the above paths while leaving input-overlay.so in:
```
1. /home/reaply/.config/obs-studio/plugins/input-overlay/plugin-linux/bin/64bit/
2. /usr/lib64/obs-plugins/
```

And as I said, OBS only reads the plugin from the /usr/lib64/obs-plugins/ path. So I'm quite confused as what's going wrong here.

**Comment by reaply** [comment]
Good news! I have gotten the plugin to finally load in OBS.

So, when you have to compile `libuiohook` from source it will create two syslink files named `libuiohook.so libuiohook.so.0` that link to `libuiohook.so.0.0.0` . These syslink files are completely broken once built (at least on Fedora) and can't actually link to `libuiohook.so.0.0.0` . So, as a work around, I had to use `mv libuiohook.so.0.0.0 libuiohook.so.0` and place it in `/usr/lib64/obs-plugins` Another problem that happens is that to compile `libuiohook` you are forced to run it as root because it tries to access root level folders. This creates a permission hell hole for the files for regular users as they cannot actually see these files. I had to login via su then do `chgrp mygroup libuiohook.so.0` so my normal user group could access this file. Additionally, you can do `chmod u+x libuiohook.so.0` .

So after a lot of trial and error and a ton of testing and getting to know how Linux works further, I was able to determine the error and I hope that anyone else who runs into my problem can find this thread (or added to the readme for known bugs for Fedora) and they can fix it themselves.

**Comment by univrsal** [comment]
I'll add it to the readme once I actually finish version 5 (or if I make another small release in between).

**Comment by Magicrafter13** [comment]
> Good news! I have gotten the plugin to finally load in OBS.
> 
> So, when you have to compile `libuiohook` from source it will create two syslink files named `libuiohook.so libuiohook.so.0` that link to `libuiohook.so.0.0.0` . These syslink files are completely broken once built (at least on Fedora) and can't actually link to `libuiohook.so.0.0.0` . So, as a work around, I had to use `mv libuiohook.so.0.0.0 libuiohook.so.0` and place it in `/usr/lib64/obs-plugins` Another problem that happens is that to compile `libuiohook` you are forced to run it as root because it tries to access root level folders. This creates a permission hell hole for the files for regular users as they cannot actually see these files. I had to login via su then do `chgrp mygroup libuiohook.so.0` so my normal user group could access this file. Additionally, you can do `chmod u+x libuiohook.so.0` .
> 
> So after a lot of trial and error and a ton of testing and getting to know how Linux works further, I was able to determine the error and I hope that anyone else who runs into my problem can find this thread (or added to the readme for known bugs for Fedora) and they can fix it themselves.

Granted this is almost 3 years old, but when I compiled libuiohook it actually only created `libuiohook.so.1.2.0` with sym-links named `libuiohook.so.1` (not .0) and `libuiohook.so`.

And, is there any known way to get this to work without placing something in `/usr/lib64/obs-plugins`? I would prefer to do as much as I can inside `$XDG_CONFIG_HOME/obs-studio/plugins`.
Also you state that you are forced to be root to compile libuiohook which is not (or at least no longer) true, it worked fine using the instructions in the README without any need for sudo.

To be fair however, I'm not on Fedora, not sure if that would make a difference or not.
Trying to do this on Manjaro.

Figured commenting here would be better than making a new issue, since I'm having the same problem of;
```
libuiohook.so.0: cannot open shared object file: No such file or directory
```
