### ISSUE TITLE
Gamepad display issue

### ISSUE THREAD

**Issue by skeith** [univrsal/input-overlay#49]
**Describe the bug**
Gamepad overlay display is doubled/overlapping

**To Reproduce**
Install input-overlay, add it to scene, use default preset

**Expected behavior**
Gamepad shown as included game-pad-preview.png

**Screenshots**
![image](https://user-images.githubusercontent.com/340284/44589753-f0912f80-a7eb-11e8-8758-bb3d4609dd48.png)

**Additional information:**
- Plugin version : 4.5
- Full OBS Studio log : https://gist.github.com/skeith/6fa12c1857c760afbe57f83db5619e3e

**Comment by univrsal** [comment]
hmm, this issue has occured before and I thought I fixed it, but I guess it's a little more persistent.
You'll have to give me some time for this

**Comment by skeith** [comment]
no worries

**Comment by univrsal** [comment]
I looked into the debug values logged in your log files and they do not match the ones I get when loading the gamepad overlay.
Can you put the attached *.dll into the 64bit plugin directory (usually C:\Program Files (x86)\obs-studio\obs-plugins\64bit) and try loading the overlay again? If it doesn't work please also attach the new log file.

**Comment by skeith** [comment]
I will check soon after work hours. I forgot to check it yesterday, sorry

**Comment by univrsal** [comment]
Huh, that was easier than expected. The fix should be included in the latest [release](https://github.com/univrsal/input-overlay/releases/tag/v4.7.4).
Thanks for helping me track that down
