### ISSUE TITLE
Function request of ↑ ↓ ← → key overlay display

### ISSUE THREAD

**Issue by yuya495** [univrsal/input-overlay#5]
Hello univrsal
I find it very useful to be able to display overlay ↑ ↓ ← → key on the keyboard
I am a poor English speaker in Japanese.
I am using Google translation
![xzxmbou](https://user-images.githubusercontent.com/8580180/30882361-a02592aa-a343-11e7-859b-ab465ef09508.jpg)

**Comment by yuya495** [comment]
My PC spec
OS Windows 7 Home Premium 64 bit (Service Pack 1)
RAM 24.0 GB
CPU Intel Core i7-4770 3.40 GHz
GPU Nvidia GeForce GTX 760
![amarec 20170927-063726](https://user-images.githubusercontent.com/8580180/30885470-62e6154e-a34e-11e7-84c3-a7ace2e6ee52.PNG)

**Comment by yuya495** [comment]
![image](https://user-images.githubusercontent.com/8580180/30885492-797d21bc-a34e-11e7-8aa2-6e61aeceb14a.png)

**Comment by yuya495** [comment]
Help me
How can I display the up / down / left / right keys

**Comment by univrsal** [comment]
I'm on it, give me a little time I'll make a new layout

**Comment by univrsal** [comment]
![qwerty-arrows-preview](https://user-images.githubusercontent.com/8353672/30925180-49252236-a3b1-11e7-9b40-88eb5d7898b9.png)
Here you go!  You can download it [here](https://github.com/univrsal/input-overlay/blob/master/presets/qwerty-arrows.zip?raw=true). 
If you have any issues just tell me!

**Comment by h3oCharles** [comment]
hey there, at the time of writing this, the "qwerty-arrows" preset is gone, is it possible to reupload it?

**Comment by univrsal** [comment]
It doesn't exist for version 5.0 as far as I know

**Comment by h3oCharles** [comment]
is recreating it for 5.0 at least possible? if so, when can I get an older version of that preset so I can get at least the graphical part of it?
