### ISSUE TITLE
Need help - Can't get key to appear

### ISSUE THREAD

**Issue by GreenNekoHaunt** [univrsal/input-overlay#52]
I'm trying to make a layout with single keys:

> F1 F2 F3 F4 F5
> ^ 1 2 3 4 5
>     Q W E R
>     A S D F V
> SHIFT SPACE

with every key being 1x1 except shift 2x1 and space 3x1.

However with my current setup shift doesn't appear at all the rest works as it should.
My graphic files contains 3 (or 6) rows of keys with 10 keys per row the first 2 (or 4) rows contain the single keys the 3rd (or 5th and 6th) contain the shift and space key.

[Ini @ Pastebin](https://pastebin.com/Sa0b3cTt)
[Graphic file and result @ imgur](https://imgur.com/a/AE6wwVK)

Any idea what I did wrong?

**Comment by univrsal** [comment]
Looks like a value is wrapping around. Each element that is wider than one gets a x-offset, like the spacebar here (You can see that it is offset a little to the right):

![image](https://user-images.githubusercontent.com/8353672/44957987-b4d82300-aed9-11e8-970f-986eddd39303.png)
Somehow this value is 32758, which obviously moves the element offscreen.

**Comment by univrsal** [comment]
Ok, so this offset calculation does not work, with the negative base offset in key_space_h.
It works now, there'll be a release for 4.7.x later. Also: You might want to fix the cropping on your texture it looks quite a bit off.
![image](https://user-images.githubusercontent.com/8353672/44958444-b1946580-aee0-11e8-98a7-056cb1c209ac.png)

**Comment by GreenNekoHaunt** [comment]
Okay using the newest version it now looks like this:

![image](https://user-images.githubusercontent.com/3185588/45049913-4bdedf80-b080-11e8-85ac-fc43e46c0d1c.png)

Shouldn't the offset between shift and space be equal to the offset between the other keys?

About the cropping.. each of my keys is 157x128 as defined in the .ini with a 1px border and 1px space between each key. The shift key is 334x128 (2 * 157) and the space key is 491x128 (3 * 157).

I used the wasd-minimal as the base for this.

**Comment by univrsal** [comment]
You need a 1 pixel border around the entire texture and a 3 pixel gap in between each key.
Try doing that and then give me the texture again so I can take a look the spacing for space and shift.
Try uploading the actual .png so I get the transparency

**Comment by GreenNekoHaunt** [comment]
![keys](https://user-images.githubusercontent.com/3185588/45057949-72f4db80-b097-11e8-9c71-48b3426e18c0.png)

**Comment by univrsal** [comment]
Okay, I guess there's still something wrong with the calculation.
With buttons that span over multiple columns, you'll have to take into account that the offset is -20.
So shift for example would have to be 294 (=2 * 157 - (1 * (-20)) and space would have to be 431 (=3 * 157 - (2 * (-20)).
So a key which has the width of n columns would have this formula ```n * 157 - ((n - 1) * (-20)``` for its width.
Anyways I fixed the calculations and it works now (Don't mind the additional shift key):
![image](https://user-images.githubusercontent.com/8353672/45091680-82196f00-b113-11e8-872c-b9306ca5bb18.png)
[Here](https://w.wew.wtf/docewa.png)'s the texture I used (The gaps are still a little off, but I'll leave that up to you)
Install v4.7.4 and see if it works for you

**Comment by GreenNekoHaunt** [comment]
Installed v4.7.4. Using debug graphic I made:

![image](https://user-images.githubusercontent.com/3185588/45185409-5f2dae80-b22a-11e8-94d4-36aa2b2c7a17.png)

![image](https://user-images.githubusercontent.com/3185588/45185429-6d7bca80-b22a-11e8-9ea6-229bf3a0c98f.png)

**Comment by GreenNekoHaunt** [comment]
Finally, now it should be fine from the positioning in the .png file. Now, I've tested v4.7.4 and it's not working like it does for you, did you change the .ini file?

![image](https://user-images.githubusercontent.com/3185588/45186347-6efac200-b22d-11e8-9c1f-7fe675c4242a.png)

![image](https://user-images.githubusercontent.com/3185588/45186351-74f0a300-b22d-11e8-8e66-3e9c4c8c27d7.png)

Result without debugging:
![image](https://user-images.githubusercontent.com/3185588/45186386-9a7dac80-b22d-11e8-8412-ce5a9bdbe778.png)

**Comment by univrsal** [comment]
Did you read what I wrote? You need to adjust the width of the space and shift key to account for -20 pixel space in between buttons. I even attached a texture file with the correct width, try and use it and see if it works

**Comment by GreenNekoHaunt** [comment]
Ah, sorry. I see.

That's kinda inconvenient/complicated/not intuitive.. You don't take the -20 pixels into account on 1x1 keys. (file says they're 157x128 and they're 157x128 in the wasd-minimalist and in my file).
So why do you have to take it into account on longer ones in the graphics file?
If one is 2 times as long it should be 314x128 in the file. The space which is supposed to be 3 times as long should be 471x128.

When I change the offset on 1x1 keys I don't have to edit the .png file.
When I change the offset and have keys with a multiplier I need to edit the .png file and correct it to take the new offset into consideration?

**Comment by univrsal** [comment]
If you don't take the gap into account, your shift and space keys will take up more space than the 1x1 keys:

![docewa](https://user-images.githubusercontent.com/8353672/45253318-99e83180-b365-11e8-9ff1-4b24caa1f6e8.jpg)
Does it make sense now?

**Comment by GreenNekoHaunt** [comment]
Ah, then good luck to you sir and thanks for the good support!

I'll be waiting in the shadows until I notice something else.
