### ISSUE TITLE
No Plugin?

### ISSUE THREAD

**Issue by GetTheHellOut** [univrsal/input-overlay#53]
I downloaded the Source Code because the actual input overlay download isn't there. I only see Source Code as a zip file and a tar... . Anyways I see the source code, but there's no plugin in it, so I cant use it;.

**Comment by Kiloutre** [comment]
You can see the releases on the following page

https://github.com/univrsal/input-overlay/releases

**Comment by univrsal** [comment]
As stated before, the binaries are under the releases tab. Make sure to download the correct file:
![image](https://user-images.githubusercontent.com/8353672/45295057-b5864000-b4fd-11e8-95d1-e0e55559ae80.png)
