### ISSUE TITLE
Overlay doesn't detect key presses in Tekken 7

### ISSUE THREAD

**Issue by Kiloutre** [univrsal/input-overlay#54]
I made an overlay with works perfectly well but the moment i give focus to the Tekken 7 window, the overlay doesn't detect key presses anymore, until give focus to another window

Here's the config file if needed. I don't use the mouse overlay, gamepad overlay nor key history.

https://pastebin.com/u6nn68qZ

**Comment by univrsal** [comment]
Have you tried running OBS studio as administrator?

**Comment by Kiloutre** [comment]
Running OBS as administrator does seem to make it work, thank you

**Comment by univrsal** [comment]
I don't know why, but some games have that issue
