### ISSUE TITLE
Icon misplacement

### ISSUE THREAD

**Issue by szymex73** [univrsal/input-overlay#58]
**Describe the bug**
When I try to load the `qwerty` preset from the release zip it doesn't show up properly. Same with some of the presets like `wasd-full`, `qwerty-arrows`, `wasd-extended`. Some of the key icons are misplaced

**To Reproduce**
OS: Linux Mint 18.2 'Sonya' 64bit
Latest libuiohook (1.1 branch)
OBS version: 22.0.0

Load plugin and load freshly compiled libuiohook
Create a new scene, add Input Overlay, load `qwerty` icons and .ini file.

**Expected behavior**
The keys are misplaced and on some presets there are some weird borders

**Screenshots**
`qwerty`
![screensshot_2018-10-14_18-49-58](https://user-images.githubusercontent.com/5494832/46919651-b28ddc00-cfe2-11e8-963d-13f76f48a16b.png)
`wasd-full`
![screensshot_2018-10-14_18-54-46](https://user-images.githubusercontent.com/5494832/46919653-bae61700-cfe2-11e8-8644-0b5833f0fd49.png)
`wasd-extended-numeric`
![screensshot_2018-10-14_18-55-57](https://user-images.githubusercontent.com/5494832/46919660-d4875e80-cfe2-11e8-976f-e1d912d46c6c.png)

**Additional information:**
- Plugin version: 4.7.4b
- Full OBS Studio log: https://gist.github.com/szymex73/2e0f8e1de2fdd40bf83dbde46b8b0428

**Additional context**
No additional info. If anything is needed just tell below

**Comment by szymex73** [comment]
The mouse overlay errors are because of the basic mouse overlay preset being on with the additional mouse overlay option on (the one that tracks the movement)

**Comment by univrsal** [comment]
I think I'm fairly sure what the issue is. I fixed this issue on windows, but haven't rebuild the linux version because I'm lazy. I give me a bit and I'll compile it.

**Comment by szymex73** [comment]
It's not a problem to compile it myself so I can check if the error still persists on the newer version

**Comment by univrsal** [comment]
I'm not sure whether or not the legacy branch compiles without issues on linux right now, but you can try

**Comment by univrsal** [comment]
Okay so I build the master branch on linux. It's mostly stable aside from some minor bugs (You can't select the gamepad id).
Can you try this binary and see if it'll work? Keep in mind that you'll have to use the presets from github, you can get them [here](https://github.com/univrsal/input-overlay/tree/master/presets).

[input-overlay-v5.zip](https://github.com/univrsal/input-overlay/files/2476856/input-overlay-v5.zip)

**Comment by szymex73** [comment]
It says that
```
error: os_dlopen(/usr//lib/obs-plugins/input-overlay.so->/usr//lib/obs-plugins/input-overlay.so): /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.11' not found (required by /usr//lib/obs-plugins/input-overlay.so)

**Comment by univrsal** [comment]
which version of qt is it? Also looking at the output of ```readelf -d input-overlay.so``` it shows me that it needs libQt5Widget.so and libQt5Gui.so. Can you see if any of these files are installed?
You might have to compile it yourself, since I compile it on Arch linux which might not be compatible

**Comment by szymex73** [comment]
```
~   6s
❯ file /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5: symbolic link to libQt5Core.so.5.5.1
                                                                                          
~   
❯ file /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: symbolic link to libQt5Gui.so.5.5.1
```
I think I know why it isn't loading. I have 5.5.1 and not 5.11

**Comment by szymex73** [comment]
could you help me with that? I can't find anything about that in the docs or anything

**Comment by univrsal** [comment]
sure, should I help you over github or can I contact you over any other methods? Mine are linked on my [website](https://univrsal.github.io/contact/).

**Comment by szymex73** [comment]
I think discord would be the easiest for me since compiling isn't exactly the issue topic
