### ISSUE TITLE
TAB, R and F key not showing

### ISSUE THREAD

**Issue by Censtudios** [univrsal/input-overlay#6]
So I'm using the WASD preset and import them exactly like in the vimeo tutorial video, but the TAB, R and F keys don't show (they are invisible).

It appears that the 2nd row of keys in the preset texture isn't being shown (it does show if I import the texture without the .ini ofc). I think this is the case ever since I realized that all the keys that DO show are in the 1st row of keys, and the ones not showing in the 2nd row.

**Comment by Censtudios** [comment]
My bad, I misread the title of one of the closed issues.
Apparently you already answered it here https://github.com/univrsal/input-overlay/issues/4 thanks

**Comment by univrsal** [comment]
yeah it's kinda annoying. I'll try to fix that issue soon™
