### ISSUE TITLE
mouse preset rmb/mmb mixup

### ISSUE THREAD

**Issue by networkjanitor** [univrsal/input-overlay#60]
**Description**

When pressing the mouse-rmb the overlay-mmb lights up. When pressing the mouse-mmb nothing lights up. overlay-rmb does not light up at all. When scrolling with mouse-mmb, the overlay-mmb are lit up correctly (up/down).

**Additional information:**
- plugin version: from https://github.com/univrsal/input-overlay/issues/58#issuecomment-429660046
- libuiohook version: 1.0.3
- operating system: linux/arch

I couldn't find any documentation regarding the v5 preset config file format (and frankly my c++ is pretty limited), but at least by experimenting in the .ini file I couldn't switch the buttons.

- Setting `0_rmb_code=60675` instead of `0_rmb_code=60674` makes the overlay-rmb react to mouse-mmb click. 
- Setting `0_mmb_code` to anything has no effect, probably because of `0_mmb_type=2` I would assume.
 - Switching the order of the keys has no effect.
 - The same problem as with https://github.com/univrsal/input-overlay/issues/42 happend here as well, however this could be fixed by exchanging the two codes from the smbs.

**Comment by univrsal** [comment]
Yeah I know about this issue, libuiohook on linux seems to be reporting different keycodes than on windows. I had a special case for that but I guess I accidentally removed it while working on version 5. I'll put it back in

**Comment by univrsal** [comment]
should be fixed again with 6c04cf7
