### ISSUE TITLE
All keys press simultaneously on overlay

### ISSUE THREAD

**Issue by porcuspine** [univrsal/input-overlay#63]
Every key on my custom overlay except the spacebar registers as pressed at the same time when I push any key, click either mouse button, or scroll the scroll wheel. The space button only registers as pressed when I push the "d" key.

Here's the text from my .ini file (I had to upload a .txt for github, but it's an .ini in OBS):
[mhaoj.txt](https://github.com/univrsal/input-overlay/files/2612776/mhaoj.txt)

Overlay image:
![mhaoj](https://user-images.githubusercontent.com/45323448/48974846-2dee9e80-f021-11e8-98b7-1879fb837a95.png)

**Screenshots**
How it looks in OBS
![capture](https://user-images.githubusercontent.com/45323448/48974866-8cb41800-f021-11e8-98d2-2f0b6dd1c5d5.PNG)

**Additional information:**
Plugin is version 4.7.4

Thank you so much for the work you put in to this plugin! I will continue to work on this myself as I don't want to throw this onto your shoulders, and I'll let you know if I solve it. I suspect it has something to do with the space key, since it's only reacting to the D button.

**Comment by porcuspine** [comment]
I fixed it by putting the hexadecimal code for every key! Honestly should have tried this before submitting a report... sorry.

Here's the new .ini text, just in case it's wanted:
[mhaoj.txt](https://github.com/univrsal/input-overlay/files/2612792/mhaoj.txt)

**Comment by univrsal** [comment]
Yeah, the config file is confusing. I'm aiming to fix that but I keep procrastinating
