### ISSUE TITLE
Xbox One controller support

### ISSUE THREAD

**Issue by IvanDoomer** [univrsal/input-overlay#64]
We would like to have a Xbox One controller full support, considering that it's sully integrated to Windows 10 and all new Windows 10/Play Anywhere games

Thanks

**Comment by IvanDoomer** [comment]
> Did you try to use the gamepad preset, it works with an xbox 360 controller and therefore should work with an xbox one controller.

Yes, I tried, it does not work :(

**Comment by univrsal** [comment]
Well I can't test it since I don't have an xbox one controller, sorry

**Comment by univrsal** [comment]
I'll just close this for now

**Comment by IvanDoomer** [comment]
Sorry for the late response, yes, the [v5](https://github.com/univrsal/input-overlay/files/2660858/input-overlay.v5.zip) works fine
