### ISSUE TITLE
Sony Dualshock 4 controller

### ISSUE THREAD

**Issue by jakegrabowski** [univrsal/input-overlay#66]
**Feature request**
I have dualshock 4 controller and it seem there is no support for it

**Describe the solution you'd like**
Plug and play solution - I choose DS4 preset and I have my controller overlay

Thanks

**Comment by univrsal** [comment]
I don't think there's a way to query ds4 inputs directly. You'll have to install something like ds4windows or ds4tool, which will emulate an xbox controller. Also since I do not own a Dualshock 4 controller so even if there was a way to natively support it, I couldn't test it
