### ISSUE TITLE
Unable to define backslash "\"

### ISSUE THREAD

**Issue by NNNenov** [univrsal/input-overlay#67]
Hi there, I've made a names.ini file with the content from the example names.ini file, but added two extra values in the top two rows:
"
2_0x002B=\_backslash
2_0x001E=A_custom
2_0x0034=.
2_0x0033=,
2_0x001B=]
2_0x001A=[
"

"A" works when I press it, I see "A_Custom", but "\" doesn't work, I'm not sure why. I used the code from 
/libuiohook/include/uiohook.h

which contains this:
#define VC_BACK_SLASH								0x002B	// '\'

Not sure why its not working..
Thanks!

**Comment by NNNenov** [comment]
Apologies, I just added a new line at the top of the text file and now it works. I guess if the code is on the very first row, it is ignored?

**Comment by univrsal** [comment]
Yeah the config loader expects the first line to be a comment. I don't know why I did that, sorry for the inconvenience

**Comment by NNNenov** [comment]
no problem, thanks for the great plugin!
