### ISSUE TITLE
Documentation key name config of input history

### ISSUE THREAD

**Issue by futal** [univrsal/input-overlay#68]
I did not find documentation for the key name config file used by input history.

Could you provide some short an example of the expected .ini file?

Cheers

**Comment by univrsal** [comment]
Here you go:
```
# The first line has to be a comment, since it's ignored by the config loader
# The syntax is: '2_' + key code + '=' + keyname
# 0x001E is the keyname for 'A':
2_0x001E=new name for a
2_0x0020=new name for d
2_0x001F=new name for s
2_0x0011=new name for w
```
If "use fallback names" is not checked in the source properties, any keys not mentioned in the loaded config will not be displayed

**Comment by futal** [comment]
Thanks a lot.

I have tried to find key codes for all the keys on my keyboard. I went up to 0xFF but I did not find the codes for all the keys.

I am missing: L-WIN, LEFT-CTRL+R-ALT (AltGr), R-CONTROL, UP, DOWN, LEFT, RIGHT, PRINT, DIVIDE (numpad /); and the following keys which do not even have default names: PageUp, PageDown, Del, Ins, \ (between LEFT-SHIFT and Z).

If the .ini file is not well formatted (for example a key code without a = after), it hangs or crashes OBS Studio.

Here is the template I am using:

```
# The first line has to be a comment, since it's ignored by the config loader

2_0x0001=ESC
2_0x0002=1
2_0x0003=2
2_0x0004=3
2_0x0005=4
2_0x0006=5
2_0x0007=6
2_0x0008=7
2_0x0009=8
2_0x000A=9
2_0x000B=0
2_0x000C=MINUS
2_0x000D=EQUAL
2_0x000E=BACKSPACE
2_0x000F=TAB
2_0x0010=Q
2_0x0011=W
2_0x0012=E
2_0x0013=R
2_0x0014=T
2_0x0015=Y
2_0x0016=U
2_0x0017=I
2_0x0018=O
2_0x0019=P
2_0x001A=[
2_0x001B=]
2_0x001C=ENTER
2_0x001D=LEFT CTRL
2_0x001E=A
2_0x001F=S
2_0x0020=D
2_0x0021=F
2_0x0022=G
2_0x0023=H
2_0x0024=J
2_0x0025=K
2_0x0026=L
2_0x0027=;
2_0x0028='
2_0x0029=` (LEFT OF 1)
2_0x002A=LEFT SHIFT
2_0x002B=\
2_0x002C=Z
2_0x002D=X
2_0x002E=C
2_0x002F=V
2_0x0030=B
2_0x0031=N
2_0x0032=M
2_0x0033=,
2_0x0034=.
2_0x0035=/
2_0x0036=RIGHT SHIFT
2_0x0037=NUMPAD *
2_0x0038=ALT
2_0x0039=SPACE
2_0x003A=CAP LOCK
2_0x003B=F1
2_0x003C=F2
2_0x003D=F3
2_0x003E=F4
2_0x003F=F5
2_0x0040=F6
2_0x0041=F7
2_0x0042=F8
2_0x0043=F9
2_0x0044=F10
2_0x0045=NUM LOCK
2_0x0047=NUMPAD 7
2_0x0048=NUMPAD 8
2_0x0049=NUMPAD 9
2_0x004A=NUMPAD -
2_0x004B=NUMPAD 4
2_0x004C=NUMPAD 5
2_0x004D=NUMPAD 6
2_0x004E=NUMPAD +
2_0x004F=NUMPAD 1
2_0x0050=NUMPAD 2
2_0x0051=NUMPAD 3
2_0x0052=NUMPAD 0
2_0x0053=NUMPAD .
2_0x0057=F11
2_0x0058=F12
```

**Comment by futal** [comment]
I found the codes for the remaining keys. Yet for an unknown reason, it does not work when I configure them in the ini file.

The key codes are actually called scancodes. See [article on Wikipedia](https://en.wikipedia.org/wiki/Scancode) and [Microsoft Keyboard Scan Code Specification]( Microsoft Keyboard Scan Code Specification). You can also find the scancodes for a specific keyboard with [Sharpkeys](https://github.com/randyrants/sharpkeys).

**Comment by univrsal** [comment]
The key codes are all listed in [this](https://github.com/univrsal/input-overlay/blob/master/libuiohook/include/uiohook.h#L145) file or over the tool "demo_hook_async.exe", which is inside the release zip archive under the "util" folder:
![2019-02-20_17-42-33](https://user-images.githubusercontent.com/8353672/53108329-20b95100-3537-11e9-87ab-3966c2ffaef7.png)
The keycodes are defined by libuiohook, which defines its own keycodes. Some of them might be the same as the ones defined by Microsoft, but i wouldn't bet on it.

Also you don't have to redefine each key in the config file. You can just define the ones that don't have a name or a name you want changed. Any key that's not defined in the config file will get its predefined  name.

**Comment by futal** [comment]
Thanks a lot. I have been able to display the missing keys. The goal to define names for most of the keys is that I want to hide a few of them while they had default names and a few keys had no names (because I do not use a QWERTY keyboard).
