### ISSUE TITLE
Crash with qwerty.arrows on linux.

### ISSUE THREAD

**Issue by callimero** [univrsal/input-overlay#69]
Crash with querty.arrows on linux.

error: Loading key icons from /home/cw/.config/obs-studio/presets/qwerty-arrows/qwerty-arrows.ini failed. No ccl data!

Always if I try to use icons for input history.

**Additional information:**
- Plugin version
latest
- Full OBS Studio log
22:30:49.611: CPU Name: Intel(R) Core(TM)2 Quad  CPU   Q9450  @ 2.66GHz
22:30:49.611: CPU Speed: 2138.820MHz
22:30:49.611: Physical Cores: 4, Logical Cores: 4
22:30:49.611: Physical Memory: 7974MB Total, 5003MB Free
22:30:49.611: Kernel Version: Linux 4.20.11-1-MANJARO
22:30:49.611: Distribution: "Manjaro Linux" Unknown
22:30:49.611: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.3
22:30:49.612: Portable mode: false
22:30:49.662: OBS 22.0.2-3 (linux)
22:30:49.662: ---------------------------------
22:30:49.662: ---------------------------------
22:30:49.662: audio settings reset:
22:30:49.662: 	samples per sec: 44100
22:30:49.662: 	speakers:        2
22:30:49.673: ---------------------------------
22:30:49.673: Initializing OpenGL...
22:30:49.781: Loading up OpenGL on adapter NVIDIA Corporation GeForce GTX 1050 Ti/PCIe/SSE2
22:30:49.781: OpenGL loaded successfully, version 3.2.0 NVIDIA 415.27, shading language 1.50 NVIDIA via Cg compiler
22:30:49.797: ---------------------------------
22:30:49.797: video settings reset:
22:30:49.797: 	base resolution:   1920x1080
22:30:49.797: 	output resolution: 1920x1080
22:30:49.797: 	downscale filter:  Bilinear
22:30:49.797: 	fps:               30/1
22:30:49.797: 	format:            NV12
22:30:49.797: 	YUV mode:          601/Partial
22:30:49.798: Audio monitoring device:
22:30:49.798: 	name: Default
22:30:49.798: 	id: default
22:30:49.798: ---------------------------------
22:30:51.050: No blackmagic support
22:30:51.067: NVENC supported
22:30:51.082: VLC found, VLC video source enabled
22:30:51.082: ---------------------------------
22:30:51.082:   Loaded Modules:
22:30:51.082:     vlc-video.so
22:30:51.082:     text-freetype2.so
22:30:51.082:     rtmp-services.so
22:30:51.082:     obs-x264.so
22:30:51.082:     obs-transitions.so
22:30:51.082:     obs-outputs.so
22:30:51.082:     obs-libfdk.so
22:30:51.082:     obs-filters.so
22:30:51.082:     obs-ffmpeg.so
22:30:51.082:     linux-v4l2.so
22:30:51.082:     linux-pulseaudio.so
22:30:51.082:     linux-jack.so
22:30:51.082:     linux-decklink.so
22:30:51.082:     linux-capture.so
22:30:51.082:     linux-alsa.so
22:30:51.082:     input-overlay.so
22:30:51.082:     image-source.so
22:30:51.082:     frontend-tools.so
22:30:51.082: ---------------------------------
22:30:51.082: ==== Startup complete ===============================================
22:30:51.083: Service '' not found
22:30:51.086: All scene data cleared
22:30:51.086: ------------------------------------------------
22:30:51.090: pulse-input: Server name: 'pulseaudio 12.2'
22:30:51.090: pulse-input: Audio format: s16le, 48000 Hz, 2 channels
22:30:51.091: pulse-input: Started recording from 'alsa_output.pci-0000_00_1b.0.analog-stereo.monitor'
22:30:51.091: pulse-input: Server name: 'pulseaudio 12.2'
22:30:51.091: pulse-input: Audio format: s16le, 44100 Hz, 1 channels
22:30:51.091: pulse-input: Started recording from 'alsa_input.usb-MICE_MICROPHONE_USB_MICROPHONE_201308-00.analog-mono'
22:30:51.218: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
22:30:51.218: 	title: Blender
22:30:51.218: 	class: Blender
22:30:51.234: [ccl] Encountered errors when loading '/home/cw/.config/obs-studio/presets/mouse-alternative/mouse-2-reverse.ini':
22:30:51.234:  [ERROR] Cannot get bool value of 'show_mouse_movement'. Doesn't exist or type mismatch
22:30:51.234:  [ERROR] Cannot get bool value of 'use_arrow'. Doesn't exist or type mismatch
22:30:51.234:  [ERROR] Cannot get int value of 'mouse_field_radius'. Doesn't exist or type mismatch
22:30:51.234:  [ERROR] Value with id 'mouse_field_radius' does not exist
22:30:51.234:  [ERROR] Value with id 'show_mouse_movement' does not exist
22:30:51.234:  [ERROR] Value with id 'use_arrow' does not exist
22:30:51.234:  1 more error(s) reported
22:30:51.234: Switched to scene 'Scene'
22:30:51.234: ------------------------------------------------
22:30:51.234: Loaded scenes:
22:30:51.234: - scene 'Scene':
22:30:51.239:     - source: 'Window Capture (Xcomposite)' (xcomposite_input)
22:30:51.239:     - source: 'InputHistory' (input-history)
22:30:51.239:     - source: 'InputOverlay' (input-overlay)
22:30:51.239: ------------------------------------------------
22:30:51.628: adding 23 milliseconds of audio buffering, total audio buffering is now 23 milliseconds
22:30:57.693: [ccl] Encountered errors when loading '/home/cw/.config/obs-studio/presets/mouse-alternative/mouse-2-reverse.ini':
22:30:57.693:  [ERROR] Cannot get bool value of 'show_mouse_movement'. Doesn't exist or type mismatch
22:30:57.693:  [ERROR] Cannot get bool value of 'use_arrow'. Doesn't exist or type mismatch
22:30:57.693:  [ERROR] Cannot get int value of 'mouse_field_radius'. Doesn't exist or type mismatch
22:30:57.693:  [ERROR] Value with id 'mouse_field_radius' does not exist
22:30:57.693:  [ERROR] Value with id 'show_mouse_movement' does not exist
22:30:57.693:  [ERROR] Value with id 'use_arrow' does not exist
22:30:57.693:  1 more error(s) reported
22:31:18.412: Loading key icons from /home/cw/.config/obs-studio/presets/qwerty/qwery-arrows.ini failed. No ccl data!

**Additional context**

Linux installation is quite obscure. Maybe I messed something up....

**Comment by callimero** [comment]
I now tried a portable version (compiled myself like in the wiki).  Runs well without input-overlay.
Tried to adapt the install instructions, put the file where I think they belong:

12:00:20.514: Command Line Arguments: --verbose --unfiltered_log
12:00:20.530: CPU Name: Intel(R) Core(TM)2 Quad  CPU   Q9450  @ 2.66GHz
12:00:20.531: CPU Speed: 2338.299MHz
12:00:20.531: Physical Cores: 4, Logical Cores: 4
12:00:20.531: Physical Memory: 7974MB Total, 4031MB Free
12:00:20.531: Kernel Version: Linux 4.20.11-1-MANJARO
12:00:20.531: Distribution: "Manjaro Linux" Unknown
12:00:20.531: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.3
12:00:20.532: found alternate keycode 218 for OBS_KEY_PRINT which already has keycode 107
12:00:20.533: Portable mode: false
12:00:20.592: OBS 23.0.1-9-g0f8c405e (linux)
12:00:20.592: ---------------------------------
12:00:20.592: ---------------------------------
12:00:20.592: audio settings reset:
12:00:20.592: 	samples per sec: 44100
12:00:20.592: 	speakers:        2
12:00:20.603: ---------------------------------
12:00:20.603: Initializing OpenGL...
12:00:20.697: Loading up OpenGL on adapter NVIDIA Corporation GeForce GTX 1050 Ti/PCIe/SSE2
12:00:20.697: OpenGL loaded successfully, version 3.2.0 NVIDIA 415.27, shading language 1.50 NVIDIA via Cg compiler
12:00:20.698: convert_sampler_info: 1 <= max_anisotropy <= 16 violated, selected: 0, set: 1
12:00:20.699: convert_sampler_info: 1 <= max_anisotropy <= 16 violated, selected: 0, set: 1
12:00:20.699: convert_sampler_info: 1 <= max_anisotropy <= 16 violated, selected: 0, set: 1
12:00:20.699: convert_sampler_info: 1 <= max_anisotropy <= 16 violated, selected: 0, set: 1
12:00:20.700: convert_sampler_info: 1 <= max_anisotropy <= 16 violated, selected: 0, set: 1
12:00:20.700: convert_sampler_info: 1 <= max_anisotropy <= 16 violated, selected: 0, set: 1
12:00:20.702: convert_sampler_info: 1 <= max_anisotropy <= 16 violated, selected: 0, set: 1
12:00:20.702: convert_sampler_info: 1 <= max_anisotropy <= 16 violated, selected: 0, set: 1
12:00:20.702: convert_sampler_info: 1 <= max_anisotropy <= 16 violated, selected: 0, set: 1
12:00:20.702: convert_sampler_info: 1 <= max_anisotropy <= 16 violated, selected: 0, set: 1
12:00:20.703: convert_sampler_info: 1 <= max_anisotropy <= 16 violated, selected: 0, set: 1
12:00:20.703: convert_sampler_info: 1 <= max_anisotropy <= 16 violated, selected: 0, set: 1
12:00:20.703: convert_sampler_info: 1 <= max_anisotropy <= 16 violated, selected: 0, set: 1
12:00:20.703: convert_sampler_info: 1 <= max_anisotropy <= 16 violated, selected: 0, set: 1
12:00:20.705: convert_sampler_info: 1 <= max_anisotropy <= 16 violated, selected: 0, set: 1
12:00:20.705: convert_sampler_info: 1 <= max_anisotropy <= 16 violated, selected: 0, set: 1
12:00:20.705: convert_sampler_info: 1 <= max_anisotropy <= 16 violated, selected: 0, set: 1
12:00:20.707: convert_sampler_info: 1 <= max_anisotropy <= 16 violated, selected: 0, set: 1
12:00:20.707: convert_sampler_info: 1 <= max_anisotropy <= 16 violated, selected: 0, set: 1
12:00:20.708: convert_sampler_info: 1 <= max_anisotropy <= 16 violated, selected: 0, set: 1
12:00:20.708: convert_sampler_info: 1 <= max_anisotropy <= 16 violated, selected: 0, set: 1
12:00:20.708: convert_sampler_info: 1 <= max_anisotropy <= 16 violated, selected: 0, set: 1
12:00:20.709: convert_sampler_info: 1 <= max_anisotropy <= 16 violated, selected: 0, set: 1
12:00:20.709: convert_sampler_info: 1 <= max_anisotropy <= 16 violated, selected: 0, set: 1
12:00:20.709: ---------------------------------
12:00:20.709: video settings reset:
12:00:20.709: 	base resolution:   1920x1080
12:00:20.709: 	output resolution: 1920x1080
12:00:20.709: 	downscale filter:  Bicubic
12:00:20.709: 	fps:               30/1
12:00:20.709: 	format:            NV12
12:00:20.709: 	YUV mode:          601/Partial
12:00:20.712: NV12 texture support not available
12:00:20.713: Audio monitoring device:
12:00:20.713: 	name: Default
12:00:20.713: 	id: default
12:00:20.713: ---------------------------------
12:00:20.717: ---------------------------------
12:00:20.718: Loading module: decklink-ouput-ui.so
12:00:20.734: ---------------------------------
12:00:20.736: Loading module: frontend-tools.so
12:00:20.747: ---------------------------------
12:00:20.748: Loading module: image-source.so
12:00:20.748: ---------------------------------
12:00:20.768: Loading module: input-overlay.so
12:00:20.773: [input-overlay] hook_enable [383]: Thread Result: (0).
12:00:20.773: 

So input overlay is loaded at last. No error not finding a locale. But here it stops...

**Comment by univrsal** [comment]
I don't know if the plugin works with obs version 23. Does it just crash? Do you have a crash report?

**Comment by callimero** [comment]
Ok, No crash it just sits there as shown in the log. Need to CTRL-C or Kill.

So it is V22? And the V5.0 you are working on? For now I use key-monitor (external programm).

**Comment by univrsal** [comment]
version 5 isn't done yet. I also haven't tested input-overlay with the new obs studio version, so you'll have to give me some time

**Comment by univrsal** [comment]
It's been a while and I've refreshed the linux build for the plugin, so if you're still interested you could try out the latest release. I'll close this for now and if you still have issues just comment and I'll see what I can do
