### ISSUE TITLE
No Input entry in the menu

### ISSUE THREAD

**Issue by Maxiride** [univrsal/input-overlay#7]
After following the installation video, I reloaded OBS but still can't see the new entry in the sources menu.

Is there anything I could provide for debugging?

EDIT:
Only the 64bit version doesn't show the new menu entry. The 32bit one works!

**Comment by univrsal** [comment]
hmm I guess the 64bit version wasn't installed correctly?
you can try running this in a commandline (Windows + R, then enter "cmd" and hit enter):
```
if exist "%programfiles% (x86)\obs-studio\obs-plugins\64bit\input-overlay.dll" ( echo 1 ) else ( echo 0 )
```
and see if it returns 1 or just check manually if the file input-overlay.dll exists at the path above

**Comment by Maxiride** [comment]
The 64bit version of OBS is installed correctly, it's the one that I use
normally. The input overlay dll is also present into the directory.

Il gio 23 nov 2017, 4:36 PM Alex <notifications@github.com> ha scritto:

**Comment by univrsal** [comment]
Hmm, that's rather strange since it works just fine for me even after reinstalling obs and the latest version of the plugin
What version of OBS Studio are you using and are you using any other plugins?

**Comment by univrsal** [comment]
I'll just close this issue for now until I get more info
