### ISSUE TITLE
Mouse and Keyboard .ini and .png not inside obs-studio folders

### ISSUE THREAD

**Issue by microverte** [univrsal/input-overlay#70]
After following all the steps if installing the input overlay (latest version of obs studio and the input overlay) the actual overlay images are not within any of the obs studio folders. I have tried re-installing the input overlay many times but it will not show up.
![why2](https://user-images.githubusercontent.com/48168244/53690148-2fb3b680-3d22-11e9-9a9e-4dbbc189e715.png)
![why](https://user-images.githubusercontent.com/48168244/53690149-317d7a00-3d22-11e9-8e2f-a1a91ae92e05.png)

**Comment by univrsal** [comment]
the overlays are inside the "preset" folder in the zip file:
![image](https://i.imgur.com/TM8Bo4c.png)
