### ISSUE TITLE
Capture from specific window/process

### ISSUE THREAD

**Issue by ZXGuesser** [univrsal/input-overlay#71]
Would it be possible/practical to have an option to only capture keypresses when a designated window has focus? I'm thinking to prevent things showing up when tabbing out of the window and typing in another off-stream.

**Comment by univrsal** [comment]
Would definitely be possible. I added it to the todo list

**Comment by univrsal** [comment]
![image](https://user-images.githubusercontent.com/8353672/55628727-ff3bbe00-57a0-11e9-9231-3a52e01dec50.png)
There you go. It'll be included in the next release
