### ISSUE TITLE
macOS?

### ISSUE THREAD

**Issue by theonlygusti** [univrsal/input-overlay#72]
can I build this for macOS

**Comment by univrsal** [comment]
Theoretically yes, the project only uses libraries which are available for macOS, but I haven't made any changes to the code so it most likely won't compile until the platform specific parts are adjusted to inlcude macOS.

**Comment by theonlygusti** [comment]
@univrsal where are the platform-specific parts?

**Comment by univrsal** [comment]
Mostly anything with header guards _WIN32/LINUX, so the CMakeLists.txt needs to be tweaked to handle macOS and add a #define for macOS.

The gamepad code is windows/linux only:
https://github.com/univrsal/input-overlay/blob/master/io-obs/hook/gamepad_hook.hpp#L18
https://github.com/univrsal/input-overlay/blob/master/io-obs/hook/gamepad_hook.cpp#L125
A quick search gave me this project for gamepad input on macOS:
https://github.com/marnovo/macOS-controller-binder/blob/master/Classes/NJDevice.m
If you don't need gamepad monitoring you can probably just comment any compile errors with this out

This utility part needs a header guard for macOS:
https://github.com/univrsal/input-overlay/blob/master/io-obs/util/util.hpp#L13

The libuiohook might need some macOS specific headers:
https://github.com/univrsal/input-overlay/blob/master/io-obs/hook/hook_helper.cpp
See:
https://github.com/univrsal/libuiohook/blob/1.1/src/demo_hook_async.c#L34

You'll have to compile libuiohook and netlib for macOS
https://github.com/univrsal/libuiohook
https://github.com/univrsal/netlib

I haven't tried to compile either on macOS, but libuiohook should definetely work, while netlib might pose some issues. If you don't want to go through the trouble of compiling netlib, you could disable the network option (eg. commeting out anything using netlib :P)

**Comment by L1cardo** [comment]
Same need !
It will be cool to have a Mac version!

**Comment by univrsal** [comment]
Maybe eventually, but it's not a priority. I'd like to finish version five first, whenever I get the time for that

**Comment by univrsal** [comment]
As I've decided with all my other projects I won't be supporting macOS. I did for a bit with other plugins and it wasn't worth the effort. So I'll just close this now.

**Comment by BrettMoan** [comment]
😭 came here hoping to avoid a propriety overlay solution hope one day you would re-consider, as it would be nice to get an input overlay as part of my OBS instead of a standalone app i have to start.

**Comment by univrsal** [comment]
Highly unlikely, at least from me. My past experience with supporting macOS was horrendous and I'd have to be paid generously to even consider touching it again.
