### ISSUE TITLE
display issue

### ISSUE THREAD

**Issue by Appiibaka** [univrsal/input-overlay#74]
**Describe the bug**
keyboard overlay display is broke

**To Reproduce**
Install input-overlay, add it to scene, use default preset

**Expected behavior**
Gamepad shown as included wasd-15-fps-preview.png

**Screenshots**
![Screenshot_17](https://user-images.githubusercontent.com/49212531/55436998-12327080-559e-11e9-978c-6de520949661.jpg)

**Additional information:**
- Plugin version v4.7.3
- Full OBS Studio log https://gist.github.com/Appiibaka/f1a3ee6b5807637e7a797c29e17d154f

**Comment by univrsal** [comment]
you used the preview image file.
Do not use this file:
![wasd-minimal-preview](https://user-images.githubusercontent.com/8353672/55500972-0051db80-5639-11e9-85b3-99a91e5fe2ff.png)
Use this one:
![wasd](https://user-images.githubusercontent.com/8353672/55500981-05168f80-5639-11e9-8508-c522013b837f.png)

**Comment by Appiibaka** [comment]
oh okay XD now it work Thanks
