### ISSUE TITLE
Fails to load any INI present

### ISSUE THREAD

**Issue by szmarczak** [univrsal/input-overlay#78]
**Describe the bug**
No image present.

**To Reproduce**
Try to load any preset.

**Expected behavior**
An input overlay.

**Screenshots**
![image](https://user-images.githubusercontent.com/36894700/59564852-ef1b4700-904b-11e9-96e2-3319bc06d4cb.png)

**Additional information:**
- Plugin version: latest (v4.7.4)
- Full OBS Studio log: https://obsproject.com/logs/wHBccJtCkPGJMvfP

<details>
<summary><code>wasd-minimal.ini</code></summary>

```
0_overlay_height=394
0_overlay_width=568
0_space_key_code=57
5_space_key_mapping=1301,2,421,128
4_space_key_pos=137,266
0_space_key_type=1
0_space_key_z_level=0
1_ctrl_key_next=space_key
0_ctrl_key_code=29
5_ctrl_key_mapping=1121,1,157,128
4_ctrl_key_pos=0,266
0_ctrl_key_type=1
0_ctrl_key_z_level=0
1_d_key_next=ctrl_key
0_d_key_code=32
5_d_key_mapping=961,1,157,128
4_d_key_pos=411,133
0_d_key_type=1
0_d_key_z_level=0
1_s_key_next=d_key
0_s_key_code=31
5_s_key_mapping=801,1,157,128
4_s_key_pos=274,133
0_s_key_type=1
0_s_key_z_level=0
1_a_key_next=s_key
0_a_key_code=30
5_a_key_mapping=641,1,157,128
4_a_key_pos=137,133
0_a_key_type=1
0_a_key_z_level=0
1_shift_key_next=a_key
0_shift_key_code=42
5_shift_key_mapping=481,1,157,128
4_shift_key_pos=0,133
0_shift_key_type=1
0_shift_key_z_level=0
1_e_key_next=shift_key
0_e_key_code=18
5_e_key_mapping=321,1,157,128
4_e_key_pos=411,0
0_e_key_type=1
0_e_key_z_level=0
1_w_key_next=e_key
0_w_key_code=17
5_w_key_mapping=161,1,157,128
4_w_key_pos=274,0
0_w_key_type=1
0_w_key_z_level=0
1_q_key_next=w_key
0_q_key_code=16
5_q_key_mapping=1,1,157,128
4_q_key_pos=137,0
0_q_key_type=1
0_q_key_z_level=0
0_space_v=5
0_space_h=-20
0_default_height=128
0_default_width=157
1_first_element=q_key
```

</details>

**Comment by univrsal** [comment]
You're trying to load a version 5 preset with version 4 of input overlay. Where did you get the presets?

**Comment by szmarczak** [comment]
Ah, that checks out. Sorry for interruption. I've used the ones from the `master` branch instead of the v4 ZIP.

When is v5 going to be released?

**Comment by univrsal** [comment]
man, if I knew that. It's a picture book example of the 80-20 rule. There's almost nothing left feature wise, but I'll have to do some extended testing and I've been putting that off for a while now so I really have no clue when it's going to be done
