### ISSUE TITLE
Input history - "ban" keypresses

### ISSUE THREAD

**Issue by Sharingisnotillegal** [univrsal/input-overlay#79]
Would love a way to "ban" keys from within the plugin.
I do understand that it may be possible to do using the INI's
I just wish it was simple, without having to 'enter' files.

For example, holding shift is something i'd like to "hide" from it.

But i'd like to show all combos while holding shift.

Example:
Press W = show
Hold shift = hide
Press Shift + W = show

Optimal in my eyes would be a picture of a keyboard, where you press keys to "ban".
I do understand that it may be complicated to allow combos of a certain banned key. But thats OK.

Extention to this "ban" would be a way to map international keyboards.

**Comment by univrsal** [comment]
When would that come in useful?

**Comment by Sharingisnotillegal** [comment]
I hold alt to select self in league, then q w e r to cast. But sometimes I hold it for a long extended period, and therefor it clutters things.

But also, when for example holding shift and w to run, it would spam that i am holding those 2 buttons. It's generally quite obvious that i'm running.(Example; battlefield) In that case i would ban the combo space + w

**Comment by univrsal** [comment]
Are you talking about input overlay or input history? Because it wouldn't clutter anything in an overlay

**Comment by univrsal** [comment]
It's possible to completely exclude keys by providing a custom key name file.
All keys mentioned in the file will be shown and any other key will not.
The middle ground of excluding if it's not used in a combination is not possible and to be honest it's too specific. I can't add a feature for every specific use case

**Comment by univrsal** [comment]
See #122
