### ISSUE TITLE
"Hidden password"

### ISSUE THREAD

**Issue by Sharingisnotillegal** [univrsal/input-overlay#80]
Problem:
Users being able to see your password if you dont have a dedicated scene when streaming.

Solution:
When detecting certain key combos, pause plugin for 10 seconds.

How it would work?

When you type your username, certain text etc., pause script for X seconds to prevent giving out your password/personal info.

**Comment by szmarczak** [comment]
Instead wouldn't it be better just to clone the scene and switch between them?

**Comment by univrsal** [comment]
It's already implemented as mentioned in #71 but it's part of version five. It's not exactly the same, but it'll allow you to either only capture input from selected windows or exclude input from selected windows

**Comment by Sharingisnotillegal** [comment]
@szmarczak sometimes you just forget to switch between the scenes.

**Comment by szmarczak** [comment]
Then the solution is simple: do not forget. Display the preview on a second monitor.

**Comment by univrsal** [comment]
Or you use the automatic scene switcher
