### ISSUE TITLE
Problems with build

### ISSUE THREAD

**Issue by Azzurite** [univrsal/input-overlay#83]
Hey, I'm trying to build the project locally.

However, I'm not using Visual Studio.

I've fixed a bunch of errors, but right now I'm stuck at one I can't figure out:

I've got a bunch of global variables that are not defined for me, [`STATE_RELEASED`](https://github.com/univrsal/input-overlay/blob/e530f0c5379b7c48676e8311ebc6612341157121/io-obs/hook/xinput_fix.cpp#L104) and [`DPAD_UP`](https://github.com/univrsal/input-overlay/blob/e530f0c5379b7c48676e8311ebc6612341157121/io-obs/hook/xinput_fix.cpp#L113), [`DPAD_DOWN`](https://github.com/univrsal/input-overlay/blob/e530f0c5379b7c48676e8311ebc6612341157121/io-obs/hook/xinput_fix.cpp#L115), [`DPAD_LEFT`](https://github.com/univrsal/input-overlay/blob/e530f0c5379b7c48676e8311ebc6612341157121/io-obs/hook/xinput_fix.cpp#L117), [`DPAD_RIGHT`](https://github.com/univrsal/input-overlay/blob/e530f0c5379b7c48676e8311ebc6612341157121/io-obs/hook/xinput_fix.cpp#L119) in `xinput_fix.cpp` as well as [`DPAD_CENTER`](https://github.com/univrsal/input-overlay/blob/master/io-obs/hook/gamepad_hook.cpp#L96) in `gamepad_hook.cpp`.

I've not been able to figure out where they could be coming from. Could you maybe tell me which dependency I'm missing?

**Comment by univrsal** [comment]
yeah I changed some enums. I actually fixed that recently though. When did you clone the repository?

**Comment by Azzurite** [comment]
Yesterday night, I'm at e530f0c5379b7c48676e8311ebc6612341157121

**Comment by Azzurite** [comment]
So they didn't come from a lib? Then I'm pretty sure that they are not currently in the project, as I did a full-text search on all files.

**Comment by univrsal** [comment]
yeah no, I just changed the names. Are you compiling on windows? Cause I haven't updated the names in the windows portion, yet

**Comment by Azzurite** [comment]
Yes, windows, that's why. Are these the correct names? https://github.com/univrsal/input-overlay/commit/9e2440eeabc7a4d6b4633355f54f27ed75ac60fc

**Comment by univrsal** [comment]
yeah, I'll change them

**Comment by univrsal** [comment]
Try pulling 764396f, I skimmed through all files, but I might've missed some.

**Comment by Azzurite** [comment]
There's more issues, but that fixed these for now (not all, but the rest I could do myself).

**Comment by Azzurite** [comment]
Does this repository have to be checked out *inside* of the obs-studio repository? Because of [this line](https://github.com/univrsal/input-overlay/blob/764396f43881586c67ea85517bf1810f3b5a13f5/io-obs/CMakeLists.txt#L161). It seems I'm missing this lib while linking.

**Comment by univrsal** [comment]
yeah it has to be installed into the plugins folder of the obs repo, then modify the CMakeLists.txt in th ep plugins folder and add ```add_subdirectory(input-overlay)``` to the bottom of the file.

**Comment by univrsal** [comment]
I'll close this for now
