### ISSUE TITLE
Creates a huge empty overlay since 4.8b

### ISSUE THREAD

**Issue by lnandor** [univrsal/input-overlay#84]
Hello,

I've updated the plugin to 4.8b and tried to load a new preset, but it only creates a huge overlay with no content in it. It was working fine with 4.7.4b. Loading an older version preset in the new version also works. I'm using KDE Neon.

![ezgif-4-fa707d99576c](https://user-images.githubusercontent.com/36826444/63475973-6079da80-c47f-11e9-867c-5deac4e116c6.gif)

**Comment by aTosser** [comment]
Same issue using Gentoo Linux.

**Comment by univrsal** [comment]
I think I know what the problem is. Just use the previous version with previous presets for now.

**Comment by lnandor** [comment]
Thank you for looking into it.

**Comment by Corben78** [comment]
Ah yeah, I get the same issue on Ubuntu. In the obs logfile it says something like this:
```
18:38:46.798:  [ERROR] Cannot get int value of 'key_count'. Doesn't exist or type mismatch
18:38:46.798:  [ERROR] Cannot get int value of 'layout_type'. Doesn't exist or type mismatch
18:38:46.798:  [ERROR] Invalid type '
' at line 35
18:38:46.798:  [ERROR] Invalid type '0' at line 10
18:38:46.798:  [ERROR] Invalid type '0' at line 11
18:38:46.798:  [ERROR] Invalid type '0' at line 13
```

**Comment by univrsal** [comment]
I fixed an issue when loading a config file with empty lines and with that I also changed the ids for config value types, which required an update for all config files, but I did not recompile the linux version, because I was using windows at the time. If all goes well I just have to compile the new version

**Comment by ShermanZero** [comment]
I'm having the same problem with my Windows 10 machine.  The texture loads-in correctly when I choose the **OverlayFile**, but upon choosing the **LayoutFile**, everything disappears  😞

**Comment by univrsal** [comment]
@ShermanZero yeah sorry about that, as I said just use the previous version for now. 4.8 only had a small fix for input-history and apparently broke everything else. Also that config creation tool you were looking for isn't done yet :P

**Comment by univrsal** [comment]
Alright, I've rebuilt the linux version and also fixed some issues I discovered.
Can you please test [this](https://github.com/univrsal/input-overlay/releases/download/v4.8/input-overlay.v.4.8b.linux64.zip) release?
I'll try my best to fix windows tomorrow

**Comment by lnandor** [comment]
Tested on Linux, KDE neon, works flawlessly! Some button alignment issues were fixed too. Thank you very much.

**Comment by univrsal** [comment]
Seems like this is fixed then.
@ShermanZero I just tried the latest release and had no problems, can you make sure that you're using the new presets?

**Comment by maritz** [comment]
I just downloaded a fresh 4.8b on Windows 10 and have the exact same issue.

```
input-overlay-presets/wasd/wasd-full.ini':
11:42:39.747:  [ERROR] Cannot get int value of 'key_count'. Doesn't exist or type mismatch
11:42:39.747:  [ERROR] Cannot get int value of 'layout_type'. Doesn't exist or type mismatch
11:42:39.747:  [ERROR] Invalid type '0' at line 10
11:42:39.747:  [ERROR] Invalid type '0' at line 11
11:42:39.747:  [ERROR] Invalid type '0' at line 13
11:42:39.747:  [ERROR] Invalid type '0' at line 4
11:42:39.747:  7 more error(s) reported
```

**Comment by univrsal** [comment]
That's weird, do other presets work? You're using the ones that are shipped with the plugin, right?

**Comment by maritz** [comment]
I was using the ones shipped with the plugin, yes. I tried WASD-full, mouse, wasd-extended. All had these errors.

**Comment by univrsal** [comment]
Are you using obs studio 32bit? I can't reproduce the issue on Windows 10 64bit

**Comment by maritz** [comment]
No, 64bit. But I ended up not using the overlay anyways (for other reasons), so if it works for others, no worries.

**Comment by univrsal** [comment]
I'd still like to know what's causing it though
