### ISSUE TITLE
Blender Screencast addon compare

### ISSUE THREAD

**Issue by brothermechanic** [univrsal/input-overlay#85]
Hello
I wand to show you small compare test
[2019-08-24 05-03-15.zip](https://github.com/univrsal/input-overlay/files/3536764/2019-08-24.05-03-15.zip)
There is addon's code 
https://github.com/nutti/Screencast-Keys
Hope you find something good for you.

**Comment by univrsal** [comment]
thanks, but since it's a blender add on I don't think there's much in there that I can reuse
