### ISSUE TITLE
Stopped working completely as of yesterday.

### ISSUE THREAD

**Issue by KeyserSozeTV** [univrsal/input-overlay#88]
Everything worked perfectly until about halfway through stream yesterday and then stopped.  Now neither keyboard or mouse inputs are working.  I have tried deleting and adding back.  I have tried starting OBS as admin.  I'm not sure what changed or what else to try.  Log files attached.

Thank you,
Jeremy
[2019-08-27 09-04-34.txt](https://github.com/univrsal/input-overlay/files/3547143/2019-08-27.09-04-34.txt)

**Comment by univrsal** [comment]
Which version are you using? Are you using the presets provided with the plugin in the archive?
Also what doesn't work? Do the presets show up correctly and the input itself isn't displayed or does loading the presets do nothing at all?
