### ISSUE TITLE
Mouse wheel up/down not registered on mouse preset

### ISSUE THREAD

**Issue by MarkusNemesis** [univrsal/input-overlay#9]
Cannot see mousewheel up or down on mouse. Uncommenting MWU and MWD on preset ini just messes up the alignment.

**Comment by univrsal** [comment]
Yeah, sadly the mouse wheel input cannot be captured like all the other input. It's not possible to detect that without using a separate hook which isn't really possible through an obs plugin. That's why it's not supported and probably will not be, unless someone can help me out with it
