### ISSUE TITLE
Keyboard not working 100%

### ISSUE THREAD

**Issue by shibou3** [univrsal/input-overlay#90]
The plugin does not show my Q when I press it, other keys are ok

**Comment by univrsal** [comment]
Can you download [this](https://github.com/univrsal/input-overlay/releases/download/v4.8/util.zip) and run `demo_hook.exe` and tell me what keycode it reports when you press 'q'?

**Comment by shibou3** [comment]
![image](https://user-images.githubusercontent.com/23579978/64870919-93e0fc80-d61a-11e9-9827-b2057c43834b.png) @univrsal

**Comment by univrsal** [comment]
strange, I'll look into it, but it'll take a bit

**Comment by univrsal** [comment]
Okay I tested it myself, but couldn't reproduce it. Can you tell me what version ob OBS and input overlay you're using and what keyboard layout you use?

**Comment by shibou3** [comment]
OBS Studio 23.2.1 (64 bit)
input-overlay.v4.8b.win32.64.zip
Portuguese (Brasil) - US Keyboard (international) [ https://puu.sh/EhYzb/9025c72770.png ]

**Comment by univrsal** [comment]
Okay, I fixed it. Sorry this took so long. The wasd-full preset was using the wrong keycode for the 'q' key. Just re-download the latest release
