### ISSUE TITLE
v4.8 from releases page fails to load when installed

### ISSUE THREAD

**Issue by zoton2** [univrsal/input-overlay#91]
**Describe the bug**
I have attempted to install the most recent version available on the releases page (v4.8) into the most recent version of OBS (v24.0.1 64-bit) and it fails to load the DLL, displaying in the logs `LoadLibrary failed for '../../obs-plugins/64bit/input-overlay.dll': The specified module could not be found.` I attempted to figure out what might be missing myself using [lucasg/Dependencies](https://github.com/lucasg/Dependencies) but all I could find was `netlib.dll`. Installing v4.7.4 on the same version of OBS works fine however.

**To Reproduce**
Steps to reproduce the behavior: Attempt to install the released version of the plugin on OBS v24.0.1 64-bit and open OBS.

**Expected behavior**
The plugin to load.

**Additional information:**
- Plugin version: v4.8
- Full OBS Studio write_log: https://obsproject.com/logs/W51fYxq_SOXgeUWc

**Comment by univrsal** [comment]
I'll check it out tomorrow

**Comment by univrsal** [comment]
Okay, so I'd like to claim that I test my stuff but apparently that's not true.
Can you please try the attached build and tell me if it works?
[input-overlay.v4.8b.win32.64.zip](https://github.com/univrsal/input-overlay/files/3683413/input-overlay.v4.8b.win32.64.zip)

**Comment by zoton2** [comment]
Yep, that version appears to work fine for me. Plugin loads and I can show everything I want at least. 👍

**Comment by univrsal** [comment]
Yeah probably. I have a script that grabs the builds and it probably grabbed the 5.0 test build.
