### ISSUE TITLE
add AUR package installation 

### ISSUE THREAD

**Issue by networkjanitor** [univrsal/input-overlay#92]
In the AUR (=> for ArchLinux) there is now a package to install the input-overlay plugin:
https://aur.archlinux.org/packages/obs-input-overlay-bin/

Presets are extracted to `/usr/share/obs/obs-plugins/obs-input-overlay/presets/`.

Didn't know where to add it in the project documentation (probably wiki?).

**Comment by univrsal** [comment]
oh nice, thanks a lot. I'll add it to the wiki and the forum post

**Comment by univrsal** [comment]
One thing: you're the installation folder shouldn't be ``/usr/share/obs/obs-plugins/obs-input-overlay/`` but rather ``/usr/share/obs/obs-plugins/input-overlay/`` otherwise obs-studio won't find the language files, because it's using the plugin name (which is input-overlay) to find them

**Comment by networkjanitor** [comment]
fixed the installation directory

**Comment by univrsal** [comment]
thanks!
