### ISSUE TITLE
scroll horizontal 

### ISSUE THREAD

**Issue by dremuler** [univrsal/input-overlay#94]
I cant figure out how can enable the HORIZONTAL SCROLL because many mouses have it and
multitouch gestures like zoom and that stuff. is there a way to enable it or perform it by myself or need to be developed from here

**Comment by univrsal** [comment]
I haven't implemented anything like that and as far as I know there's no signal for horizontal scrolling, only for normal vertical scrolling

**Comment by dremuler** [comment]
> I haven't implemented anything like that and as far as I know there's no signal for horizontal scrolling, only for normal vertical scrolling

Is there a way that i can help to implement that? Theres many mouses that have multiscrolling, i mean vertical scrolling and horizontal scrolling, is possible develop that or tell me how can do it??i can help in anything needed.

**Comment by univrsal** [comment]
Well if you can direct me to a resource which covers getting an input event for vertical scrolling I'll take a look at it, but I can't promise anything

**Comment by dremuler** [comment]
I was looking for a mouse tester to get some  information and i get one that recognize vertical and horizontal scrollibg but idk how can extract information useful for you. Which tool do yo use to get moude info, probably i can perform tests and extract info for you and send it

**Comment by univrsal** [comment]
what's the tool called?

**Comment by dremuler** [comment]
x-Mouse button control 
http://www.highrez.co.uk/downloads/xmousebuttoncontrol.htm

And its absoluteley free

**Comment by univrsal** [comment]
It's not open source though so I can't see how it works

**Comment by dremuler** [comment]
Yes, thats why i dont know how helps, however, i would like to know which tools do you use, so i can perform tests and that stuff to send you the needed data

**Comment by univrsal** [comment]
input overlay uses [libuiohook](https://github.com/kwhat/libuiohook) I don't think that's gonna help you much though

**Comment by dremuler** [comment]
I dont know how to perform this, but. What do you think about non open source program, with memory adresss dumps? I mean, a memory adress dump when idle and a memory adress dump when scroll happens, that couls help? Or not? I mean thats translatable to a information useful for your tool ? 🤔🤔.
Because when i perform horizontal scroll, your tool recognize it as vertical. Thats curious, because it shouldnt be recognized.

**Comment by univrsal** [comment]
Nah I'm not gonna spend time trying to reverse engineer someone elses program. I don't know why the scrolling is picked up by the plugin, because the scrolling is handled by the library I just linked.
Frankly I don't think a feature like this is worth the effort. If it would be a small change in libuiohook I could do it, but I don't even know where to start

**Comment by dremuler** [comment]
Yes, its strange that the library recognize it. Im using a magic mouse (apple) in a windows 10 pc (non mac) works like a charm in the 1909 version ive found a way to make it work with scrolling, actually theres no solution to make it work, but i found it and im gonna publish it. However magic mouse (as other high cost mouses) have multiscroll thats why i contact you.
I hope theres a way to fix this or include it in the future, if you need help let me know i would like to contribute

**Comment by univrsal** [comment]
This is most likely not going to happen. Maybe @kwhat knows if libuiohook even supports that but if it doesn't it definitely won't happen.
