### ISSUE TITLE
input overlay seems to lump the keys together under unknown circumstances

### ISSUE THREAD

**Issue by amphipath** [univrsal/input-overlay#95]
https://i.imgur.com/HFJa1zx.png

when taking the preset for qwerty given and taking out all keys except just the first two as below:

https://i.imgur.com/BlRBwKS.png

it seems to cause the plugin to lump everything into 1_key_col=0. the rows work fine and the keys react when pressed as expected but they're all pushed to the left. i'm not sure why this works fine for the full default config, but simply taking out keys from it will cause this behaviour.

if there has been a change such that the number of keys in the config must match exactly the keys inside the template image, then it's a pretty egregious "feature" since users will no longer be able to mix and match by tweaking premade configs.

**Comment by amphipath** [comment]
https://i.imgur.com/3wzjsF1.png

after further experimentation, the solution turned out to be leaving a blank line at the end of the config. -_-

**Comment by univrsal** [comment]
yeah the config loader is a bit of a trashfire, but I haven't had time or motivation to look into it
