### ISSUE TITLE
NumPad with NumLock off?

### ISSUE THREAD

**Issue by KeronCyst** [univrsal/input-overlay#97]
[A game](https://www.chiark.greenend.org.uk/~sgtatham/puzzles/js/inertia.html) I am trying to record uses input only from NumPad numbers with NumLock off. I can't figure out where the NumPad is, if any.

**Comment by univrsal** [comment]
input overlay supports the numpad functional keys (7 is home, 8 is up, 9 is page up etc.).  Technically [these](https://github.com/univrsal/input-overlay/blob/master/libuiohook/include/uiohook.h#L283) should be the keycodes you're looking for, but some might be swapped. If they don't work, swap them for the non keypad versions (e.g. switch ``VC_KP_END`` with ``VC_END``)

**Comment by univrsal** [comment]
I'll just close this for now
