### ISSUE TITLE
overlay not showing up

### ISSUE THREAD

**Issue by Shigetorum** [univrsal/input-overlay#99]
**Describe the bug**
Overlay does not show up when the config file is applied

**To Reproduce**
1.get the presets wasd
2. Img file = wasd.png
3.Config file = wasd-minimal.ini

**Expected behavior**
it wont show up

**Screenshots**
![imagen](https://user-images.githubusercontent.com/59333909/71563334-361fd580-2a8e-11ea-8662-2d695a92b750.png)
![imagen](https://user-images.githubusercontent.com/59333909/71563336-45068800-2a8e-11ea-94cc-6f3caaad3ccf.png)

**Additional information:**
- Plugin version (4.17)
- Full OBS Studio write_log

**Additional context**

**Comment by szmarczak** [comment]
Have you looked into #78?

**Comment by Shigetorum** [comment]
Fixed already, thanks.
